### ISSUE TITLE
Profile card color bug on switch profile screen

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21203] opened 2024-09-06 13:36 UTC
# Design Feedback 2.30

## Profile card color bug on switch profile screen
I got this bug on random occasions while logging in and out: the profile picture color didn't match the card, there was no identicon ring around the profile picture and sometimes the profile picture was missing entirely.

**Possible solution**
If this problem is caused by slow internet connection or fetching issues our suggestion is to add a loading state for the profile card to avoid the issue.

Figma review [here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#934555318)

#### Expected behavior

<img width="175" alt="Screenshot 2024-09-06 alle 15 34 11" src="https://github.com/user-attachments/assets/a1c97b3e-f1b6-473d-8115-8f02709de32f">

#### Actual behavior

<img width="190" alt="Screenshot 2024-09-06 alle 15 34 56" src="https://github.com/user-attachments/assets/5a434fc5-2c31-40a3-b3e8-49d5bfefa409">

### Reproduction

1. Create a profile
2. Log out

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13,

**Comment by ilmotta** [comment] 2024-10-15 00:13
Thank you reporting the bug in detail @Francesca-G. I'm closing this issue because it's a duplicate of https://github.com/status-im/status-mobile/issues/20016

**Closed as completed by ilmotta** 2024-10-15 00:13 UTC
Labels: mobile-core, design-feedback
