### ISSUE TITLE
Wallet design - Request Transaction

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1526] opened 2017-07-30 10:22 UTC
### User Story

As a user, I want to Request transaction to the wallet and specify amount and share the request. 

#### Acceptance

- [ ] I can start the Request transaction flow by tapping the Request button on the wallet main screen
- [ ] I can scan the generated QR code on the screen to send the transaction in the other app 
- [ ] I can send the request to a contact in the app Contacts

Not in scope - should be presented but not required to be implemented in the scope if this issue (each item will have a separate issue):
- [ ] I can't select currency (only ETH)
- [ ] I can't select the wallet to receive to
- [ ] I can't share the request

Mockup for reference
![image](https://user-images.githubusercontent.com/1944596/30110796-ffd61fac-9313-11e7-9214-b48689f2353e.png)

Zeplin mockups zpl://screen?pid=58aac7d018d4584d91998e79&sid=5987fd0a9560ffae5b4a3684 (row 4).

**Comment by denis-sharypin** [comment] 2017-08-14 19:39
UI is here zpl://screen?pid=5863cdcee68455850f1929f2&sid=5991fb23d214630c91088208

**Comment by yenda** [comment] 2017-08-18 08:08
https://app.zeplin.io/project/5863cdcee68455850f1929f2/screen/5991fb23d214630c91088208

**Comment by asemiankevich** [comment] 2017-09-13 14:07
**Android:**

1. * CR code shoud not be scrollable and must be centered. 
2. * Wallet amount is not shown
3. * SEND **A** REQUEST copy should be shown
4. * I can send request with empty amount field / invalid data in the field - should not allow to proceed to another screen as there is no sense in it
5. * CR code disappears when entering amount
6. 

![image](https://user-images.githubusercontent.com/28752642/30381535-5b39d226-98a5-11e7-8185-643354936055.png)

![image](https://user-images.githubusercontent.com/28752642/30381776-1066b7ae-98a6-11e7-891c-30ec85dfd021.png)

@annadanchenko to check on iOS

**Comment by flexsurfer** [comment] 2017-09-13 14:23
@asemiankevich 
1. we should ask @andmironov 
2. will do
3. what does this mean?
4. we should ask @andmironov 
5. as designed

**Comment by asemiankevich** [comment] 2017-09-13 14:33
@flexsurfer for number 3 as stated on the mock 
![image](https://user-images.githubusercontent.com/28752642/30383133-9ef29170-98a9-11e7-95be-dc4913376f7e.png)

for number 5: just looking at the mock (
![image](https://user-images.githubusercontent.com/28752642/30383204-d57f3252-98a9-11e7-934f-42bf879b1172.png)). No pressure :)

**Comment by flexsurfer** [comment] 2017-09-13 14:45
3. will be fixed in mockup. "send request" is a right version

**Comment by annadanchenko** [comment] 2017-09-13 19:40
### 1. iOS/Android:

Currently max length of the amount: 15 characters including separator (./,). This is different from the amount user can type for /send command in chat. It should be consistent in both places and seems like Wallet is a place to adjust:
1.1 Expected: Amount before separator - seems like can be of any length or I can't find the limit
1.2 Expected: Amount after separator - should be not more than 18 digits after comma (e.g 0.123456789012345678). Currently, it's possible to enter only 13 digits after comma (e.g. 0.1234567890123)
1.3 "0"  is now not allowed as a sum to send. In some cases, it's valid to send "0" (e.g https://contribute.status.im/sgt.html ), so it should be fine to request it too. 

### 2. Android
2.1. Select contact screen, top part with phone icons (carrier, battery status, time) is on black background. Expected: white background, black text/icons
2.2 There is some empty space between "Contacts" heading
![screenshot_20170913-222723](https://user-images.githubusercontent.com/6584810/30396825-90a9e0a8-98d3-11e7-8808-94c0f87cc2f4.png)
expected: 
<img width="363" alt="screen shot 2017-09-13 at 22 33 47" src="https://user-images.githubusercontent.com/6584810/30396856-ae976fae-98d3-11e7-8c93-85aea4f78993.png">


### 3. iOS:
3.1 "x" instead of "<" 
![img_2304](https://user-images.githubusercontent.com/6584810/30397011-243637a4-98d4-11e7-9d51-5370c7c7df82.jpg)

**Comment by flexsurfer** [comment] 2017-09-13 19:50
3.1 we decided that these screens shouldn't be modal because we can open choose contact modal screen, so mockups should be changed

**Comment by flexsurfer** [comment] 2017-09-14 07:21
- [ ] CR code should not be scrollable and must be centered.
- [ ] Wallet amount is not shown
- [ ] Amount field doesn't highlight in focus
- [ ] Contacts screen looks wrong on Android
- [ ] Amount rules

**Comment by asemiankevich** [comment] 2017-09-14 08:55
https://github.com/status-im/status-react/issues/1855 to track

**Comment by asemiankevich** [comment] 2017-09-15 14:30
Closing this out. Opened `https://github.com/status-im/status-react/issues/1867` to implement the rules for amount field

**Comment by flexsurfer** [comment] 2017-10-19 10:09
Fixed in develop, will be in release 0.9.12

**Closed by flexsurfer** 2017-10-19 10:09 UTC
Labels: high-priority, story, wallet
