### ISSUE TITLE
App crashes after sending location command to chat several times [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1435] opened 2017-07-12 07:31 UTC
### Description

*Type*: Bug

*Summary*: Use location command 3-4 times to send some address by selecting it on the map and app crashes

#### Expected behavior
Address is sent, user can continue to send other addresses
#### Actual behavior
app crashed

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7MDYxZXBkRG1xWjg
- Open Status
- Open 1-1 chat with Jarrad
- tap on /location
- in the map shown move pin to some location to get an address
- tap on the address shown and send it in 1-1 chat
- repeat same actions 2-3 times to send other addresses

### Log
[crash14.log.txt](https://github.com/status-im/status-react/files/1141206/crash14.log.txt)

### Additional Information
* Status version:  0.9.8-63-g06bff32f+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by flexsurfer** [comment] 2017-07-12 10:25
looks like the problem in mapbox component it requires a lot of resources on initializing

**Comment by rasom** [comment] 2017-07-13 15:03
I can't reproduce issue on iOS device (`develop` branch).

**Comment by flexsurfer** [comment] 2017-07-13 15:11
I can't reproduce issue on Android device (develop branch), but i saw on ios simulator how cpu usage grows, we can try to get cpu logs in TestFairy

**Comment by rasom** [comment] 2017-07-13 15:15
I can reproduce it on my Android device.

**Comment by annadanchenko** [comment] 2017-08-13 10:14
Real Samsung Galaxy S6, Android 6.0.1
Build 0.9.8-130-g6a56b600
Popup is shown and then Status app stopped if send 3-4 location messages in chat (by moving pin on the map as described in steps to reproduce)
![screenshot_20170813-120814](https://user-images.githubusercontent.com/6584810/29248792-ce951b92-8020-11e7-86cd-1e1a8c606076.png)

**Comment by annadanchenko** [comment] 2017-08-17 17:53
verified ok on PR build 0.9.8-140-g4406d138+
both iOS (real iphone 6s, iOS 10.3.3) and Android (Google Pixel XL/7.1.2 Android and Galaxy S6/6.0.1 Android)

**Comment by jeluard** [comment] 2017-10-20 13:57
Fixed in develop

**Closed by jeluard** 2017-10-20 13:57 UTC
Labels: advanced, bug, medium-priority, Tested - OK
