### ISSUE TITLE
json: cannot unmarshal hex string when token transaction sent without internet connection

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8352] opened 2019-06-04 08:57 UTC
# Problem

`:wallet/transaction-error :code 2 :message json: cannot unmarshal hex string "0x" into Go value of type *hexutil.Big`

# Logs

```
2019-06-04 11:48:58.174 7313-7409/? D/StatusModule: sendTransaction
2019-06-04 11:48:58.298 7313-7408/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :wallet.callback/transaction-completed
2019-06-04 11:48:58.304 7313-7408/? W/ReactNativeJS: WARN [status-im.wallet.core:337] - :wallet/transaction-error :code 2 :message json: cannot unmarshal hex string "0x" into Go value of type *hexutil.Big
2019-06-04 11:48:58.313 7313-7408/? D/ReactNativeJS: DEBUG [status-im.ui.screens.navigation:86] - :navigate-back
2019-06-04 11:48:58.342 7313-7408/? D/ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:31] - :on-will-focus :browser
2019-06-04 11:48:58.349 7313-7408/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :wallet.dapp/transaction-on-error
2019-06-04 11:48:58.353 7313-7408/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :screens/on-will-focus
2019-06-04 11:48:58.359 7313-7408/? D/ReactNativeJS: DEBUG [status-im.ui.screens.views:85] - :main-component-did-update :browser
2019-06-04 11:48:58.379 7313-7313/? I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected number in JSON at position 94", source: https://ciqne5onq6dbtaqlamhh6yi3bv36o7olkaaucygae5gmdd4boxceyja.infura.status.im/ (1)
2019-06-04 11:48:58.380 7313-15269/? E/GoLog: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected number in JSON at position 94", source: https://ciqne5onq6dbtaqlamhh6yi3bv36o7olkaaucygae5gmdd4boxceyja.infura.status.im/ (1)
2019-06-04 11:48:58.462 7313-7408/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :show-tab-bar
2019-06-04 11:48:58.466 7313-7408/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set
2019-06-04 11:48:58.473 7313-7408/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set-once
2019-06-04 11:48:58.643 7313-7408/? D/ReactNativeJS: DEBUG [status-im.utils.handlers:34] - Handling re-frame event:  :set-once
```

## Steps

1. request eth in simple dapp
2. throttle internet connection (or limit it to 0 kbs)
3. request stt in simple dpp

This also was seen when buying stickers.

![image](https://user-images.githubusercontent.com/28752642/58865597-83d28c00-86bf-11e9-8ee9-5ac419622e5a.png)

## Build 

nightly https://status-im.ams3.digitaloceanspaces.com/StatusIm-190603-025900-34300c-nightly.apk

**Comment by rachelhamlin** [comment] 2019-10-17 14:18
Note - if this issue is only happening when connection is throttled, it could simply be fixed by changing the error copy to be more instructive, e.g. `Connection lost. Please try again.`

**Comment by churik** [comment] 2020-02-26 15:57
Can't see this error anymore in case of limited connection now I just can't sign a transaction because the network fee is not set automatically.
Consider it as expected behavior, @rachelhamlin please reopen if will see this again

**Closed as completed by churik** 2020-02-26 15:57 UTC
