### ISSUE TITLE
You can send message to the past if you set custom date

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6946] opened 2018-11-29 15:43 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to see messages in order that they were sent

### Description
*Type*: Bug
*Summary*: if you set date on sender side to yesterday manually and send a message, receiver will see it below "Yesterday", so order is wrong.

#### Expected behavior
Message is last

#### Actual behavior
Message is shown as sent yesterday (so below "Yesterday")
![kkk](https://user-images.githubusercontent.com/4557972/49233127-9fe62f80-f3f5-11e8-9a24-26c9a1928b14.png)

### Reproduction

- Open Status on device A
- Join any chat (i.e. #test)
- Send some message to it
- Open Status on device B
- Set device B date to yesterday
- Send some message 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 29/11/2018
* Operating System: all

**Comment by lukaszfryc** [comment] 2018-11-30 10:04
duplicate of https://github.com/status-im/status-react/issues/5605?

**Comment by churik** [comment] 2018-11-30 12:22
Yes, it is closed, so couldn't find it. So reopen #5605 or leave this one?

**Comment by lukaszfryc** [comment] 2018-11-30 13:22
We can leave this one

**Comment by Swader** [comment] 2019-02-28 13:29
Still a thing

**Comment by churik** [comment] 2019-06-06 08:40
Everyday test "Can join test public chat and send/recieve text messages" https://ethstatus.testrail.net/index.php?/tests/view/705822 is failed in nightly because of this issue.
The reason is that device and runner are located in different timezones - so test is seeking message below "Today", in fact it is located under yesterday.
Logs/video: https://app.saucelabs.com/tests/ddf863e56f544cf5896136a714fd771d?auth=c26b016cb28c842c3e03e815e7b0c6e4

**Comment by churik** [comment] 2019-08-13 14:10
cc @rachelhamlin 
From my POV it is not acceptable to have the possibility to send a message in the past and change chat history.

**Comment by rachelhamlin** [comment] 2019-08-14 09:17
What are the reasons a user would change the date to the past on their device? Is this a real possibility?

**Comment by churik** [comment] 2019-08-14 11:33
@rachelhamlin  just to fake chat history.
Normal user shouldn't do this.
I'm not sure about timezones - but can investigate it.

**Comment by rachelhamlin** [comment] 2019-08-21 07:58
Mmm good point. Thanks @churik. Let's see if anything comes up about this during the audit.

**Comment by rachelhamlin** [comment] 2019-08-29 12:30
Requesting @cammellos or @adambabik to take a look into this one to see if it's a) a go fix and b) a straightforward one 🤞

**Comment by cammellos** [comment] 2019-08-29 12:41
it's a status react fix, i can take a look at it

**Comment by rachelhamlin** [comment] 2019-08-29 13:00
@cammellos if you can fix it, lmk but I wouldn't put it above other v1 related work.

**Comment by cammellos** [comment] 2019-08-29 13:02
it s  a quick fix, we never got around it as it might break data compatibility, but we are past that point

**Comment by acolytec3** [comment] 2019-10-28 11:10
@rachelhamlin
I'm down to take a look though it looks like @cammellos is already on the case. Is the preferred approach to not let the sender even send to the past or to resolve on the receiver side?

**Comment by cammellos** [comment] 2019-10-28 11:15
I am on this one, sorry @acolytec3  :)

**Comment by StatusSceptre** [comment] 2019-10-28 11:24
Ahaha okay! Easy. I'll find you another one @acolytec3. Please hold... :)

**Comment by acolytec3** [comment] 2019-10-28 11:25
@cammellos My job here is done. 😁

**Comment by cammellos** [comment] 2019-11-04 07:11
Closed via https://github.com/status-im/status-react/pull/9294

**Closed as completed by cammellos** 2019-11-04 07:11 UTC
