### ISSUE TITLE
Context tags are broken in jump-to screen

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#17552] opened 2023-10-05 08:32 UTC
### Screenshot
![image](https://github.com/status-im/status-mobile/assets/17097240/dc7bfb95-3843-4e11-92b8-7b260ed9f661)

### Link to figma
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:66732&mode=design#567169852

**Comment by ibrkhalil** [comment] 2024-01-28 16:45
Can't reproduce
![image](https://github.com/status-im/status-mobile/assets/33176106/895b5a41-e5a1-464c-9c4c-b044bd885881)

**Comment by ibrkhalil** [comment] 2024-01-30 14:07
@status-im/mobile-qa 
Can you please make sure that this is still reproducible?

**Comment by pavloburykh** [comment] 2024-01-30 14:38
> Can't reproduce ![image](https://private-user-images.githubusercontent.com/33176106/300278836-895b5a41-e5a1-464c-9c4c-b044bd885881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjQ2NTgsIm5iZiI6MTcwNjYyNDM1OCwicGF0aCI6Ii8zMzE3NjEwNi8zMDAyNzg4MzYtODk1YjVhNDEtZTVhMS00NjRjLTljNGMtYjA0NGJkODg1ODgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE0MTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YmVjMWI0OTdhM2E1Zjg5MWNiNjg1NDVmNTA5ODdhNTk0OWE3YzllM2UxYTk4ODg2MzQ4NDQ2ODdmODhhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBRZI2OMZPrr8qpD4XdYgZv79JseC3llswTTIpyUjWU)

Hi @ibrkhalil! Thanks for looking at the issue. 
I got 1 question: how were you able to generate such context tag that is shown on your screenshot? Current mobile app generates regular community links that do not generate such context tag within chat card and are displayed as a regular message (see screenshot below). 

![photo_2024-01-30 16 36 48](https://github.com/status-im/status-mobile/assets/97245802/6bf4d8f2-cb67-4415-b5a9-06a1eba3efde)


For reproduction of this issue we need to user community invite cards which have been recently deprecated in favor of regular links so I do not know how to verify if the issue still exists. Give me some tips please on how you have managed to generate such community link

**Comment by ibrkhalil** [comment] 2024-01-30 15:17
> > Can't reproduce ![image](https://private-user-images.githubusercontent.com/33176106/300278836-895b5a41-e5a1-464c-9c4c-b044bd885881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjQ2NTgsIm5iZiI6MTcwNjYyNDM1OCwicGF0aCI6Ii8zMzE3NjEwNi8zMDAyNzg4MzYtODk1YjVhNDEtZTVhMS00NjRjLTljNGMtYjA0NGJkODg1ODgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE0MTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YmVjMWI0OTdhM2E1Zjg5MWNiNjg1NDVmNTA5ODdhNTk0OWE3YzllM2UxYTk4ODg2MzQ4NDQ2ODdmODhhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VBRZI2OMZPrr8qpD4XdYgZv79JseC3llswTTIpyUjWU)
> 
> Hi @ibrkhalil! Thanks for looking at the issue. 
> I got 1 question: how were you able to generate such context tag that is shown on your screenshot? Current mobile app generates regular community links that do not generate such context tag within chat card and are displayed as a regular message (see screenshot below). 
> 
> ![photo_2024-01-30 16 36 48](https://github.com/status-im/status-mobile/assets/97245802/6bf4d8f2-cb67-4415-b5a9-06a1eba3efde)
> 
> 
> For reproduction of this issue we need to user community invite cards which have been recently deprecated in favor of regular links so I do not know how to verify if the issue still exists. Give me some tips please on how you have managed to generate such community link 

I remember using Desktop to share

**Comment by pavloburykh** [comment] 2024-01-30 17:39
> I remember using Desktop to share

I tried Desktop too (the latest nightly build). But got the same link as in mobile.

So currently I cannot verify if the bug is fixed as I cannot generate community context tag which appeared to be broken according to the issue description.

**Comment by ibrkhalil** [comment] 2024-01-30 20:57
> > I remember using Desktop to share
> 
> I tried Desktop too (the latest nightly build). But got the same link as in mobile.
> 
> So currently I cannot verify if the bug is fixed as I cannot generate community context tag which appeared to be broken according to the issue description.

Okay, Thank you very much for trying it out
I'll update my desktop/mobile clients and retry to reproduce

**Comment by pavloburykh** [comment] 2024-01-30 21:02
> Okay, Thank you very much for trying it out
> I'll update my desktop/mobile clients and retry to reproduce

Thank you for looking at the issue @ibrkhalil. Maybe after this one https://github.com/status-im/status-mobile/pull/18484 is merged we will be able to verify if the bug exists? WDYT?

**Comment by ibrkhalil** [comment] 2024-01-30 21:04
> > Okay, Thank you very much for trying it out
> > I'll update my desktop/mobile clients and retry to reproduce
> 
> Thank you for looking at the issue @ibrkhalil. Maybe after this one #18484 is merged we will be able to verify if the bug exists? WDYT?

Sure thing :)

**Comment by ibrkhalil** [comment] 2024-02-13 21:25
Can I please get more clarification if this issue exists or not and what _is_ exactly broken here?
CC: @pavloburykh

**Comment by pavloburykh** [comment] 2024-02-14 08:18
> Can I please get more clarification if this issue exists or not and what _is_ exactly broken here? CC: @pavloburykh

@ibrkhalil we will check if it is reproducible when we will take this https://github.com/status-im/status-mobile/pull/18484 into testing. Currently we are busy with testing those features that need to be included into upcoming release so there might be delay with testing of other PRs.

**Comment by mariia-skrypnyk** [comment] 2024-02-19 14:02
Hi @ibrkhalil !
Unfortunately I have no ability to check how context tag works at this moment and if this issue exist as we do not have implementation of shared community link view inside 1-1 chat.
<img width="387" alt="Screenshot 2024-02-19 at 15 28 11" src="https://github.com/status-im/status-mobile/assets/147824399/f85327a0-9600-4680-a871-7ff69d84eb60">
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=611-22756&mode=design&t=IvH1kGG6pzeCCD1A-0

So, this issue is not connected to the preview you've implemented [here.](https://github.com/status-im/status-mobile/pull/18484)

**Comment by mariia-skrypnyk** [comment] 2024-02-20 09:00
Hi @Parveshdhull @ibrkhalil !
This design review [comment](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6117:66732&mode=design#567169852) is no longer an expected behaviour for now as we discussed that current implementation previews communities as **links** and not as **tags**. 
Temporary we decided it is a normal behaviour.

I am going to close this issue.

For more details please look at this thread: https://discord.com/channels/624634427930312714/975775548007678033/1209198425074307193

**Closed as completed by mariia-skrypnyk** 2024-02-20 09:00 UTC
