### ISSUE TITLE
Wallets: grey screen without Main Wallet is shown 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#955] opened 2017-03-29 18:57 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Grey screen without Main Wallet "card" is shown. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Wallets screen with Wallet "card" is shown
![expected wallets](https://cloud.githubusercontent.com/assets/6584810/24470855/a06d52b4-14c0-11e7-90a3-daa3bc6e7db5.png)

#### Actual behavior
[comment]: # (Describe what actually happened.)
Grey screen with no Main Wallet "card" is shown
![grey wallets](https://cloud.githubusercontent.com/assets/6584810/24470857/a3b1c612-14c0-11e7-9fc8-9d840750abd9.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Screencast on Android 6.0.1  (Samsung Galaxy S6): https://www.screencast.com/t/MWH44Yeh
Screencast on Android 7.0 (Samsung Galaxy S7): https://www.screencast.com/t/Ssyc4yHSZdw
- Open Status and login
- In Chats tap on Wallet -> ok Wallets screen with Main Wallet card is shown
- Tap on device Back button to return to Chats
- Tap on console 
- In console tap on "commands" button
- Tap on /faucet command
- Tap on "Status Testnet Faucet" and tap on send icon
- Tap on "<" to return to Chats
- Tap on Wallet 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.4
* Operating System: Android 6.0.1  (Samsung Galaxy S6) and Android 7.0 (Samsung Galaxy S7)
Note that there is Instabug report on iOS too, however I can't find the steps to reproduce it on iOS.

#### Logs
* Android 7.0 (Samsung Galaxy S7):  [20172903192135-logcat.txt](https://github.com/status-im/status-react/files/880045/20172903192135-logcat.txt)
* Android 6.0.1  (Samsung Galaxy S6): [20172903191951-logcat.txt](https://github.com/status-im/status-react/files/880046/20172903191951-logcat.txt)

#### Instabug reports:
iOS:
Not sure how to reproduce issue on iOS
* 0.9.4 (grey screen) https://dashboard.instabug.com/applications/status/beta/bugs/166

Android:
* 0.9.4 (grey screen) https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/327
* 0.9.4 (grey screen) https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/312
* 0.9.2 (grey screen) https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/245
* 0.9.2 (grey screen) https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/234
* 0.9.2 (grey screen) https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/217
* 0.9.1 (grey screen) https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/146

**Comment by rasom** [comment] 2017-04-12 13:56
> Grey screen on android happens when our web3 is not properly injected, and this can happen because we don’t have any guaranty of loading of that script on android. This is not a problem, for example, for bchat, because when this app tries to connect to http://localhost:8545 everything just works. For Wallet this is a problem because of `https`

This error can't be reproduced on iOS devices because `web3` object with custom provider is always injected before page loading there.

**Comment by annadanchenko** [comment] 2017-05-16 10:33
Issue can be reproduced if turn on Developer option "Do not keep activities" in Android and put app on the background and than back. After this open Wallet and grey screen is shown. In addition, Maker Market starts to show "Not connected":
![do not keep activities](https://cloud.githubusercontent.com/assets/6584810/26102003/8bec8fec-3a33-11e7-8f39-4faa9972dd9e.png)
![not connected maker market](https://cloud.githubusercontent.com/assets/6584810/26102004/8bedfc92-3a33-11e7-810f-4825928ee232.png)
![grey wallet](https://cloud.githubusercontent.com/assets/6584810/26102005/8bf05974-3a33-11e7-9011-93ef02cb0c71.png)

Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7SlFlUkQtc0NtbFU
Log: 
[20171605115827-logcat.txt](https://github.com/status-im/status-react/files/1004019/20171605115827-logcat.txt)

Steps: 
- enable option "Do not keep activities"
- run Status
- open Wallet (see it opens fine)
- open Maker Market (see it opens fine)
- switch to some other app, so Status is on background
- switch back to Status
- open Wallet - it shows grey screen
- open Maker Market - it shows "Not connected to Ethereum"

Option "Do not keep activities" "changes the framework's behavior so it will always destroy your activity when it goes into the background or backstack. This allows you to test how your activity responds to what is normally a rare occurrence." http://stackoverflow.com/questions/22400859/dont-keep-activities-what-is-it-for

**Comment by yenda** [comment] 2017-10-19 10:49
Can this be closed with the wallet redisign @annadanchenko ?

**Comment by asemiankevich** [comment] 2017-10-20 11:33
closed as we dont have old wallet anymore

**Closed by asemiankevich** 2017-10-20 11:33 UTC
Labels: bug, intermediate, medium-priority, wallet, wontfix
