### ISSUE TITLE
Error Invariant Violation after sign in when Offline

### ISSUE THREAD

**Issue by Marina-Kovalevich** [status-im/status-react#3615] opened 2018-03-18 09:33 UTC
### Description

*Type*:Bug

*Summary*: Error "Invariant Violation:'refreshing' prop must be set as a boolean in order to use 'onRefresh',but got 'null' " after sign in Status when Offline

#### Expected behavior
User is able to sign in when offline

#### Actual behavior
Error when sign in, If tap OK blanket screen appeares.

![screenshot_2018-03-18-12-09-58-954_im status ethereum](https://user-images.githubusercontent.com/36479997/37564487-1fb0832c-2aa8-11e8-9c6d-5f10d10ac2be.png)

### Reproduction
- Open Status
- Fill in your password
- Tap Sign in

### Additional Information

* Status version: Nightly build 17/03/2018

* Operating System: Android 7.0, MIUI Global 9.2 Stable 9.2.1.0 Xiaomi Redmi Note 4

**Comment by asemiankevich** [comment] 2018-03-18 09:36
Can repro on ios as well

**Comment by antdanchenko** [comment] 2018-03-18 10:03
@Marina-Kovalevich thanks for adding an issue, however it seems to be a duplicate of https://github.com/status-im/status-react/issues/3568

**Closed as completed** 2018-03-18 11:03 UTC
