### ISSUE TITLE
"Cannot locate account for address" toast shown on transaction confirmation page after attempting to send tokens from recovered account

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20394] opened 2024-06-07 10:18 UTC
### Steps:
1. Create a derived account (derivation path example: m/44'/60'/0'/0/1).
2. Import an additional account using a seed phrase.
3. Perform a backup.
4. Restore the current account.
5. Attempt to send a transaction from any derived account or from an account imported from a seed phrase.

### Actual result:
The "Cannot locate account for address" toast message is shown, transaction is not sent
![image](https://github.com/status-im/status-mobile/assets/52490791/a2e5bb5f-f8fc-40e6-90b1-a44c2cd06bec)

### Expected result:
The transaction are sent succesfully

### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs.zip](https://github.com/user-attachments/files/15737571/Status-debug-logs.zip)

**Comment by ulisesmac** [comment] 2024-06-10 21:13
@J-Son89 
Do you know what is the issue referring to in the step 3 (perform a backup)?
Maybe this is part of wallet settings?

**Comment by smohamedjavid** [comment] 2024-06-21 15:40
(Not a bug. This is supposed to be a feature issue 😄 )


Fixed here: https://github.com/status-im/status-mobile/pull/20464

**Comment by OmarBasem** [comment] 2024-07-08 06:03
@smohamedjavid I see the PR https://github.com/status-im/status-mobile/pull/20464 was merged. Should this issue be closed?

**Comment by smohamedjavid** [comment] 2024-07-08 09:08
Yes, it's fixed 👍 and we can close this issue. Thanks! 🙏

**Closed as completed by smohamedjavid** 2024-07-08 09:08 UTC
Labels: wallet: Derivation Path, wallet-core
