### ISSUE TITLE
Refactor and update chat handlers and views

### ISSUE THREAD

**Issue by alwx** [status-im/status-react#2341] opened 2017-11-02 08:46 UTC
We can easily restructure `status-im.chat.handlers` and apply the same approach we use for events (`register-handler-fx` and reduced number of side effects). It will improve the code readability.

It can also potentially reduce the number of dispatch calls in some namespaces, for instance, `status-im.chat.views.input.input`. 

The goal of this issue is to also get rid of some leftovers in `status-im.chat`.

**Comment by janherich** [comment] 2017-11-02 08:51
@alwx PR partially solving the issue is already opened, reviewed and waiting to be merged: https://github.com/status-im/status-react/pull/2027

**Comment by alwx** [comment] 2017-11-02 08:58
@janherich this PR doesn't introduce any changes to `status-im.chat.views.input.input` and there are still usages of `side-effect!` in `status-im.chat`. The goal is to remove them as well.

**Comment by janherich** [comment] 2017-11-02 09:14
@alwx Yeah, I know it doesn't do the whole thing but there is already a lot of work regarding moving the chat handlers to more functional style, so I just wanted to make sure that you are aware of it and we are not making duplicate work (for example in your PR, just don't port those events which are already ported in my PR).

**Comment by alwx** [comment] 2017-11-02 20:06
@janherich sure, don't worry

**Closed as completed** 2018-09-21 11:02 UTC
