### ISSUE TITLE
Users don't automatically join auto-accept request communities when the owner of the community and requester go online

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#17678] opened 2023-10-18 12:48 UTC
### Description: 
Users aren't automatically joining auto-accept request communities when both the community owner and the requester go online. The problem still occurs even without users going offline - online, although it happens less frequently in such cases. The steps below replicate this issue more consistently.

### Steps:
1. `User A` is an owner of an auto-accept request community
2. `User A` shares community to `User B`
3. `User A` **goes offline** using Airplane mode
4. `User B` sends a request to join the community 
5.  `User B` **goes offline**
6. Wait 30 seconds - 1 minute
7. `User A` **goes online**
8. `User B` **goes online**
9. `User B`  checks community status

### Actual result:
`User B` is not joined to community. Community is still shown in the pending status

https://github.com/status-im/status-mobile/assets/52490791/db09bddb-229f-4fb7-a781-6126c6c218eb

### Expected result:
As soon as the community owner goes online all users requested to join the community automatically join the current community if current community is with auto-accept request

reference to feature related to this issue [here](https://github.com/status-im/status-mobile/pull/16917)

### ENV:
- Nightly 18 Oct 2023

### Additional info:
In my case, this issue is reproducible only when the community owner uses a real device (Pixel 7a, Android 13). But also it occurs during e2e tests running (here an example https://ethstatus.testrail.net/index.php?/tests/view/3261326)

### Logs from physical devices:
- Community owner (`User A`) logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13112814/Status-debug-logs.zip)

- Community requester (`User B`) logs:
[logs.zip](https://github.com/status-im/status-mobile/files/13112818/logs.zip)

### Logs from e2e failed run:
- Community owner (`Device 1`) logs:
[logcat (1).log](https://github.com/status-im/status-mobile/files/13113683/logcat.1.log)

- Community requester (`Device 2`) logs:
[logcat.log](https://github.com/status-im/status-mobile/files/13113685/logcat.log)

**Comment by churik** [comment] 2023-10-23 08:51
@VolodLytvynenko if `User A` goes offline on desktop, the issue is reproducible?

**Comment by VolodLytvynenko** [comment] 2023-10-23 09:22
> @VolodLytvynenko if `User A` goes offline on desktop, the issue is reproducible?

@churik The issue is no longer reproducible on mobile or desktop when 'User A' is offline. It seems that the last time it happened, there was a delivery issue. However, it's strange because it reproduced very easily earlier in every try even when message delivery worked perfectly for me. 
I'll close this issue until re-investigate the steps just to be sure if the issue is no longer valid.

**Comment by VolodLytvynenko** [comment] 2023-10-24 09:56
> @VolodLytvynenko if `User A` goes offline on desktop, the issue is reproducible?

this issue is not reproducible if `User A` goes offline using a desktop in my case. Looks like this issue might be device-specific or happens randomly

**Comment by pavloburykh** [comment] 2023-11-13 15:12
I have faced the issue with mobile admin node. Will check if the bug happens when admin node is Desktop.

**Comment by churik** [comment] 2023-11-21 14:44
The same happens to me with admin on desktop ([0.15 RC3 ](https://ci.infra.status.im/job/status-desktop/job/release/job/release%2F0.15.x/14/))

After admin goes back online, the request is Pending and the state is not changing **until desktop re-logins**

**Comment by qfrank** [comment] 2023-11-29 07:36
FYI, i don't have such issue  with local waku node, thought i can reproduce it with local waku node so i can go in deep 😅

**Comment by pavloburykh** [comment] 2023-12-06 10:12
Comment from closed duplicate issue https://github.com/status-im/status-mobile/issues/18087#issue-2028120361

As reported by @yevh-berdnyk 

### Problem

Steps:

- User A creates an open community and invites User B
- User A goes offline
- User B requests to join this community
- User A goes back online

Actual result:
  Community is shown as pending endlessly
  
Expected result:
User B has joined the community
[user_A_logcat.log.zip](https://github.com/status-im/status-mobile/files/13572071/user_A_logcat.log.zip)
[user_B_logcat.log.zip](https://github.com/status-im/status-mobile/files/13572073/user_B_logcat.log.zip)
[user_A_geth.log.zip](https://github.com/status-im/status-mobile/files/13572090/user_A_geth.log.zip)
[user_B_geth.log.zip](https://github.com/status-im/status-mobile/files/13572095/user_B_geth.log.zip)
Note: As we can create communities only on e2e mobile builds I need also a desktop build with this status-go version to check this functionality

Related to PR : https://github.com/status-im/status-mobile/pull/17773

**Comment by pavloburykh** [comment] 2023-12-06 10:13
Andrea's comment from closed duplicate issue https://github.com/status-im/status-mobile/issues/18087#issuecomment-1842523813

@siddarthkay 
```
ERROR[12-05|04:05:07.134|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:162]                                          Error getting new mailserver             error="error during polling loop: recvfrom: socket operation on non-socket"
```

**Comment by siddarthkay** [comment] 2023-12-19 14:44
@VolodLytvynenko @pavloburykh  can you check if this issue is still reproducible ?

**Comment by pavloburykh** [comment] 2023-12-19 15:10
> @VolodLytvynenko @pavloburykh can you check if this issue is still reproducible ?

@siddarthkay we have recently faced failed e2e because of this bug. So I believe it is still there. @VolodLytvynenko will provide more info on manual reproduction.

**Comment by siddarthkay** [comment] 2023-12-19 15:13
Awesome! Thanks for confirming

**Comment by VolodLytvynenko** [comment] 2023-12-19 16:05
> @siddarthkay we have recently faced failed e2e because of this bug. So I believe it is still there. @VolodLytvynenko will provide more info on manual reproduction.

@pavloburykh @siddarthkay I can't reproduce this issue manually anymore. Previously, it was easy to do so, especially when users returned from offline, as described here: https://github.com/status-im/status-mobile/issues/17678#issue-1949673649

**Comment by pavloburykh** [comment] 2023-12-19 16:17
Thank you @VolodLytvynenko! @siddarthkay let's keep this issue open anyway. Once we have some update we will post it here.

**Comment by qoqobolo** [comment] 2024-01-03 15:28
Keep facing this problem in e2e with the same steps:

1. User A creates an open community and invites User B
2. User A goes offline
3. User B requests to join this community
4. User A goes back online

Adding logs from the test https://ethstatus.testrail.net/index.php?/tests/view/3320253

UserA (admin):
[test_community_join_when_node_owner_offline_geth1.log.zip](https://github.com/status-im/status-mobile/files/13820695/test_community_join_when_node_owner_offline_geth1.log.zip)

UserB:
[test_community_join_when_node_owner_offline_geth2.log.zip](https://github.com/status-im/status-mobile/files/13820696/test_community_join_when_node_owner_offline_geth2.log.zip)

cc @siddarthkay

**Comment by siddarthkay** [comment] 2024-01-03 15:30
Thanks for confirming @qoqobolo : I'll take a look

**Comment by pavloburykh** [comment] 2024-02-01 15:53
closing as issue is not reproducible anymore

**Closed as completed by pavloburykh** 2024-02-01 15:53 UTC
Labels: e2e test blocker, community, status-go
