### ISSUE TITLE
Error Null is not an object (evaluating 'c.greaterThanOrEqualTo') is displayed when trying to send ETH offline

### ISSUE THREAD

**Issue by ReneeAB** [status-im/status-react#2631] opened 2017-12-06 13:24 UTC
### Description

*Type*: Bug

*Summary*: 
When the user is not connect to the wifi, Error Null is not an object (evaluating 'c.greaterThanOrEqualTo') is displayed when trying to send ETH from the wallet.

#### Expected behavior

The user should be able to enter an amount and a recipient before signing in.

#### Actual behavior
The error message prevent the user to select a recipient or an amount.

### Reproduction

- Open Status and set up account
- Turn off the Wifi
- Click Switch users
- Login back to the same account go to the "Wallet", tap "Send".
- Select a recipient then enter an amount (or enter the amount first then the recipient) right after the "Error Null is not an object" message is displayed.

![img_2](https://user-images.githubusercontent.com/33925578/33663407-c2b397ec-da87-11e7-8c31-3230520aa8e6.png)

![screenshot_3](https://user-images.githubusercontent.com/33925578/33663497-24f1007a-da88-11e7-898e-2599db96935d.png)

![screenshot_4](https://user-images.githubusercontent.com/33925578/33663560-63fbef8c-da88-11e7-9efd-d4f733d9583a.png)

### Additional Information

* Status version: 0.9.12 (1557.321)

* Operating System: Android and iOS

**Comment by asemiankevich** [comment] 2017-12-06 14:05
Hey @ReneeAB ! 

Thank you for your time spent on this bug report, could you please add more details how to reproduce it? OS version and device would be bunch of help!

**Comment by graemerycyk** [comment] 2017-12-06 18:43
@asemiankevich 

I have been able to reproduce this on iOS 11.2 & iPhone SE if this helps.

Reproducing seems pretty straightforward, this was how I got this error message to appear, ETH seems to be the issue, and not being offline, I think...

Preconditions: I guess being offline isn't required, as I can reproduce this error message when online, I think wallet just needs to be empty.

Steps:
* Open Status and Login
* Then go to the "Wallet" tab
* Press "Send" segment
* The "Amount text field will begin focus and a numeric keypad should be visible
* Type the digit 1
* "Error null is not an object (evaluating 'c.greaterThanOrEqualTo')" will be visible as an app alert

EXTRA:
You can also get this error after pressing OK to the first error mentioned above then selecting a recipient and trying to select a contact.

**Comment by graemerycyk** [comment] 2017-12-06 18:49
@asemiankevich @ReneeAB I would suggest trying to reproduce this with a fresh install and as new user, as it looks like this is not longer reproducible after you do this:

* Open Status and Login
* Then go to the "Wallet" tab
* Press "Send" segment
* The "Amount text field will begin focus and a numeric keypad should be visible
* Type the digit 1
* "Error null is not an object (evaluating 'c.greaterThanOrEqualTo')" will be visible as an app alert
* Press OK
* Select a contact
* "Error null is not an object (evaluating 'c.greaterThanOrEqualTo')" will be visible as an app alert (again)
* Press OK (again)
* Contacts modal will close

Then this issue won't be reproducible (or it wasn't for me)

**Comment by graemerycyk** [comment] 2017-12-06 18:59
Figured it out, offline is the best way to reproduce this in fact but the cause is due to this ... you see in the USD on the main wallet screen. Offline is causing an issue with the calculation (guessing here), but what happens is it leads to a null value in the wallet and then throwing the user that error.

![img_f8528a11cd75-1](https://user-images.githubusercontent.com/10434839/33679731-d7b4cfd4-dabf-11e7-99c1-e1238282dffb.jpeg)

I think I have narrowed this one down.

**Comment by ReneeAB** [comment] 2017-12-06 20:22
Hi @grycyk you are right, I haven't been able to reproduce it again with my two users, I guess each user will see the issue one or two times then, it will not be reproducible. Thanks for your explanation.

**Comment by asemiankevich** [comment] 2017-12-07 07:42
@ReneeAB @grycyk I can't reproduce it with my iOS 11.11 , will update the device and dig more. Thank you!

**Comment by graemerycyk** [comment] 2017-12-07 09:32
@asemiankevich this might help you? -> http://share.xctest.io/mT9lsY

**Comment by asemiankevich** [comment] 2017-12-07 11:42
@grycyk yes, appreciate that. That makes a lot of sense

**Comment by asemiankevich** [comment] 2017-12-07 11:57
I checked latest develop http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk and the issue is not there. I assume it is fixed in develop build but it is taking place in `0.9.12` release.

**Comment by graemerycyk** [comment] 2017-12-07 11:59
Ok lmk when there is a new testflight build and i can retest if you need.

**Comment by annadanchenko** [comment] 2017-12-07 22:42
I can confirm that issue exists in 0.9.12 (can reproduce on iOS) and does not exist in nightly develop build from Dec 07. Closing it as can't reproduce on more recent version, so nothing to fix. Thank you @ReneeAB and @grycyk for reporting and digging into it!

**Closed as completed by annadanchenko** 2017-12-07 22:42 UTC
