### ISSUE TITLE
Bottom tabs are overlayed by the main screen (reproduced on Android emulator)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15762] opened 2023-04-26 15:42 UTC
@Parveshdhull would appreciate if you take a look when have a chance.

Reproduced this bug on emulated Android (Size 5", Resolution: 1080*1920, Density: xxhdpi), but there is a chance that it can be reproduced on some physical devices. 

<img width="350" alt="Android Emulator - my_emu_nex_API_32:5554 2023-04-26 17-32-17" src="https://user-images.githubusercontent.com/97245802/234624558-3b7afe3f-1ef3-4e44-9cf9-35ac5322dc23.png">

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment] 2023-04-26 16:52
duplicate of https://github.com/status-im/status-mobile/issues/15164

**Closed as completed by Parveshdhull** 2023-04-26 16:52 UTC
