### ISSUE TITLE
[Android] Scroll starts lagging in a chat with a long message

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16185] opened 2023-06-05 15:17 UTC
### Bug Description:
After leaving or performing long tap-on reactions in a long message, the app experiences a lag and slow performance.

### Steps to Reproduce:
1. Open a chat conversation with a long message 
2. Leave all reactions on the message
3. Perform a long tap on a few reactions in the message.
4. Tap each reaction randomly on the 'who sent' screen
5. Scroll the message that is shown upper of 'who sent' screen
6. Observe the app's performance.

### Actual Result:
Upon leaving, long-tapping the reactions on a message or tapping the reactions within 'who sent' page, the app lags and exhibits noticeable performance degradation

https://github.com/status-im/status-mobile/assets/52490791/6649be0f-d040-4981-8922-bfaa5d0856e7

### Expected Result:
The app should remain responsive and perform smoothly after interacting with reactions.

### Device:
- Real device: Pixel 7a, Android 13

### ENV:
Nightly 5 Jun 2023

**Comment by rasom** [comment] 2023-06-06 14:40
When it comes to communities on my Android device in dev env chat screen is extremely slow right away after sending some messages, even if there was no interaction with emojis.

**Comment by rasom** [comment] 2023-06-06 15:43
On the other hand, after re-login I can't reproduce the issue at all.

**Comment by rasom** [comment] 2023-06-07 08:12
@VladimrLitvinenko so with those specific steps I can't reliably reproduce those performance issues. Maybe some steps or conditions are missing.

**Comment by VolodLytvynenko** [comment] 2023-06-07 08:59
> @VladimrLitvinenko so with those specific steps I can't reliably reproduce those performance issues. Maybe some steps or conditions are missing.

Understood. It appears that the performance issue is specific to certain devices. I have successfully reproduced it on a real device, specifically the Pixel 7a on Android 13. However, I have not been able to replicate it on devices within Android Studio. It's worth noting that @qoqobolo , who also uses a Pixel 7a with Android 13, consistently experiences these performance issues.

I will try to investigate it on more devices on Android Studio and maybe will be lucky to reproduce it there

**Comment by rasom** [comment] 2023-06-07 09:09
I tested it on Redmi, will try on Samsung now.

**Comment by rasom** [comment] 2023-06-08 09:15
still can't reproduce

**Comment by qoqobolo** [comment] 2023-06-08 10:56
I can easily reproduce lagging scroll with these steps, but only on Pixel 7a (which also heats up when it starts lagging):

1. Send a long message / open a channel with a long message
2. Start scrolling the screen up and down

In the video, you can see that the scroll starts lagging in less than a minute

https://github.com/status-im/status-mobile/assets/67952253/402c943e-0874-4946-92bb-0aaea4c8051b

**Comment by qoqobolo** [comment] 2023-06-08 11:07
Since it was decided that the user experience should be the best on Pixel 7a, this issue should be fixed as it is easily reproducible and makes the chat unusable.

**Comment by pavloburykh** [comment] 2023-06-08 11:07
> When it comes to communities on my Android device in dev env chat screen is extremely slow right away after sending some messages, even if there was no interaction with emojis.

In my case interaction with interface (scrolling/bottom sheet opening/composer expand etc) is quite laggy too (Android 12, Samsung Galaxy A52) espacially in case with long messages in chat history. And it remains laggy even after app re-opening.  

Although it is not even close to those laggs that occur on Pixel devices reprorted by @VladimrLitvinenko and @qoqobolo  I beleive we still need to handle such performance issues as it has impact on user experience.

**Comment by rasom** [comment] 2023-06-12 08:40
maybe related https://github.com/facebook/react-native/issues/30034

**Comment by rasom** [comment] 2023-06-12 08:42
claimed fix https://github.com/AudiusProject/audius-client/pull/3457/files

**Closed as completed** 2023-06-13 15:18 UTC
