### ISSUE TITLE
Flickering dark stripes appear when navigating throughout Profile screen [Android]

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19118] opened 2024-03-06 11:49 UTC
Reproducing on Android 12, Samsung Galaxy A52, Pixel 7a, Huawei P40 lite

**Steps:** 

1. Navigate to Profile screen
2. Open any other screen, i.e. Edit profile
3. Go back to Profile main screen
4. Pay attention at dark stripes in the left part of the screen with appear during back navigation to Profile page

**Actual result:** 

1) Vertical dark stripes in the left part of the screen appear during back navigation to Profile page

https://github.com/status-im/status-mobile/assets/97245802/c43dd60e-5d39-4833-9c6d-bb63f455cb12

2) Horisontal flickering dark stripes appear when opening and closing Profile screen. Slow mo video is recorded on Pixel 7a:

https://github.com/status-im/status-mobile/assets/97245802/92bfd72f-ed6c-4c60-a530-bd271e819fdb

### Additional Information

- Status version: nightly 
- Operating System: Android 12

**Comment by seanstrom** [comment] 2024-03-18 15:48
@pavloburykh Is this issue reproducible with a simulator or does it require one of those mentioned hardware devices?

**Comment by pavloburykh** [comment] 2024-03-19 08:36
> @pavloburykh Is this issue reproducible with a simulator or does it require one of those mentioned hardware devices?

Hi @seanstrom! I didn't reproduce it on emulator. By default we perform testing on real devices and videos from description are captured on hardware devices.

**Comment by cammellos** [comment] 2024-04-11 13:34
@churik this looks like low-priority/wont-fix, what do you think?

**Comment by cammellos** [comment] 2024-04-30 08:24
Closing as low priority, feel free to reopen if you think otherwise

**Closed as completed by cammellos** 2024-04-30 08:24 UTC
Labels: android, profile
