### ISSUE TITLE
Plain text instead of map is shown to recipient of location command [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1469] opened 2017-07-18 13:32 UTC
### Description

*Type*: Bug

*Summary*: Plain text instead of map is shown to recipient of location command in 1-1 and group chats. There is special condition: Recipient should not have 1-1 chat screen opened when location is sent to him. After message is received then chat screen should be opened. Currently, plain text is shown to recipient even if wait for several seconds. For sender the expected map is shown. After app is re-launched on recipient's side the expected map is shown after several seconds. Issue exists if send message from iOS to iOS device, from Android to iOS and from iOS to Android.

![plain](https://user-images.githubusercontent.com/6584810/28319304-cacec934-6bcd-11e7-9ee3-d12c0aaf366e.jpg)

#### Expected behavior
Map is shown
#### Actual behavior
Message with plain text is shown

### Reproduction
TestFairy session sender: https://app.testfairy.com/projects/4803590-status/builds/6196610/sessions/12/?accessToken=ey94qfXsTMPdCIBqapo0J07XyGs
TestFairy session recipient: https://app.testfairy.com/projects/4803590-status/builds/6196610/sessions/13/?accessToken=KOPZh4WX4QF6E/Q23hlE6qI5kF4
- Open Status
- As recipient: Open Chats. Do NOT open 1-1 chat
- As sender: Open 1-1 chat and send `/location Amsterdam` or select some address on the shown map and send it
- As recipient: open 1-1 chat and check the received message

### Additional Information
* Status version: develop  0.9.9d100
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by sla-shi** [comment] 2017-07-27 12:44
@annadanchenko can you please verify this again, it seems to be fixed now.

**Comment by annadanchenko** [comment] 2017-07-27 13:30
@sla-shi issue can be reproduced on today's develop build with some extra condition. I've updated the description and added 2 TestFairy sessions for issue sender/recipient

**Comment by asemiankevich** [comment] 2017-08-03 12:10
I can reproduce the case when app is re-launched on recipient's side the expected map is shown after several seconds

https://app.testfairy.com/projects/4803590-status/builds/6251318/sessions/8?source=latest-sessions

**Closed** 2017-08-15 16:27 UTC
Labels: bug, high-priority, Tested - OK
