### ISSUE TITLE
"Invalid event protocolMembershipUpdateEvent..." error is shown after invited to the group chat user sends the message

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14574] opened 2022-12-19 12:09 UTC
**Steps to reproduce:**
1. Check the status.prod fleet is set for USER_A and USER_B
2. Make USER_A and USER_B mutual contacts
3. Create a group chat as USER_A -> Invite USER_B 
4. Open group chat as USER_B
5. Send the message

**Actual result:**
"Invalid event protocolMembershipUpdateEvent..." error is shown

https://user-images.githubusercontent.com/52490791/208422879-1912a44f-7d28-4f6f-b7e9-48d2e82bc5c3.mp4

**Logs:** [geth.log](https://github.com/status-im/status-mobile/files/10259099/geth.log)

**Expected result:**
The message is sent

**ENV:** any android

**Additional info:**
- Reproduced only in 10% of cases. Maybe logs can help to understand the error
- The current issue happens for USER_B only for 1st group chat. If it is not reproduced during message sending in the group chat, then the user should be re-created and steps from 'steps to reproduce' should be repeated again

**Comment by pavloburykh** [comment] 2022-12-19 17:35
This issue results in constant failing of group e2e tests. 
![photo_2023-01-03 16 23 44](https://user-images.githubusercontent.com/97245802/210376127-41f1f0b6-1d2b-4e8b-a0e2-1997c47db8bf.jpeg)

**Comment by churik** [comment] 2023-01-03 13:27
@rasom  in case you have a chance to look at it

**Comment by qfrank** [comment] 2023-01-03 13:31
@churik did it happen on ios?

**Comment by churik** [comment] 2023-01-03 13:37
I haven't faced it on IOS and in description only android is mentioned, so I suppose that it is Android-specific bug

**Comment by qfrank** [comment] 2023-01-03 13:39
then i can't help ATM, as i got a problem building for android on M1 macbook  ):

**Comment by pavloburykh** [comment] 2023-01-03 13:42
@qfrank the bug is reproducible both on IOS and Android

**Comment by qfrank** [comment] 2023-01-03 13:46
then i may take a look tomorrow if @rasom won't take it

**Comment by qfrank** [comment] 2023-01-06 12:13
Hi @rasom , i can't reproduce this issue, can u take a look? thanks

**Comment by rasom** [comment] 2023-01-06 12:56
I will take a look on Monday

**Comment by VolodLytvynenko** [comment] 2023-01-09 10:36
Hi @rasom it is become harder to catch this issue. To reproduce it I use 3 devices (android studios can help here)
**Steps to reproduce:**
1. Create USER_A, USER_B, USER_C
2. Using USER_A Send requests to USER_B and USER_C
3. Accept both requests
4. Using USER_A create group chat inviting USER_B and USER_C
5. Send a message in the group chat as each user

**Actual result:** 
Error is shown for at least one user

**Expected result**
Messages are successfully sent

**ADDITIONAL INFO:**
I was not able to reproduce it for IOS, but for androids it is reproducible in 50% of cases for me. Try to use only androids to catch it

**Comment by rasom** [comment] 2023-01-09 11:03
As far as I understand from the output, this happens because, for instance, USER_B joins group chat while USER_C still doesn't know that USER_B was added.

**Comment by VolodLytvynenko** [comment] 2023-01-09 11:26
> As far as I understand from the output, this happens because, for instance, USER_B joins group chat while USER_C still doesn't know that USER_B was added.

I don't think so. This happens even without USER_C and sometimes it's enough just to use 2 users. I added the case with the third user (USER_C) for the ability to increase the percentage to reproduce this issue. The more users are invited into the group, the more possibility to catch this issue

**Comment by rasom** [comment] 2023-01-09 12:57
well... I can't even start a chat in `develop`, can't sent a ,message... how do you test it?

**Comment by pavloburykh** [comment] 2023-01-09 13:03
> well... I can't even start a chat in `develop`, can't sent a ,message... how do you test it?

Hi @rasom ! Start chat functionality on chats tab is currently not working. Please, use community tab to start a chat: tap Community tab - Plus button - create group chat

Also, keep in mind that in order to add chat members to the group, users should be mutual contacts.

**Comment by rasom** [comment] 2023-01-09 14:41
thanks, I managed to reproduce it

**Comment by rasom** [comment] 2023-01-10 11:43
@VladimrLitvinenko ok, you are right, the reason is that `MEMBER_JOINED` event he's lower clock value than `CHAT_CREATE` and `MEMBERS_ADDED`.

As a result when the group is initialised (and that for some reason requires rerunning all events again each time new message is received), `MEMBER_JOINED` "happens" before group is "created" and so error occurs.

Now I'm trying to figure out how to fix this.

**Comment by VolodLytvynenko** [comment] 2023-01-10 11:50
> @VladimrLitvinenko ok, you are right, the reason is that `MEMBER_JOINED` event he's lower clock value than `CHAT_CREATE` and `MEMBERS_ADDED`.
> 
> As a result when the group is initialised (and that for some reason requires rerunning all events again each time new message is received), `MEMBER_JOINED` "happens" before group is "created" and so error occurs.
> 
> Now I'm trying to figure out how to fix this.

Oh, thank you very much for debugging. A really annoying issue that needs to  be fixed :) Let me know when I should recheck it

**Comment by rasom** [comment] 2023-01-10 20:18
@VladimrLitvinenko it should be fixed in https://github.com/status-im/status-mobile/pull/14750

**Closed as completed** 2023-01-12 18:09 UTC
Labels: ios, android, e2e test blocker, messaging
