### ISSUE TITLE
Status Console invalid error messages

### ISSUE THREAD

**Issue by juliomvr** [status-im/status-react#5146] opened 2018-07-12 01:19 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user and/or developer, I want to see a correct error message when using the Status Console.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...
When opening the Status console and start using it sometimes when and invalid command is typed the error message that is currently being displayed doesn't give any valuable information.

For example: open the Status Console and type "Help", you will get a message saying: "{:line 1, :Column 5}"

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If an invalid command is typed on the console a different message should be added, for example "Invalid Command" or "undefined command" so the user knows that command doesn't exists and the error is not caused by the app

#### Actual behavior
[comment]: # (Describe what actually happened.)
When an invalid command or a bad used command are typed error message with no meaning are being displayed.

For example:
Command         ----    Message
help                  -    "{:line 1, :Column 5}"
console            -   "{:line 1, :Column 8}"
web3.isConnected()     -   "{:line 394, :Column 22583}"

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to Status Console "Chat"
- type words like: console, help, status or even commands like web3.isConnected()

you will get error messages with no meaning for an user 

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- Better Error messages on the console

### Additional Information

* Status version: 0.9.22
* Operating System: Android 8.1
* Device: Google Pixel 2 XL

**Comment by annadanchenko** [comment] 2018-07-13 10:23
duplicate of https://github.com/status-im/status-react/issues/2622

**Closed as completed by annadanchenko** 2018-07-13 10:23 UTC
