### ISSUE TITLE
Not possible to Change gas price in Dapp transactions

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#4602] opened 2018-06-02 21:51 UTC
### User Story

As a user, I want to set a higher gas price so that my transaction is less likely to be frontrunned or get too late.

### Description

*Type*: Bug

*Summary*: at sign transaction screen I want to easily adjust gas price.

#### Expected behavior

Gas price editable for dapp transactions

#### Actual behavior

Gas price not editável for dapp transactions

### Reproduction

Try buy a cryptokitty with higher gas price.

**Comment by goranjovic** [comment] 2018-06-03 09:47
duplicate of #4065

**Closed as completed by goranjovic** 2018-06-03 09:47 UTC
