### ISSUE TITLE
Low contrast in activity center colors

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#14684] opened 2022-12-31 10:13 UTC
Low contrast in activity center text, Text is really hard to read

![image](https://user-images.githubusercontent.com/33176106/210132951-025f744e-3c29-47b0-9c7c-1112f8df6c00.png)

**Comment by flexsurfer** [comment] 2022-12-31 11:47
@ibrkhalil is it a bug or is it by design ?

**Comment by flexsurfer** [comment] 2022-12-31 11:48
also status-bar color looks wrong

**Comment by ibrkhalil** [comment] 2022-12-31 13:24
> @ibrkhalil is it a bug or is it by design ?

If it's the proposed design then we need to change it

**Comment by flexsurfer** [comment] 2022-12-31 14:03
сс @pedro-et @xAlisher

**Comment by ilmotta** [comment] 2023-01-04 22:23
This is a subtle bug, quite easy to fix @ibrkhalil. The text components inside the `empty-tab` component need to explicitly specify a color for dark mode, because the Activity Center is designed for dark mode only.

Here's where we should fix: https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/activity_center/view.cljs#L34

**Comment by smohamedjavid** [comment] 2023-03-03 18:18
This issue is fixed in https://github.com/status-im/status-mobile/pull/14916

**Closed as completed by smohamedjavid** 2023-03-03 18:18 UTC
