### ISSUE TITLE
Flow stuck after repairing keycard

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-react#13738] opened 2022-07-29 07:06 UTC
# Bug Report
## Problem

Flow seems broken/unresponsive when repairing keycard at sign in.

## Reproduction

1. Unpair keycard using keycard connect
2. Sign out of Status
3. Sign in Status with keycard
4. Get error that keycard is not paired, follow the flow to pair keycard
5. Enter keypair code, enter pin, tap keycard (in whichever order the flows ask)
6. Then it just remains on a screen (sorry did not screenshot) which header "1 out of 2" and with the pairing code in the middle of the screen
7. wait.. nothing happens
8. do back... ah, I am signed in

### Additional Information

- Status version: 1.19.0
- Operating System: Android

**Comment by qoqobolo** [comment] 2022-08-01 09:11
@fryorcraken thanks for reporting this!

Can reproduce it on Nightly 1/08/22 using the `Unpair Others` option in Keycard Connect

<img width="391" alt="Screenshot 2022-08-01 at 11 09 42" src="https://user-images.githubusercontent.com/67952253/182114623-6f3d4191-1a32-4e4b-bbba-a79c22d768eb.png">

https://user-images.githubusercontent.com/67952253/182114270-49ee9873-ee6c-4ec5-affb-c5d99a514b45.mp4

**Comment by churik** [comment] 2023-06-01 10:00
Closing because of redesign

**Closed as completed by churik** 2023-06-01 10:00 UTC
