### ISSUE TITLE
Emoji and text keyboards are shown in the same time after specific scenario

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1624] opened 2017-08-16 11:05 UTC
### Description

*Type*: Bug

*Summary*: Both emoji and text keyboard are shown after sending transaction, emoji and tap inside input field

![screenshot_20170816-095721](https://user-images.githubusercontent.com/6584810/29360513-8d608692-8283-11e7-87cb-5e098e8f9a2d.png)

#### Expected behavior
only 1 keyboard is shown: text 
#### Actual behavior

2 keyboards (text and emoji) are shown
### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/6366923/sessions/5/?accessToken=NL2nvoYR64RQ2k/7e/fWHA-R3tY
- Open Status
- Open 1-1 chat
- Send x eth, confirm transaction, type correct password
- Tap on "Got it" button after transaction was sent
- in 1-1 chat tap on emoji icon in the input field
- tap on several emojis and send them by tapping on send icon
- tap inside input field (to get text keyboard shown) 

### Additional Information
* Status version: release 0.9.10 and develop 0.9.8-137-g9bacc65c 
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.3.3

**Comment by janherich** [comment] 2017-09-11 08:43
Can't reproduce on #1710 branch.

**Comment by asemiankevich** [comment] 2017-10-04 14:05
I can't reproduce this in latest develop `0.9.10-162-gcede0957+`, closing

**Closed as completed by asemiankevich** 2017-10-04 14:05 UTC
Labels: Tested - OK
