### ISSUE TITLE
Password request message is not shown after application is launched after install

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2925] opened 2018-01-05 13:38 UTC
### Description

*Type*: Bug

*Summary*: we have this issue appears from time to time and there are several issues closed for this https://github.com/status-im/status-react/issues/2049, https://github.com/status-im/status-react/issues/1130 for example and this issue is stable to reproduce in `release build ` from Jan 5 2018

https://jenkins.status.im/job/status-react/job/release/job/release%252F0.9.13/1/

#### Expected behavior
I can set up password

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/34611451-9cca6062-f236-11e7-9415-55329ada3534.png)

### Reproduction
- Open Status

### Additional Information

* Status version: release build 0.9.13 from Jan 5 2018
* Operating System: Android

**Comment by oskarth** [comment] 2018-01-05 16:19
Can reproduce on release build 3. Workaround is to already have an account...

**Comment by annadanchenko** [comment] 2018-01-07 21:29
1. Password request is not shown on iOS devices (tried on iPhone 6s, iOS 10.3.3 and iPhone 7 plus, iOS 11.0.3)
Release build 5 
https://jenkins.status.im/job/status-react/job/release/job/release%252F0.9.13/5/console
No TF sessions are recorded

2. Password request is shown on Android device on the same build (Pixel XL, Android 8.1.0) in 4 out of 5 attempts. On the failing attempt there was an error shown `bot.js loading failed console ReferenceError: 'status' is not defined` after this no password request was shown. TF: https://app.testfairy.com/projects/4803622-status/builds/7443571/sessions/127/?accessToken=UrKoIhO1b8UMpkoV-VWr3Qf53gU

**Comment by oskarth** [comment] 2018-01-08 06:28
Gonna try to reproduce and look into this, but since it is bug fixing day and this is high-priority I think it'd be fine if someone else looked into it as well.

**Comment by oskarth** [comment] 2018-01-08 07:14
Repro on release build:
- Remove app from phone
- Install Release build 5 on iPhone X (iOS: https://i.diawi.com/MQaoL1)
- Try to setup password
- Click allow notifications
- No password prompt

Also repro locally on release branch with `cp .env.prod .env`. Logs: https://gist.github.com/oskarth/d472e5b42503e62e5df979a6662ddbe4

Hypothesis: something is different in .env that surfaces behavior (JSC? logs? dev?). Testing.
  
UPDATE: Hypothesis tentatively confirmed. Setting LOG_LEVEL_STATUS_GO=info and JSC_ENABLE=1 makes it unable to repro for N=1. Hypothesis 2: Diff code path for JSC off surfaces some bug / UI thread SNAFU.

UPDATE 2: Found issue, submitting PR.

**Comment by pedropombeiro** [comment] 2018-01-08 13:47
@oskarth what do you think about merging https://github.com/status-im/status-react/pull/2946 instead of https://github.com/status-im/status-react/pull/2939, since that achieves the original goal in https://github.com/status-im/status-react/pull/2803#issuecomment-354145328?

**Comment by oskarth** [comment] 2018-01-08 13:50
@PombeirP Thanks for quick PR! However, right now we are going to merge #2939 since:

- It fixes root issue (which blocks people from using app/release branch)
- Has been tested by QA
- Default user flag (good practice)

But we will also review and test your PR :)

**Comment by oskarth** [comment] 2018-01-13 09:51
Already fixed in develop and release but https://github.com/status-im/status-react/pull/2946 fixes additional stuff.

**Closed as completed by oskarth** 2018-01-13 09:51 UTC
