### ISSUE TITLE
Mention list moved to the center of the screen in chat view

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19252] opened 2024-03-14 11:16 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)
Mentioned list is not on the right place and overlaps sent messages 

#### Expected behavior
Mentioned list looks as designed [here](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=2102-171080&mode=design&t=VU4GLu04l1c0wQVc-0)
<img width="227" alt="Screenshot 2024-03-14 at 12 09 04" src="https://github.com/status-im/status-mobile/assets/147824399/99bcbb76-4eda-4cee-b6f8-469479c3a5e2">

#### Actual behavior
Mentioned list moved to the center of the screen in 1to1 chats and communities
<img width="329" alt="Screenshot 2024-03-14 at 12 10 50" src="https://github.com/status-im/status-mobile/assets/147824399/5f97abf4-03fe-497e-b08b-b00fda04f562">

### Reproduction

1. Login to app
2. Go to 1 to 1 chat/group chat and communities
3. Type "@" to your composer

### Additional Information

- Status version: nightly (14.04)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by BalogunofAfrica** [comment] 2024-03-21 10:03
Issues seems to be more related to composer.

I was able to reproduce only if I have mention list and I swipe composer up and then down back. Otherwise, mention list behaves as expected.


![ezgif-2-1e530ee65a](https://github.com/status-im/status-mobile/assets/45393944/01b75d32-e7b2-4f9b-8f84-6e2b2ec61ec4)

**Comment by qoqobolo** [comment] 2024-03-25 10:27
> Issues seems to be more related to composer.
>
> I was able to reproduce only if I have mention list and I swipe composer up and then down back. Otherwise, mention list behaves as expected.



Thanks @BalogunofAfrica , the original bug is indeed no longer reproducible. I'm closing this issue, we'll create another one later with the steps you described

**Closed as completed by qoqobolo** 2024-03-25 10:27 UTC
Labels: chat
