### ISSUE TITLE
Can't Chat with non-contact user from Public Chat

### ISSUE THREAD

**Issue by naghdy** [status-im/status-react#6004] opened 2018-09-26 08:54 UTC
### User Story

Find a user in a group chat, click their name and start chatting with them.

### Description

# Bug

I find a user in a group chat, then tap their avatar to chat with them. After I click "Send Message" it takes me to an empty chat window. However anything I type, doesn't end up going through

#### Expected behavior
Messages should go through when I'm trying with him.

#### Actual behavior
Messages aren't seen

### Reproduction
1. Find user (not in your contacts) in a group chat
2. Click Avatar
3. Click "Send Message"
4. Type message
5. Send message

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: unsure
* Operating System: Mac OS X
<img width="1229" alt="screen shot 2018-09-26 at 10 51 34 am" src="https://user-images.githubusercontent.com/32269875/46068766-3427e200-c17a-11e8-8412-ed98a7bf0575.png">
<img width="1229" alt="screen shot 2018-09-26 at 10 51 41 am" src="https://user-images.githubusercontent.com/32269875/46068764-3427e200-c17a-11e8-8356-efd0519cf25b.png">
<img width="1230" alt="screen shot 2018-09-26 at 10 51 51 am" src="https://user-images.githubusercontent.com/32269875/46068763-3427e200-c17a-11e8-860c-5c202be2e392.png">

**Comment by churik** [comment] 2018-09-26 09:20
Closed as duplicate of https://github.com/status-im/status-react/issues/5645
Fixed after merge of https://github.com/status-im/status-react/pull/5782

**Closed as completed by churik** 2018-09-26 09:20 UTC
