### ISSUE TITLE
Enable biometrics from settings without password

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19084] opened 2024-03-04 10:24 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)
Follow up to https://github.com/status-im/status-mobile/pull/18258

Currently, when enabling biometrics from the password settings, the user is prompted to enter their password, which is different from the figma user flows.

This is necessary due to us using having to store the password in the keychain so that during the log-in flow, the successful biometrics check would log the user in with the keychain password. One way to avoid that is to always store the password during onboarding, not only if the user enables biometrics, and never delete the password from the keychain (currently we delete it when disabling biometrics and when logging out). 

This could have security implications, so it should be discussed with the design team and the CCs (in the discord `#biometrics` channel).

#### Expected behavior

The password is **not** prompted when the user enables biometrics in the password settings

#### Actual behavior

The password is prompted when the user enables biometrics in the password settings

**Comment by flexsurfer** [comment] 2024-05-13 08:10
@clauxx could you please elaborate, i see the password in figma
<img width="927" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/c2c3260a-a947-417e-a3a6-61fc6447668e">

https://www.figma.com/file/JlpPhJp0SMnEyBQy4nOZHo/Settings-for-Mobile?type=design&node-id=7212%3A149947&mode=design&t=JDdq7AtuF6AICoJX-1

**Comment by clauxx** [comment] 2024-05-13 08:17
@flexsurfer we adapted the designs to include the password cause it was easier/quicker at the time, but originally it wasn't there. It was needed because the password was necessary for enabling the biometrics and we didn't want to make all users store it in the keychain, hence we're prompting the user every time. Here we should find a way to do it without (i guess storing the hashed password in the keychain when the user adds the password during onboarding)

CC @cammellos

**Comment by flexsurfer** [comment] 2024-05-13 08:45
thank you, then we should descope it from release I guess

**Comment by flexsurfer** [comment] 2024-05-13 08:47
This is not exactly a very frequent action; usually biometric is enabled in onboarding so I would keep password for enabling onboarding from settings for security reasons

**Comment by flexsurfer** [comment] 2024-05-13 09:57
@churik should we remove this from 2.29?

**Comment by cammellos** [comment] 2024-05-15 08:55
removing from milestone

**Comment by ilmotta** [comment] 2024-10-08 07:17
I'm closing this issue as _not planned_ because this issue is not a bug, but rather a potential feature  (although questionable due to security implications as already mentioned).

**Closed as not planned by ilmotta** 2024-10-08 07:17 UTC
Labels: feature, onboarding, profile, mobile-core
