### ISSUE TITLE
Incoming token transactions are shown as outgoing ETH transactions in wallet -> transactions history

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#6835] opened 2018-11-21 17:45 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: For token transactions data of normal transactions is shown and expected data is not.
For example:
Here is incoming STT transaction:
https://ropsten.etherscan.io/tx/0x89dd2d0937d7e4f4101d5ceabbf71e67c61b21a161746504533511e68a39f40d - 1000 STT received
But in the wallet it's shown as outgoing transaction with value 0 ETH

#### Expected behavior
Correct value, `to` and `from` addresses are shown for token transactions

#### Actual behavior
Incoming token transactions are shown in the history as outgoing ETH transactions.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Recover an account with tokens transactions 
- Navigate to wallet -> Transactions history
- Open transactions list for the account in Etherscan, e.g. https://ropsten.etherscan.io/address/0x80b663e82657caf5657ce79b11aeaeda02c6cd92
- Compare data from transactions history with data from Etherscan

### Additional Information
Status version: 0.9.3 (12790); node 27700aa2 (Nov 21 nightly build)
Operating System: Android, iOS

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://ropsten.etherscan.io/tx/0x89dd2d0937d7e4f4101d5ceabbf71e67c61b21a161746504533511e68a39f40d">Ropsten Transaction 0x89dd2d0937d7e4f4101d5ceabbf71e67c61b21a161746504533511e68a39f40d</a></strong></div><div>Ropsten (ETH) detailed transaction info for 0x89dd2d0937d7e4f4101d5ceabbf71e67c61b21a161746504533511e68a39f40d</div></blockquote>
<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://ropsten.etherscan.io/address/0x80b663e82657caf5657ce79b11aeaeda02c6cd92">Ropsten Accounts, Address And Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>

**Comment by yevh-berdnyk** [comment] 2018-11-21 17:46
@goranjovic please confirm that this was not intentionally changed

**Comment by asemiankevich** [comment] 2018-11-22 08:03
@bhauman i believe that could be caused by the token history fix, could you please double check?

**Comment by goranjovic** [comment] 2018-11-22 08:30
This is a token minting transaction (e.g. from Status Test Dapp or by directly sending 0 ETH to contract).
So, the bug here is a missing token transfer event (or not merged with the tx).

Worth checking if token transfers show up for incoming tokens which are sent by another user. 
Also worth checking if mainnet works ok, i.e. maybe the bug affects only ropsten

**Comment by asemiankevich** [comment] 2019-01-28 07:56
@goranjovic is it something we can fix someday soon? want to have our nightly e2e in green, this is the only blocker for them now

**Comment by mandrigin** [comment] 2019-04-11 18:53
@asemiankevich @goranjovic what do you think of making it a reasonable size bounty?

**Comment by churik** [comment] 2019-04-22 15:01
It is OK for new transactions in https://github.com/status-im/status-react/pull/8005 (last days), but still the case for older transactions.

sometimes it is still reproducible after relogin or just after recover account (can be related to https://github.com/status-im/status-react/issues/7329)

**Comment by churik** [comment] 2019-06-03 09:09
closed in https://github.com/status-im/status-react/pull/8228

**Closed as completed** 2019-10-10 14:59 UTC
Labels: e2e test blocker
