### ISSUE TITLE
Allow to scan QR code with an address which doesn't conform to eip55

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#9984] opened 2020-02-05 14:15 UTC
# Allow to scan qr with an address which doesn't conform to eip55

[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to scan qr with an address which doesn't conform to eip55 to avoid copy/pasting it manually. 

### Description

Many local exchanges (for instance some of those which I use for crypto to cash exchange) do not support eip55 yet and it is quite annoying that I have to copy address instead of just scanning it. Anyway we allow to paste the address which is not formatted according to eip55. So I would suggest showing some warning instead of not allowing to scan such address as we do now:
<img width=320 src=https://user-images.githubusercontent.com/2364994/73849428-985cba80-4832-11ea-88ed-f68f66afcc94.PNG />
 

### Acceptance Criteria

[comment]: # (Rules for the future PR to be accepted.)

### Notes

[comment]: # (For the developer who will implement. Include planning poker estimates, guidance, etc.)

**Comment by leafcutterant** [comment] 2020-02-13 19:59
Duplicate of #9748

**Closed as completed** 2020-02-29 12:47 UTC
Labels: feature
