### ISSUE TITLE
The keyboard doesn't appear when using Send command second time [send]

### ISSUE THREAD

**Issue by NataliaGrigoreva** [status-im/status-react#1387] opened 2017-06-30 00:04 UTC
### Description

*Type*: Bug

*Summary*: 
The keyboard doesn't appear at once when using send command for the second time

#### Expected behavior
The keyboard should appear when the user use Send command

#### Actual behavior
The keyboard doesn't appear at once when user uses Send command for the second time. So the user has to tap on the input field to get the keyboard.

### Reproduction

- Launch app "Status"
- Login with valid credentials
- Go to 1-1 chat
- Tap on the Send command
- Chhose the recepient and type the ammount
- Send the ammount
- Tap on the Send command again

Video:
https://drive.google.com/open?id=0B0pYIvdvIoAHNnA0MDZjQWZ5T0E

### Additional Information

* Status version: 0.9.8-56-gd743691+
* Operating System: Android 5.0

**Comment by annadanchenko** [comment] 2017-07-06 11:17
can reproduce on real devie Galaxy S6, Android 6.0.1

**Comment by annadanchenko** [comment] 2017-08-28 17:01
The initial bug report contains video where popup with error is shown instead of successful send flow. The issue (no keyboard is shown if use /send or /request command second time) happens for the normal flow too and this is the main issue to be fixed. 

Here is a video (and log) with normal flow, start from 0:20 (1st send) and 00:43-00:46 (shows 2nd send with issue) https://app.testfairy.com/projects/4803622-status/builds/6448327/sessions/9/?accessToken=ADYnYmjPJvAMxtqOLmxdFoeyE/c

So, it's expected to get this state after choosing a recipient:
![screenshot_20170828-193157](https://user-images.githubusercontent.com/6584810/29784020-36332c9c-8c2b-11e7-83cb-3355d7ad8002.png)


But issue is that no keyboard is shown, so user needs to tap inside the input field to get to the expected state:

![screenshot_20170828-193219](https://user-images.githubusercontent.com/6584810/29784060-4fd481f0-8c2b-11e7-955b-344c93bb7822.png)

**Comment by x-goose-x** [comment] 2017-08-29 17:26
I could use some guidance with this issue.

Here's what I've determined so far: `send`, `receive` and `@browse` will focus
the input component the first time they run, but after that they won't
trigger the `basic-text-input` `:on-focus` event.

Interestingly, tapping the `/location` command will focus text input and bring
up the keyboard again, allowing one subsequent use of `send`, `receive` or `@browse`
to show the keyboard.

The major difference between `/location` and the wallet commands or `@browse` is
that `/location` is a reagent component while the wallet commands are js react.

I'm not sure if that has anything to do with the problem though. Any insight from
the clojure team, or some next steps to debug?

[video example here](https://drive.google.com/open?id=0B-eUTMyNoFvPcjJobUdETnRsQjg)

**Comment by yenda** [comment] 2017-10-19 10:31
Moved to in testing because it seems to be fixed with the rework.
Doesn't happen anymore for me on One Plus 3

**Comment by asemiankevich** [comment] 2017-10-20 12:46
it doesn't happen to me either in latest develop . seems to be fixed in send rework

**Closed by asemiankevich** 2017-10-20 12:46 UTC
Labels: beginner, bug, medium-priority
