### ISSUE TITLE
'Wrong password' is shown if provide correct password while device is or was offline

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1295] opened 2017-06-08 18:40 UTC
### Description

*Type*: Bug

*Summary*: "Wrong password" error is shown if provide correct password when device is offline. Expected to get "Offline" message. If connection is available again app still says "Wrong password" and user needs to re-launch and app, so it "sees" connection.
![screenshot_20170608-213241](https://user-images.githubusercontent.com/6584810/26945134-88768954-4c93-11e7-8c26-6efd4cde8407.png)

#### Expected behavior
If device is offline and it's not possible to log in then "Offline" message should be shown to user
#### Actual behavior
"Wrong password" message is shown that is very confusing because user typed correct password

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7UENvYkhpZ0JnT00
- Close Status app 
- Turn on Airplane mode
- Run Status and provide correct password
- Tap Sign in

### Additional Information
* Status version: 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

### Instabug
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/655
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/754

**Comment by 3esmit** [comment] 2017-06-09 16:22
Wrong password should only prompt if is wrong password. This wrong message takes user trust and can induce to user making bad decisions regarding app installation (such as removing it).

**Comment by jeluard** [comment] 2017-06-15 19:38
Currently we rely on local RPC calls (over HTTP) for our RN -> go communications. This will change in the following weeks.
This bug should become irrelevant by then.

**Comment by Ferraiya** [comment] 2017-06-22 08:27
Also, this bug is reproduced on iPhone 5, iOS 9.3.5 using mobile internet connection. 
Video: https://drive.google.com/file/d/0B5WergArvaY1Mm5VaS11YjFxd0E/view?usp=sharing

**Comment by annadanchenko** [comment] 2017-06-27 22:07
On recover access screen (when "Wrong passoword" for lost connection can be reproduced): nothing happens if enter passphrase, password and tap on Recover acess. Expected: offline message is shown or new account is created - need to re-check when Wrong password bug is fixed

**Comment by Ferraiya** [comment] 2017-06-28 21:44
Summary: "Wrong password" message is shown after entering right password when there is a slow internet connection (3G mobile)

Device/OS: iPhone 5, iOS 9.3.5
App version 0.9.9d5

Steps: 
1. Launch the app
2. Tap on the 1-st account
3. Enter the password of this account

Actual result: "Wrong password" message is shown
Expected result: app enters the account

Console log: https://drive.google.com/file/d/0B5WergArvaY1NWI2ZEVHRGZpaVU/view?usp=sharing
Speed: https://drive.google.com/file/d/0B5WergArvaY1VmRzdV9hVUFPZk0/view?usp=sharing

**Comment by danielmcclure** [comment] 2017-07-24 22:44
Also seen on iPhone 6 with latest iOS.

**Comment by annadanchenko** [comment] 2017-08-04 15:09
re-check after this is done https://github.com/status-im/status-react/pull/1115

**Comment by rasom** [comment] 2017-08-04 19:28
So this problem is related to something on status-go side, the output is "no running geth node detected".
<img src=https://user-images.githubusercontent.com/2364994/28983796-ec619b5a-7963-11e7-9c44-9c72a89a9ddc.PNG width=320 />

**Comment by sla-shi** [comment] 2017-08-14 12:40
Per @flexsurfer it needs investigation on the go side @tiabc.

**Comment by tiabc** [comment] 2017-08-15 06:19
Will be fixed at https://github.com/status-im/status-go/pull/250

**Comment by jeluard** [comment] 2017-08-28 07:00
While there is an issue go side the error message itself is incorrectly generated `status-react` side
This will require changes there too.

**Comment by jeluard** [comment] 2017-08-31 08:35
User facing error messages have been improved (see this [commit](https://github.com/status-im/status-react/commit/dd6d67932205d7010075647f20b1edacb9227252)).

**Comment by adambabik** [comment] 2017-09-05 10:48
I tried to reproduce this issue with the current develop and I couldn't. Actually, being without the Internet, I could log in to my account and use the app, just seeing a banner "Offline". I think it's the expected behavior because being offline shouldn't prevent from logging into the app.

**Comment by asemiankevich** [comment] 2017-09-08 10:03
I can't reproduce it either. Closing

**Closed by asemiankevich** 2017-09-08 10:03 UTC
Labels: advanced, blocked, bug, medium-priority

**Comment by rasom** [comment] 2017-09-08 10:04
@asemiankevich did you turn airplane mode on before starting app? If not please try
