### ISSUE TITLE
Editing of users phone number via the action sheet doesn't work on iOS

### ISSUE THREAD

**Issue by graemerycyk** [status-im/status-react#2627] opened 2017-12-06 12:01 UTC
### User Story

As a User, I want to "Edit" my Phone number so that my Phone number is changed and stored in my profile.

### Description

*Type*: Bug

*Summary*: When the user opens the profile view and Phone Number is set to "Not specificed" pressing the "..." and “Edit” in the action sheet, results in nothing happening when "Edit is pressed" the action sheet button doesn’t seem to work.

#### Expected behavior
When the "Edit" action sheet button is pressed the Phone number should be editable

#### Actual behavior
Nothing happens apart from the action sheet is closed

### Reproduction

- Open Status
- Sign in
- Open the fly out menu
- press the "..." / more actions button
- scroll to the phone number table view cell
- press the "..." inside the phone number cell
- when action sheet is visible
- press the "Edit" button
- *nothing will happen*

### Solution
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information

* Status version: 0.9.12

* Operating System: iOS 11.2 iPhone SE

#### Logs

n/a

**Comment by annadanchenko** [comment] 2017-12-07 14:26
duplicate of #1677

**Closed as completed by annadanchenko** 2017-12-07 14:26 UTC

**Comment by graemerycyk** [comment] 2017-12-07 14:30
Whoops, sorry @annadanchenko I searched the open issues but didn't come across #1677
