### ISSUE TITLE
Communities – Implement "View token requirements" 

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17907] opened 2023-11-15 10:09 UTC
# Feature Issue
#[Figma Design](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10459-412961&mode=design&t=DFdZ6z4Iz5nvXADf-0)

### User Story
![image](https://github.com/status-im/status-mobile/assets/5999878/dd908d11-66a1-46dc-8d9c-dff70bb2d2a9)

### Description

From the communities top Menu, user can select "View token requirenents", which will display a bottom sheet to be implemented.

### Acceptance Criteria
- Follow Figma design
- User can navigate to  "View token requirements" screen/bottom sheet
- User can see the required tokens to join the community

**Comment by ilmotta** [comment] 2023-11-16 17:53
FYI @FFFra this one is a duplicate of an older one from June https://github.com/status-im/status-mobile/issues/16316.

**Closed as completed by ilmotta** 2023-11-16 17:53 UTC
Labels: feature, community
