### ISSUE TITLE
Error undefined is not an object (evaluating 'u[n]') if tap many times on Contact Group title

### ISSUE THREAD

**Issue by ahmetmertugrul** [status-im/status-react#2577] opened 2017-12-02 13:32 UTC
### Description

*Type*: Bug

I clicked too much on the gray area.
![1](https://user-images.githubusercontent.com/6959106/33515774-4084c794-d778-11e7-8f6c-94ebd480833d.png)

The error message came to the screen.

![2](https://user-images.githubusercontent.com/6959106/33515791-99f029b8-d778-11e7-8c66-8b1c0b5494e8.png)

 Video: [https://drive.google.com/file/d/1xTwrBdHJHbMnaYnf5ND2A4Oc557hhwr9/view](https://drive.google.com/file/d/1xTwrBdHJHbMnaYnf5ND2A4Oc557hhwr9/view)
 Video 2: [https://drive.google.com/file/d/1qgS7XhkSF4HBw7XkPDMl1xON2UfwasIr/view](https://drive.google.com/file/d/1qgS7XhkSF4HBw7XkPDMl1xON2UfwasIr/view)

### Reproduction

- Open Status
- Sign in
- Open Contacts
- Many clicks on "DApps" text
- Show error message: undefined is not an object (evaluating 'u[n]')
- Click "OK"
- Many clicks on "State of the DApps" text
- Show error message: undefined is not an object (evaluating 'u[n]')
- Click "OK"
- Open profile
- Click network settings
- Many clicks on "Existing networks" text
- Show error message: undefined is not an object (evaluating 'u[n]')
- Click "OK"

### Additional Information

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by andytudhope** [comment] 2017-12-03 16:32
Thanks for submitting this issue @ahmetertugrul! The team will look into it this coming week.

**Comment by ahmetmertugrul** [comment] 2017-12-03 16:56
Not at all @andytudhope .

**Comment by annadanchenko** [comment] 2017-12-04 21:08
@ahmetertugrul thanks a lot for the bug report! 
1. Please, report each bug as a separate issue, otherwise it's hard to track what's going on with each of them (bug 1 can be fixed when bug 2 might fail verification and bug 3 might be closed)
2. Please, specify the Android OS version and the device you are using for testing
3. For the bug1 - there is another issue reported with same error message: #2581 however steps are different. Can you double-check if bug1 is not caused by accidental tapping on the contact icon, please?

**Comment by ahmetmertugrul** [comment] 2017-12-06 13:49
@annadanchenko I'm updated and added video.

**Comment by annadanchenko** [comment] 2017-12-07 16:23
Can reproduce on develop build,  but error does not stay on the screen (can see it in the log): 
`00:59 I/ReactNativeJS: MESSAGE: undefined is not an object (evaluating 'u[n]')` https://app.testfairy.com/projects/4803622-status/builds/7234321/sessions/24/?accessToken=fJKIF2Zh4bpUhM2lvwJdsDeomlM
Device: real device from BitBar cloud LG G4, ANDROID 6.0
- nightly develop build http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk
- Status version  0.9.10-427-ga68f0652+ (1984)

**Comment by ahmetmertugrul** [comment] 2017-12-08 21:18
Video: [https://drive.google.com/file/d/1NK44keXqSsea2RAyh1Dr6cmXfhTzHb7L/view](https://drive.google.com/file/d/1NK44keXqSsea2RAyh1Dr6cmXfhTzHb7L/view)

- Status version: 0.9.10-427-ga68f0652+ (1984)

- Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by status-open-bounty** [comment] 2017-12-19 09:19
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x4f1afccd9beeede2f44345ce745d28f837801f5de36af632d8e521ab19d770ce](https://etherscan.io/tx/0x4f1afccd9beeede2f44345ce745d28f837801f5de36af632d8e521ab19d770ce)

**Comment by pablanopete** [comment] 2018-01-20 08:33
This UI will be changed in MVP - can be revoked / closed.

**Comment by annadanchenko** [comment] 2018-06-17 11:34
@andytudhope can we get SNT back and then close this issue? It's no longer an issue (screen was removed)

**Closed as completed** 2018-08-31 15:36 UTC
