### ISSUE TITLE
channel naming limitations don't exist in android

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-react#12508] opened 2021-08-26 17:54 UTC
# Bug Report

issue reported by a user originally [here](https://github.com/status-im/status-desktop/issues/3275)

## Problem 

"channel naming limitations exist on linux version (such as capitalization), but not on Android."

### Additional Information
- Operating System: Android

**Comment by churik** [comment] 2021-08-27 07:54
Duplicate of https://github.com/status-im/status-react/issues/12010

**Closed as completed by churik** 2021-08-27 07:54 UTC
