### ISSUE TITLE
Missing an option to choose a default wallet 

### ISSUE THREAD

**Issue by jovancosta-zz** [status-im/status-react#12160] opened 2021-05-27 14:49 UTC
# Problem

It´s not possible to choose a default wallet. This is bringing some collaterals issue like:
User can't choose another wallet to register ENS name
User can't send/receive money with his second wallet

### Where it Happens
Mobile and Desktop

## Implementation

Just create an option on the menu to allow user to choose the default wallet or allow him do it by pressing a checkbox near to the wallet's name

## Acceptance Criteria
Suggestion:
- The first wallet must always be the default wallet
- User must be able to select the default wallet, when he adds another wallet
- User must be able to change the default wallet
- User can't remove the default wallet, except only when this wallet is the only available
- All features related to wallet must point to the default wallet (send,receive, buy cripto, register ens name)

## Notes

1)Check other wallets as a benchmark.

2)Gherkin User Story
Given I want to add more than one wallet,
When I add another wallet,
Then a modal should be presented and ask: "Please choose your default wallet."

3)Question:
In case of interaction with the chat... Where the wallet attached to the profile is still the first one.
a)Will Status allows the user to select a default wallet and use another to chat/other features(third parties) interaction?
For example: I want to keep anonymous while I'm and I want to receive or spend money(emoticons and other features) with another wallet.

## Future Steps

- Create an option to remove wallet.
- Create test cases to validate this default option feature.
- Validate it in mobile and desktop app.

**Comment by churik** [comment] 2021-07-27 12:51
@jovancosta thank you for reporting!
it is I believe is duplicate of https://github.com/status-im/status-react/issues/10142
As for sending/receiving money - you can choose what wallet to use from Send transaction screen (from 1-1 chat or from wallrt)

**Closed as completed by churik** 2021-07-27 12:51 UTC
Labels: feature
