### ISSUE TITLE
Messages with less 4096 chars are dropped from chats

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11228] opened 2020-09-24 14:30 UTC
# Bug Report

## Problem
Currently message limit for dropping messages from chats are somewhere between 3600 and 3994 char instead of expected 4096 according to https://github.com/status-im/status-go/blob/3d5e21e27689e0ff126e69db30ac6352f3dd45dc/protocol/message_validator.go#L13
Can reproduce in 1-1 and public chat

#### Expected behavior
can see messages in chat

#### Actual behavior
message with 3600 chars is sent and received, message with 3994 was sent but dropped (or never received)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join any public channel
- Send message > 3994 char

### Additional Information

- Status version: RC 1.7
- Operating System: Android, iOS

#### Logs
Message was sent at 14:18 

Sender: [Status-debug-logs.zip](https://github.com/status-im/status-react/files/5276793/Status-debug-logs.zip)
Receiver: [status_logs.zip](https://github.com/status-im/status-react/files/5276795/status_logs.zip)

**Comment by churik** [comment] 2020-09-24 14:31
cc @cammellos

**Comment by churik** [comment] 2020-09-24 14:54
Message that was sent: 
```
3994 for the Elimination of all forms of Discrimination Against Women (CEDAW): The Experience of the United Kingdom» (en inglés). p. 1. Archivado desde el original el 22 de marzo de 2011. Consultado el 17 de diciembre de 2009.
 Murdoch (2008), pág. 27.
 Gómez (2003), pág. 320 - 321.
 Sokhi-Bulley (2006), pág. 157.
 Tang, Kwong-leung (2004). «Internationalizing Women's Struggle against Discrimination: The UN Women's Convention and the Optonal Protocol». British Journal of Social Work (en inglés) 34 (8): 1182.
 Gómez (2003), pp. 319-320.
 Sokhi-Bulley (2006), pág. 158.
 Tang (2004), pág. 1185.
 División para el Adelanto de la Mujer (DAW). «Convention on the Elimination of Discrimination against Women: Optional Protocol: Decisions/Views». Consultado el 15 de julio de 2008.
 Comité para la Eliminación de la Discriminación contra la Mujer (26 de enero de 2005). «Dictamen del Comité para la Eliminación de la Discriminación contra la mujer emitido conforme al párrafo 3 del artículo 7 del Protocolo Facultativo de la Convención sobre la eliminación de todas las formas de discriminación contra la mujer. Comunicación No. 2/2003, Sra. A. T. contra Hungría». Consultado el 21 de enero de 2015.
 Gobierno de la República de Hungría (15 de junio de 2006). «Sexto informe periódico presentado por la República de Hungría a las Naciones Unidas sobre la Eliminación de Todas la Formas de Discriminación contra la mujer». p. 50. Consultado el 21 de enero de 2015.
 Comité para la Eliminación de la Discriminación contra la Mujer (14 de agosto de 2006). «Observaciones del Comité para la Eliminación de la Discriminación contra la Mujer formuladas con arreglo al párrafo 3 del artículo 7 del Protocolo Facultativo de la Convención sobre la eliminación de todas las formas de discriminación contra la mujer (36º período de sesiones) Comunicación No. 3/20044». Consultado el 21 de enero de 2015.
 Comité para la Eliminación de la Discriminación contra la Mujer (29 de agosto de 2006). «Opinión del Comité para la Eliminación de la Discriminación contra la Mujer emitida a tenor del párrafo 3 del artículo 7 del Protocolo Facultativo de la Convención sobre la eliminación de todas las formas de discriminación contra la mujer (36º período de sesiones) Comunicación No. 4/2004». Consultado el 21 de enero de 2015.
 Comité para la Eliminación de la Discriminación contra la Mujer (6 de agosto de 2007). «Opinión del Comité para la Eliminación de la Discriminación contra la Mujer formulada con arreglo al párrafo 3 del artículo 7 del Protocolo Facultativo de la Convención sobre la eliminación de todas las formas de discriminación contra la mujer (39º período de sesiones) Comunicación No. 5/2005: Şahide Goekce (difunta) contra Austria». Archivado desde el original el 21 de enero de 2015. Consultado el 21 de enero de 2015.
sdfsdfsdf;sd;fksdfkjkdsfkjsdfjkkjdlsfdfaskj
desde el original el 21 de enero de 2015. Consultado el 21 de enero de 2015.
sdfsdfsdf;sd;fksdfkjkdsfkjsdfjkkjdlsfdfaskjjjjjjjjjjj3000
«Opinión del Comité para la Eliminación de la Discriminación contra la Mujer formulada con arreglo al párrafo 3 del artículo 7 del Protocolo Facultativo de la Convención sobre la eliminación de todas las formas de discriminación contra la mujer (39º período de sesiones) Comunicación No. 5/2005: Şahide Goekce (difunta) contra Austria». Archivado desde el original el 21 de enero de 2015. Consultado el 21 de enero de 2015.
sdfsdfsdf;sd;fksdfkjkdsfkjsdfjkkjdlsfdfaskj
desde el original el 21 de enero de 2015. Consultado el 21 de enero de 2015.
sdfsdfsdf;sd;fksdfkjkdsfkjsdfjkkjdlsfdfaskjjjjjjjjjd3600
«Opinión del Comité para la Eliminación de la Discriminación contra la Mujer formulada con arreglo al párrafo 3 del artículo 7 del Protocolo Facultativo de la Convención sobre la 
sdfsdfsdf;sd;fksdfkjkdsfkjsdfjkkjdlsfdfaskjjjjjjjjjd3600la Eliminación de la Discriminación cotra la Mujer formulada con arreglo al párrafo 3 del artículo 7 del Protocolo Facultativo de la Convención sobreeee 3994
```

**Comment by cammellos** [comment] 2020-09-24 14:55
Confirmed that for some reason is being marked as too long 
```
t=2020-09-24T14:18:40+0000 lvl=warn msg="failed to validate message" site=handleChatMessage error="text shouldn't be longer than 4096"
t=2020-09-24T14:18:40+0000 lvl=warn msg="failed to handle ChatMessage" site=RetrieveAll error="text shouldn't be longer than 4096"
```

**Comment by cammellos** [comment] 2020-09-24 14:58
The issue is unicode characters, as we are counting byte length and not characters length here
https://github.com/status-im/status-go/blob/3d5e21e27689e0ff126e69db30ac6352f3dd45dc/protocol/message_validator.go#L13

https://stackoverflow.com/questions/12668681/how-to-get-the-number-of-characters-in-a-string

**Comment by churik** [comment] 2020-09-24 15:17
Yes, you are right abot chinese/japanese language. Limit is less in that case.
1310 still can be sent and received, 2620 - no.
Message:
```
2620選り抜き記事
アイザック・アシモフ
アイザック・アシモフ（英: Isaac Asimov, 1920年1月2日 - 1992年4月6日）は、アメリカの作家、生化学者。その著作は500冊以上を数える。彼が扱うテーマは科学、言語、歴史、聖書など多岐にわたり、デューイ十進分類法の10ある主要カテゴリのうち9つにわたるが、特にSF、一般向け科学解説書、推理小説によってよく知られている。

日本では「アシモフ」と「アジモフ」等の表記があり、前者での表記が一般的である。本人の望んでいた発音は後者に比較的近い[ˈaɪzək ˈæzɪmɒv]である。ジュブナイル作品ではポール・フレンチという筆名を用いた。1942年発表のSF短編 Time Pussy では George E. Dale という筆名を用いた。1971年の著書 The Sensuous Dirty Old Man では Dr. A という筆名を用いた。……

秀逸な記事おまかせ表示つまみ読み選考
吾妻四郎助光（生没年不詳、伝・1221年没）は鎌倉時代の『吾妻鏡』に登場する人物で、弓の名手である。吾妻助光とも。上野国吾妻郡を治めた吾妻氏の一族であるとか、岩櫃城城主であったなどという伝説があるが……
アメリカン航空587便墜落事故は、2001年11月12日にアメリカン航空のエアバスA300-600型機がジョン・F・ケネディ国際空港を離陸直後に墜落した航空事故である。上昇中に前方を飛行するボーイング747の後方乱気流に遭遇し……
海王星は、太陽系の第8惑星で、太陽系の惑星の中では最も太陽から遠い位置を公転している。太陽系の惑星の中では、直径は4番目、質量は3番目に大きく、最も密度が高いガス惑星である……
良質な記事おまかせ表示つまみ読み選考
""新しい記事
ムスチスラフ・ケルディシュ（1911年1月28日〈新暦2月10日〉- 1978年6月24日）は、ソビエト連邦の数学者で、宇宙開発や計算機科学をはじめとするソ連科学の発展に重要な役割を果たした指導者として知られる。……
服忌（服紀）とは、喪に服すること、もしくはその期間のこと。日本の服忌は当初は中国の礼制、すなわち儒教的な考え方を取り入れて制度化されたが、後に仏教や神道の考え方が取り入れられて変化していった。古代中国の礼制では、……
多久神社は、京都府京丹後市峰山町丹波小字涌田山にある神社。式内社。本殿と、秋の祭礼で奉納される芝むくり神事が、京都府登録民俗文化財に登録されている。祭神は豊宇賀能売命、別名を「豊受大神」。伝承によれば豊宇賀能売命は……
好古家とは、骨董品・古美術品・古銭・稀覯本・遺物などを蒐集したり、古地図・古俗・地域史・史跡・碑文などを調査したりする人のこと。つまり「好古趣味」（「好古癖」「好古学」「好古」とも）をたしなむ人のこと。……
丹波の大溝とは、1655年（明暦元年）に完成した京都府京丹後市峰山町の用水路である。上流部の峰山町荒山に水門を設け、ここから用水路を京都府京丹後市峰山町丹波までひいたもので、21世紀初頭現在まで丹波の田のおよそ4割に13101310選り抜き記事
アイザック・アシモフ
アイザック・アシモフ（英: Isaac Asimov, 1920年1月2日 - 1992年4月6日）は、アメリカの作家、生化学者。その著作は500冊以上を数える。彼が扱うテーマは科学、言語、歴史、聖書など多岐にわたり、デューイ十進分類法の10ある主要カテゴリのうち9つにわたるが、特にSF、一般向け科学解説書、推理小説によってよく知られている。

日本では「アシモフ」と「アジモフ」等の表記があり、前者での表記が一般的である。本人の望んでいた発音は後者に比較的近い[ˈaɪzək ˈæzɪmɒv]である。ジュブナイル作品ではポール・フレンチという筆名を用いた。1942年発表のSF短編 Time Pussy では George E. Dale という筆名を用いた。1971年の著書 The Sensuous Dirty Old Man では Dr. A という筆名を用いた。……

秀逸な記事おまかせ表示つまみ読み選考
吾妻四郎助光（生没年不詳、伝・1221年没）は鎌倉時代の『吾妻鏡』に登場する人物で、弓の名手である。吾妻助光とも。上野国吾妻郡を治めた吾妻氏の一族であるとか、岩櫃城城主であったなどという伝説があるが……
アメリカン航空587便墜落事故は、2001年11月12日にアメリカン航空のエアバスA300-600型機がジョン・F・ケネディ国際空港を離陸直後に墜落した航空事故である。上昇中に前方を飛行するボーイング747の後方乱気流に遭遇し……
海王星は、太陽系の第8惑星で、太陽系の惑星の中では最も太陽から遠い位置を公転している。太陽系の惑星の中では、直径は4番目、質量は3番目に大きく、最も密度が高いガス惑星である……
良質な記事おまかせ表示つまみ読み選考
""新しい記事
ムスチスラフ・ケルディシュ（1911年1月28日〈新暦2月10日〉- 1978年6月24日）は、ソビエト連邦の数学者で、宇宙開発や計算機科学をはじめとするソ連科学の発展に重要な役割を果たした指導者として知られる。……
服忌（服紀）とは、喪に服すること、もしくはその期間のこと。日本の服忌は当初は中国の礼制、すなわち儒教的な考え方を取り入れて制度化されたが、後に仏教や神道の考え方が取り入れられて変化していった。古代中国の礼制では、……
多久神社は、京都府京丹後市峰山町丹波小字涌田山にある神社。式内社。本殿と、秋の祭礼で奉納される芝むくり神事が、京都府登録民俗文化財に登録されている。祭神は豊宇賀能売命、別名を「豊受大神」。伝承によれば豊宇賀能売命は……
好古家とは、骨董品・古美術品・古銭・稀覯本・遺物などを蒐集したり、古地図・古俗・地域史・史跡・碑文などを調査したりする人のこと。つまり「好古趣味」（「好古癖」「好古学」「好古」とも）をたしなむ人のこと。……
丹波の大溝とは、1655年（明暦元年）に完成した京都府京丹後市峰山町の用水路である。上流部の峰山町荒山に水門を設け、ここから用水路を京都府京丹後市峰山町丹波までひいたもので、21世紀初頭現在まで丹波の田のおよそ4割に2620
```

**Closed as completed** 2020-10-06 09:18 UTC
