### ISSUE TITLE
Chat top bar problems

### ISSUE THREAD

**Issue by du82** [status-im/status-react#16149] opened 2023-06-02 11:37 UTC
Phone: OnePlus Nord N20 5G
OS: Android 11

![Screenshot_2023-06-01-16-26-10-63_65ad86f86fd2321a85272a99323da10f](https://github.com/status-im/status-mobile/assets/65834069/0d75fc69-6fb3-423f-8984-a4579404e50b)

![Screenshot_2023-06-01-16-29-56-83_65ad86f86fd2321a85272a99323da10f](https://github.com/status-im/status-mobile/assets/65834069/036a967f-8758-4050-b64c-1693196d0b81)

**Comment by qoqobolo** [comment] 2023-06-02 11:46
Duplicate of https://github.com/status-im/status-mobile/issues/16141

**Closed as completed by qoqobolo** 2023-06-02 11:46 UTC
