### ISSUE TITLE
Notifications in Activity Center and unread messages are not synced if they were received before syncing and while the secondary device was offline

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13176] opened 2022-03-16 11:01 UTC
# Bug Report

## Problem 
If a User received new notifications in the Activity center before pairing, and the secondary device was offline at that time (or the account has not yet been restored on it), then after returning online and syncing, the notifications will not appear in the Activity center on the secondary device.

#### Expected behavior
Notifications received while the secondary device was offline and before syncing, are synced in the same way as other data, i.e. public chats, contacts, etc. 

#### Actual behavior
No notifications after syncing

### Reproduction

1. Create an account on device1
2. Recover the same account on device2, close the app
3. Create another account on device3 and start a new 1-1 chat with device1 / invite device1 to a new group chat (_device1 has a new notification in the Activity center_)
4. Open the app on device2, sync device1 with device2
5. Check the Activity center on device2

### Additional Information

- Status version: nightly 16/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment] 2022-04-07 10:05
The same for unread messages: if they appeared before sync, there are no unread messages after initial sync.

**Comment by audriu** [comment] 2022-06-21 10:21
I can not reproduce it with the current `develop` branch.

**Comment by pavloburykh** [comment] 2022-06-21 10:29
Hey @audriu! Bug is being replicated when notifications in activity center are received by Device 1 before restoring the same account on Device 2. 

**Steps:** 

1. Create an account on Device1
2. Create another account on Device 3 and start a new 1-1 chat with Device1 / invite device1 to a new group chat (Device1 has a new notification in the Activity center)
3. Recover the same account (as on device 1) on Device 2
4. Sync Device 1 with Device 2
5. Pay attention if notifications appeared on Device 2 

**Actual result:** notifications are not synced. Reproduced on latest nightly 21/06

**Expected result:** notifications are synced


https://user-images.githubusercontent.com/97245802/174778763-35c26a2a-eb8a-42d2-ac3a-df32437367ba.mp4

**Comment by audriu** [comment] 2022-06-22 08:45
these stems and steps in the ticket's reproduction description are different. Steps 2 and 3 were swapped and therefore work differently.

**Comment by pavloburykh** [comment] 2022-06-22 08:47
> these stems and steps in the ticket's reproduction description are different. Steps 2 and 3 were swapped and therefore work differently.

ok, so did you mange to reproduce the bug with these steps https://github.com/status-im/status-react/issues/13176#issuecomment-1161562383 ?

**Comment by cammellos** [comment] 2022-07-15 09:39
Closing this for now, the case from @pavloburykh is expected, since we don't sync messages on new devices, we have to dig a bit deeper as some notifications might need syncing, but we can probably open issue for those specifically, feel free to re-open if disagree or I have missed something.

**Closed as completed by cammellos** 2022-07-15 09:39 UTC
Labels: activity-center, syncing
