### ISSUE TITLE
Not able to edit phone number in settings option

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2641] opened 2017-12-06 16:42 UTC
### Description

Type: Bug

*Summary*: ...
Not able to edit/ enter  phone number in settings option.
Please see attached screenshot.
![screenshot_2017-12-06-21-58-14-099_im status ethereum 1](https://user-images.githubusercontent.com/20433356/33673220-3825b9f2-dad2-11e7-9c34-035e5293e334.png)

#### Expected behavior
User should be able to enter/edit number on UI.

#### Actual behavior
Not able to enter/edit.

### Additional Information

* Status version: ... 0.9.12

* Operating System: Android 6.0

**Comment by graemerycyk** [comment] 2017-12-06 18:29
@annadanchenko This looks like a duplicate of https://github.com/status-im/status-react/issues/2627

**Comment by annadanchenko** [comment] 2017-12-06 20:32
@Monali109 Please, search for the known issues before reporting new ones. As @grycyk mentioned it's a duplicate of #2627, so no need to report it again. However, if you find some known issue where you can add extra info, especially if they have label "Help to reproduce" then please write a comment with any extra info/video/logs you can add.

**Closed as completed by annadanchenko** 2017-12-06 20:32 UTC
