### ISSUE TITLE
Quo2 components - Drawers / Drawer Top

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#15007] opened 2023-02-07 10:42 UTC
Implement this component in the quo2 component library as per the design spec:

Designs - Drawers / Drawer Top
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=2500%3A42270&t=29WaMjPTYMtHqa1n-0

** There is an implementation of one variation of this more or less done in https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/communities/menus/request_to_join/view.cljs#L83-L98

Acceptance Criteria

dark and light mode
component tests (jest)
quo2 preview
export from quo2/core.cljs
adjust usage in communities join screen to use this component

**Comment by J-Son89** [comment] 2024-02-08 14:41
@smohamedjavid , @ulisesmac  @ajayesivan any of you know if this is a duplicate now? do we need it anymore??

**Comment by smohamedjavid** [comment] 2024-02-08 14:49
At first glance, #17021 is a duplicate of this and it looks like there are a few new types added in the Figma design compared to the screenshot in the issue.

**Comment by ajayesivan** [comment] 2024-02-09 07:41
I'm working on an [issue](https://github.com/status-im/status-mobile/issues/18616) related to this component for the community account selection feature. During that, I will also verify this.

**Comment by ajayesivan** [comment] 2024-02-18 22:22
Hi @J-Son89,
I noticed that the `type` prop of this component has a variety of values, including combinations like "Default + Description," which strikes me as somewhat unconventional. It seems to blur the distinction between different types of information. In my opinion, it might be clearer to have separate props for each distinct type of information. 

What do you think, should we talk to the designers to clarify this, or is this a pattern that we use with other components as well?

### Types
1.  Default
2. Default + Description
3. Context tag
4. Context tag + button
5. Info
6. Info + Description
7. Account
8. Label
9. Keypair
10. Keypair
11. Keycard
12. Default keypair
13. Counter
14. Token
15. Token hidden
16. 2 Context
17. 2 Context + button

**Comment by J-Son89** [comment] 2024-02-19 09:51
Hey @ajayesivan, of course. I think that's fine to use your best judgement.
I think ideally design would just change this component to improve the developement experience and make it easier to implement, in that I still think it is worth discussing them the pain points here, although it might not be possible for them to change it here without making adjustments to many design files?? 🤔 

In any case we really need to revisit how the designers are building the design system because it doesn't scale well with the development process. 
@ilmotta has discussed this in a few prs and I have requested that 3/4 developers talk with designers in the offsite and bring some feedback of what can be improved in the design system approach as it is something we really need to get on top of 👍

**Comment by ilmotta** [comment] 2024-02-21 20:05
> Hey @ajayesivan, of course. I think that's fine to use your best judgement. I think ideally design would just change this component to improve the developement experience and make it easier to implement, in that I still think it is worth discussing them the pain points here, although it might not be possible for them to change it here without making adjustments to many design files?? 🤔
> 
> In any case we really need to revisit how the designers are building the design system because it doesn't scale well with the development process. @ilmotta has discussed this in a few prs and I have requested that 3/4 developers talk with designers in the offsite and bring some feedback of what can be improved in the design system approach as it is something we really need to get on top of 👍

Thank you very much @J-Son89 for using the offsite time to bring this very important topic to designers 😍

**Comment by churik** [comment] 2024-11-07 10:53
Closing as not planned and due to the lack of activity.

Reopen if still relevant.

**Closed as not planned by churik** 2024-11-07 10:53 UTC
Labels: feature, design-system, mobile-core
