### ISSUE TITLE
Unread message counter in Console chat shows "1" after using command when actually all messages are read

### ISSUE THREAD

**Issue by churik** [status-im/status-react#3016] opened 2018-01-12 10:08 UTC
Associated with #2915 
### Description

*Type*: Bug
*Summary*: after upgrade console chat shows 1 unread message after using command (faucet, web3, ect) in "Chat" view, which are not marked as read.
<img width="332" alt="counter" src="https://user-images.githubusercontent.com/4557972/34830425-78ddc198-f6ec-11e7-9a0e-eb455347da65.png">

#### Expected behavior
all messages are read

#### Actual behavior
1 unread message 

#### Prerequisites

Data before upgrade (0.9.12):
* Console (last message - Faucet request is received)

#### Steps
* upgrade to version with #2915
* log in
* go to "Chat". Last message in Console chat is unread
* go to console chat
* use /faucet 
* go back to "Chat"

### Additional Information
* Status version: 
f93b8916+ (2101) - with PR 2915
* Operating System: Android (7.0, Samsung Galaxy S7), iOS 11.0.3 (IPhone 7)

#### Logs
TF session (00:15-00:45): https://app.testfairy.com/projects/4803622-status/builds/7475151/sessions/13/?accessToken=1OThjcbaMKYka5VVbpFJX4gDBYc

**Comment by Serhy** [comment] 2018-01-16 14:34
Could not reproduce upgrading from 0.9.12+ on latest develop (0.9.11d581) - (after #3002 is merged) 
Closing this issue.

**Closed as completed** 2018-01-16 14:34 UTC
