### ISSUE TITLE
Desktop offline inbox broken

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6564] opened 2018-11-01 07:55 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a desktop user, I want to fetch messages so that I can read offline messages.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Since Cryptolife offline messages have been broken for several people.

The app says "could not connect to mail server. Tap to reconnect" then "fetching messages... (2 requests left)" but no messages are fetched.

I tried the usual tricks of restarting or changing mail servers but it didn't help.

The app seems to receive messages when online though.

#### Expected behavior
Offline messages downloaded

#### Actual behavior
No offline messages downloaded

### Reproduction

Just grab the nightly.  No older messages are downloaded.

I did some testing and can reproduce every time with this:

- create new account
- join #status (or other channels) 
- no history is shown

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Desktop nightly
* Operating System: Mac

cc @siphiuel @MaxRis @vkjr @churik @PombeirP @cammellos @yenda @adambabik 
(sorry for the mass ping but wanted to get visibility and obviously I can't use Status :P )

**Comment by chadyj** [comment] 2018-11-01 08:02
[Status.log ](https://gist.githubusercontent.com/chadyj/4f821a6f16117bd41c74607287781469/raw/33ceb8be65100b1a5c7ecee4aedee6bddec93630/Status.log)

I tried looking for problems but this log file is gnarly!

**Comment by chadyj** [comment] 2018-11-01 08:18
Also tried logging out, creating a new account, joining public chats, but still didn't download history.

**Comment by asemiankevich** [comment] 2018-11-01 08:28
i saw that and reinstalled status for today's nightly and finally was able to get some messages

**Comment by chadyj** [comment] 2018-11-01 09:52
[Geth.log](https://gist.githubusercontent.com/chadyj/8d150eb2037e0bd94eede57d1797d507/raw/633298e44d526043fad014e859da8d53c5afc503/geth.log) by request :)

**Comment by churik** [comment] 2018-11-01 09:57
Some of people mentioned the same for mobile, so I don't think it is device-specific

**Comment by churik** [comment] 2018-11-01 10:41
Steps to reproduce with new public chat:

- Mobile: create new public chat  (i.e. `#testone`)
- Mobile: send a message to this chat (i.e. `123`)
- Mobile: close an app
- Desktop: log in
- Desktop: join `#testone` 
- Waiting for messages to fetch

Expected result:
messages are fetched
Actual result:
no messages, constant  "Fetching messages"

Reproducible only for desktop.
[Status.log](https://github.com/status-im/status-react/files/2538132/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2538136/geth.log)

**Comment by chadyj** [comment] 2018-11-01 11:27
Tried to repro on latest android nightly, and mobile works ok. As far as I can see it is desktop only.

**Comment by cammellos** [comment] 2018-11-01 11:29
yes, so far it feels almost like mobile & desktop are running two different versions of status-go, but investigating

**Comment by cammellos** [comment] 2018-11-01 11:39
figured out the reason, desktop pulls a version which is generated by github automatically.
That means that it is not pulling the code you uploaded, but the code of status-go at the time you created a release (therefore it might not be the same in mobile, and also we can't really choose which code desktop is bundled with).

**Comment by maxhora** [comment] 2018-11-01 11:48
@cammellos currently, the URL of status-go sources is obtained there https://github.com/status-im/status-react/blob/develop/modules/react-native-status/desktop/CMakeLists.txt#L41 as
```
URL https://github.com/status-im/status-go/archive/v${STATUS_GO_VERSION}.zip
```
where ${STATUS_GO_VERSION} gets the value from file https://github.com/status-im/status-react/blob/develop/STATUS_GO_VERSION and at the moment it's `0.16.4-4-gaf1f6eb5`

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by vitvly** [comment] 2018-11-01 11:48
@cammellos great find! We are pulling the release from e.g. https://github.com/status-im/status-go/archive/v0.16.4-4-gaf1f6eb5.zip, and not https://github.com/status-im/status-go/releases/download/v0.16.4-4-gaf1f6eb5/status-go-0.16.4-4-gaf1f6eb5.aar (in case of Android). Why would they be different? 

<blockquote></blockquote>
<blockquote></blockquote>

**Comment by cammellos** [comment] 2018-11-01 11:54
@siphiuel @MaxRis basically to give a concrete example:
We created a release based on a branch on jenkins excluding a commit in develop, as it gives this error on the mailserver. This commit was therefore excluded from the ios/android artifact.

We then created a release on github uploading the artifacts (without that commit), but the archive that desktop uses is created automatically on github based on the state of the develop branch at the moment you create the release, so the commit was included.

For now I have made it so that the code needs to be explicitly uploaded by us https://github.com/status-im/status-react/pull/6566/files , but I think it's time to automate this, so likely I will be working on it next.


<blockquote><img src="https://avatars3.githubusercontent.com/u/1017008?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/6566">Dont use github archive for desktop status-go version by cammellos · Pull Request #6566 · status-im/status-react</a></strong></div><div>status: ready</div></blockquote>

**Comment by pedropombeiro** [comment] 2018-11-01 13:06
Some time ago I had started https://github.com/status-im/status-go/pull/1208 to harmonize the way we build mobile and desktop (to download prebuilt status-go on both cases), but for some reason that wasn't merged and then I got started on the Windows port effort.

**Closed as completed** 2018-11-01 14:04 UTC
