### ISSUE TITLE
"Add to contact" bar does not hide when "X" button is clicked to close it

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6450] opened 2018-10-22 12:40 UTC
### Description

*Type*: Bug

*Summary*: 

Clicking "X" should hide the "Add to contacts" bar so it is never shown again. But, at this moment "X" does nothing. 

<img src="https://user-images.githubusercontent.com/7532782/47292629-e9c64380-d607-11e8-8f05-e58465c749d4.png" width="200">

#### Expected behavior
When "X" is clicked, the bar is hidden forever. If chat is opened again the bar is not shown.

#### Actual behavior
Clicking "X" does nothing to the bar.

### Reproduction

- Send 1-1 message to a new user

### Additional Information
* Status version: nightly, Oct 22
* Operating System: Android, iOS
* Please note that non-contact still can be added as contact from the profile view

**Comment by asemiankevich** [comment] 2018-10-23 08:07
@lukaszfryc @annadanchenko @churik its a dupe of https://github.com/status-im/status-react/issues/5695

**Comment by churik** [comment] 2018-10-23 08:13
Yes, thanks @asemiankevich

**Closed as completed** 2018-10-23 08:41 UTC
