### ISSUE TITLE
wallet. - remove goerli support

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20273] opened 2024-05-30 13:22 UTC
We no longer need support for testnet Goerli, remove all uses of it 👍

**Comment by churik** [comment] 2024-10-07 13:53
@shivekkhurana why this issue is added to 2.31, maybe I missed something or it was added by mistake?

**Comment by churik** [comment] 2024-10-09 09:12
Postponed for the next release due to time constraint and no steps to reproduce. 

cc @ilmotta @shivekkhurana

**Comment by friofry** [comment] 2024-10-16 11:31
fixed by @saledjenic in status-go https://github.com/status-im/status-go/pull/5945

Keeping this issue for possible changes required in status-mobile.

**Comment by smohamedjavid** [comment] 2024-10-22 11:05
If no one is working on removing Goerli-related code on mobile, I can pick this up 👍

**Closed as completed** 2024-11-04 12:40 UTC
Labels: feature, tech-debt, wallet-core
