### ISSUE TITLE
Transaction send message is not shown in chat when skipping Got It button

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4821] opened 2018-06-19 10:11 UTC
### Description

*Type*: Bug

*Summary*: `/send` transaction message is not shown in 1x1 chat when skipping to tap `Got It!` button

#### Expected behavior

`/send` message is shown when the transaction is signed and does not depend on `Got It` button

#### Actual behavior

`/send` message is not shown in 1x1 chat (shown in txn history)

### Reproduction

• Open Status
• Open 1-1 chat
• Type "/send" and send some ETH to a 2nd user
• Confirm the transaction but do not press "Got it"
• kill the app and open it again to go back to the 1-1 chat

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment] 2018-06-19 12:01
@asemiankevich I think it maybe closed as duplicate of https://github.com/status-im/status-react/issues/4759

**Comment by asemiankevich** [comment] 2018-06-19 12:11
https://github.com/status-im/status-react/issues/4759 should be closed as i tested the PR and it is merged i guess

**Comment by asemiankevich** [comment] 2018-06-19 12:12
@lukaszfryc https://github.com/status-im/status-react/pull/4804

**Closed as completed** 2018-06-20 16:06 UTC
