### ISSUE TITLE
The app is still offline and swipe functionality is broken after the user tried to open the transactions history while offline.

### ISSUE THREAD

**Issue by ReneeAB** [status-im/status-react#2626] opened 2017-12-06 11:59 UTC
### Description

*Type*: Bug

*Summary*: There are a couple of issues when the app is disconnected to the Wifi when using an iPhone. 
First, after trying to open the Transaction history from the "Wallet", when the user swipes right to a different page the "Wallet" tab at the bottom of the page is still highlighted and clicking on the "Wallet", "Chats", "Discover" and "Contacts" does not work. Then, when the user reconnects to the wifi, the app is still offline.

Note: when you swipe back to the "Wallet"  the "Error loading data" message is still displayed at the top of the page ater reconnectiong to the wifi.

#### Expected behavior
The Transaction history should be displayed when selected on the "Wallet" page.

#### Actual behavior
After trying to open the transactions history, the swipe functionality is broken and the app stays offline when the users connects again to the wifi.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

•	Log into Status on iPhone, the “Chats” page is displayed.
•	Select the phone settings and select the airplane mode.
•	Go back to Status, the “Chats” page is displayed and “Offline” is displayed at the top of the chat page.
•	Select the "Wallet" tab at the bottom of the page, the wallet is displayed and the text “Error loading data” is displayed at the top of the page.
•	Tap the Transaction history (double arrows) at the top right of the page, nothing will happens the transaction history will not be displayed.
•	Swipe right to another page and keep swiping, notice that the "Wallet" tab is highlighted all the time independently of the current page.
•	Reconnect the iPhone to the Wi-Fi, and go back to Status.
•	Select the “Chats” tab at the bottom, the chats page is displayed and “Offline” is still displayed at the top of the chat page.

![image-2](https://user-images.githubusercontent.com/33925578/33663735-152eb366-da89-11e7-9187-7f2f8a9c84c2.png)

### Additional Information:

* Status version: 0.9.12 (1557.321)
* Operating System: <iOS version 11.1.2> iPhone SE   -  Android: #2314

**Comment by annadanchenko** [comment] 2017-12-07 22:55
@ReneeAB thank you for the bug report! Can you please be more specific with steps to reproduce? For example, on what step is Flight mode is turned on? What makes you think that app is offline at the end in `Reconnect the iPhone to the wifi, Status is still offline.`? There is definitely a bug, however it looks like app is just frozen and does not respond to any taps except swiping, so I would not call it Offline. 

The behaviour looks similar to https://github.com/status-im/status-react/issues/2314 but it starts a bit earlier then in #2314

**Comment by ReneeAB** [comment] 2017-12-08 14:43
Hi @annadanchenko, I modified the steps to make it easier to reproduce, when I switched off the airplane mode I opened Status again and I wait to see if the "Offline" disappears after few seconds but it was still displayed at the top of the "Chats" page.

**Comment by asemiankevich** [comment] 2018-04-20 11:52
no swipe functionality now, closing

**Closed as completed by asemiankevich** 2018-04-20 11:52 UTC
