### ISSUE TITLE
Update the Qt version that is used by Jenkins to Qt 5.11.2

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6053] opened 2018-09-28 11:50 UTC
Updating Qt will fix several issues with the desktop app.
There should be no downsides given our current experience

**Comment by chadyj** [comment] 2018-10-01 08:51
@jakubgs 👍 All good to proceed! Thank you!

**Comment by churik** [comment] 2018-10-01 08:52
Tested `Status` with QT 5.11.2 - no regression issues are found

**Comment by jakubgs** [comment] 2018-10-02 04:13
Prepared the change here: https://github.com/status-im/status-react/pull/6062
Successful Build: https://ci.status.im/job/status-react/job/pull%20requests/job/PR-6062/17/
Docker image name: `statusteam/linux-desktop-ubuntu:qt-5.11.2`


<blockquote><img src="/static/39b36f89/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/pull%20requests/job/PR-6062/17/">status-react » pull requests » PR-6062 #17 [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment] 2018-10-03 15:24
I'm going to merge the QT upgrade PR since it's tested and everything seems to be working fine.

**Comment by jakubgs** [comment] 2018-10-03 15:51
Merged at: https://github.com/status-im/status-react/commit/4f9b2d91ead3dc44e8a7b34cb08b3c549c2f0987

**Comment by jakubgs** [comment] 2018-10-03 15:53
We will proabably also have to do this:
https://github.com/status-im/react-native-desktop/pull/355
Butt builds are failing right now on tests, and I'm not sure how to solve that, maybe @vkjr can help.

**Closed as completed** 2018-10-03 17:24 UTC

**Comment by vkjr** [comment] 2018-10-04 08:12
@jakubgs, looking into it!
