### ISSUE TITLE
Create profile screen: no error when user entered short password

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#21324] opened 2024-09-25 13:53 UTC
# Bug Report

User doesn't receive error when inserting short password but "Confirm password" button stays inactive

![Simulator Screenshot - iPhone 13 - 2024-09-25 at 14 41 52 - 01](https://github.com/user-attachments/assets/2c441956-ad9e-4758-a7b7-6c026f8e889e)

## Problem 
It should be obvious for the user why "Confirm button" can't be pressed. Currently it is not the case.

#### Expected behavior
User receives an error indicating that password is too short

#### Actual behavior
User doesn't receive an error

### Reproduction

1. Start creating new account
2. Enter same password in both fields that is less than 10 character

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ilmotta** [comment] 2024-10-04 13:42
@vkjr I reduced the priority on this issue and removed the `bug` label because the user has a hint the password must be at least 10 characters long. What this issue suggests is an improvement, so I changed the issue to be a `feature`. Is there a reference in Figma about the expected outcome?

**Comment by churik** [comment] 2024-10-07 14:29
Removed from milestone due to limited capacity and low priority.
@ilmotta this particular case is not covered in figma, referring to  https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=12860-104969&t=a8tJ8pFviPwov11C-4 


I believe there should be just "Minimum 10 characters" and the disabled button, agree that this is very minor bug
![Image](https://github.com/user-attachments/assets/ce711024-4af6-4c5e-a7f4-a8e1c2b75d50)

**Comment by israr002** [comment] 2024-11-26 19:00
@ilmotta @churik @vkjr Just wanted to confirm is this the expected behaviour ??
https://github.com/user-attachments/assets/889a8d66-b7cd-42c4-b767-3ecc4d65d5ad

**Comment by ilmotta** [comment] 2024-11-26 21:35
@israr002, from the video you shared https://github.com/user-attachments/assets/889a8d66-b7cd-42c4-b767-3ecc4d65d5ad, I see that as an improvement over what's currently in status-mobile `develop` 👍🏼 

Just a side note, unrelated but worth mentioning, the checkbox "I understand ..." will go away in the next release. The password strength verification is also bringing some confusion to the table because the information of weak/strong password is only there for show and doesn't block the user, but it does confuse some users as far as I've heard because they think they need to fulfill the strength verification "algorithm". My intention is to remove this feature, but this requires further discussions with other people and not everybody fully agrees on why password strength validators are bad or can be bad.

**Comment by vkjr** [comment] 2024-11-27 12:38
@israr002, for me - yes. If user can't press "confirm password" then it means there is some error. And on your video highlighting the "minimum characters" requirement gives a good clue on what the error is.

**Comment by israr002** [comment] 2024-11-27 13:27
@vkjr  Should I raise the PR for this issue, or hold off since @ilmotta mentioned the checkbox will be removed in the next release? There's also some confusion regarding password validation.

**Comment by vkjr** [comment] 2024-11-27 13:48
@israr002, I would say yes. Even if the checkbox will be removed, if you have an improvement, why not to apply it!
@ilmotta, wdyt?

**Comment by churik** [comment] 2024-11-27 15:30
checked this part, would be nice to not show "Password match" in a case when Minimum 10 characters are shown. To be honest, this is a very low-prio issue, and it is better to wait https://github.com/status-im/status-mobile/issues/21567 which will be ready in the upcoming days, as a checkbox indeed will be removed there

**Comment by ilmotta** [comment] 2024-11-27 15:44
@israr002 usually we also double-check with the Design team suggestions that affect the user experience. Also because they need to update Figma so we can (try to) keep the app and Figma synchronized.

Due to timezone differences, today is already a bit late for some folks. We can tag them here (@xAlisher @Francesca-G), but it may take a while to get feedback due to other higher priorities. I'll try to get in touch with them about this issue tomorrow. 

I hope this process isn't frustrating to you, but it's the process we follow even when there are small UI changes. Sometimes a simple issue uncovers deeper problems.

**Comment by israr002** [comment] 2024-11-27 17:30
@ilmotta Np, I completely agree that aligning as a team is crucial, even for small changes.
will wait for the feedback

**Comment by ilmotta** [comment] 2024-12-03 02:07
Update: For those with access to the Discord server, the topic has been raised to designers here https://discord.com/channels/1210237582470807632/1274068685266489434.

**Comment by xAlisher** [comment] 2024-12-03 08:01
Thank you for noticing that bug.

As part of our onboarding simplification initiative, we will remove the checkbox.

Passwords shorter than 10 characters should trigger an error label reading "Minimum 10 characters" in red, and the button should remain disabled.

Hope this helps!

**Comment by israr002** [comment] 2024-12-05 06:38
@ilmotta So i can raise the PR for error label "Minimum 10 characters" ?? and later Once the new onboarding flow ticket is implemented, the checkbox will be removed as part of that update.

**Comment by ilmotta** [comment] 2024-12-05 13:00
> [@ilmotta](https://github.com/ilmotta) So i can raise the PR for error label "Minimum 10 characters" ?? and later Once the new onboarding flow ticket is implemented, the checkbox will be removed as part of that update.

@israr002 I think so, I believe you can implement as @xAlisher suggested above. Probably better to wait until this other PR is merged https://github.com/status-im/status-mobile/pull/21715, which should be soon (this week probably).

**Comment by israr002** [comment] 2024-12-18 13:18
@ilmotta As shared in the earlier video, I implemented the logic to show an error for first Input  only when the passwords don’t match and the password length is less than 10 characters.
do we now need to show the error as soon as the user starts typing and then blurs out of the password field and if the length is less than 10 characters?

**Comment by churik** [comment] 2024-12-19 10:30
![Image](https://github.com/user-attachments/assets/4a38d1b5-57b9-4064-8c21-0412d5daa2b5)

Now it looks like this with a password of less than 10 characters. I believe this is **acceptable** and matches the expectations outlined in [this comment](https://github.com/status-im/status-mobile/issues/21324#issuecomment-2513801308).  

While the error message is not in red, I think it’s still **understandable and acceptable**.  

Please, **reopen the issue** if you want to prioritize it.  
cc @xAlisher @ilmotta  

Thank you for your activity, @israr002!  
If you’d like to contribute further, there are plenty of issues tagged with [design-feedback](https://github.com/status-im/status-mobile/issues?q=is%3Aissue%20state%3Aopen%20label%3Adesign-feedback) that you can pick. Feel free to choose something!

Do not hesitate to ask if you have any questions!

**Closed as completed by churik** 2024-12-19 10:30 UTC
Labels: mobile-core

**Comment by israr002** [comment] 2025-02-13 07:13
@churik I`m trying to raise a PR, but I'm getting a permission denied error. The documentation doesn't mention the need to create a fork. Do I need to fork the repository before raising the PR?

**Comment by ilmotta** [comment] 2025-02-17 09:47
> [@churik](https://github.com/churik) I`m trying to raise a PR, but I'm getting a permission denied error. The documentation doesn't mention the need to create a fork. Do I need to fork the repository before raising the PR?

Correct @israr002, you always need to fork the `status-mobile` repo to open a PR.
