### ISSUE TITLE
Design review: 1-1 chats (chat view)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16867] opened 2023-08-03 12:50 UTC
- [x] 1. Long names are not handled - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510047182) - https://github.com/status-im/status-mobile/issues/17217
- [x] https://github.com/status-im/status-mobile/issues/17252 - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510223499)  
- [x] https://github.com/status-im/status-mobile/issues/17251  - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510226735)  
- [x] 4.  User avatar is bigger than in designs - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511406255) 
- [x] #16894
- [x] https://github.com/status-im/status-mobile/issues/17250 - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3817-74882&mode=design&t=7oGIJsujWlrIaN19-4)
- [x] https://github.com/status-im/status-mobile/issues/17249 - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3817-74882&mode=design&t=7oGIJsujWlrIaN19-4)
- [x] #16907
- [x] #16904
- [x] #16908

**Comment by cammellos** [comment] 2023-08-04 16:24
4, 6 check with @yqrashawn since he's working on user avatars

2,5, 8, 9, 10 should be easy fixes, I would include those in 1.25

7 looks also fairly simple, but not 100% sure
1 I am not sure, I think it needs a bit more context on how long names are handled, I will look around to see an example, but if you have one, comment here

**Comment by churik** [comment] 2023-08-07 08:46
Requested from design team - got an example for chat list
here's the long name example for the messenger home https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8836%3A546523&mode=design&t=ajZQb3LrmFdQuxgc-1 

cc @Francesca-G if you can get more examples for the edge cases

**Comment by Francesca-G** [comment] 2023-08-07 09:51
> cc @Francesca-G if you can get more examples for the edge cases

Here's some other design examples that Mario kindly provided :)

Messages: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=9289%3A105042&mode=design&t=sX01KIK6NS6HGbKO-1

Community long description: https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=13726%3A96206&mode=design&t=TgGp16EYozKdvnpK-1
If the Community name is too long it should go on 2 lines

Hope this helps!

**Comment by cammellos** [comment] 2023-08-07 16:34
@Francesca-G I had a look at this comment:

https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511397756

I have checked by comparing the feedback screenshot with the designs and superimposing them, it looks like the icon is the right size, the boxes for normal emojii are slightly longer (not sure if that's an issue, it seems really a small difference), but one thing that is quite different though, is the "add emojii" box (the last one on the right), which is considerably shorter in the designs, while in the implementation all boxes have the same width. Is that what the comment is referring to?

thank you!

**Comment by Francesca-G** [comment] 2023-08-07 16:42
> @Francesca-G I had a look at this comment:
> 
> https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#511397756
> 
> I have checked by comparing the feedback screenshot with the designs and superimposing them, it looks like the icon is the right size, the boxes for normal emojii are slightly longer (not sure if that's an issue, it seems really a small difference), but one thing that is quite different though, is the "add emojii" box (the last one on the right), which is considerably shorter in the designs, while in the implementation all boxes have the same width. Is that what the comment is referring to?
> 
> thank you!

Yes, I was referring to the boxes :)
The problem Is mainly noticeable with the one on the right "add emoji" as you mentioned, but as you can see all the boxes are slightly bigger

<img width="653" alt="Screenshot 2023-08-07 alle 18 40 39" src="https://github.com/status-im/status-mobile/assets/122543089/fde90d08-f235-4d6f-84da-30872ca1ddcb">

**Comment by cammellos** [comment] 2023-08-07 16:43
@Francesca-G Thank you, I was following you on figma while doing the comparison, very helpful to see how it's done properly. I'll address the issue.

**Comment by yqrashawn** [comment] 2023-08-24 03:14
6 should be fixed in develop, working on 4

**Comment by yqrashawn** [comment] 2023-08-24 06:05
4 is probably fixed?
The message above long press action drawer is using the same message component. Both avatars are 32px
![CleanShot 2023-08-24 at 14 01 14](https://github.com/status-im/status-mobile/assets/15090582/40b9f4a5-19c5-4908-8988-e05985f9c150)
![CleanShot 2023-08-24 at 14 04 32](https://github.com/status-im/status-mobile/assets/15090582/0412728f-f8d0-405c-84bb-28c0bc829215)

**Comment by flexsurfer** [comment] 2023-08-24 07:27
hey @yqrashawn are you working on this issue ?

**Comment by yqrashawn** [comment] 2023-08-24 07:28
> hey @yqrashawn are you working on this issue ?

No. Only 4 and 6
@flexsurfer

**Comment by flexsurfer** [comment] 2023-08-24 07:38
1. Long names are not handled - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510047182)
there is a rule for handling long names?

**Comment by flexsurfer** [comment] 2023-08-24 07:42
7. Background of the back button is not visible - comment [here](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3817-74882&mode=design&t=7oGIJsujWlrIaN19-4)
it seems like its visible, but there is a light picture in the background in the designs, and contrast is higher, so it depends, design input is needed

**Comment by cammellos** [comment] 2023-09-13 12:35
@jo-mut are you still working on 1 and 4?

**Comment by ajayesivan** [comment] 2023-09-13 13:14
@cammellos @jo-mut I'm working on 1 here: https://github.com/status-im/status-mobile/issues/17217. Waiting for designs rn.

**Comment by jo-mut** [comment] 2023-09-13 13:17
@cammellos @ajayesivan  1: is out of the scope of my pr. I intend to first merge the pr and do a follow-up and 4: seems to have been resolved i think in @yqrashawn merged pr.

**Comment by churik** [comment] 2023-10-13 10:10
As 1 is tracked separately, closing this one

**Closed as completed** 2023-10-19 15:25 UTC
Labels: messaging
