### ISSUE TITLE
Composer UI shouldn't jump when opening keyboard and animation shouldn't stop

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#19567] opened 2024-04-09 09:11 UTC
## Problem 
[comment]: # (A problem description)
![CleanShot_2024-04-08_at_22 44 27](https://github.com/status-im/status-mobile/assets/33176106/fa03cab6-ab3b-483e-8da1-74d56a79895b)

#### Expected behavior
Composer UI shouldn't jump when opening keyboard and shouldn't stop mid animation, It should either finish completely or not start at all

#### Actual behavior
Composer UI jumps when opening keyboard, And animation stops when opening keyboard on an empty chat

**Comment by Parveshdhull** [comment] 2024-04-09 09:16
Hi @ibrkhalil, Thank you for reporting this issue. If we want to make sure we don't interpolate with scroll position(which changes here with keyboard state), we should animate it using timing to its final state. But first we should discuss this with design team to make sure they are ok with this.

**Comment by ilmotta** [comment] 2024-06-24 22:37
I'm closing this issue because we are parking work on the composer as much as possible due to its complexity and how easy it is to introduce regressions there. We want to lower this risk for the upcoming releases.

FYI: We are still looking for a simplification in the composer, like in this PR https://github.com/status-im/status-mobile/pull/20125.

**Closed as completed by ilmotta** 2024-06-24 22:37 UTC
Labels: blocked, chat-composer, mobile-core, wont-fix
