### ISSUE TITLE
Bug causing white screen until app restarted when rapidly switching tabs

### ISSUE THREAD

**Issue by ThreeMuskets12** [status-im/status-react#1672] opened 2017-08-23 02:36 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarize the bug and what you did, what you expected to happen, and what actually happens. Sections below)

*Summary*: When tapping back and forth rapidly between any of the three "Chats" "Discover" or "Contacts" tab, the screen stops switching between the tabs while the "Chats" "Discover" or "Contacts" tab still change from white to purple to indicate that they are active. If this action is continued and then stopped, the screen scrolls left to a blank screen and the app is unusable until restarted.

#### Expected behavior

[comment]: # (Describe what you expected to happen.)

I would expect that no matter how quickly I change tabs, that the correct tab would be displayed as I clicked it. 

#### Actual behavior

[comment]: # (Describe what actually happened.)

As you change tabs quickly, the screen no longer displays the correct tab that it is supposed to be displaying, and rather is stuck displaying one of the tabs. If you keep clicking between two different tab buttons while the screen is frozen and then stop, the screen scrolls left and a white screen is produced with no way to escape rendering the app unusable until restarted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Log into an account
- Start rapidly alternating by pressing one tab button on the bottom of the screen followed by pressing another tab, such as pressing "Chats" and then "Contacts" and then "Chats" and then "Contacts" and so on and so forth, as fast as possible.
-The screen will no longer switch between tabs and will be stuck displaying one of the 3 tabs.
-If you abruptly stop the pressing of the buttons and wait, the screen will slide to the left as if it were scrolling to a fourth tab, and display a plain white screen.
-There is no way to go back to any of the other tabs until the app is restarted.

### Solution

[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- The way that the app processing switching between tabs needs to be looked at and diagnosed until the bug causing code is found and subsequently repaired.

### Additional Information

[comment]: # (Please do your best to fill this out.)

* Status version: 0.9.10 (1558)

[comment]: # (Android or iOS.)

* Operating System: iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

**Comment by annadanchenko** [comment] 2017-08-23 07:00
Duplicate of #1038

**Closed as completed by annadanchenko** 2017-08-23 07:00 UTC
