### ISSUE TITLE
"null is not an object" appeared every time I wanted to switch networks

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4554] opened 2018-05-31 08:27 UTC
### Description

*Type*: Bug

*Summary*: The error was appearing when I tried to switch networks. I was on Rinkeby and I wanted to switch to Ropsten. In the end I wasn't able to change networks. Every time I pressed connect button, the error appeared. Killing the app fixed it. I could not replicate it anymore.

<img src="https://user-images.githubusercontent.com/7532782/40771041-873c4c6c-64bc-11e8-9468-594c0d1023c2.png" width="200">

#### Expected behavior
No error when switching networks.

#### Actual behavior
"null is not an object" error was preventing me from switching networks.

### Reproduction

I was not able to reproduce the issue.

### Additional Information
* Status version: release/0.9.19 25, 08e0ee9, May 31
* Operating System: happened on iOS

**Comment by chadyj** [comment] 2018-06-11 10:40
@lukaszfryc is this fixed now?

**Comment by lukaszfryc** [comment] 2018-06-11 11:01
@Serhy any idea about it? I remember you have tested a PR that should fix it

**Comment by Serhy** [comment] 2018-06-11 17:26
There were several PRs which indirectly may fix it (I assume).
1) https://github.com/status-im/status-react/pull/4221#issuecomment-389900440 - is where I was able to reproduce this issue (it was connected to GroupChats). But I can't reproduce the scenario is described there: GroupChats a hidden and invitation from GroupChats are blocked
2) https://github.com/status-im/status-react/issues/4597 (`DateTimeProtocol.plus-` issue had been involved there as well - we are about to fix this issue soon. 

This is a sporadic issue which may happen again, but I haven't seen it on during last week.

Let's close it for now and reopen if it appears again (with the TF session if possible or logs).

**Closed as completed** 2018-06-12 08:02 UTC
