### ISSUE TITLE
Profile picture for android device is not updated in 1x1 chat when change it offline

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6481] opened 2018-10-23 11:26 UTC
### Description

*Type*: Bug

*Summary*: If i change pic on Android for an account that is recovered on desktop and mobile at the same time, the picture is not updated in 1x1 chat when I go back online. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction

- Recover account on desktop
- Recover same account on android
- Create account on ios
- Add ios and android to contacts
- Change picture on Android
- Make sure it is updated in 1x1 chat with iOS
- Go to airplane mode on Android
- Change profile pic on android while offline
- Go online
- Check on iOS that profile picture for Android is not updated

### Additional Information
* Status version: release 0.9.30 candidate
* Operating System: Android 8
* Works when vise versa with IOS

**Comment by lukaszfryc** [comment] 2018-10-23 12:12
Duplicate of https://github.com/status-im/status-react/issues/5746?

**Closed as completed** 2019-01-29 17:08 UTC
