### ISSUE TITLE
Posts & attachments - Pinned messages drawer - Incorrect colors behind overlay

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#17531] opened 2023-10-04 13:58 UTC
# Bug Report

On Android, the top bar color and the button colors are incorrect when the pinned messages drawer is visible. This is likely a general issue when opening any bottom sheet on this screen.

<img src="https://github.com/status-im/status-mobile/assets/46027/e3f7683e-4fd8-4997-979f-7d27a5211460" width="375" />

## Expected

<img width="375" alt="Pinned Message" src="https://github.com/status-im/status-mobile/assets/46027/74c5806e-32bc-4d2d-b607-86333bf167c1">

## Resources

Reported at: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

Figma specs: https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=3505-368386&mode=design&t=tqru9be4o4mYQhQm-0

**Comment by jo-mut** [comment] 2024-02-04 23:35
this might be device specific.  It seems not reproducible on android 13 or 14

Android 13 & 14

<img src="https://github.com/status-im/status-mobile/assets/28704507/2b6d3afa-9679-4adf-b448-85001154a414" width="325">
<img src ="https://github.com/status-im/status-mobile/assets/28704507/ce31e447-9643-49a2-8dd5-63cad95c13c7"
width="325">

@Francesca-G could you let me know what android version the design team was able to reproduce this bug on please

**Comment by Francesca-G** [comment] 2024-02-05 08:16
> @Francesca-G could you let me know what android version the design team was able to reproduce this bug on please

This was found on Android 8.1.0

**Comment by jo-mut** [comment] 2024-02-12 23:21
This looks like its only reproducible on android 8.1 as mentioned https://github.com/status-im/status-mobile/issues/17531#issuecomment-1926434170. I was unable to reproduce it on android 14, 13, 12, 11, 9. 

Following a discussion we had in the **`Ui fit & Finish`** crew, there is not value in working further on this particular bug given that android 8 has a market share of about 2%

**Android 9**

<img src="https://github.com/status-im/status-mobile/assets/28704507/c2105b33-06ce-470f-b91d-326b89b3e26e" width="325">

cc @Samyoul

**Comment by jo-mut** [comment] 2024-02-13 15:50
@pavloburykh am not sure its worth working on this one.

**Comment by pavloburykh** [comment] 2024-02-14 07:11
> https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=6130-58226&mode=design&t=ZiIFjqxnna5FtOFo-0

@jo-mut if it is only reproducible on Android 8.1.0 then we can close the issue. I am not able to reproduce on Android 12.

**Closed as completed by pavloburykh** 2024-02-14 07:11 UTC
Labels: android
