### ISSUE TITLE
Sometimes add contact screen is closed by itself after scanning QR code (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18085] opened 2023-12-06 09:22 UTC
Most likely a regression of https://github.com/status-im/status-mobile/pull/17767 cc @jo-mut 

Reproducing on Samsung Galaxy A52, Android 12. Might be device/OS specific as failed to reproduce on Pixel 7a, Android 13. 

**Steps:** 

1. User A (Android) open Add contact screen
2. User A (Android) scans profile QR code of User B
3. See if Add contact screen is not closed by itself and User's profile link is displayed in the input field
4. Bug might not be reproduced from the first time (See the attached video). Try scanning different QR codes one by one unlit you get the described below unexpected behaviour

**Actual result:** sometimes Add contact screen in closed by itself after scanning QR. 

https://github.com/status-im/status-mobile/assets/97245802/7e3cb604-9ba6-49f8-bbf3-83de496008e6

**Expected result:** Add contact screen is not closed after scanning QR. 

- Status version: nightly 
- Operating System: Android 12
- Device: Samsung Galaxy A52

**Comment by jo-mut** [comment] 2023-12-06 09:26
I will take a look at this

**Comment by jo-mut** [comment] 2023-12-06 13:38
I tried reproducing this and seems to work well on Android 13. I am using Samsung s22. Looks like its devices specific as mentioned

**Comment by pavloburykh** [comment] 2023-12-06 15:10
> I tried reproducing this and seems to work well on Android 13. I am using Samsung s22. Looks like its devices specific as mentioned

@jo-mut it can be OS specific. I am reproducing it on Android 12, @qoqobolo reproduced it on Huawei P40 lite, Android 10.

**Comment by pavloburykh** [comment] 2023-12-06 15:13
@jo-mut also have updated description with a video as it hasn't been uploaded for some reason.

**Comment by jo-mut** [comment] 2023-12-06 15:13
I currently can get my hands on only android 13 but I will try see if i can get my hands on another device

**Comment by pavloburykh** [comment] 2023-12-06 15:24
> I currently can get my hands on only android 13 but I will try see if i can get my hands on another device

I have posted in general, maybe some of the devs have Android version < 13 and can help with debugging.

**Comment by Parveshdhull** [comment] 2023-12-06 16:33
Actually, bug is not directly related to #17767. Issue is already present in the implementation of `scan-qr-code` component.
#17767 started using this component for adding contact, and bug got highlighted.

I am also not able to produce above bug while scanning status qr codes in my Android 9 device, but if I scan any wrong qr code from google then issue is reproducible for me (sometime).

There is also another bug. If I open scan camera and then close using hardware back button then I am not able to reopen this screen. (no need to log separately, will be fixed in the scope of current issue)

https://github.com/status-im/status-mobile/assets/17097240/af2d03a5-16d2-4e3b-befb-d1f64c9a2e8f

**Comment by Parveshdhull** [comment] 2023-12-06 17:48
(Probably we should log this one separately, looks tricky)
on pressing hardware back button, system camera get dismissed on own. But we are also listening for hardware back button clicks in jump-to.view file, which dispatches :navigate-back event and causes to also dismiss add-contact screen.
Weird thing is I tried removing this listener and `:navigate-back` event is still getting dispatched :thinking:

**Comment by Parveshdhull** [comment] 2023-12-06 17:51
logged https://github.com/status-im/status-mobile/issues/18102

**Comment by pavloburykh** [comment] 2023-12-06 18:35
@Parveshdhull thank you so much for investigation of this issue!


> There is also another bug. If I open scan camera and then close using hardware back button then I am not able to reopen this screen. (no need to log separately, will be fixed in the scope of current issue)

Hmm, interesting! Thank you for finding and logging  @Parveshdhull . This issue has been fixed some time ago here https://github.com/status-im/status-mobile/pull/17694 but reproducible again. BTW, in my case any navigation does not respond until I tap system back button again


https://github.com/status-im/status-mobile/assets/97245802/fd4ce0f6-1ff0-4295-8d68-b53a7a646aee

**Comment by pavloburykh** [comment] 2023-12-06 18:43
@Parveshdhull sorry for the Video above. It is not showing touches but in fact I am trying to navigate to different app screens but there is not response until I tap system back button again.

**Comment by pavloburykh** [comment] 2023-12-06 18:59
Here is a video with showing taps @Parveshdhull 


https://github.com/status-im/status-mobile/assets/97245802/1b269d4b-0c89-48c9-8fa5-499654fd5d8d

**Closed as completed** 2023-12-08 13:23 UTC
