### ISSUE TITLE
[Communities] There is no bottom margin on iPhone SE under the Slide to request to join button 

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#18997] opened 2024-02-26 10:56 UTC
Follow up #18761

# Bug Report
During the refactoring to fix Community rules scroll we discovered that the fix is not perfect on iPhone SE and small devices.

Please check the following [comment](https://github.com/status-im/status-mobile/pull/18761#issuecomment-1948635977)

## Problem 
There is no bottom margin on iPhone SE under the Slide to request to join button 

#### Expected behavior
Should looks like [Figma](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=15331-285065&mode=design&t=26fIK54eJTrGJu3S-0)

![image](https://github.com/status-im/status-mobile/assets/5999878/f3b5f303-b43a-4b7c-be52-c09770d41f48)

#### Actual behavior
![image](https://github.com/status-im/status-mobile/assets/5999878/0c6aa5e3-4f41-462f-b43e-2074b1db2a17)

### Reproduction

1. Activate the Accounts Selection feature flag.
2. Input text of maximum length into the 'Dialog for new members' field on the desktop.
3. Invite a user and attempt to join this community on a mobile device.
4. Run the app on iPhone SE and verify that the slide is not rendering as expected
 
### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ibrkhalil** [comment] 2024-03-05 13:21
Duplicate of https://github.com/status-im/status-mobile/issues/18929
CC: @mohsen-ghafouri

**Closed as completed** 2024-03-08 16:24 UTC
Labels: community-permissions, accessibility
