### ISSUE TITLE
My contacts can't see my most up to date profile details

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4809] opened 2018-06-18 12:10 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to update my profile details (name and picture) so that my friends will be able to see them too. 
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: My profile details update properly on the "Profile" menu but the new ones are not visible for my contacts. 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

Everyone in my contacts should be able to see my most up to date profile details.

#### Actual behavior
[comment]: # (Describe what actually happened.)
The picture and the name don't update for them.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status on device A and B
2. Login with A and B
3. Make the 2 accounts friends
4. Go to the "Profile" menu of A
5. Click on "Edit"
6. Click on the "Edit" button of the profile picture circle
7. Click on "Select from gallery"
8. Select a photo
9. Change the name
9. Confirm the profile changes (Everything looks fine at this moment because the profile picture and the name are updated on my "Profile" menu)
11. Check the profile picture and the name of A with B

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: This is a newly introduced bug which I was not able to reproduce on 0.9.19 (6034). The target here is to get back to the normal behavior of the application when the profile details were visible for my friends at step 11 from the reproductions steps above.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.20, Nightly build "June 18", http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-b40b04-n-fl.apk
and 0.9.19 from AppStore

[comment]: # (Android or iOS.)
* Operating System: Android (can't test on iOS)
* Device: Xiaomi Redmi Note 5

#### Logs

https://gist.github.com/GeorgiG/7ca2bfa199a692eb630af65d84f8bfcf

<blockquote><img src="https://avatars1.githubusercontent.com/u/5781465?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/GeorgiG/7ca2bfa199a692eb630af65d84f8bfcf">profile photo not updating</a></strong></div><div>GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute to over 85 million projects.</div></blockquote>

**Comment by annadanchenko** [comment] 2018-06-18 12:34
@GeorgiG can you reproduce it several times?

**Comment by GeorgiG** [comment] 2018-06-18 12:39
@annadanchenko, yep, I did it a few times but forgot to mention that the 2 devices use 2 separate versions of Status.

**Comment by annadanchenko** [comment] 2018-06-18 14:21
@GeorgiG @cammellos afaik we might have even worse issues with 0.9.19 and 0.9.20 - like not getting messages sometimes (because old cluster is used in 0.9.19). 

@GeorgiG please, test with similar versions on both devices for now and if you can reproduce on same 0.9.20 then it's an issue

**Comment by annadanchenko** [comment] 2018-06-18 14:28
in addition we have known open issue that lead to similar problem: https://github.com/status-im/status-react/issues/3955

**Comment by GeorgiG** [comment] 2018-06-18 15:15
@annadanchenko, I can confirm what you've noticed with the missing messages sometimes. 

The issue is not reproducible with similar versions, or at least I was not able to with my testing so far.

Update: I've performed a lot of further testing and it seems that the issue is not reproducible in 100% of the time, just as not getting the messages just sometimes, which makes sense. For example, I was able to see the updates of A and B properly multiple times, then I logged out and in without any further changes and the updates were not visible again.

**Comment by annadanchenko** [comment] 2018-06-18 17:16
@GeorgiG sorry I was not clear enough. I mean that it's expected that there will be issues between 0.9.19 and 0.9.20. 

So, if you can see original issue when only 0.9.20 is used on both devices then it's something to be investigated and fixed. I will close this report for now. Please, feel free to re-open if you can reproduce on 0.9.20 installed on both devices

**Closed as completed** 2018-06-18 17:18 UTC
