### ISSUE TITLE
Username overlaps the frame of a reply quote for desktop

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6364] opened 2018-10-17 13:47 UTC
Type: Bug

Summary: Username overlaps the reply quotation frame when resizing the app window

**Expected behavior**

Text is not overlapping the quotation frame

**Actual behavior**

Text is overlapping the quotation frame

**Reproduction**

1. Open Status desktop with any chat
2. Reply to any message 
3. Resize the app window to reproduce one of the cases below:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/43638377/47090228-26bac080-d22b-11e8-9692-9c2a1c936ab3.png">

<img width="255" alt="image" src="https://user-images.githubusercontent.com/43638377/47090282-4a7e0680-d22b-11e8-8da8-c6caae46a194.png">

**Additional Information**

Status version: Release 0.9.30 (10755) - a nightly from 17 Oct 2018
Tested on MacOS 10.13.4

**Comment by churik** [comment] 2018-11-30 14:59
Duplicate of https://github.com/status-im/status-react/issues/6216

**Closed as completed by churik** 2018-11-30 14:59 UTC
