### ISSUE TITLE
Some of mutual contacts can not be added to the group chat

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14027] opened 2022-09-16 17:16 UTC
Bug is related to recent changes in status go https://github.com/status-im/status-go/pull/2828 cc @osmaczko 

In some cases it is impossible to create a group chat with mutual contact or to add this mutual contact to an existing group. 

For reproduction of the bug we have an example of 2 users who are mutual contacts. 

**User A:** Super Harmful Wildcat
**passphrase:** length depend bottom mom kitchen solar deposit emerge junior horse midnight grunt

**User B:** Lightsalmon Wry Umbrette
**passphrase:** style case lazy pole general section dawn royal slice evoke crowd boat

**Steps:** 
1. Restore User A on device 1 and User B on device 2
2. After account is being restored wait untill users' backed up contacts will appear
3. Make sure that users are mutual contacts (User A is a contact to User B and User B is a contact to User A)
4. Try to create a new group chat by User A with adding User B as a member OR try to add User B to an existing group. 
5. Observe the result

**Actual result:** User A cannot create group chat with mutual contact User B (or add User B to an existing group). At the same time, User B can create group chat with User A or add User A to an existing group. 

**Expected result:** User A can create group chat with mutual contact User B (or add User B to an existing group).

https://user-images.githubusercontent.com/97245802/190696402-d0a49c90-e886-467d-8d9b-1ef606deebee.mp4

[geth.log](https://github.com/status-im/status-mobile/files/9585945/geth.log)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**IMPORTANT:**
A small request to the one who will be fixing this issue, please do not remove existing contacts of given User A, as this user is a part of e2e test ID 5721. Deleting contacts will break the test. At the same time you can add/remove User B from contacts if it will be needed. 

[comment]: # (Please, add logs/notes if necessary)

**Comment by osmaczko** [comment] 2022-09-19 08:04
The issue seems to be contacts backup problem, most likely backed up contacts do not restore some properties correctly. This is confirmed by `log: t=2022-09-16T15:44:35+0000 lvl=warn msg="Served wakuext_addMembersToGroupChat" reqid=68 t="483.084µs" err="group-chat: can't add members who are not mutual contacts"`.

**Comment by churik** [comment] 2022-09-19 09:12
I don't think that these users have such property, it is a backward compatibility issue - "backup" feature was implemented earlier than mutual contacts, but we need to support this anyway

**Comment by cammellos** [comment] 2023-07-14 11:11
closing as descoped

**Closed as not planned by cammellos** 2023-07-14 11:11 UTC
Labels: group-chat
