### ISSUE TITLE
Hide "Back", "Forward" and "Reload" buttons when keyboard open on Android

### ISSUE THREAD

**Issue by churik** [status-im/status-react#5202] opened 2018-07-17 11:12 UTC
### Description
_Type_: Bug
_Summary_: If user opens keyboard to modify URL in webview on Android, he can see navigation buttons and accidentally tap on them. 

#### Expected behavior
navigation buttons are hidden (overlapped by keyboard) like on iOS
![ios](https://user-images.githubusercontent.com/4557972/42813942-49c7409c-89cb-11e8-9354-d07c3d100641.png)

#### Actual behavior
OnAndroid:
![1234](https://user-images.githubusercontent.com/4557972/42813822-e2510a60-89ca-11e8-96f8-1451bc75ff69.png)

### Reproduction

* Open Status on Android
* Send link to public chat
* Open link
* Put focus to webview URL field (to open keyboard)

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: [nightly 17/07](https://webapp.diawi.com/install/xk9Bsd)
NOTE: is not reproducible on last release 0.9.22(6164)
* Operating System: iOS

**Comment by flexsurfer** [comment] 2018-07-17 15:43
i'm not sure we need these buttons while typing, but we need more content area for sure, so maybe it's not a bug but the feature? :)

**Comment by churik** [comment] 2018-07-26 14:30
I believe it is a bug, because we hadn't it before (on release 0.9.22(6164) and behavior is different on Android.

**Comment by flexsurfer** [comment] 2018-07-26 15:11
I believe it is a feature, because i made this change :) do you really need these buttons?

**Comment by churik** [comment] 2018-07-27 07:55
I don't; but I think  it should be the same in Andorid and IOS on such case

**Comment by Serhy** [comment] 2018-10-03 13:07
Issue still takes place in 0.9.29 Release

@denis-sharypin what's better way to go here to have the same behavior on both iOS and Android when keyboard appears in webview?
- bottom webview tool panel (Back/Fwd/ModalChat/Refresh buttons) is hidden (current iOS behavior)
- bottom webview tool panel is above keyboard (current Android behavior)

I support @flexsurfer idea to not have them when I need to type anywhere withing webview to have more area for webview content. 
Also having the panel always on foreground increase probability of miss tapping the right item. E.g. google quick answers list:
<img width="364" alt="screen shot 2018-10-03 at 16 06 04" src="https://user-images.githubusercontent.com/8749671/46412130-4a0f4700-c726-11e8-9850-c46628da9509.png">
Attempt to tap `status ethereum github` may result in tap on Back/Fwd button.

**Comment by denis-sharypin** [comment] 2018-10-04 07:01
@Serhy Yep, we don't need this panel while editing an URL. So this option is preferable
`bottom webview tool panel (Back/Fwd/ModalChat/Refresh buttons) is hidden (current iOS behavior)`

**Comment by rachelhamlin** [comment] 2018-10-04 12:27
Updated issue to say the opposite :)

**Comment by Serhy** [comment] 2019-01-02 13:18
Issue still present in 0.9.33 develop build (removing `stale` label, updating platform label)

**Comment by churik** [comment] 2020-02-24 18:17
still relevant in Status v1.0.1 (Android 9, IOS 13)
The issue is that it is different on IOS and Android - I would prefer to have the same behavior on both platforms.

**Comment by cammellos** [comment] 2020-11-18 08:19
@churik I would list this as won't fix , closing it for now, please feel free to re-open if you think otherwise. Thanks!

**Closed as completed by cammellos** 2020-11-18 08:19 UTC
Labels: android
