### ISSUE TITLE
'Unknown' contact screen is shown after transaction signed in Dapp

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6283] opened 2018-10-12 09:22 UTC
### Description

*Type*: Bug

*Summary*: Unknown contact screen is shown after i requested stt from simple dapp on Ropsten
There is a forced navigation chat screen happens after Sign Transaction -> tap 'Got it' button in the case when `Transaction Fee` being updated during. 
Navigation occurs to the most recent chat visited before transacting in the Dapp. In a case, there were no chats prior Dapp TX at all - 'Unknown' chat created.
In any case issue is that we navigate to chat screen after the transaction in Dapp made. 

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/46860549-5330a000-ce19-11e8-84f4-f726a95345e7.png)

#### Expected behavior
 User stays on Dapp screen after transaction sign in Dapp.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status develop (build locally)
- Go to Ropsten with new account
- Request ETH in simple dapp
- Request STT in simple dapp (expand Adnaced screen )
- Pay attention to the screen after you tap Got it

### Reproduction 2 
1) Open Status and create an account
2) Join public chat (e.g. `#cryptopeople`)
3) Open `SimpleTestDapp` -> `Assets`
4) `Request Ropsten ETH` (skip if you have ETH already)
4) `Advanced` -> `Transaction Fee` -> Tap `Done` button
5) Sign transaction 
**Actual result:** Contact navigated to `#cryptopeople` public chat 

TF session with logs: https://app.testfairy.com/projects/4803622-status/builds/8625368/sessions/4403800939/?accessToken=Zxcidk0V/5fszsWM0ymrc9M3n3I

**Comment by lukaszfryc** [comment] 2018-10-12 10:39
It maybe related to #5606 (react navigation) as there was https://github.com/status-im/status-react/issues/5878 which should be already fixed now. cc @rasom @yenda

**Comment by asemiankevich** [comment] 2018-10-12 11:00
@lukaszfryc as i know it was not the case for e2e runs for all the current week @Serhy right?

**Comment by Serhy** [comment] 2018-10-12 13:49
@lukaszfryc @asemiankevich your both assumptions are right :) 
Same e2e test that failed today and revealed this issue was OK during last week. 
And assuming that it's a regression from #5606 (react navigation) also makes sense, because we didn't have specific scenario checking that "After Dapp TX there is no navigation to another screen" 

We'll update the existing test script test_send_transaction_from_daap to cover this issue

**Closed as completed** 2022-05-23 12:42 UTC
Labels: e2e test blocker
