### ISSUE TITLE
Existing Account Address is overwritten if the same account is scanned with chains

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20822] opened 2024-07-19 14:13 UTC
# Bug Report

Steps: 

1. Login to app as User A
2. Go to Profile -> Wallet -> Saved addresses
3. Tap on + and paste address in such format `0xed620c9dc11401b63b35dfe8e93f2b11db0f6f9e` with no chains.
4. Save address as `Test1`
5. Tap + and past the same address with added chain "eth:0xed620c9dc11401b63b35dfe8e93f2b11db0f6f9e"
6. Save address as `Test2`

#### Actual behavior

No `Test1` record in the list of Saved Addresses anymore, `Test2` record is created as a new one

#### Expected behavior

Validation should take place when we try to create the `Test2` record.

<img width="301" alt="Screenshot 2024-07-19 at 16 10 16" src="https://github.com/user-attachments/assets/1d8659b4-67cf-436b-95b3-31acd0196487">

https://www.figma.com/design/QWJV5WRbroXVDsdubEDjAT/Wallet-settings-for-Mobile?node-id=71-142051&t=EHg0EQkMykeEi6qM-0

### Additional Information

- Status version: nightly 19/07
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mohsen-ghafouri** [comment] 2024-07-29 14:53
Hey @mariia-skrypnyk, could you please check this issue if still reproducible or not, I belivee this issue already has been resolved in this PR https://github.com/status-im/status-mobile/pull/20839, and as i checked with latest dev changes, couldn't reproduce the issue 

<img src="https://github.com/user-attachments/assets/027f30e8-1ca7-4e23-bc45-edd4f714709d" width="390px"/>

**Comment by mohsen-ghafouri** [comment] 2024-08-29 19:11
Hey @mariia-skrypnyk in case you may missed my message, please check again this issue if it's reproducible anymore or not. thanks

**Comment by mariia-skrypnyk** [comment] 2024-09-09 11:27
> Hey @mariia-skrypnyk in case you may missed my message, please check again this issue if it's reproducible anymore or not. thanks

Thanks @mohsen-ghafouri !
Issue is resolved, checked on nightly. 🙌

**Comment by mohsen-ghafouri** [comment] 2024-09-09 11:32
Thank you @mariia-skrypnyk.

**Comment by mohsen-ghafouri** [comment] 2024-09-09 11:33
Thank you @mariia-skrypnyk.

**Closed as completed by mohsen-ghafouri** 2024-09-09 11:33 UTC
Labels: wallet: Settings
