### ISSUE TITLE
No share working on Invite to community empty state

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19744] opened 2024-04-19 16:35 UTC
# Bug Report

**Steps:**

1. Login to app with user that has no contacts
2. Use any link to any community and Join it
3. Make a long tap on community from communities list
4. Tap Invite people from contact list

#### Expected behavior
<img width="587" alt="Screenshot 2024-04-19 at 18 27 38" src="https://github.com/status-im/status-mobile/assets/147824399/d2281a14-2773-4703-b982-b3970a8e214c">

https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=5933-283369&mode=design&t=MRQW8bYYMZbMhkHI-0

#### Actual behavior
Nothing happens when user taps on `Send community link` button

https://github.com/status-im/status-mobile/assets/147824399/f77d8c86-074b-402c-bf1f-e4e8441c4130

### Reproduction

1. 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment] 2024-04-22 11:01
duplicate of https://github.com/status-im/status-mobile/issues/19725 
closing this one.

**Closed as completed by pavloburykh** 2024-04-22 11:01 UTC
