### ISSUE TITLE
If you tap on "Send message" from user profile, which is opened from public chat, icon with first letter of username is shown instead of user icon

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6827] opened 2018-11-21 12:50 UTC
### User Story

As a user, I want to see user picture when I started the chat.
### Description
*Type*: Bug
*Summary*: if you are navigating to user profile from public chat and then tap on "Send message" you will see an icon with first letter of username instead of user icon.

#### Expected behavior
User icon is shown in chat header

#### Actual behavior
![wr_icon](https://user-images.githubusercontent.com/4557972/48841811-cf13f580-ed92-11e8-8fc0-1d117fe50190.png)

### Reproduction

- Open Status
- Join any chat
- Tap on user icon to see his profile
- Tap on 'Send message'

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly 21/11/2018
* Operating System: Android, iOS

**Comment by mandrigin** [comment] 2019-02-27 14:13
cannot reproduce on iPhone XS, iOS 12, closing

**Closed as completed by mandrigin** 2019-02-27 14:13 UTC
