### ISSUE TITLE
Can't use dApps (outside of dApp explorer) in iOS app

### ISSUE THREAD

**Issue by cstrat** [status-im/status-react#10657] opened 2020-05-15 01:12 UTC
# Problem

In previous versions I was able to use dApps from within the app just by navigating to their URL.
This is now not possible, it looks as if I have not given permission - but there is no way to grant permission.

## Implementation

Example, navigate to dapp via URL not via the dApp explorer.
The dApp loads but it loads as if there were no web3 interface.
There is no prompt to give permission so the dApp doesn't work.

This previously worked fine in Test Flight 100% it worked, I am not certain at what point it stopped working but definitely now that I am using the live app it doesn't work.

**Comment by churik** [comment] 2020-05-15 10:10
@cstrat
Thank you for reporting!
Can you please specify DApp URL what is worked before, and stopped working now?

**Comment by cstrat** [comment] 2020-05-15 12:06
dice2.win and etheroll.com (although the second isn't working at the moment anyway)

**Comment by churik** [comment] 2020-05-18 08:13
@cstrat 
I tried dice2.win now on Status v.1.0 (we updated webview on v1.3) and I see that it supports only Trust Wallet.
I didn't manage to connect etheroll.com to Status wallet as well. 

It would be really helpful if you can specify Status version when they worked before.
Currently, I'm not able to reproduce this issue because for me it looks like apps don't support Status at all.

**Comment by cstrat** [comment] 2020-05-18 09:43
I remember seeing that same trust wallet message or something similar in the past when I hadn't given permission to status. There was an update to status somewhere along the way when they made you explicitly give permission for dApps.

Maybe there was an update with dice2.win and they now don't support status? I thought status just had a web3 interface.

**Comment by cammellos** [comment] 2020-12-02 08:32
Closing as tracked already here https://github.com/status-im/status-react/issues/5162 and dice2.win seems to be explicitly only supporting trust wallet.

**Closed as completed by cammellos** 2020-12-02 08:32 UTC
