### ISSUE TITLE
Dev Mode showed as enabled but not enabled for new account

### ISSUE THREAD

**Issue by martinklepsch** [status-im/status-react#3830] opened 2018-04-11 08:01 UTC
Steps to reproduce:

1. Log into an account and ensure that dev mode is enabled, and the console is visible in Home tab
2. Log out
3. Create new account
4. Verify the following issues:
    - Dev mode toggle will be enabled
    - The console is not visible on Home tab
    - Tapping Dev mode toggle again will keep the toggle enabled and Console will appear in home tab.

Untested: maybe this issue also occurs when switching between existing accounts? 

Platform: iOS

**Comment by lukaszfryc** [comment] 2018-04-11 08:05
Duplicate of https://github.com/status-im/status-react/issues/3777

**Closed as completed by lukaszfryc** 2018-04-11 08:05 UTC
