### ISSUE TITLE
"BigNumber Error: div() not a number: null" error on Transaction History screen after network change

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#5357] opened 2018-08-01 15:07 UTC
### Description

*Type*: Bug

*Summary*: `TaskQueue: Error with the task : BigNumber Error: div() not a number: null` shown when refreshing txn history (android). Happens when changing account network from Mainnet (where there are a lot of transactions) - to Ropsten/Rinkeby and staying on Transaction History screen.

Transaction History could be accessed from main Wallet screen or from modal wallet screen (at top app panel in 1-1 chat/webview) and is reproduced in both cases (see steps to reproduce)

#### Actual behavior
```
07:58 I/ReactNativeJS: NAME: "BigNumber Error"
07:58 I/ReactNativeJS: MESSAGE: TaskQueue: Error with task : BigNumber Error: div() not a number: null
07:58 I/ReactNativeJS: 
07:58 I/ReactNativeJS: This error is located at:
07:58 I/ReactNativeJS:     in t
07:58 I/ReactNativeJS:     in RCTView
07:58 I/ReactNativeJS:     in t
07:58 I/ReactNativeJS:     in RCTView
07:58 I/ReactNativeJS:     in RCTScrollView
07:58 I/ReactNativeJS:     in AndroidSwipeRefreshLayout
07:58 I/ReactNativeJS:     in RefreshControl
07:58 I/ReactNativeJS:     in ScrollView
07:58 I/ReactNativeJS:     in t
07:58 I/ReactNativeJS:     in t
07:58 I/ReactNativeJS:     in t
07:58 I/ReactNativeJS:     in reagent56
07:58 I/ReactNativeJS:     in RCTView
07:58 I/ReactNativeJS:     in history-list
07:58 I/ReactNativeJS:     in reagent133
07:58 I/ReactNativeJS:     in RCTView
07:58 I/ReactNativeJS:     in transactions
07:58 I/ReactNativeJS:     in reagent131
07:58 I/ReactNativeJS:     in RCTView
07:58 I/ReactNativeJS:     in main
07:58 I/ReactNativeJS:     in root
07:58 I/ReactNativeJS:     in reagent1
07:58 I/ReactNativeJS:     in RCTView
07:58 I/ReactNativeJS:     in RCTView
07:58 I/ReactNativeJS:     in t
07:58 I/ReactNativeJS: 
07:58 I/ReactNativeJS: Q@index.android.bundle:25:6268
07:58 I/ReactNativeJS: A@index.android.bundle:25:11801
07:58 I/ReactNativeJS: W@index.android.bundle:25:2594
07:58 I/ReactNativeJS: div@index.android.bundle:25:12273
07:58 I/ReactNativeJS: token__GT_unit@index.android.bundle:12:1352214
07:58 I/ReactNativeJS: internal__GT_formatted@index.android.bundle:12:1352925
07:58 I/ReactNativeJS: render_transaction@index.android.bundle:12:6920816
07:58 I/ReactNativeJS: index.android.bundle:12:6928130
07:58 I/ReactNativeJS: index.android.bundle:12:5747670
07:58 I/ReactNativeJS: value@index.android.bundle:349:9998
07:58 I/ReactNativeJS: f@index.android.bundle:136:83728
07:58 I/ReactNativeJS: beginWork@index.android.bundle:136:87321
07:58 I/ReactNativeJS: o@index.android.bundle:136:128242
07:58 I/ReactNativeJS: a@index.android.bundle:136:128621
07:58 I/ReactNativeJS: T@index.android.bundle:136:132129
07:58 I/ReactNativeJS: y@index.android.bundle:136:131565
07:58 I/ReactNativeJS: v@index.android.bundle:136:131402
07:58 I/ReactNativeJS: h@index.android.bundle:136:130681
07:58 I/ReactNativeJS: c@index.android.bundle:136:129935
07:58 I/ReactNativeJS: enqueueSetState@index.android.bundle:136:60044
07:58 I/ReactNativeJS: setState@index.android.bundle:198:1225
07:58 I/ReactNativeJS: _updateCellsToRender@index.android.bundle:327:19792
07:58 I/ReactNativeJS: index.android.bundle:328:597
07:58 I/ReactNativeJS: value@index.android.bundle:283:1025
07:58 I/ReactNativeJS: I@index.android.bundle:282:1181
07:58 I/ReactNativeJS: index.android.bundle:118:1787
07:58 I/ReactNativeJS: x@index.android.bundle:118:643
07:58 I/ReactNativeJS: k@index.android.bundle:118:1007
07:58 I/ReactNativeJS: callImmediates@index.android.bundle:118:3188
07:58 I/ReactNativeJS: value@index.android.bundle:113:3183
07:58 I/ReactNativeJS: index.android.bundle:113:1516
07:58 I/ReactNativeJS: value@index.android.bundle:113:3009
07:58 I/ReactNativeJS: value@index.android.bundle:113:1486
07:58 I/ReactNativeJS: [native code]
07:58 I/ReactNativeJS: value@index.android.bundle:113:1094
07:58 I/ReactNativeJS: [native code]
07:58 I/ReactNativeJS: 
07:58 I/ReactNativeJS: ***
07:58 I/HwPointEventFilter: do not support AFT because of no config
```

![image](https://user-images.githubusercontent.com/28752642/43530068-542c1f12-95b5-11e8-98df-5c467fdcafac.png)

### Reproduction 1

1. Recover account with > ~10 transactions on Mainnet (Mainnet network enabled by default in that case)
2. Navigate to Wallet -> Transaction History
3. Switch to Ropsten/Rinkeby network
4. Navigate to `Wallet` -> `Transaction history` list and stay on that screen up to 1 minute.

### Reproduction 2

1. Recover account with > ~10 transactions on Mainnet (Mainnet network enabled by default in that case)
2. Navigate to Wallet -> Transaction History
3. Switch to Ropsten/Rinkeby network
4. Navigate to `Open Dapp` -> open any Dapp and from webview tap on modal Wallet icon at hte top-right of screen and then -> to list of transactions (`<-/->` button)

### Additional Information
* Status version: develop
* Operating System: Android, iOS

TF session with logs (from 03:00 to 04:30): https://app.testfairy.com/projects/4803622-status/builds/8546611/sessions/4397939236/?accessToken=cjUZukcngV3IVf2K11yIAbjDa3c
 
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8543805/sessions/4397614944/?accessToken=jq0G1t09Hq7xPIK4ToogQK/iGDU">TestFairy: Status 0.9.24 (6289) @2018</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment] 2018-08-14 14:07
I've just got this error after switching to Ropsten, sending STT and going to Transaction History. I tested on 0.9.26 (6368)

**Comment by Serhy** [comment] 2018-08-14 15:57
Reproduced with `0.9.26 (6381) node a6d69eb` develop build.

**Comment by dmitryn** [comment] 2018-09-05 14:15
@Serhy @lukaszfryc @asemiankevich i cannot reproduce it on latest nightly https://status-im.ams3.digitaloceanspaces.com/StatusIm-180905-104553-c8e726-nightly.apk
and current develop branch c8e7267f3ad876f70e1be04966d03ed0758a41fa 

<blockquote></blockquote>

**Comment by Serhy** [comment] 2018-09-05 15:53
I hardly tried to reproduce with the same nightly build, @dmitryn. Android 6.0.1, Android 7.0, iOS 11.4.1 but couldn't. 
Happy to close this issue for now!

**Closed as completed by Serhy** 2018-09-05 15:53 UTC
Labels: ios, android
