### ISSUE TITLE
Error when requesting to join community

### ISSUE THREAD

**Issue by chair28980** [status-im/status-react#20928] opened 2024-07-30 18:21 UTC
# Bug Report

## Problem 

Request to join community flow breaks after password input.

#### Expected behavior

A confirmation message that the request was sent after password input.

#### Actual behavior

Screen freezes after 'Request to join' button is pressed after password input.

### Reproduction

1. Find the Zuzalu.city community 
2. Request to join on mobile

### Additional Information

- Status version: nightly 
- Operating System: iOS

https://github.com/user-attachments/assets/87068c65-088c-4c27-af47-f92588808c9d

**Comment by ilmotta** [comment] 2024-07-30 19:23
The failure is due to this error:

```
Signing a joining community request for accounts migrated to keycard must be done with a keycard
```

And further in status-go:

> Provided accounts must not belong to a keypair that is migrated to a keycard.
> Otherwise, the signing will fail, cause such accounts should be signed with a keycard.
>
> -- https://github.com/status-im/status-go/blob/5d309e2c64f59eb46fbfd40fd38f5f1102f6ff8f/protocol/messenger_communities.go#L1409-L1411

**Comment by chair28980** [comment] 2024-07-31 03:25
@ilmotta Interesting, I'm 99% certain I have not migrated that account to keycard 😅

**Comment by ilmotta** [comment] 2024-07-31 11:26
@chair28980, it does look like you are hitting a bug due to a very recent regression in status-go, now reported in status-desktop https://github.com/status-im/status-desktop/issues/15899

**Comment by ilmotta** [comment] 2024-08-01 00:47
@chair28980 This bug will likely be fixed once we update the mobile release branch using this PR https://github.com/status-im/status-mobile/pull/20938 because it will include the fix in status-go release branch.

**Comment by ilmotta** [comment] 2024-08-06 03:23
@chair28980, testflight should already have the fix. Please, let us know if you are now able to join that community. Thanks 🙏🏼

**Comment by chair28980** [comment] 2024-08-07 05:24
I have sent a request to join on mobile and it is pending.

**Comment by chair28980** [comment] 2024-08-08 00:46
Update, request still pending.

**Comment by churik** [comment] 2024-08-08 16:03
@chair28980 I'll close this is favor of https://github.com/status-im/status-mobile/issues/20991, you can track the progress there

Initial issue was already fixed

**Closed as completed by churik** 2024-08-08 16:03 UTC
