### ISSUE TITLE
Allow open membership communities

### ISSUE THREAD

**Issue by du82** [status-im/status-react#12609] opened 2021-09-21 13:05 UTC
As a community manager, I want to let anyone into my community without requiring them to go through an approval queue so they can instantly join and talk.
It would be great to have the option to switch between invite only, open membership, and closed invite.

**Comment by churik** [comment] 2021-09-22 07:05
Duplicate of https://github.com/status-im/status-react/issues/12548

**Closed as completed by churik** 2021-09-22 07:05 UTC
Labels: feature
