### ISSUE TITLE
Wallet: Disable "From" networks in send & bridge flow

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18655] opened 2024-01-29 04:28 UTC
As a user
I want to be able to disable some routes when sending a token

- [ ] Implement UI
- [ ] Implement functionality

Desings: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2396-514803&mode=design&t=TjDFfH5wuwKsAop1-4

**Comment by J-Son89** [comment] 2024-02-01 16:50
It seems that this is a duplicate of:
https://github.com/status-im/status-mobile/issues/16974
Maybe we can just combine the two together as the other issue seems to have more details (but perhaps too much in some ways)

**Comment by OmarBasem** [comment] 2024-02-02 04:11
@J-Son89 these are different issues. This issue is about disabling some network/route. The linked issue is about inputing specific amount for a network/route.

The linked issue is actually a duplicate of https://github.com/status-im/status-mobile/issues/18672

**Comment by briansztamfater** [comment] 2024-03-20 19:29
@OmarBasem I am assigning myself this one and probably start working on it tomorrow, let me know if you did any progress on this so we don't collision 🙏

**Comment by OmarBasem** [comment] 2024-03-21 10:18
@briansztamfater sure feel free to work on it. I haven't started on it

**Closed as completed** 2024-04-15 15:04 UTC
Labels: feature, wallet: Send
