### ISSUE TITLE
Composer - Mention search issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19313] opened 2024-03-18 12:27 UTC
# Design Feedback 2.27

## [Composer] Mention search issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=103%3A86534&mode=design&t=3F5nURAsrqk8P873-1)

- **Contact icon** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=103:86534&mode=design#727537479)] isn't showing next to the name
- **Missing avatars** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35448&mode=design#726031244)] from the list

<img width="500" alt="Screenshot 2024-03-18 alle 13 26 35" src="https://github.com/status-im/status-mobile/assets/122543089/341a7410-c84c-45b2-a54a-d1e97b12edb2">

### Reproduction

1. Open a chat / group chat / community
2. Type the **@** symbol

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment] 2024-03-18 15:48
> Missing avatars [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35448&mode=design#726031244)] from the list

Logged here: https://github.com/status-im/status-mobile/issues/17229

**Comment by codemaster115** [comment] 2024-04-05 14:42
@Francesca-G , @qoqobolo  
Could you please check this issue again? I was not able to reproduce on my end.

**Comment by Francesca-G** [comment] 2024-04-08 07:49
> @Francesca-G , @qoqobolo Could you please check this issue again? I was not able to reproduce on my end.

As you can see there are missing avatars and names from the list and I wasn't able to mention anyone of my contacts 
(I tap on them ➡️ pressed state appears but I'm not able to mention them in the input field)

https://github.com/status-im/status-mobile/assets/122543089/adfbe385-6ccd-4d45-abae-0aad38824b1a

**Comment by churik** [comment] 2024-05-03 11:25
can be closed in favour of https://github.com/status-im/status-mobile/issues/17229

**Closed as completed** 2024-05-03 11:25 UTC
