### ISSUE TITLE
Rinkeby: null is not an object (evaluating s.replace) if send faucet request 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2172] opened 2017-10-16 17:16 UTC
### Description

*Type*: Bug

*Summary*: both Rinkeby and Rinkeby with upstream RPC: is send faucet request then popup `null is not an object (evaluating s.replace)` is shown, expect to
1. get message Faucet request is sent
2. get 0.1 eth after 2-3 minutes 

### Reproduction
https://app.testfairy.com/projects/4803590-status/builds/6867806/sessions/11/?accessToken=ss6inuV1bZz2iTt0sEPMwC2shEk
- switch to Rinkeby or to Rinkeby with upstream RPC network
- Open Status
- Open Console
- tap on faucet command and send it

### Additional Information
* Status version: develop
* Operating System: 
Real device iPhone 7 plus, iOs 11.0.3
Real device Google Pixel XL, Android 8.0

**Comment by asemiankevich** [comment] 2017-10-17 07:32
The issue is fixed in `0.9.10-244-g6718caf8+`

**Closed as completed** 2017-10-17 07:46 UTC
