### ISSUE TITLE
Can't run app because target run-android fails

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#18848] opened 2024-02-15 17:20 UTC
# Problem

Since commit 42cab0855330e80b3469859841fa6052c4435edb was merged, the make target `run-android` always fails on my NixOS system.

What have I tried before reporting, in this order:

1. `make clean`
2. `make android-clean`
3. Hard reset
4. The usual steps, in order, `run-clojure` + `run-metro` + `run-android`.

These steps seem to exclude the chance of spurious state in the system. I'm currently blocked from developing against `develop`.

### Logs

```
$ make run-android
Configuring Nix shell for target 'android'...
warning: ignoring untrusted substituter 'https://nix-cache.status.im/', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
trace: getEnvWithDefault ORG_GRADLE_PROJECT_hermesEnabled (default: true): false
warning: ignoring untrusted substituter 'https://nix-cache.status.im/', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
trace: getEnvWithDefault ORG_GRADLE_PROJECT_hermesEnabled (default: true): false
No changes detected.
Done in: 0.570s
adb_devices_abis.sh DEBUG: device_name=emulator-5554
adb_devices_abis.sh DEBUG: device_status=device
adb_devices_abis.sh DEBUG: device_product_abi=x86
adb_devices_abis.sh DEBUG: resulting abis:
warning: ignoring untrusted substituter 'https://nix-cache.status.im/', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
trace: getEnvWithDefault BUILD_TYPE (default: release): debug
trace: getEnvWithDefault ANDROID_ABI_INCLUDE (default: armeabi-v7a;arm64-v8a;x86): x86
trace: getEnvWithDefault ORG_GRADLE_PROJECT_hermesEnabled (default: true): false
Running: nix-build --pure --fallback --no-out-link --show-trace --attr targets.mobile.android.build --option extra-sandbox-paths /tmp/tmp-status-mobile-local/tmp.oqOqOQsAyh --argstr secretsFile /tmp/tmp-status-mobile-local/tmp.oqOqOQsAyh --argstr buildEnv debug --option build-use-sandbox true
warning: ignoring untrusted substituter 'https://nix-cache.status.im/', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
trace: getEnvWithDefault BUILD_TYPE (default: release): debug
trace: getEnvWithDefault ANDROID_ABI_INCLUDE (default: armeabi-v7a;arm64-v8a;x86): x86
trace: getEnvWithDefault ORG_GRADLE_PROJECT_hermesEnabled (default: true): false
these 3 derivations will be built:
  /nix/store/4x3vqjrj87dx1dcxqhr3v0dbcg7byhf6-status-mobile-jsbundle.drv
  /nix/store/rqp3py15al8p6xzir797qv484ffnrs8m-status-go-0.174.6-f95dd35-android.drv
  /nix/store/3mar54vaa8vajjr4kpgygwf0pgv6zr8v-status-mobile-build-debug-android.drv
building '/nix/store/rqp3py15al8p6xzir797qv484ffnrs8m-status-go-0.174.6-f95dd35-android.drv'...
building '/nix/store/4x3vqjrj87dx1dcxqhr3v0dbcg7byhf6-status-mobile-jsbundle.drv'...
unpacking sources
unpacking source archive /nix/store/c9vl7q5spfi0kc5m3d4wn8x5i5ihpmc6-status-go-f95dd35-source
unpacking sources
unpacking source archive /nix/store/r6pvfdx3dadn434y0xy29yk54raznkyd-status-mobile-source-jsbundle
source root is status-mobile-source-jsbundle
secretsPhase
/nix/store/37p8gq9zijbw6pj3lpi1ckqiv18j2g62-stdenv-linux/setup: line 1594: /tmp/tmp-status-mobile-local/tmp.oqOqOQsAyh: No such file or directory
error: builder for '/nix/store/4x3vqjrj87dx1dcxqhr3v0dbcg7byhf6-status-mobile-jsbundle.drv' failed with exit code 1;
       last 5 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/r6pvfdx3dadn434y0xy29yk54raznkyd-status-mobile-source-jsbundle
       > source root is status-mobile-source-jsbundle
       > secretsPhase
       > /nix/store/37p8gq9zijbw6pj3lpi1ckqiv18j2g62-stdenv-linux/setup: line 1594: /tmp/tmp-status-mobile-local/tmp.oqOqOQsAyh: No such file or directory
       For full logs, run 'nix-store -l /nix/store/4x3vqjrj87dx1dcxqhr3v0dbcg7byhf6-status-mobile-jsbundle.drv'.
error (ignored): error: cannot unlink '/tmp/nix-build-status-go-0.174.6-f95dd35-android.drv-2/status-go-f95dd35-source/vendor/github.com': Directory not empty
error: 1 dependencies of derivation '/nix/store/3mar54vaa8vajjr4kpgygwf0pgv6zr8v-status-mobile-build-debug-android.drv' failed to build
removed '/tmp/tmp-status-mobile-local/tmp.oqOqOQsAyh'
make: *** [Makefile:282: run-android] Error 1

```

cc @siddarthkay

**Comment by siddarthkay** [comment] 2024-02-19 14:54
@ilmotta : I checked in with @jakubgs regarding this issue and he mentioned it could have something to do with your nix daemon configuration and something to do with extra path settings.

i upgraded my NixOS from 22-11 to 23-05 and couldn't reproduce this issue, neither could @jakubgs.

What should the next steps be here?

**Comment by ilmotta** [comment] 2024-02-19 15:14
> something to do with your nix daemon configuration and something to do with extra path settings.

Could you be more specific about what do you mean by "something to do with your nix daemon configuration and something to do with extra path settings"?

> What should the next steps be here?

I don't know either. It seems the only thing left for me is to try to fix it myself because nobody has the same problem. What I need to find is what has the commit done https://github.com/status-im/status-mobile/commit/42cab0855330e80b3469859841fa6052c4435edb that systematically makes `run-android` fail for me where it never happened before.

I'll investigate today. Thanks guys. If you have any tips, please share.

**Comment by siddarthkay** [comment] 2024-02-19 15:16
I'd recommend hold off investigating till https://github.com/status-im/status-mobile/pull/18900 gets merged.

The new build step is essentially very similar to running `make build-android`
Could you check if that command failed before https://github.com/status-im/status-mobile/commit/42cab0855330e80b3469859841fa6052c4435edb for you ?

**Comment by ilmotta** [comment] 2024-02-19 18:20
@siddarthkay, that explains everything!

I have secrets exported via env vars, like `INFURA_TOKEN`, this already made the target `release-android` fail for me a long time ago already. Now that the new build step is doing something similar, I'm getting the same error. @jakubgs pointed out to me back then that maybe `extra-sandbox-paths` doesn't work in my system.

Once I remove the env var, the problem is gone. I'll go with that for now. Thank you so much for investigating.

**Comment by siddarthkay** [comment] 2024-02-19 18:51
Amazing! Glad to know that helped.
Closing this issue for now then :)

**Closed as completed by siddarthkay** 2024-02-19 18:51 UTC
Labels: developer-xp

**Comment by ilmotta** [comment] 2024-02-19 19:13
@siddarthkay, I forgot to ask you if you could try to export, e.g. `INFURA_TOKEN` and check if the `build-android` fails as well. Once you have some time :)

**Comment by siddarthkay** [comment] 2024-02-19 19:20
ah i see 

https://github.com/status-im/status-mobile/blob/f394fcc3d5f1ae4b5924be81e30fa589cdb76de9/scripts/build-android.sh#L45-L54

probably why it could cause potential issues
