### ISSUE TITLE
Random redirect (to home or wallet screens) when scanning extension QR code

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#7995] opened 2019-04-18 08:31 UTC
# Problem

User is redirected to Home screen right after scanning extension qr code, which does not allow him to actually press the Install button

# Steps
1. open status
2. enable dev mode -> extensions
3. tap Scan button and scan any extension QR (for ex https://get.status.im/extension/ipfs@Qmb1B3jXNdc9WZCcWFzpkTXtrurnKxYQFvUDhp2J4SVCCX)

Please check the video attached
https://drive.google.com/open?id=1JCEWhsxgkHQMEeHc73G7VcHANaMEf8dp

# Note 

I can install extension via copy/paste the link and install (not scanning).

**Comment by Serhy** [comment] 2019-04-18 11:08
Looks like this is the same as https://github.com/status-im/status-react/issues/7948
Let's keep both issues open, - I think fix of https://github.com/status-im/status-react/issues/7948 likely will resolve Scan QR code when adding extensions

**Comment by asemiankevich** [comment] 2019-04-18 11:34
> Looks like this is the same as #7948
> Let's keep both issues open, - I think fix of #7948 likely will resolve Scan QR code when adding extensions

oh sorry @Serhy i did not notice this one, my bad!

**Comment by rachelhamlin** [comment] 2019-04-25 14:42
So is this issue conditional upon user scanning an extension first, or is it 3 separate things that are all  blocked? 

1. Can't scan valid extension QR
2. Can't scan valid boot node QR
3. Can't scan valid mail server QR?

The latter two are more important than the first. @jeluard how hard is it to come up with a fix for this, do we know why it's happening?

**Comment by jeluard** [comment] 2019-04-25 14:58
@rachelhamlin I have to look into this, the other similar issue I fixed is not related. It looks like a bad regression indeed.

Can someone clarify if this is only for extensions, as detailed in the description?

**Comment by Serhy** [comment] 2019-04-25 16:40
@jeluard @rachelhamlin sorry for the confusion here

There is the same bug when scanning QR code from any of:
`Profile` -> `Extentions` -> tap `Scan QR code` -> scan valid QR code
`Profile` -> `Bootnodes` ->`+` ->  tap `Scan QR code` -> scan valid QR code
`Profile` -> `Mailserver` ->`+` ->  tap `Scan QR code` -> scan valid QR code

And once QR code value read, - there is a redirect to an unexpected screen happens. 

Let me create separate issue for bootnode + mailserver parts as they have higher priority than when scanning QR code part from Extentions view (according to https://github.com/status-im/status-react/issues/7995#issuecomment-486702002)

**Comment by Serhy** [comment] 2019-04-25 17:17
Created https://github.com/status-im/status-react/issues/8044 as a separate issue for Bootnodes and Mailserver parts

**Comment by Serhy** [comment] 2019-04-26 12:42
https://github.com/status-im/status-react/pull/8048 fixed issue of QR code scan when adding Extension.
Closing this one.

**Closed as completed by Serhy** 2019-04-26 12:42 UTC
