### ISSUE TITLE
No push notifications are coming from contact if it was not added through activity centre and changed profile after adding you as contact

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12776] opened 2021-11-01 16:07 UTC
# Bug Report

## Problem 
User A with enabled notifications won't see them from the User B if User B changed profile photo after adding User A as contact (if User A added User B from public chat or via + button, not from activity centre)
Issue is reproducible on 1.17.

#### Expected behavior
Can see PN from User B

#### Actual behavior
no PN from User B

### Reproduction

1) User A: create multiaccount
2) User B: create multiaccount with enabled push notifications
3) User A: add User B to contacts
4) User A: set image
5) User B: add User A as contact ( via  + > New chat or public chat for instance), put app to background
6) User A: send message to 1-1 with User B

### Additional Information

- Status version: nightly 01/11/21
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by rasom** [comment] 2021-11-02 12:03
@qoqobolo I believe it is not related to profile photo at all, it is just if you have a contact but haven't started a 1-1 chat with them then PN will not appear. It works fine after relogin for instance

**Comment by qoqobolo** [comment] 2021-11-02 14:06
@rasom can you try these exact steps, please? I can constantly reproduce the issue only with them and only in this order. 

1. User A: create multiaccount
2. User B: create multiaccount with enabled push notifications
3. User A: Profile > Contacts > Add User B to contacts via QR-code
4. User A: Set image
5. User B: Home screen > + > Start new chat > scan QR-code of User B > Tap Add to contacts in the 1-1 chat view > put the app to background
6. User A: send message to 1-1 with User B

It doesn't seem to matter if the photo was added before or after User A was added to contacts, however, I can't reproduce the issue without a photo at all.

**Comment by rasom** [comment] 2021-11-03 07:55
```
t=2021-11-03T07:54:37+0000 lvl=info msg="Pushing a new push notification" notification="&{ID:0x4e9600abb6ebae382bd22ce70cc4ce799c7f5b4fa4759edd4dc039950bdc4263 Platform:0 Body:{Message:clock:1635926077104 timestamp:1635926077104 text:\"Kik\" chat_id:\"0x04a63c53ff8553a62777aabdb5be6df78c7dbcc11f927e89fe55cb38bd43e6452de3d845d4bd3127401aa47ab7addbfafeb72347aab670c5513a25d010f28e690e\" message_type:ONE_TO_ONE content_type:TEXT_PLAIN  Contact:0x40022eb080 Chat:0x400180c6e0 Community:<nil>} BodyType:message Title:Opulent Critical Arrowana Message:Kik Category:newMessage Deeplink:status-im://p/0x04c203bdedd18884fe80385fccf16e9f612e4b64a7fa98c7db94882ed27d1842db459566e323a5cbe6386c5fe6c78131a32faa49d8378c370cdb53a07cfe8a6626 Image: IsScheduled:false ScheduledTime: IsConversation:true IsGroupConversation:true ConversationID:0x04c203bdedd18884fe80385fccf16e9f612e4b64a7fa98c7db94882ed27d1842db459566e323a5cbe6386c5fe6c78131a32faa49d8378c370cdb53a07cfe8a6626 Timestamp:1635926077000 Author:{ID:0x04c203bdedd18884fe80385fccf16e9f612e4b64a7fa98c7db94882ed27d1842db459566e323a5cbe6386c5fe6c78131a32faa49d8378c370cdb53a07cfe8a6626 Icon: Name:Opulent Critical Arrowana} Deleted:false}"
```

**Comment by qoqobolo** [comment] 2021-11-23 15:48
Double-checked and found out that the problem now is in the test itself.
So close it again as it is not relevant.

**Closed as completed by qoqobolo** 2021-11-23 15:48 UTC
Labels: push-notifications
