### ISSUE TITLE
Can't remove Custom token (SNTMiniToken) on Ropsten

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8664] opened 2019-07-29 12:20 UTC
# Problem

Can't remove custom token from Assets list if added this token `0x25B1bD06fBfC2CbDbFc174e10f1B78b1c91cc77B`

## Steps

1. open status
2. switch to ropsten
3. go to wallet -> manage assets
4. add custom token with this address for ex 
 `0x25B1bD06fBfC2CbDbFc174e10f1B78b1c91cc77B`
5. long tap the token once added -> remove token
6. long tap the token -> view details -> remove token

NOTE: i can add / remove `0x1a7a8bd9106f2b8d977e08582dc7d24c723ab0db` on mainnet

@andytudhope @flexsurfer

**Comment by PfanP** [comment] 2019-07-30 00:53
Can I fix this issue?

**Comment by asemiankevich** [comment] 2019-07-30 06:02
@alex-coding-c sure, go ahead!

**Comment by PfanP** [comment] 2019-07-30 08:30
Would you assign it to me?

**Comment by PfanP** [comment] 2019-07-30 08:36
What's the best way to chat with you @asemiankevich? I am very new to this project so I might need some help while deploying it on my local.

**Comment by asemiankevich** [comment] 2019-07-30 08:38
the best way to chat with someone - join Status channel - someone will assist. Also, checkout https://status.im/docs/contributor_guide.html   @alex-coding-c

**Comment by PfanP** [comment] 2019-07-30 08:43
How can I join Status channel? Is it on the gitter?

**Comment by asemiankevich** [comment] 2019-07-30 08:44
it is a channel in Status app

**Comment by PfanP** [comment] 2019-07-30 08:44
Ah I see

**Comment by churik** [comment] 2020-02-26 16:45
Issue is still reproducible.
On Ropsten with 0x25B1bD06fBfC2CbDbFc174e10f1B78b1c91cc77B (SNTMiniToken).
Tried other tokens on mainnet - couldn't reproduce.

**Comment by iurimatias** [comment] 2020-04-20 19:05
@churik I can't reproduce this issue, it seems fixed.

**Comment by churik** [comment] 2020-04-21 08:15
Yes, I'm surprized, because rechecked it  on 26 Feb https://github.com/status-im/status-react/issues/8664#issuecomment-591525514
Thank you for taking a look!

**Closed as completed by churik** 2020-04-21 08:15 UTC
