### ISSUE TITLE
Wallet QRCode Scanner says invalid address for valid address scanned

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10107] opened 2020-02-28 15:42 UTC
# Bug Report

## Problem

Not all sites use EIP-681 for expressing payment requests, or the QRCode is used only to share ethereum address. For example in Etherscan and many crypto payment systems.

![image](https://user-images.githubusercontent.com/224810/75562461-656ba800-5a27-11ea-8fe3-d00a91b61a90.png)

How to reproduce:

1. Go to Wallet
2. Open the desired wallet
3. Tap Send
4. Enter some value
5. Scan the QRCode of address, as example above. 

![image](https://user-images.githubusercontent.com/224810/75562635-a9f74380-5a27-11ea-9b70-7f86768df1e8.png)

#### Expected behavior

When only an address is entered, it should be filled in the address, otherwise it must be following ERC-681

#### Actual behavior

Status don't know what to do with scanned address.

**Comment by churik** [comment] 2020-02-28 18:36
duplicate of https://github.com/status-im/status-react/issues/9748
This issue has more descriptive title and description, so will leave this one and close https://github.com/status-im/status-react/issues/9748

Thanks!

**Comment by jakubgs** [comment] 2020-04-01 17:05
The QR code contents should be a whole https://join.status.im/ URL to make it work in any QR code scanning app.

**Closed as completed** 2020-04-14 09:53 UTC
