### ISSUE TITLE
Implement "Share future addresses" functionality

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#18977] opened 2024-02-23 18:59 UTC
As a user
I want to be able to select share future addresses
So that if I generate a new account, that's automatically shared with a community

### Description

When generating a new wallet account, if `Share future addresses` is selected for any community, we should notify the community of the new address.
This change should also be reflected on paired devices.

This is mostly a backend focused task, since the frontend has already been implemented.

**Comment by ibrkhalil** [comment] 2024-03-31 09:17
Awaiting on: https://github.com/status-im/status-mobile/issues/18976

**Comment by Parveshdhull** [comment] 2024-04-14 12:51
duplicate of https://github.com/status-im/status-mobile/issues/18012? @cammellos @ilmotta

**Comment by cammellos** [comment] 2024-04-14 13:57
@Parveshdhull the other one is tracking the frontend, this is the backend task

**Comment by ilmotta** [comment] 2024-05-09 22:13
@cammellos is this feature ~deprecated~ descoped given new wallet priorities? If so, we can add a feature flag on the client to keep the code if we intend to get back to this in the near future. Or is it still a priority for 2.29? I remember you saying the backend part could be a can of worms, but to know that for sure we need to dig a little bit on status-go.

**Comment by ilmotta** [comment] 2024-09-11 14:13
Closing because this feature was implemented in:

- https://github.com/status-im/status-go/pull/5354
- https://github.com/status-im/status-mobile/pull/20549

**Closed as completed by ilmotta** 2024-09-11 14:13 UTC
Labels: feature, community-permissions
