### ISSUE TITLE
Empty Gas limit and Gas price if you send transaction from DApp

### ISSUE THREAD

**Issue by churik** [status-im/status-react#3022] opened 2018-01-12 16:50 UTC
### User Story

As a user, I want to see Gas limit and Gas price for transaction from DApp (Auction house in my case)

### Description
*Type*: Bug
*Summary*: on "Send transaction"  screen details no info about Gas limit and Gas price which will be used for transaction from DApp, but after a while you can see that Transaction is send and gas was used.

#### Expected behavior
Can see actual Gas price/Gas limit

#### Actual behavior
empty Gas price/Gas limit
<img width="323" alt="empty" src="https://user-images.githubusercontent.com/4557972/34885498-d97784d0-f7c8-11e7-95d6-c580e6f514e5.png">

### Reproduction

- Open Status
- Request some ETH in Console via /faucet
- Go to Contacts -> dApps
- Tap on Acution House dApp
- Tap on Create an auction
- Enter unique name to 'Register Name' input
- Click on 'Register Name'
- Tap on advanced

### Additional Information
* Status version: 0.9.11d557 (2114)  - nightly 12\01
* Operating System: Android, iOS
 
Issue for investigation.
Probably can be related to #2653

**Comment by chadyj** [comment] 2018-02-20 23:29
Fixed in https://github.com/status-im/status-react/pull/3000

**Comment by annadanchenko** [comment] 2018-02-28 17:27
@chadyj issue exists on nightly build from Feb 28. It looks like it was never fixed (according to the request from @goranjovic to create separate issue for this Dapp case in https://github.com/status-im/status-react/pull/3000#issuecomment-357270600 ) Re-opening issue as it happens for the same steps to reproduce

**Closed as completed** 2018-04-02 11:07 UTC
Labels: Tested - Issues
