### ISSUE TITLE
`Jump to` overlaps the last message in chat view in case of scrolling back and forth

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16331] opened 2023-06-20 13:13 UTC
# Bug Report
Follow-up on design call from 19/06/23.

## Problem 
`Jump to button` should not overlap the last message in chat

<img width="464" alt="photo_2023-06-20 14 08 40 jpeg 2023-06-20 14-09-25" src="https://github.com/status-im/status-mobile/assets/4557972/96e68e66-e91d-4c19-84f6-7b7f9b870d72">

Designs:
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=3101-347945&t=Yspiy1M9ZTNBqu6s-4

### Reproduction

1) Open Status
2) Send message 

### Additional Information

- Status version: nightly 20/06/23
- Operating System: Android, iOS

**Comment by smohamedjavid** [comment] 2023-06-22 14:41
Related to https://github.com/status-im/status-mobile/issues/16153

**Comment by briansztamfater** [comment] 2023-06-23 14:10
Maybe mark it as blocked? wdyt @churik @smohamedjavid ?

**Comment by smohamedjavid** [comment] 2023-06-23 17:06
Partially yes, but I believe @alwx would be the best person to comment. 

There is an open PR from @alwx to adjust the bottom space (https://github.com/status-im/status-mobile/pull/16235). This may solve the issue.

**Comment by alwx** [comment] 2023-06-23 18:32
https://github.com/status-im/status-mobile/pull/16235 might indeed solve the issue

**Comment by vkjr** [comment] 2023-06-27 12:12
@alwx, would you mind assigning this issue to yourself if you think #16235 will solve it?

**Comment by alwx** [comment] 2023-07-06 08:20
@churik I think this one is fixed after we merged #16235. Could you check/verify?

**Comment by churik** [comment] 2023-07-06 12:30
Now it works better, but has this leftover: 

https://github.com/status-im/status-mobile/assets/4557972/61819ef2-9bb4-4278-96bc-7f22b838f6e3

So if you are srolling to the top and use "scroll to bottom", the jump to still overlaps the last message.

But this is not that visible anymore, so I'm moving the issue to the next milestone

**Comment by alwx** [comment] 2023-07-11 09:17
That appeared to be trickier than I was expecting — React Native simply doesn't seem to provide a way to jump to the very very bottom — it can only jump to the last message, and that's it. I'm checking possible ways of dealing with it but setting an offset doesn't work either :(

**Comment by alwx** [comment] 2023-07-28 10:37
Ok, I spent quite some time and have to say that it cannot be achieved without a huge effort from our side — the thing is React Native cannot really calculate where to scroll (I tried it with all the possible functions like `scrollToIndex`, `scrollToOffset`, `scrollTo`, whatever) and always leaves some space in the end.

However, I think the original issue is already fixed and that small issue with the "scroll to the end" button can be moved to a separate issue, probably not that important as the original issue was.
cc @churik

**Comment by churik** [comment] 2023-07-31 08:01
@alwx can you elaborate on the original issue that was fixed (which one and where?)
Thank you!

**Comment by alwx** [comment] 2023-07-31 14:00
@churik in this one: https://github.com/status-im/status-mobile/pull/16235

By the original issue I mean scrolling back and forth (= basically any scenario except using the "scroll to the bottom" button).
If you want me to explain further: the issue is that we cannot really jump to the very bottom, the rest should be covered and should work well.

**Comment by Parveshdhull** [comment] 2023-08-10 21:01
fixed in https://github.com/status-im/status-mobile/pull/16981
cc: @alwx

**Comment by Parveshdhull** [comment] 2023-08-25 16:01
will be fixed in https://github.com/status-im/status-mobile/pull/17113

**Closed as completed** 2023-08-30 09:05 UTC
