### ISSUE TITLE
[iOS] App crashes while using Status app when user recovered his account from a seed phrase 

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18622] opened 2024-01-25 10:26 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)
Floating bug. 
We tried to reproduce it by every mobile QA member.
Only 2 of 4 QA's faced with this issue.
Please, use our steps to catch this tricky little monster.

#### Expected behaviour
No crashes while using Status app when user recovered his account from a seed phrase 

#### Actual behavior
Random crashes : 
- right after Onboarding
- after user start to explore Status app

### Reproduction

1. Install app
2. Sign up a new user using a seed phrase
3. Go through onboarding (in this place I had a stuck on "Key saved" step once, shaked logs attached(unfortunately, we can only get such shake logs as we use a logcat only for Android)
[status_logs.zip](https://github.com/status-im/status-mobile/files/14050233/status_logs.zip)
5. Communities screen opens (I also had a crush on this step)
6. Make some actions like: chatting, friend request (Diana catched crush on these steps 1-2 times randomly)
*please, let us know if you'll need some additional info or our seed phrase

### Additional Information

- Status version: PR builds ([first ](https://github.com/status-im/status-mobile/pull/18523) and [second](https://github.com/status-im/status-mobile/pull/18449))
- Operating System: iOS
- Devices: iPhone SE, ios 17.2.1; iPhone 13, ios 17.2.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment] 2024-01-26 16:29
Update on iPhone SE:
now it crashes each time when I create even a new profile (without recovering it from seed phrase). 
Animation of the transition between screens starts to be laggy and eventually the app crashes (sometimes earlier, sometimes later, but always after confirming the password). 


https://github.com/status-im/status-mobile/assets/67952253/38693ce4-d1dd-4ca5-bfe8-7475467793f0

**Comment by mohsen-ghafouri** [comment] 2024-02-23 20:47
I tried multiple times with seed phrases and couldn't reproduce the issue.

**Comment by qoqobolo** [comment] 2024-03-14 08:43
My iPhone SE keeps crashing randomly, but it's probably something different. Closing this one for now, will reopen if face it again

**Closed as completed by qoqobolo** 2024-03-14 08:43 UTC
Labels: ios
