### ISSUE TITLE
Elements overlap each other on Android (profile selection page; chat view)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16693] opened 2023-07-14 15:29 UTC
# Bug Report

## Problem 

<img width="368" alt="Screenshot 2023-07-14 at 17 16 25" src="https://github.com/status-im/status-mobile/assets/67952253/e5f894ec-a78d-492e-889e-5e09c42c80ec">

<img width="538" alt="Screenshot 2023-07-14 at 17 16 10" src="https://github.com/status-im/status-mobile/assets/67952253/b0003b7d-928e-4c04-846c-6438112260a9">

### Reproduction

We were able to reproduce these scenarios:

### 1. 

1. Create several accounts
2. Add at least one community to each of them
3. Log out
4. Open the profile selection page

At some point the cards start overlaying each other 

### 2. 

1. Create a profile, create a community
2. Log out
5. Create another profile, join a community

### 3.

**Preconditions:** at least 1 profile is already created

1. Create one more fresh profile - User A
2. UserA: send CR to UserB
3. UserB: accept CR 
4. UserA: log out right after User B accepts CR
5. Open the profile selection screen by User A

### Additional Information

- Status version: RC
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment] 2023-07-14 15:52
Hi @qoqobolo, Are you able to reproduce this issue on multiple Android devices?

**Comment by qoqobolo** [comment] 2023-07-14 16:56
> Hi @qoqobolo, Are you able to reproduce this issue on multiple Android devices?

Yes, we reproduced this on at least Pixel, Huawei and Samsung

**Comment by Parveshdhull** [comment] 2023-07-14 17:22
> > Hi @qoqobolo, Are you able to reproduce this issue on multiple Android devices?
> 
> Yes, we reproduced this on at least Pixel, Huawei and Samsung

Thank you for confirming

**Comment by Parveshdhull** [comment] 2023-07-17 06:21
```
(defn view
  []
  (let [show-profiles?    (reagent/atom false)
        set-show-profiles #(reset! show-profiles? true)
        set-hide-profiles #(reset! show-profiles? false)]
    (fn []
      [:<>
       [background/view true]
       (if @show-profiles?
         [profiles-section {:set-hide-profiles set-hide-profiles}]
         [login-section {:set-show-profiles set-show-profiles}])])))
```
Profile screen is controlled by a regent atom and only one view should be visible at a time. Don't know why both are visible. Maybe you have some idea @flexsurfer

Both profiles and chat screens force updates view at runtime, and removes old view and renders new one
First using reframe subscription and second using reagent atom. But for some reason old view is not getting removed and both views getting rendered simultaneously 🤔

**Comment by Parveshdhull** [comment] 2023-07-17 06:21
@qoqobolo, I tried creating several accounts with communities and navigating to profiles, but I am not able to reproduce the issue.
Please can you confirm the frequency of occurrence, if it is quite rare and non-blocker, Please can we move this to the next release?

**Comment by Parveshdhull** [comment] 2023-07-17 06:25
> Don't know why they are visible both

In https://github.com/status-im/status-mobile/pull/16433 we implemented layout animation, so if a toast is shown it enables them. Just a guess, but that might be breaking layout while animating it.

Because once enabled, it starts to affect other places too: https://github.com/status-im/status-mobile/issues/14752

**Comment by Parveshdhull** [comment] 2023-07-17 08:03
Should I create a pr for disabling layout animations for QA, to check if it fixes the issue?

**Comment by qoqobolo** [comment] 2023-07-17 08:43
> @qoqobolo, I tried creating several accounts with communities and navigating to profiles, but I am not able to reproduce the issue.
Please can you confirm the frequency of occurrence, if it is quite rare and non-blocker, Please can we move this to the next release?

Thank you very much for investigating the issue!
It's quite severe and also occurs in other places (screens) of the app, but it's really not that easy to reproduce, and since we don't have a simple and quick solution, let's move it to 1.25 👍

> Should I create a pr for disabling layout animations for QA, to check if it fixes the issue?

Yes, please do this so we can test the hypothesis after testing the release.

**Comment by Parveshdhull** [comment] 2023-07-17 08:45
> Yes, please do this so we can test the hypothesis after testing the release.

Sounds good, thank you very much

**Comment by Parveshdhull** [comment] 2023-07-20 10:32
Hi @qoqobolo, I created a pr with disabled layout animations. Whenever you have some spare time, please give it a try and let me know if the issue is still reproducible for you. Thank you very much for looking into this issue.

https://github.com/status-im/status-mobile/pull/16729

**Comment by qoqobolo** [comment] 2023-07-21 09:25
thank you @Parveshdhull, we will check!
Added the `request-manual-qa` label just for better visibility.

**Comment by qoqobolo** [comment] 2023-08-31 08:40
Reopening the issue since it's reproducible again. 
Device: Pixel 7a

Steps:
1. Create a profile
2. Log out from the profile screen
3. Quickly tap the `Profiles` button (at the top right)

Sometimes you need to repeat this a couple of times.

https://github.com/status-im/status-mobile/assets/67952253/e33f3e31-6e94-40e7-a79d-faad64bb33fe

**Comment by qoqobolo** [comment] 2023-09-01 09:41
Unable to reproduce it again.

**Comment by pavloburykh** [comment] 2023-09-21 10:20
@Parveshdhull unfortunately still reproducible, so reopening the issue. Steps are yet unknown. 

Reproduced on Android 12, Samsung Galaxy A52
Build nightly (21 Sep, 2023)

[Status-debug-logs (63).zip](https://github.com/status-im/status-mobile/files/12683382/Status-debug-logs.63.zip)

![photo_2023-09-21 13 19 40](https://github.com/status-im/status-mobile/assets/97245802/9cd7bab8-b5b1-4c64-9aee-50eee15c8731)

https://github.com/status-im/status-mobile/assets/97245802/2df45a61-8f9c-4808-9477-90db4017fc5d

**Comment by Parveshdhull** [comment] 2023-09-21 13:04
It looks like issue is most probably with reanimated library version and will be fixed in reanimated v3. More info https://github.com/status-im/status-mobile/pull/16832

**Comment by churik** [comment] 2023-10-19 15:20
closing this for now, reopen if reproducible

**Closed as completed by churik** 2023-10-19 15:20 UTC
Labels: android
