### ISSUE TITLE
Invalid Error message on offline transaction 

### ISSUE THREAD

**Issue by juliomvr** [status-im/status-react#5095] opened 2018-07-08 21:05 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user I want to see the correct error message, not an error message that may confuse me or don't understand.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 
after login connected to wifi, lost wifi connection and try to send some funds from wallet or 1:1 chat the app "allows" me to send the funds but incorrect error message is displayed.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If intenet connection is lost after login and user try to make a transaction the app should:
1)Display correct error message, for example: "No internet connection found" or "Network error, try later" something that tells the user that he is not connected to the internet.
OR
2) just verify the internet connection when the user click "Send transaction" and display a message saying "Check internet connection" or something like that

#### Actual behavior
[comment]: # (Describe what actually happened.)
If intenet connection is lost after login and user try to make a transaction the app is displaying message:
"Post https://ropsten.infura.io/z6GCTmjdP3FETEJmMBI4: dial tcp: lookup ropsten.infura.io: No address associated with hostname" 
This error message is incorrect, there is an address associated to the hostname but the app just can't find it because it doesn't have internet connection.
![image](https://user-images.githubusercontent.com/25910226/42423915-9c546300-82d0-11e8-9a07-63e1aa25e950.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- after login, disable Wifi
- Go to wallet
- Click on Send transaction
- Select recipient, Select Asset and specify Amount
- Sign transaction

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [1] Correct error message should be displayed, something related to network issue or internet connection
or
- [2] A validation checking internet connection should be done when the user try to send a transaction

### Additional Information

* Status version: 0.9.21
* Operating System: Android 7.0
*Device: Samsung Galaxy J3

<blockquote></blockquote>

**Comment by lukaszfryc** [comment] 2018-08-27 11:25
@obi2020 can you suggest a more humand readable copy here? :)

**Comment by obi2020** [comment] 2018-08-27 19:19
@lukaszfryc  Is this the only reason this error is shown? If so, I would suggest

> **Connection failed**

> Looks like you're not online. Please check your connection and try again.

> [OK]

If it might be used in other cases, we may need to write it to be more generic.

**Comment by lukaszfryc** [comment] 2018-08-28 11:31
I think it may also happen when the host (infura.io) is offline

**Comment by goranjovic** [comment] 2018-11-16 11:22
Duplicate of #4966

**Closed as completed by goranjovic** 2018-11-16 11:22 UTC
Labels: feature
