### ISSUE TITLE
Cannot Click last chat in a list on mobile

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#7870] opened 2019-04-01 07:17 UTC
### Description

Due to the new chat icon, the last chat in a list on mobile can not be clicked if there is a list longer than screen length.

#### Expected behavior
When clicking on the chat I expect it to open.

#### Actual behavior
Nothing happens.

### Reproduction
Ensure you have more chats active than can fit on a screen, scroll to the bottom and try to open the last chat.

### Additional Information
* Status version: 0.11.0
* Operating System: iOS
![image](https://user-images.githubusercontent.com/7621705/55309738-f6748080-545e-11e9-9ef3-7fe0a68b1306.png)

**Comment by annadanchenko** [comment] 2019-04-01 08:47
duplicate of #7859

**Closed as completed by annadanchenko** 2019-04-01 08:47 UTC
