### ISSUE TITLE
No Android SDK tarballs are available for system architecture: aarch64-darwin

### ISSUE THREAD

**Issue by weizihua** [status-im/status-react#15352] opened 2023-03-15 09:53 UTC
# Bug Report

make run-android
npx react-native run-android --appIdSuffix debug
Configuring Nix shell for target 'android'...
error: No Android SDK tarballs are available for system architecture: aarch64-darwin

## Problem 
[comment]: # (A problem description)
Compiling on macos M1, an error occurs

**Comment by Parveshdhull** [comment] 2023-03-15 13:05
duplicate of https://github.com/status-im/status-mobile/issues/12794

**Closed as completed** 2023-03-15 13:05 UTC

**Comment by Parveshdhull** [comment] 2023-03-15 13:08
> The current solution is to simply not use an `arm64` shell to run builds, but instead use the [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)) dynamic binary translator through the `arch -x86_64` command or [`Terminal x86` application](https://www.notion.so/Run-x86-Apps-including-homebrew-in-the-Terminal-on-Apple-Silicon-8350b43d97de4ce690f283277e958602).

https://github.com/status-im/status-mobile/issues/12794#issue-1045695658
