### ISSUE TITLE
Create password screen - cannot see tips while typing a password on iOS

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#15501] opened 2023-03-27 20:19 UTC
# Bug Report

## Problem 

If the `Type password` field is focused, the tips (`Lower case`, `Upper-case`, `Numbers`, `Symbols`) are hidden behind the keyboard on iOS devices, so `Return`  must be pressed to see again the tips.

https://user-images.githubusercontent.com/67952253/227577278-74912850-422f-4658-955c-5a8b74112509.MP4

#### Expected behavior
the `Tips` component stays above the keyboard when it is open, according to [designs](https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2241-251868&t=LVrK5l6OdrYZKIix-4)

#### Actual behavior

Tips are hidden behind the keyboard on iOS devices

### Reproduction

1. Open Status as a completely new user
2. Navigate to I'm new to Status -> Generate Keys -> Set a username & color -> Create password screen
3. Focus the password field 

### Additional Information

- Operating System: iOS

## Additional notes

Probably this problem can be solved by using the `keyboardAvoidingView` component, but must be considered that this UI is using a `ScrollView` in order to look good in devices with a small screen.

**Comment by churik** [comment] 2023-06-01 13:59
duplicate of https://github.com/status-im/status-mobile/issues/15508

**Closed as completed by churik** 2023-06-01 13:59 UTC
