### ISSUE TITLE
User enters seed - add warning if word not in dictionary

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#8968] opened 2019-09-11 10:47 UTC
# Situation

When a user imports a multiaccount by typing in his 12 words seed phrase:
- We *do* check the words against our dictionary. 
- Even if they don't match our dictionary, we currently allow the user to proceed without warning.
- If there is a mispelling or use of unsupported language, the user will end up with a new, empty account
- If the seed phrase IS valid, intentionally does not match our dictionary, and comes from another wallet, the user will see the funds from that account inside Status.

# Improvement

Upon detection of a word that is not in our dictionnary, we will show a warning pop-up.

This pop-up will thus show if there is a mispelling, or the user types a seed phrase in a language we don't support

# Definition of the popup 
WARNING : exact copy is not ok on figma or image below. Copy should be : 
"This looks like a custom seed phrase and doesn't match the Status dictionary. This could also mean some words are misspelled. If so, you'll end up creating a new account.
Continue
Cancel"

https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702

![Onboarding_–_Figma](https://user-images.githubusercontent.com/11461437/64691090-2dc96d80-d492-11e9-872e-6fe800714287.jpg)

cc @rachelhamlin @andmironov @hesterbruikman

**Comment by rachelhamlin** [comment] 2019-09-11 11:44
Copy suggestion, now reflected in Figma:

`This looks like a custom seed phrase and doesn't match the Status dictionary. This could also mean some words are misspelled. If so, you'll end up creating a new account.`

**Comment by 3esmit** [comment] 2019-09-12 20:33
Duplicate of #8810

By default, words outside the dictionary **should not be allowed** because it will diverge from standard, making it only recoverable in Status, not in MetaMask or any other following the standard. 

Also, it's a security weakness to allow users to enter a low entropy seed, read more about this here https://github.com/MyCryptoHQ/support.mycrypto.com/blob/a5b2bcd34088d93a6ac4bfdaefcab40b42159485/src/content/private-keys-passwords/parity-phrases-are-no-longer-supported.md#but-whyyyyy

**Comment by rachelhamlin** [comment] 2019-09-13 08:31
But what of this use case @3esmit?

> If the seed phrase IS valid, intentionally does not match our dictionary, and comes from another wallet, the user will see the funds from that account inside Status.

Can't the user import a valid seed phrase from another wallet?

**Comment by 3esmit** [comment] 2019-09-13 11:19
> Can't the user import a valid seed phrase from another wallet?

Yes, this should happen. 

>If the seed phrase IS valid, intentionally does not match our dictionary, and comes from another wallet, the user will see the funds from that account inside Status.

I don't see how does a word would "intentionally does not match our dictionary, and comes from another wallet", if that's the case is the other wallet which would not be following the mnemonic standard. 

Personally I am not against allowing custom words in the dictionary, but the standard is: it would diverge from standard and they would only work in Status (or other wallets supporting this custom dictionary mnemonic). 
The main problem would be if this feature would allow a low entropy seed phrases to be used.

**Comment by rachelhamlin** [comment] 2019-09-13 14:02
So I'll admit, I have no idea how derivation paths or seed phrases work. 

But it sounds like Status dictionary = common. And if a word doesn't match our dictionary, it can't also be a correct mnemonic coming from MEW or Trust or another wallet either?

In which case, this should really only be an error about misspelling/incorrect seed phrase. And should be prevented.

**Comment by guylouis** [comment] 2019-09-13 15:10
so it seems the question we have to answer is : do we keep on accepting a seed which includes word which are outside of BIP39 'official' lists here : https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md
right ? 

Two options
1/ today we accept such a seed (going against BIP39 then), and just warn the user about this. Risk is letting the user setting up low entropy seed phrases.
2/ we don't accept anymore such seed (I checked and Trust and Metamask don't accept it) and just need to warn the user when his seed phrase is wrong

I don't know if there was a particular reason why we let the user use any word in his list of 12 words. @dmitryn do you know ? 

cc @gravityblast

**Comment by 3esmit** [comment] 2019-09-13 22:01
> But it sounds like Status dictionary = common. And if a word doesn't match our dictionary, it can't also be a correct mnemonic coming from MEW or Trust or another wallet either?

If Status, MEW and Trust are following the mnemonic specification correctly, no. If a word doesn't match BIP39 dictionary, it is not a valid BIP39 (or whatever is supported) seed phrase; it can be a valid mnemonic of other specification, which isn't supported.

If Status want to support multiple specifications, would be a positive aggregation, but for me seems like everyone is already using BIP39.

Opening words outside dictionary of BIP39, i.e. allowing invalid BIP39 seed phrases, does not seem to bring benefit to users, and will probably cause interoperability issues, recovery mistakes and low entropy seeds (with potential loss of funds).

Instead of this, I suggest:
- auto-completion (@yenda suggestion);
- error "red underline" in unrecognized words, which would suggest similar words when tapped (just like any spell checker tool); 
- plan to allow plugins/extensions to enable different types of keystore/mnemonic specifications.

**Closed as completed** 2019-09-25 07:39 UTC

**Comment by gravityblast** [comment] 2019-09-25 08:17
@guylouis @rachelhamlin @3esmit 
there's another thing, checking only the words is not enough. we should check the checksum of the mnemonic phrase to check if it's really a valid phrase generated with the right algorithm. 
For example the following mnemonics contain valid words, but only the first one is valid:


1: `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about`

2: `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon`

the other wallets check this, and don't allow importing the second one.

**Comment by guylouis** [comment] 2019-09-25 10:04
@yenda 
given @gravityblast are you ok we open this again ?

**Comment by 3esmit** [comment] 2019-09-26 02:44
I guess is a different issue now.

**Comment by yenda** [comment] 2019-09-26 04:06
Ok I agree with Ricardo we should not allow it
