### ISSUE TITLE
Registering a ENS username crashes the app

### ISSUE THREAD

**Issue by Engareh** [status-im/status-react#14117] opened 2022-10-06 21:36 UTC
# Problem

In status app I have two wallet one of them is empty and another one have 10 snt and 0.014 eth when I was going to register my ENS username in the last phase after signing the transaction suddenly it exist from the app and app closed
I repeated this over and over and each time the same result.

## Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

## Acceptance Criteria

Rules for the future PR to be accepted.

## Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

## Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by flexsurfer** [comment] 2022-10-07 07:08
cc @churik

**Comment by flexsurfer** [comment] 2022-10-07 07:10
@Engareh thank you for the report, could you please share the app version you are using, and your device info (os), thank you

**Comment by JMBpm21** [comment] 2022-10-07 07:26
KASIKORNBANK KASITHBK Thailand Number 1021933445

**Comment by JMBpm21** [comment] 2022-10-07 07:44
KASIKORNBANK KASITHBK Thailand Number 1021933445

**Comment by churik** [comment] 2022-10-07 08:29
@Engareh 
Failed to reproduce it on 1.20.2 and current `develop`(on both test networks and mainnet)
As far as I see from the email you're on 1.19.

It would be incredibly helpful if you can update your app and recheck if the issue is still there.

**Comment by flexsurfer** [comment] 2022-10-07 09:26
could you please also elaborate on the last state of the app before crash, it crashes right after you enter your password and press sign button ?

**Comment by Engareh** [comment] 2022-10-07 17:56
> could you please also elaborate on the last state of the app before crash, it crashes right after you enter your password and press sign button ?

Exactly yes and also this happened for status desktop and also for situation of transferring from on wallet to another wallet both in my status account ( this happened in both mobile and desktop too)

**Comment by Engareh** [comment] 2022-10-07 18:31
> @Engareh 
> Failed to reproduce it on 1.20.2 and current `develop`(on both test networks and mainnet)
> As far as I see from the email you're on 1.19.
> 
> It would be incredibly helpful if you can update your app and recheck if the issue is still there.
> 

We are in Iran and internet heavily filtered so that I do not have access to Google play either.
So would you please send me a link for status update other than Google play for example a link in Dropbox

Thanks

**Comment by Engareh** [comment] 2022-10-07 20:03
> @Engareh 
> Failed to reproduce it on 1.20.2 and current `develop`(on both test networks and mainnet)
> As far as I see from the email you're on 1.19.
> 
> It would be incredibly helpful if you can update your app and recheck if the issue is still there.
> 

I was finally able to update the status through google play with the help of vpn but the same thing happened again

**Comment by Engareh** [comment] 2022-10-07 21:08
> # Problem
> 
> In status app I have two wallet one of them is empty and another one have 10 snt and 0.014 eth when I was going to register my ENS username in the last phase after signing the transaction suddenly it exist from the app and app closed
> I repeated this over and over and each time the same result.
> 
> ## Implementation
> 
> Known steps towards feature implementation.
> What needs further specifying and investigating.
> 
> ## Acceptance Criteria
> 
> Rules for the future PR to be accepted.
> 
> ## Notes
> 
> Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.
> 
> ## Future Steps
> 
> Steps which should be taken after this issue has been resolved.
> 

I could finally register my ENS username of course while using VPN

And also by changing the network in advanced settings to something else I could do this without using VPN 

I think the problems caused by internet filtering in my country "Iran"

**Comment by daferna** [comment] 2022-10-12 16:15
Infura does region block by IP address, I tried to use curl to try out Infura's endpoint through some proxies, but I couldn't get what error code is returned. It may not be an error code, perhaps the TCP connection is being closed without response. Either way, the app shouldn't crash because of an RPC call. Either status-go doesn't have the exception handling in-place or the error is being fumbled in the handoff between react and status-go. This would also make a great unit test, whatever the root cause turns out to be.

**Comment by cammellos** [comment] 2023-07-14 11:29
Closing for now as it will have to be re-evaluate in the scope of the new wallet

**Closed as not planned by cammellos** 2023-07-14 11:29 UTC
