### ISSUE TITLE
Can't change PIN in Keycard settings in Profile if relogin with fingerprint 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11048] opened 2020-08-06 08:43 UTC
# Bug Report

## Problem

After relogin with fingerprint if try to change PIN in Keycard settings in Profile this pop-up is shown: "You're unauthorized to perform this operation. Please tap valid card and try again".

#### Actual behavior

![ezgif com-resize (11)](https://user-images.githubusercontent.com/67952253/89509679-e5185280-d7cf-11ea-9304-c5550e825c03.gif)

### Reproduction

- Have Keycard multi account
- Open app
- Set "Don't ask for card to sign in" in login screen
- Tap "Enable Fingerprint", touch sensor
- Enter valid PIN
- Login with keycard
- Close app
- Open app
- Login via Fingerprint
- Profile > Keycard > Change 6-digit passcode

### Additional Information

- Status version: Release 1.5
- Operating System: Android 10

**Comment by bitgamma** [comment] 2021-05-25 08:00
duplicate of #12137?

**Comment by churik** [comment] 2021-05-25 15:13
definitely. thanks

**Closed as completed by churik** 2021-05-25 15:13 UTC
