### ISSUE TITLE
When creating a reply to the messages of different user, the first user is shown as the message author in the reply bubble in message input area

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6991] opened 2018-12-03 21:57 UTC
Description

Type: **Bug**

**Summary:** When creating a reply to the messages of different user, the first user is shown as the message author in the reply bubble in the message input area
After the message is posted though, the correct author is shown in the 'reply' bubble.
The issue is valid on mobile and desktop both.

**Expected behavior:** The icon and the name of original author of a message should be shown

**Actual behavior:** The icon and the name of the first message you replied to is shown

<img width="437" alt="image" src="https://user-images.githubusercontent.com/43638377/49403353-3ba8d000-f755-11e8-87fb-305b2f235f23.png">

**Reproduction:**

1. Open Status 
2. Join one of the public chats/group chats that have at least 3 members with messages posted
3. Reply to the message of one user
4. Without closing the initial reply 'bubble' in the message area, reply to the message of a different user and check who is displayed as an author
Note: when the reply is posted, the correct author's data is displayed in the reply 'bubble' in the chat (visible on the video)

**Additional Information:**

Status version: nightly 03/12/2018
Operating System: Mac OS for desktop, Android/iOS for mobile
Video: https://drive.google.com/file/d/1jsFIK_YokuDUAWbgrRJbu82kizu7oNED/view?usp=sharing
(note: vvvvvv is the current user)

<blockquote><div><strong><a href="https://drive.google.com/file/d/1jsFIK_YokuDUAWbgrRJbu82kizu7oNED/view?usp=sharing">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>

**Comment by churik** [comment] 2018-12-04 14:44
Closed as duplicate of https://github.com/status-im/status-react/issues/6214

**Closed as completed by churik** 2018-12-04 14:44 UTC
