### ISSUE TITLE
Message from newly joined participant of public chat is shown not at the end of a chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1015] opened 2017-04-15 15:46 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: public chat has 2 participants: One and Two. They exchanged some messages. Later, new participant Three joined and sent a message. Issue: both previous participants see message from Three not at the end of their conversation but in the beginning.
![public chat](https://cloud.githubusercontent.com/assets/6584810/25064798/5628d4fe-2202-11e7-8212-cbadf0428b89.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New messages from all participants are shown at the end of the chat

#### Actual behavior
[comment]: # (Describe what actually happened.)
Message from new participant is shown in the beginning of the chat for old participants

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7UmhKQlRoWnRURG8
As One:
- Open Status and login
- Add Two and Three to your contacts (they also need to add you to the Contacts)
- join public chat #testingall and write "Hi"
- take another device with account Two
As Two:
- join public chat #testingall and write "Hi from Two" also add the time when message was sent
As One 
- reply to Two in public chat "Hi Two how are you this is one on [insert time]"
As Two
- reply to One "I'm fine thanks one. Its now [insert time]"
As One 
- reply to Two "Let's see what happens when Three will join [insert time]
Both One and Two check that all messages are in correct order in public chat
As Three:
- Join public chat #testingall and write "Hi it's Three joined you on [insert time] after all got message let's see what happens"
As One and Two check in public chat where is the message from Three 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  0.9.6d43
* Operating System: Android and iOS
- One: iOS 10.2.1 iPhone6s
- Two: Android 7.0 Galaxy S7
- Three: iOS 10.3.1 iPhone7 plus

**Comment by rasom** [comment] 2017-04-16 08:17
This shouldn't be related to `ui-refersh`, i suppose this bug can be reproduced in `develop`.

**Comment by flexsurfer** [comment] 2017-05-05 12:24
@annadanchenko can't reproduce anymore, looks like it was fixed by https://github.com/status-im/status-react/pull/1047

**Comment by flexsurfer** [comment] 2017-05-05 12:32
but i can reproduce it a group chat, if messages not loaded, so it looks like if you open public chat and messages not loaded, then messages' order became broken

**Comment by flexsurfer** [comment] 2017-05-10 09:39
we need to rethink `:clock-value`, because with the current implementation of `:clock-value` it's complicated to fix this issue

**Comment by asemiankevich** [comment] 2017-08-08 09:32
I can't reproduce it anymore

Build version: 0.9.8-114-g243cb7de+ Android, 0.9.9d114 iOS
Tested: public chats, group chats

**Closed** 2017-08-15 16:23 UTC
Labels: advanced, bug, high-priority, Tested - OK
