### ISSUE TITLE
Chats order is off on chats tab

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1849] opened 2017-09-13 12:24 UTC
### Description

*Type*: Bug

*Summary*: Chats order is off on chats tab

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
iOS
![image](https://user-images.githubusercontent.com/28752642/30377091-3cbd5880-9897-11e7-9d51-725a7eb6d600.png)

Android 
![image](https://user-images.githubusercontent.com/28752642/30377108-50b8430e-9897-11e7-971b-881c3ae28612.png)

### Reproduction

- Open Status
- Go to chats tab and create several chats
- Pay attention to the chats order

### Additional Information
* Status version: 0.9.10-87-gf21f9ddf+
* Operating System: Android, iOS

**Comment by oskarth** [comment] 2017-09-13 12:26
May be related to https://github.com/status-im/status-react/issues/1818 (PR: https://github.com/status-im/status-react/pull/1836). @asemiankevich can you see if it is possible to reproduce with that build and not possible to reproduce before that build?

Also to note (screenshot on iOS is mine): when I did pull-to-refresh on iOS on group chat order got corrected. So it might be related to ListView and data source not being updated in subscription somehow. See https://github.com/status-im/status-react/issues/1840 for possibly related w.r.t list update semantics.

**Comment by asemiankevich** [comment] 2017-09-13 12:49
@oskarth I can see the same weird order in http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-efd5a4.apk build (http://185.90.37.243:8080/job/status-react-nightly/300/)

**Comment by oskarth** [comment] 2017-09-13 13:01
Ok, and since that build was based on `develop` and started 1 day 2 hr ago, this PR (https://github.com/status-im/status-react/pull/1836#event-1246572121) that was merged into `develop` 7 hours ago couldn't have caused it.

**Comment by oskarth** [comment] 2017-09-13 13:01
@asemiankevich Thanks. Ok, and since that build was based on `develop` and started 1 day 2 hr ago, this PR (https://github.com/status-im/status-react/pull/1836#event-1246572121) that was merged into `develop` 7 hours ago couldn't have caused it.

**Comment by annadanchenko** [comment] 2018-03-22 09:55
@asemiankevich what's the expected behaviour? Should be chats sorted by date/time when last message was sent there? So chat with more recent message is on top?

**Comment by asemiankevich** [comment] 2018-03-22 10:54
I do expect the following:

chats are ordered by creation date from old to new, newest on top of the list
when i receive message in any chat - it appears on top of others

that is a quite old issue, let me double check it in develop now , probably we should close it :)

**Closed as completed** 2018-03-27 13:51 UTC
