### ISSUE TITLE
Navigate back by swiping from the left side of the screen (left-edge swipe) (iOS)

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3804] opened 2018-04-09 08:11 UTC
### User Story

As a user, I want to navigate back by swiping from the left side of the screen so that I don't always need to reach my finger to back button at the top. 

### Description

*Type*: Feature

*Summary*:  To achieve a user story you need to implement a left-edge swipe on a system level. 

#### Expected behavior
The general rule for having this would be: left-edge swipe should work where Navigation/Tool bar has a back button (`< `arrow). This swipe duplicates the behavior of the back button.
It means it should not work for swiping between tabs for instance.

#### Actual behavior
While having 1-to-1 chat do the left-edge swipe and nothing happens, need to tap back button on the top to return back to the list of chats (home tab). 

### Additional Information
* Operating System: iOS

**Comment by annadanchenko** [comment] 2018-04-11 09:13
@denis-sharypin I expect that it will be applicable not only for 1:1 chats but for group and public chats. If so, can you update the expected result and issue description, please? 

If there are other cases (navigating in Wallet, Profile, DApps) can you share general rule and also exceptions? One exception I can think of is what happens if use swiping on main Home screen - will the "previous" screen be shown? What if I'm in webview and looking at Dapp screen - what happens when I swipe? Do I need to go back to the previous screen in website or to screen with Dapps list/Home screen?

**Comment by status-open-bounty** [comment] 2018-04-16 13:51
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe6f8a4c7d14e05996b10eecf0afeb25864bdc839eb073c13a372237d67715913](https://etherscan.io/tx/0xe6f8a4c7d14e05996b10eecf0afeb25864bdc839eb073c13a372237d67715913)

**Comment by denis-sharypin** [comment] 2018-04-16 14:09
Thanks, @annadanchenko I updated the Expected behavior

**Comment by okilimnik** [comment] 2018-05-11 11:56
what do you think of implementing [react-navigation](https://github.com/react-navigation/react-navigation) ? it has this feature by default as well as other transitions between screens.

**Comment by jeluard** [comment] 2018-05-11 11:58
@okilimnik This is something we considered already. If you can take this opportunity to explore how we could integrate it into status that would be awesome!

**Comment by denis-sharypin** [comment] 2018-05-11 12:27
@okilimnik SCREEN TRANSITIONS! YAS!

**Comment by okilimnik** [comment] 2018-05-11 20:25
I can implement react-navigation, but I need to understand the task precisely.
Current navigation implementation stacks all the history in a plain vector but it is not an idiomatic behavior for mobiles, especially	for Android, since it has a hardware back button and a user can return to login or intro screen, or return to chat from main tabs. And there are modal screens there also, and they are not needed in case of react-navigation approach.
Also, the new approach will demand a remake of iPhone X support and, I suppose, could break your tests.

**Comment by jeluard** [comment] 2018-05-12 13:17
@okilimnik We don't plan to change the user experience for now. One option could be to detail what would change with `react-navigation` but t's probably out of the scope for this issue.

**Comment by mandrigin** [comment] 2018-08-20 07:57
Closing because it is a duplicate of https://github.com/status-im/status-react/issues/4866

**Closed as completed by mandrigin** 2018-08-20 07:57 UTC
Labels: ios
