### ISSUE TITLE
Sometimes keyboard does not appear on login screen after opening the app (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19982] opened 2024-05-10 15:37 UTC
Reproducing on Android 12, Samsung Galaxy A52

**Steps:** 

1. Open app on login page
2. See if keyboard appeared
3. If it has appeared - try reopening app until keyboard fails to appear

**Actual result:** sometimes does not appear on login screen despite password input field is active by default

https://github.com/status-im/status-mobile/assets/97245802/694a3465-8f2c-426d-9e46-3d4903ef7a1d

### Additional Information

- Status version: nightly 
- Operating System: Android 12

**Comment by Parveshdhull** [comment] 2024-06-08 12:33
Tried forcing keyboard open using some suggestion from https://stackoverflow.com/questions/42456069/how-to-open-keyboard-automatically-in-react-native. for ex. calling .focus in on-layout or in set-timeout, but nothing works.

**Comment by ilmotta** [comment] 2024-06-12 00:32
@Parveshdhull Thank you for sharing the investigation details!

I'm in the process of simplifying the Mobile Core board and realized sometimes we don't move an issue to `In Progress` even though we did work on the task.

The benefit of moving to `In Progress` whenever some non-trivial work is done (let's say more than 1h) is that it makes all parties involved think about next steps to be taken to get the issue to its final state (bet it Done or Closed).

With that in mind, @pavloburykh @Parveshdhull what do you think we should do with this issue? Do you think it's worth trying something else to fix it or should we assume for now we tried whatever we could and we close it until the problem re-surfaces? Edit: or else move the issue back to `No Status`.

**Comment by pavloburykh** [comment] 2024-06-12 13:53
Hey @ilmotta 

> or else move the issue back to ```No Status```

I am not sure what does this mean, but looks like it would be better option than just closing it. I would leave the issue opened in our repo at least to identify that it is known. For sure this bug does not worth spending more efforts on it  as we have lot of higher priority tasks. Thanks for investigation @Parveshdhull

**Comment by ilmotta** [comment] 2024-06-12 15:12
Sorry @pavloburykh, moving back to `No Status` (a special GH "status") means getting the card out of any of the known status, like `Iteration Backlog`, `In Progress`, and so on. The issue can of course still be open, but completely parked because @Parveshdhull already tried and solving this seems particularly tricky, so something we might only want to come back to if it becomes more urgent.

I'll move to `No Status` but keep it open :) 

Edit: `No Status` can be seen as: something deprioritized.

**Comment by ilmotta** [comment] 2024-10-03 17:54
@pavloburykh, I'm marking the issue as "close as not planned" because the bug is very benign and we couldn't reproduce so far.

**Closed as not planned by ilmotta** 2024-10-03 17:54 UTC
Labels: mobile-core
