### ISSUE TITLE
Community page out of perportion

### ISSUE THREAD

**Issue by du82** [status-im/status-react#14945] opened 2023-01-31 19:37 UTC
Some communities are out of perportion
Version: nightly

https://user-images.githubusercontent.com/65834069/215864490-0a7daca8-3fce-4c76-83de-c322bf8530f9.mp4

**Comment by ajayesivan** [comment] 2023-02-09 11:09
@du64 I'm not able to reproduce this issue. Any hints to reproduce?

**Comment by du82** [comment] 2023-02-09 16:50
> @du64 I'm not able to reproduce this issue. Any hints to reproduce?

No clue, it just started happening. WHen it happens, it will happen every time for specific communities, it's not something that rarely shows up or an edge case.

**Comment by cammellos** [comment] 2023-07-14 11:02
Closing until we can replicate

**Closed as not planned by cammellos** 2023-07-14 11:02 UTC
