### ISSUE TITLE
"Sync using mobile data?" bottom sheet is overlapped with keyboard if app is in foreground

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10392] opened 2020-04-21 16:08 UTC
# Bug Report

## Problem
Issue is reproducible when focus is set in input field with open keyboard (i.e. chat) and app is in foreground (so you don't manually switching off wi-fi to trigger it)

#### Expected behavior
Keyboard is closed, bottom sheet is visible

#### Actual behavior

![photo_2020-04-21 17 51 54](https://user-images.githubusercontent.com/4557972/79886544-60105580-83f9-11ea-87a0-31538706c518.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on wi-fi network
- Join to any chat and set focus in input field
- Go out from WI-FI zone to activate mobile connection (it is not reproducible if the change was triggered manually)

### Additional Information

- Status version: Release v1.3
- Operating System: iOS, iPhone 7 
I don't think it is platform specific, but don't have android with mobile connection to try it.
@Serhy can you assist please?

**Comment by Serhy** [comment] 2020-04-22 07:35
Not reproducible on Android 8. I guess it iOS specific. I remember in the past there was such issue I could see on iOS only, so possible to be iOS specific. 

Howerver on iPhoneX with iOS 13.3 I could not reproduce it...
Device with WIfi and Mobile network enabled -> Opened public chat with focus in message input -> turned off wifi router and in ~20 sec: Keyboard disappeared + `Sync using mobile data?` bottom sheet appeared.

**Comment by hesterbruikman** [comment] 2021-03-18 09:44
Closing as I can no longer reproduce on iOS (1.12). Belief this is resolved as the bottom sheet no longer pops up automatically, but after tapping on 'no wifi' icon

cc @churik @Serhy

**Closed as completed by hesterbruikman** 2021-03-18 09:44 UTC
Labels: ios
