### ISSUE TITLE
Can't upgrade Release app to nightly version: "Status" has the same bundle ID [iOS]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6339] opened 2018-10-16 10:51 UTC
**_Type_**: Bug

_Summary_: Attempt to upgrade release app version installed from TestFlight onto nightly build app (**in Diawii**) fails right away with `"Status" has the same Bundle ID as "Status - Ethereum. Anywhere."` message on iOS.

#### Expected behavior
I can upgrade from Release app version to Nightly build (in Diawii) 

#### Actual behavior
Can't upgrade Release app to nightly version: "Status" has the same bundle ID [iOS]
![](https://user-images.githubusercontent.com/8749671/47011116-bbe58880-d149-11e8-9404-33acba7cde2f.png)

### Reproduction

* Install Status from TestFlight (e.g. 0.9.29 version)
* Upgrade to nightly build from https://status-im.github.io/nightly/

### Additional Information

* Status version: Upgrade 0.9.29 (TF) -> to 0.9.30 (Diawii)
* Operating System: iOS only

<blockquote><div><strong>[Status.im Nightly Builds](https://status-im.github.io/nightly/)</strong></div></blockquote>

**Comment by asemiankevich** [comment] 2018-12-04 12:37
@rasom @jakubgs anything we can do here?

**Comment by jakubgs** [comment] 2019-01-07 17:08
Is this still an issue? As far as I can tell the number used in nightlies should be generated the same way as releases, which means it should be a timestamp like this: `2019010718` or something to that effect.

Can someone that has an iOS device confirm that nightlies use a build number like that?

**Comment by annadanchenko** [comment] 2019-01-08 10:03
@jakubgs I can upgrade fine on real iOS device from 0.9.32 release to today's nightly, so looks like there is no issue anymore. Version after upgrade to nightly: 0.9.33 (201901083)

**Comment by jakubgs** [comment] 2019-01-08 10:43
Thanks for verifying!

**Comment by Serhy** [comment] 2019-01-08 10:56
@jakubgs @annadanchenko, with iPhoneX  iOS 12.1.2 I still see the error when I try to upgrade Release 0.9.32 to latest nightly.
1) Install from Test Flight release version 0.9.32 (2018121711). 
2) Create new account. Status version displays as 0.9.32 (9999) in `Profile` -> `About` info
3) Upgrade to latest nightly build from Diawii: Navigate to https://i.diawi.com/c2kfqQ -> tap `Install application`
**Actual result:** 
<img width="267" alt="screenshot 2019-01-08 at 12 53 44" src="https://user-images.githubusercontent.com/8749671/50826514-7c8f9800-1344-11e9-94ca-aeb899df47bd.png">



<blockquote><div><strong><a href="https://i.diawi.com/c2kfqQ">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by jakubgs** [comment] 2019-01-08 11:04
>1. Install from Test Flight release version 0.9.32 (2018121711).
>2. Create new account. Status version displays as 0.9.32 (9999) in Profile -> About info

Wait, what? You mean to say that the build number changes despite you not installing a different Status version? Or am I misunderstanding?

**Comment by jakubgs** [comment] 2019-01-08 11:05
~~What is the build ID of this release: https://i.diawi.com/c2kfqQ ?~~

Okay, so the build number of https://i.diawi.com/c2kfqQ is `2019010803`, which is different from both `2018121711` and `9999`, so it should install just fine.

**Comment by annadanchenko** [comment] 2019-01-08 11:18
I've rechecked once more on another iOS device with iOS 12.1.2 (latest available version) and can reproduce issue. So, despite different version number for nightly there is issue with upgrade.

In https://github.com/status-im/status-react/issues/6339#issuecomment-452242224 iOs version was 11.0.3 and issue does not exists on that device for same steps

**Comment by mandrigin** [comment] 2019-01-08 11:26
@annadanchenko hmm, can't find any information about changes in iOS 12 related to that, but it looks like an iOS issue...

**Comment by hesterbruikman** [comment] 2019-07-26 14:16
@Serhy have you experienced this issue since? @simonricoo is running into the same issue trying to install nightly

**Comment by jakubgs** [comment] 2019-07-26 15:14
Which nightly? Can you tell us what is the current version you have and which nightly you are trying to install?

**Comment by Serhy** [comment] 2019-07-26 15:38
@hesterbruikman yes, I have.
Reproduced when I upgrade Release 0.13.0 build installed from TestFlight onto latest  https://i.diawi.com/oBPN38 nightly build (2019072603) - the same error as in description prevents me to do that

**Comment by hesterbruikman** [comment] 2019-07-26 15:44
Interesting! Best for @simonricoo to confirm. Afaik latest attempt was installing today's nightly on top of 0.13 from Testflight on iPhone X.

**Comment by Serhy** [comment] 2019-07-26 15:47
> Interesting! Best for @simonricoo to confirm. Afaik latest attempt was installing today's nightly on top of 0.13 from Testflight on iPhone X.

Exact app version and device where I just confirmed issue still valid.

**Comment by churik** [comment] 2020-02-25 13:50
Issue is still valid on nightly 25/02/2020 at attempt to upgrade from release v1.0.1

**Comment by cammellos** [comment] 2020-09-17 10:16
marking as wontfix , not sure we should encourage this, as it's bound to cause problems for users

**Comment by churik** [comment] 2020-09-17 11:04
Agree

**Closed as completed by churik** 2020-09-17 11:04 UTC
