### ISSUE TITLE
Add 'Search with DuckDuckGo' to the address bar in browser

### ISSUE THREAD

**Issue by du82** [status-im/status-react#12539] opened 2021-09-02 14:52 UTC
# Feature Issue

### User Story

As a user, I want to be able to search with DuckDuckGo and possibly other search engines along with being able to enter an address **so that I can quickly search DuckDuckGo from the address bar**. 

### Description

*Summary*: This feature exists on every mainstream browser, and also exists on the Status Desktop app, but after talking to many Status users, is the drawback which keeps them using Chrome or Safari. Adding this would give users the ability to switch to the Status browser, and remove the spying browsers.

### Extra thoughts

Maybe bangs could be introduced similar to how DuckDuckGo does them, so in the address bar of Status you could type **!w (query)** to be redirected to the appropriate page or search result without having to redirect from DuckDuckGo to the wikipedia page, or typing in wikipedia.com.

Adding Google and Bing as optional defaults with a "Warning: This search engine does not respect your privacy" popup would be nice.

**Comment by churik** [comment] 2021-09-06 08:23
@hesterbruikman @ducheng0 I believe it is duplicate of https://github.com/status-im/status-react/issues/10575

**Closed as completed by churik** 2021-09-06 08:23 UTC
Labels: feature

**Comment by hesterbruikman** [comment] 2021-09-06 11:22
Should be covered by #10575 indeed. Thanks for the ping.

@ducheng0 you'll find designs in that issue as well. Thanks for resurfacing! Still love this idea
