### ISSUE TITLE
Wallet: account options menu

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#17598] opened 2023-10-10 05:24 UTC
Implement a wallet account options menu UI

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=878-237757&mode=design&t=eshzHW0FkL1DRBGs-0

**Comment by smohamedjavid** [comment] 2023-10-11 09:26
Duplicate of #17367

**Closed as completed** 2023-10-13 13:19 UTC
Labels: feature, wallet: Accounts
