### ISSUE TITLE
Public Chats for New User Experience

### ISSUE THREAD

**Issue by jbostick00** [status-im/status-react#3929] opened 2018-04-18 19:09 UTC
As a <user>, I want to ask:

 I notice when new users first log in and go to #Status channel, if they don't see a response right away, they leave.  Also the channel is blank when you first log in because of no inboxing so it looks blank.  Is it possible to add a standard message when they first go to the channel explaining there is no in-boxing so just hang out for a minute and see if someone responds?  I leave the channel open when at work and try to respond when I can but I notice I miss a lot of people that log on and then leave right away.

### Description

[comment]: # (Feature)
*Type*: <Feature>

[See above]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...

#### Expected behavior
[Need information or need to see prior posts]: # (Describe what you expected to happen.)

#### Actual behavior
[blank when first log into public chats, post a quick message and no one answers and they leave the app]: # (Describe what actually happened.)

### Reproduction
[NA]: # (Describe how we can replicate the bug step by step.)

- Open Status
- ...
- Step 3, etc.

### Solution
Set up something for first time log ins to Public Chat so they hang out for a while and understand why they do not see any messages.: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] ...
- [ ] ...

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ...
[comment]: # (Android or iOS.)
* Operating System: <Android|iOS>

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by lukaszfryc** [comment] 2018-05-09 14:50
This is very true. 

At this moment there is placeholder saying "There are no messages in this chat yet". Maybe we should change it to "There are no new messages in this chat yet." or "New #status messages will appear in this chat.". @chadyj ?

**Comment by lukaszfryc** [comment] 2018-05-09 14:51
Closing as duplicate of #3930. Let's continue discussion there.

**Closed as completed by lukaszfryc** 2018-05-09 14:51 UTC
