### ISSUE TITLE
0.9.32 mobile release

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6891] opened 2018-11-27 09:52 UTC
We will use this issue to manage 0.9.32 release.

open issues and PRs for release: https://github.com/status-im/status-react/labels/release

**Comment by lukaszfryc** [comment] 2018-11-27 09:58
@chadyj can we fill description of this issue with:
1) Go to dev person who will take care of cutting the release branch and doing hot-fixes
2) QA person responsible for release testing
3) Product person to coordinate the release with marketing, etc.

Also, are we going to release next week? If yes, can we cut the release/0.9.32 tomorrow? We have group chats that we should release asap as they will minimize the impact of PFS release in the future. 

> Enabling PFS for 1-to-1 will be a breaking change, but if we release group chats (or pairing, or both ) next week, those clients will be already compatible, so it will give us a bit more time for users to upgrade, making the upgrade less painful.   
https://github.com/status-im/status-react/issues/6882#issuecomment-441974577

**Comment by chadyj** [comment] 2018-11-27 15:03
@mandrigin any comments for the above?

@jeluard Mentioned that this release needs to be out by Sunday Nov 2nd, so lets hustle!

@jeluard Is everything in develop and ready to go? What are the Kyber changes needed?

**Comment by jeluard** [comment] 2018-11-27 15:06
@chadyj Some commits are still missing. Realistically the target date would be Dec 7

**Comment by annadanchenko** [comment] 2018-11-27 15:24
I can be responsible for release testing and coordinating with test team except this Friday (nov 30).

@jeluard when missing commits will be ready, so we cut off the branch for testing? Ideally, we'd like to have 1st release build for regression testing tomorrow morning.

**Comment by jeluard** [comment] 2018-11-27 15:33
@annadanchenko Sounds good!

**Comment by mandrigin** [comment] 2018-11-27 16:33
@chadyj emm, what did you want me to comment on? 😆

**Comment by chadyj** [comment] 2018-11-27 18:06
> @chadyj emm, what did you want me to comment on? 😆

This comment https://github.com/status-im/status-react/issues/6891#issuecomment-441998313
Specifically who is the go-to dev person, and cutting the release tomorrow.  Some feedback [here](https://notes.status.im/mobile-release-guide) would be good too.

**Comment by mandrigin** [comment] 2018-11-28 08:54
Well, I can fix some bugs for this release.

**Comment by annadanchenko** [comment] 2018-11-28 09:04
@mandrigin can you create 0.9.32 release build, please? Should also have version 0.9.32 in the app

**Comment by chadyj** [comment] 2018-11-28 09:36
Translation string updates are ready for testing and review https://github.com/status-im/status-react/issues/6891

**Comment by mandrigin** [comment] 2018-11-28 09:38
@annadanchenko done. `release/0.9.32` is cut and the build is running: https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/">release/0.9.32 [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by chadyj** [comment] 2018-11-28 09:51
- [Release notes](https://notes.status.im/mobile-release-notes?both)
- [Release guide](https://notes.status.im/mobile-release-guide) Everyone please update as you go :)

cc @Blockchain-Islander @pablanopete @j-zerah  Take a look. If all goes well well we can release Monday or Tuesday.

**Comment by annadanchenko** [comment] 2018-11-28 10:10
@corpetty @mandrigin guys, do we need to do anything extra from security pov on the release 0.9.32 built today? like review again  dependencies, as https://github.com/status-im/status-react/issues/6906 is not done yet.

**Comment by annadanchenko** [comment] 2018-11-28 10:18
according to @cammellos we need to cherry pick https://github.com/status-im/status-go/pull/1293 into the release if we want to have group chats in it. 

If it's a low impact change on status-go side then I'm fine with it. Any opinions on it @adambabik @mandrigin @chadyj ?

**Comment by chadyj** [comment] 2018-11-28 10:20
> If it's a low impact change on status-go side then I'm fine with it. Any opinions on it

I'd love to see group chats #6882 in the release if this is a low impact change.

**Comment by lukaszfryc** [comment] 2018-11-28 10:27
Btw, I've been checking average battery consumption in nightlies for the last 20 days and it looks stable. For measurements, I used https://github.com/status-im/status-react/pull/6692 with some reference tests like creating new account, sending message, etc. [Screenshot of latest results](https://monosnap.com/file/7718oJhaMcg1w0KWSuDhKB5Dyne9sK).

**Comment by chadyj** [comment] 2018-11-28 10:36
Kudos @lukaszfryc for checking battery consumption!!!

**Comment by Serhy** [comment] 2018-11-28 11:58
Release 0.9.32 builds (https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/2/) has the `(9999)` version both on iOS and Android: 
Version `0.9.32 (9999); node 27700aa2`

https://github.com/status-im/status-react/issues/6881 is related and it's fix already in progress:  https://github.com/status-im/status-react/pull/6894

@jakubgs, @mandrigin  we'll need to add it in release/0.9.32 as well in order to have app version with new format.  

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/2/">status-react » release » release/0.9.32 #2 [Jenkins]</a></strong></div></blockquote>

**Comment by corpetty** [comment] 2018-11-28 13:02
> @corpetty @mandrigin guys, do we need to do anything extra from security pov on the release 0.9.32 built today? like review again dependencies, as #6906 is not done yet.

Do we have a timeframe on getting #6906 done?  I don't have anything else that is incredibly pressing for this release.

**Comment by mandrigin** [comment] 2018-11-28 13:09
I made it work on macOS just fine, on Linux npm behaves weirdly :( fixing that now...

**Comment by Serhy** [comment] 2018-11-28 15:49
#6894 has been merged into develop. 
@mandrigin could we cherry pick it release also please?

**Comment by annadanchenko** [comment] 2018-11-28 17:16
and https://github.com/status-im/status-react/pull/6917 is also ready to be merged and cherry picked @mandrigin

**Comment by mandrigin** [comment] 2018-11-28 17:36
@corpetty @annadanchenko #6906 — let's switch to yarn instead. I'll work on it, but it shouldn't stop the release. We can check the modified package-lock file for release builds separately, if needed.

**Comment by mandrigin** [comment] 2018-11-28 17:43
#6894 — cherry-picked to `release/0.9.32`
#6917 — merged to `develop` and cherry-picked to `release/0.9.32`

**Comment by jeluard** [comment] 2018-11-28 17:47
FYI There's a bunch of extensions related commits that will have to be cherry picked.

**Comment by jeluard** [comment] 2018-11-28 17:52
@mandrigin There are 2 branches: `release/0.9.32` and `releases/0.9.32`. Which one is the right one?

**Comment by mandrigin** [comment] 2018-11-28 17:52
`release/0.9.32`, there is a typo in the second one

**Comment by jeluard** [comment] 2018-11-28 17:56
@mandrigin Could you delete it so that I don't mixup both ? :)

**Comment by mandrigin** [comment] 2018-11-28 18:07
done

**Comment by chadyj** [comment] 2018-11-29 09:57
Release notes for 0.9.32 so far are:

## 0.9.32

Added
- Private group chats with increases security using Signal's double ratchet algorithm (In beta. Still being tested. Feedback welcome!)
- Device pairing and syncing with perfect forward secrecy (in dev mode)


Changed
- Support multi-extensions store
- Restyled wallet onboarding flow, main wallet screen, and sent-transaction screen
- Faster sign-in

Fixed
- Rransaction history fixes 
- Updating enabled tokens before navigating to wallet 

[All changes](https://github.com/status-im/status-react/compare/release/0.9.31...release/0.9.32)

@rachelhamlin @jeluard anything you'd like to add for the new extensions work?  Notes can be edited here https://notes.status.im/mobile-release-notes?edit

**Comment by annadanchenko** [comment] 2018-11-29 15:17
@chadyj @mandrigin it looks to me like a release blocker https://github.com/status-im/status-react/issues/6944  if agree, please add release label to it

**Comment by mandrigin** [comment] 2018-11-29 15:20
agreed

**Comment by annadanchenko** [comment] 2018-11-29 15:29
adding https://github.com/status-im/status-react/issues/6903 to the release scope (as according to @yenda  it's same case as reported in #6944 )

**Comment by rasom** [comment] 2018-11-30 06:00
regarding https://github.com/status-im/status-react/issues/6903 

Fix to make it work properly on nigthly side is relatively simple (recalculate old id, store it along with message, use both `message-id` and `old-message-id` in order to fetch the reference).

In order to make it work on both sides, we can always send an old message id as a reference id. Though IMO this will only complicate things.

The simplest way for us is to introduce breaking change in `0.9.32` and also add (again) random `message-id` so that we will not need to have similar issues in future.

**Comment by yenda** [comment] 2018-11-30 07:15
@rasom I'm in favor of breaking change as long as we now pass the message-id with the message to avoid that type of problem the next time we change message-id generation

**Comment by mandrigin** [comment] 2018-11-30 08:25
I 100% agree with @yenda. It has bitten us before, and it will bite us in the future unless we fix it now.

**Comment by lukaszfryc** [comment] 2018-11-30 08:54
re breaking changes, I think we may have another one when PFS is implemented. Am I right @cammellos? If yes, maybe we should release both things at once?

**Comment by rasom** [comment] 2018-11-30 09:03
@lukaszfryc we can make it compatible, and i'm going to introduce the change for this during next hours

**Comment by Serhy** [comment] 2018-11-30 11:37
There is a release blocker: https://github.com/status-im/status-react/issues/6963 
Which is already fixed in the scope of https://github.com/status-im/status-react/pull/6932

@mandrigin @chadyj since #6932 is not in the scope of release we could go with: a) Include #6932 in scope of release or b) Cherry-pick commit fixing issue #6963 in the release. What's the best option for us at this moment? (I'd go with (b) case)

**Comment by cammellos** [comment] 2018-11-30 11:40
I'll make it easy for everyone, I will just cherry pick the small fix (it's a one line change), and then if we want to include the whole PR we can decided later

**Comment by cammellos** [comment] 2018-11-30 13:14
cherry picked https://github.com/status-im/status-react/pull/6965

**Comment by lukaszfryc** [comment] 2018-11-30 15:16
When https://github.com/status-im/status-react/pull/6932 is merged, it will contain fixes for #6963 and #6965. 

So apart from #6903 (not a blocker?) we are almost done. We just need to re-test some areas of the app on Monday.

**Comment by chadyj** [comment] 2018-11-30 15:19
@jeluard You all set?

**Comment by jeluard** [comment] 2018-11-30 16:17
I’d love to have #6957 too but I am AFK. @flexsurfer can you handle that?

**Comment by flexsurfer** [comment] 2018-11-30 16:52
cherry picked  #6957  https://github.com/status-im/status-react/commit/18b75226423374fac58ee96583f0fe05e1159ceb

**Comment by Serhy** [comment] 2018-11-30 17:46
> When #6932 is merged, it will contain fixes for #6963 and #6965.

That's fine, agree.
Ideally, I'd exclude #6932 from cherry-picking, though. Because mostly it contains additional features we are about to include after release branch cut off (PR #6935 fixed original release blocker #4868)

**Comment by rachelhamlin** [comment] 2018-12-01 14:07
Are we targeting Tuesday for release @chadyj?

cc @j-zerah

**Comment by chadyj** [comment] 2018-12-01 15:12
> Are we targeting Tuesday for release @chadyj?

Ideally yes, but could run late with testing and more fixes.

**Comment by lukaszfryc** [comment] 2018-12-03 07:57
> > When #6932 is merged, it will contain fixes for #6963 and #6965.
> 
> That's fine, agree.
> Ideally, I'd exclude #6932 from cherry-picking, though. Because mostly it contains additional features we are about to include after release branch cut off (PR #6935 fixed original release blocker #4868)

TBH, I don't see a reason **why we should not** include #6932 in the release. It contains useful feature for group chats and is all tested. cc @Serhy @cammellos 

Anyway, we need to retest some parts of the app before the regression.

**Comment by Serhy** [comment] 2018-12-03 10:47
> TBH, I don't see a reason **why we should not** include #6932 in the release. It contains useful feature for group chats and is all tested. cc @Serhy @cammellos

The reason, in a nutshell, is to follow the plan in what we about to release (the new features and bugfixes we stick to by release branch cut off). 
It makes sense to include fixes to outstanded regressions, but not really makes sense to include new features (what for to cut off the release branch then?)

@lukaszfryc @cammellos let's cherry-pick #6932 in `release/0.9.32`, this is the part we were aimed to retest anyway. 
But lets agree (and keep in release notes) afterwards, the rules we try to follow in relation to similar questions in future. 
cc @chadyj

**Comment by cammellos** [comment] 2018-12-03 10:49
@Serhy thanks, cherry-picked

**Comment by asemiankevich** [comment] 2018-12-03 11:13
> > TBH, I don't see a reason **why we should not** include #6932 in the release. It contains useful feature for group chats and is all tested. cc @Serhy @cammellos
> 
> The reason, in a nutshell, is to follow the plan in what we about to release (the new features and bugfixes we stick to by release branch cut off).
> It makes sense to include fixes to outstanded regressions, but not really makes sense to include new features (what for to cut off the release branch then?)
> 
> @lukaszfryc @cammellos let's cherry-pick #6932 in `release/0.9.32`, this is the part we were aimed to retest anyway.
> But lets agree (and keep in release notes) afterwards, the rules we try to follow in relation to similar questions in future.
> cc @chadyj

@lukaszfryc totally agree with @Serhy here. Also if u are proposing something to be included - make sure averyone impacted is aware. This is the first time i hear about this nice feature to be a part of release. cc @annadanchenko

**Comment by chadyj** [comment] 2018-12-03 13:20
@rachelhamlin @j-zerah  
There was a comment [here](https://discuss.status.im/t/status-mobile-releases/823/3) about needing Decentraland in the dapp listing by December 10. Is that still required? It needs to be in this release or it won't make the deadline.

**Comment by j-zerah** [comment] 2018-12-03 15:20
@chadyj @rachelhamlin - yes if we can add decentraland to the list in this release, it would be much appreciated. We are launching comms for a joint campaign on december 10

**Comment by chadyj** [comment] 2018-12-03 18:01
Hey devs! Can anyone help bringing decentraland back?  We used to have it and was removed in this  PR so you can grab assets and info https://github.com/status-im/status-react/pull/4232/files#diff-3f0aba2b3c8741a870b1cffc6357607dL188

<blockquote><img src="https://avatars3.githubusercontent.com/u/359723?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/4232">[#4218] Removed some DApps by jeluard · Pull Request #4232 · status-im/status-react</a></strong></div><div>fixes #4218
Summary:
Removed older DApps
status: ready</div></blockquote>

**Comment by jeluard** [comment] 2018-12-04 05:20
@chadyj Find the PR here: https://github.com/status-im/status-react/pull/6992/files

<blockquote><img src="https://avatars3.githubusercontent.com/u/359723?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/6992">Added Decentraland DApp by jeluard · Pull Request #6992 · status-im/status-react</a></strong></div><div>Added Decentraland back
Summary:
status: ready</div></blockquote>

**Comment by flexsurfer** [comment] 2018-12-04 11:07
cherry picked https://github.com/status-im/status-react/pull/6992

**Comment by flexsurfer** [comment] 2018-12-04 12:16
cherry picked https://github.com/status-im/status-react/pull/6971

**Comment by asemiankevich** [comment] 2018-12-04 13:30
@chadyj we are waiting for https://github.com/status-im/status-react/pull/6987 to be tested and merged to release branch. Then we can do final testing i guess, since i am not aware of any other commits to be included.  What was the agreed deadline for the Asia Roadshow build? 

cc @Serhy @churik @annadanchenko @mandrigin @jeluard @rachelhamlin

**Comment by asemiankevich** [comment] 2018-12-04 14:04
@jakubgs @rasom @mandrigin https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/ is failing . Please assist

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/">release/0.9.32 [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by jeluard** [comment] 2018-12-04 14:58
@asemiankevich EthSinpapore hackathon starts on Dec 6.

**Comment by asemiankevich** [comment] 2018-12-04 15:15
@mandrigin i believe https://ci.status.im/job/status-react/job/upload_release_ios/ requires the same fix, could you please assist here too? 

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/upload_release_ios/">upload_release_ios [status-react] [Jenkins]</a></strong></div></blockquote>

**Comment by mandrigin** [comment] 2018-12-04 17:14
the job is fixed and the build is submitted to Apple to be reviewed

**Comment by annadanchenko** [comment] 2018-12-05 08:51
> hackathon starts on Dec 6.

are you sure @jeluard ? on https://ethsingapore.co/ 7 Dec is a start date and 9:30PM is listed as time when it's officially begins

<blockquote><img src="images/favicon.ico" width="48" align="right"><div><strong><a href="https://ethsingapore.co/">ETHSingapore Hackathon Dec 7-9, 2018</a></strong></div></blockquote>

**Comment by rachelhamlin** [comment] 2018-12-05 09:09
@annadanchenko you're right, it's Friday the 7th.

**Comment by lukaszfryc** [comment] 2018-12-05 09:27
Looks like group chats are enabled in release builds by default. I think it's not expected as we wanted to keep them under development mode for release builds. @cammellos could you fix it?

It was probably introduced in https://github.com/status-im/status-react/commit/5795ca8d1a58ff3e7efbefa1e4c2f9b509e7e9ec

**Comment by asemiankevich** [comment] 2018-12-05 09:31
@lukaszfryc we tested this and this is done intentionally as far as i know. @annadanchenko ?

**Comment by annadanchenko** [comment] 2018-12-05 09:36
> Looks like group chats are enabled in release builds by default. I think it's not expected as we wanted to keep them under development mode for release builds. @cammellos could you fix it?
> 
> It was probably introduced in [5795ca8](https://github.com/status-im/status-react/commit/5795ca8d1a58ff3e7efbefa1e4c2f9b509e7e9ec)

I'd rather not touch release anymore unless there are functional issues. Is it so risky to have group chats enabled by default? @chadyj @lukaszfryc @cammellos

**Comment by lukaszfryc** [comment] 2018-12-05 09:42
> Is it so risky to have group chats enabled by default?

It's not. As Andrea said "with that, the only reason to have them in dev mode would be to warn users that is a beta-feature." (more in https://github.com/status-im/status-react/issues/6882). But having in mind that Status is still kind of beta, I think we can leave them enabled by default.

**Comment by annadanchenko** [comment] 2018-12-05 13:12
new release build with https://github.com/status-im/status-react/pull/7014 timed out and another one started: https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/24/

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/24/">status-react » release » release/0.9.32 #24 [Jenkins]</a></strong></div></blockquote>

**Comment by asemiankevich** [comment] 2018-12-05 14:27
started https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/26/ - should be fine

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/26/">status-react » release » release/0.9.32 #26 [Jenkins]</a></strong></div></blockquote>

**Comment by asemiankevich** [comment] 2018-12-05 15:12
@chadyj any news about apple review?

**Comment by asemiankevich** [comment] 2018-12-05 17:29
@chadyj @annadanchenko review passed as i can see in iTunesConnect

**Comment by annadanchenko** [comment] 2018-12-05 17:48
submitted new "2018120516" build to Apple review and got Approve, so it's fine on this side and can be pushed to public testing as soon as we are done with final testing on 2018120516 TestFlight build and Android release from https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/26/

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/26/">status-react » release » release/0.9.32 #26 [Jenkins]</a></strong></div></blockquote>

**Comment by chadyj** [comment] 2018-12-05 18:18
Nice job everyone! 🎉 

I expired the older build so we only have the latest available.
I also added the release notes and its ready to go.

@j-zerah @Blockchain-Islander @pablanopete Let's aim to release 3CST/9EST tomorrow. Sound good?

**Comment by pablanopete** [comment] 2018-12-05 23:55
Sounds good to me! cc @Blockchain-Islander the blog is ready to go for that time if you're good on social copy as well.

**Comment by Blockchain-Islander** [comment] 2018-12-06 00:23
Thanks all! Will get this live at 3pm CST 👍

**Comment by rasom** [comment] 2018-12-06 06:20
Hey team, it would be really great to include https://github.com/status-im/status-react/pull/7019/files to the release. There is a tiny chance that without this fix some users which had message duplicates because of issues with `message-id` calculation **BEFORE** `0.9.31` still have duplicates in their DB and migrations will not pass without this change. It only checks if the message with a new `message-id` has been added and removes duplicate. The same way it removes duplicates from `user-status` entity.

I'm really sorry for making this late update, but as it hasn't been reproduced during testing it was a bit hard to spot this possible issue. 

<blockquote><img src="https://avatars2.githubusercontent.com/u/2364994?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/7019">[WIP] fix possible user-status duplicate by rasom · Pull Request #7019 · status-im/status-react</a></strong></div><div>status: wip</div></blockquote>

**Comment by chadyj** [comment] 2018-12-06 06:24
Thanks for the fix Roman. Agree we should include this.

**Comment by asemiankevich** [comment] 2018-12-06 07:09
@mandrigin @jakubgs can't build release again https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/29/ . Please take a look!

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/29/">status-react » release » release/0.9.32 #29 [Jenkins]</a></strong></div></blockquote>

**Comment by mandrigin** [comment] 2018-12-06 07:25
Try again, it looks like saucelabs was down for some reason.

**Comment by jakubgs** [comment] 2018-12-06 07:37
Yup: https://status.saucelabs.com/

<blockquote><img src="//dka575ofm4ao0.cloudfront.net/pages-favicon_logos/original/12112/MB3zUqIkSKqxv7NnAvwE" width="48" align="right"><div><strong><a href="https://status.saucelabs.com/">Sauce Labs Inc Status</a></strong></div><div>Welcome to Sauce Labs Inc's home for real-time and historical data on system performance.</div></blockquote>

**Comment by asemiankevich** [comment] 2018-12-06 07:44
its fine now :thisisfine:

**Comment by asemiankevich** [comment] 2018-12-06 08:29
@chadyj could you please expire previous build in TestFlight? I submitted one more with Roman's commit. And also add release notes. Can't find how to do this myself :(

**Comment by chadyj** [comment] 2018-12-06 08:39
Expired. Here is the screenshot of what to press on the build page. (not sure about permissions though)

Also remember that if you upload a new build please grab the "what's new" from the old build or release notes.

<img width="1178" alt="screen shot 2018-12-06 at 9 36 19 am" src="https://user-images.githubusercontent.com/116099/49571874-b7b03d00-f93a-11e8-9f1f-4c8d1248d4d0.png">

**Comment by asemiankevich** [comment] 2018-12-06 08:40
@chadyj i dont have rights( thanks for assistance

**Comment by chadyj** [comment] 2018-12-06 12:43
Heya are we good with the `2018120610` build? @asemiankevich @annadanchenko  We are scheduled to ship in an hour.

**Comment by annadanchenko** [comment] 2018-12-06 13:29
@chadyj no blockers found, basic checks went fine

**Comment by annadanchenko** [comment] 2018-12-06 13:45
unfortunately, new blocker was found when doing minor checks: https://github.com/status-im/status-react/issues/7027

**Comment by annadanchenko** [comment] 2018-12-06 13:59
@chadyj @mandrigin do you want to postpone the release because of #7027 and fix it or we can release with (9999) in ios version?

**Comment by annadanchenko** [comment] 2018-12-06 14:03
having another thought on it - only users with diawi access can install ios builds, so typical user will have TestFlight version anyway so might not be a blocker really, unless it can influence future upgrades

**Comment by chadyj** [comment] 2018-12-06 14:04
We have the fix merged https://github.com/status-im/status-react/pull/7028 so may as well run a new build.

**Comment by annadanchenko** [comment] 2018-12-06 14:25
@chadyj we may but I'm not sure if other changes in upload release job are fine and would rather stay with 9999 as exception for this release. Unless developers will say that 9999 in the version can impact future upgrades cc @mandrigin @rasom @cammellos

**Comment by chadyj** [comment] 2018-12-06 14:48
@j-zerah @Blockchain-Islander @pablanopete  Apologies for the delay. 

There have been some tech issues and we don't have consensus on how to proceed.  Hopefully we will have an update within the hour.

**Comment by annadanchenko** [comment] 2018-12-06 15:41
@j-zerah @Blockchain-Islander @pablanopete  looks like we got consensus and will push the release in 10 minutes from now.

**Comment by j-zerah** [comment] 2018-12-06 15:43
ok thank you. Please let us know when comms can go out

**Comment by annadanchenko** [comment] 2018-12-06 16:00
@j-zerah @Blockchain-Islander @pablanopete both iOS and Android releases for 0.9.32 are published. Please, send comms cc @chadyj

**Comment by pablanopete** [comment] 2018-12-06 16:01
Ok, thanks!

**Comment by chadyj** [comment] 2018-12-06 16:07
Comms are out!
https://our.status.im/v0-9-32/
https://twitter.com/ethstatus/status/1070710037415428096

Thanks y'all!  Seeya next time 🍻 

<blockquote><img src="https://our.status.im/content/images/2018/12/Release__0.9.32.jpg" width="48" align="right"><div>Our Status</div><div><strong><a href="https://our.status.im/v0-9-32/">v0.9.32 Release - Private Group Chats</a></strong></div><div>Version 0.9.32 Introducing beta support for Private group chats! There is also alpha support of pairing (with development mode on) between mobile and desktop clients for messages and contacts syncing.</div></blockquote>
<blockquote><img src="https://pbs.twimg.com/media/DtvtGnJWoAE2rca.jpg:large" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/ethstatus/status/1070710037415428096">Status on Twitter</a></strong></div><div>“Version 0.9.32 has been released! Private group chats, device syncing and more are included in this release. Check out the release notes for more details. https://t.co/faPiNDD8EK”</div></blockquote>

**Comment by annadanchenko** [comment] 2018-12-06 16:07
@pablanopete 0.9.32 apk for cn site: http://status-im.ams3.digitaloceanspaces.com/StatusIm-181206-094952-05782d-release.apk

<blockquote></blockquote>

**Comment by chadyj** [comment] 2018-12-06 16:18
Re-opening as there are multiple reports of "unknown status-go error"

https://twitter.com/carlos_molotov/status/1070711892505698304?s=21

cc @mandrigin @annadanchenko 

<blockquote><img src="https://pbs.twimg.com/media/DtvuyaYX4AEgWbt.jpg:large" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/Carlos_molotov/status/1070711892505698304">CarlosGonzálezJuárez on Twitter</a></strong></div><div>“@ethstatus Getting this all the time. Any idea why?”</div></blockquote>

**Comment by chadyj** [comment] 2018-12-06 17:42
Shortly after the release we saw reports of an "unknown status-go error" from 3 users upgrading to 0.9.32.  After investigating @Serhy could reproduce the issue for account passwords that contained a special character (such as -/:;()$&@“.,?!’[]{}#%^*+=_\|~<>€£¥•.,?!’) and it was discovered that passwords may not be escaped properly in some circumstances.  @cammellos is working on a hotfix which we are aiming to release within the next hour.

**Comment by naghdy** [comment] 2018-12-06 17:55
Thanks @cammellos and @Serhy for working on and finding this issue. Can I please suggest we create post-mortem on this, so that we can understand how this slipped through and ensure this kind of error doesn't slip into future releases. The template can be found in this Discuss post: https://discuss.status.im/t/post-mortems-learning-from-our-mistakes/581

<blockquote><img src="https://discuss.status.im/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/post-mortems-learning-from-our-mistakes/581">Post-Mortems: Learning from our mistakes</a></strong></div><div>Our recent TestFairy blunder has shed some light on a scary reality. As an organisation, we are not ready for primetime. Incidents like this at scale damages reputation, for the most part, beyond repair.  Using 3P services has been a known concern for months now. However what is most surprising about this incident, is that this is the second time a bug in TestFairy has caused seed phrases to be leaked. Making the same mistake twice, especially for an organisation so focused on Security and Priva...</div></blockquote>

**Comment by jbostick00** [comment] 2018-12-06 18:51
This happened to me and my password does have a special character.

I downloaded version 0.9.32 to my iPhone and I was getting pink bubble appearing above my password when I entered it to launch the app and the bubble said, "Unkown Status-go error"  So I deleted the app and reloaded it.  But now when I enter my Recovery Phrase and Password then hit "Sign In" nothing happens except the Seed Phrase and password entry bubbles are blanked out.  I entered my seed phrase multiple times.  Now I can't get on status to get help.  So that is why I am posting here.

That was my experience.  Looking forward to the hot fix.  Thanks all

**Comment by chadyj** [comment] 2018-12-06 20:15
Update: A fix to this issue has been made and we are currently building and testing the changes.  If all goes well a hotfix will be released in the next 1-2 hours.  A post-mortem will also be published.

@jbostick00 Thanks for the feedback. Hang tight a fix is on its way.

**Comment by chadyj** [comment] 2018-12-06 20:48
@mandrigin @jakubgs @rasom We could use some help. The iOS upload job keeps failing.  @cammellos Has the fix but we can't publish.

> Failed to download from DigitalOcean Bucket, checking GitHub...
> Failed to download from GitHub!
> ......
> ......
> unzip:  cannot find zipfile directory in one of modules/react-native-status/ios/RCTStatus/status-go-ios-0.16.14.zip or
>         modules/react-native-status/ios/RCTStatus/status-go-ios-0.16.14.zip.zip, and cannot find modules/react-native-status/ios/RCTStatus/status-go-ios-0.16.14.zip.ZIP, period.

https://ci.status.im/job/status-react/job/upload_release_ios/65/console

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/upload_release_ios/65/console">status-react » upload_release_ios #65 Console [Jenkins]</a></strong></div></blockquote>

**Comment by cammellos** [comment] 2018-12-06 20:51
Just to add some context, the build is not on DO but it is on github, the link for ios is correct, it either times out or there's some other issue

**Comment by jakubgs** [comment] 2018-12-06 20:52
>End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found onss the last disk(s) of this archive.

It seems like the zip is corrupted, but I downloaded it by hand and it unpacks just fine.

**Comment by jakubgs** [comment] 2018-12-06 20:53
I started a build to upload that again, let's see if that helps:
https://ci.status.im/job/status-go/job/parallel/169/

Edit: Just started it with the right branch and `RELEASE` checked: https://ci.status.im/job/status-go/job/parallel/169/parameters/

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-go/job/parallel/169/">status-go » parallel #169 [Jenkins]</a></strong></div></blockquote>

**Comment by cammellos** [comment] 2018-12-06 20:53
@jakubgs I think it just fails to download it
"unzip: cannot find zipfile directory i"

**Comment by cammellos** [comment] 2018-12-06 20:54
I can download it locally fine and already an ios build has been successfuly built using that zip file 

https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/

https://ci.status.im/job/status-react/job/combined/job/mobile-ios/4877/consoleFull

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/release/job/release%252F0.9.32/">release/0.9.32 [status-react » release] [Jenkins]</a></strong></div></blockquote>

**Comment by jakubgs** [comment] 2018-12-06 20:57
This one seems to be running just fine: https://ci.status.im/job/status-react/job/upload_release_ios/66/

![tiresome](https://user-images.githubusercontent.com/2212681/49611517-0e9d2d00-f9a2-11e8-85ae-70156817ead7.png)

<blockquote><img src="/static/e7749a62/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/upload_release_ios/66/">status-react » upload_release_ios #66 [Jenkins]</a></strong></div></blockquote>

**Comment by cammellos** [comment] 2018-12-06 20:57
yes, it managed to download, thanks

**Comment by chadyj** [comment] 2018-12-06 21:44
The hot fix has been published.
iOS build 2018120621 and Android build 2018120619 are now live.

Kudos team for working late to get this sorted.

The post-mortem draft has started here https://notes.status.im/U7gkLuCiSly3faDXKzRbmQ

@pablanopete Please let us know here if there are any more issues that pop up over night.

<blockquote><div><strong><a href="https://notes.status.im/U7gkLuCiSly3faDXKzRbmQ">06/12/18 Post-mortem - CodiMD</a></strong></div></blockquote>

**Closed as completed by chadyj** 2018-12-06 21:44 UTC

**Comment by jbostick00** [comment] 2018-12-06 21:46
Thanks all

**Comment by rachelhamlin** [comment] 2018-12-07 10:02
Hey @chadyj @annadanchenko @cammellos - both Ben & I are still getting this status-go error. We've just updated to 0.9.32 now.

**Comment by cammellos** [comment] 2018-12-07 10:11
@rachelhamlin looking into this, pinged you on status with a few questions
