### ISSUE TITLE
Double pressing a button to open a modal screen, opens twice

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15373] opened 2023-03-16 05:08 UTC
On Android, trying to press any button twice that would open a modal screen (like activity-center bell), would open the screen twice.

**Comment by flexsurfer** [comment] 2023-03-16 09:44
i would say its a global issues ,not only Android or Modal screens, each time when js thread is slow you will be able to press button twice or more times

**Comment by churik** [comment] 2024-06-20 12:43
I cannot reproduce it now if app is working fine, I suppose it is reproducible only when app is becoming slow (under some circumstances), so adding it to `Performance`

Not sure though that it can be fixed globally, feel free to close it if it doesn't make sense

**Comment by flexsurfer** [comment] 2024-06-20 15:55
it's already fixed https://github.com/status-im/status-mobile/pull/18478

**Closed as completed by flexsurfer** 2024-06-20 15:55 UTC
Labels: performance, mobile-core
