### ISSUE TITLE
Show a warning when the contact is on a different network

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#4208] opened 2018-05-10 23:15 UTC
# Problem

When users are a different network, there can be confusion regarding transaction request and transaction send commands.

related issue: https://github.com/status-im/status-react/issues/4185

# Solution

 We should show a warning to the user and disable these commands for contacts that are on different networks.

**Comment by chadyj** [comment] 2018-05-11 08:24
Dupe of https://github.com/status-im/status-react/issues/4171 ?

**Comment by dmitryn** [comment] 2018-05-15 14:20
Closing as seems duplicate of https://github.com/status-im/status-react/issues/4171

**Closed as completed by dmitryn** 2018-05-15 14:20 UTC
