### ISSUE TITLE
Composer overlaps status top bar when adding image to fully expanded composer (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17842] opened 2023-11-07 12:57 UTC
Reproducing on Android 12, Samsung Galaxy A52

### NOTE (Please also test)
- https://github.com/status-im/status-mobile/issues/18234
- https://github.com/status-im/status-mobile/issues/18236
- https://github.com/status-im/status-mobile/issues/18536

**Steps:** 

1. Open any chat
2. Paste a long multiline message to fully expand the composer
3. Add an image into composer
4. Pay attention at the top of the composer

**Actual result:** composer overlaps status top bar. Composer is fixed after user starts text editing. 

https://github.com/status-im/status-mobile/assets/97245802/2a7c23d1-10e1-4495-b1e7-4d768700cf0b

**Expected result:** composer does not overlap status top bar

### Additional Information

- Status version: nightly 
- Operating System: Android

**Comment by ibrkhalil** [comment] 2023-11-11 14:01
https://github.com/status-im/status-mobile/assets/33176106/da4e5432-1d7b-4177-aaff-0bd5d12b48a6

The initial solution will make the composer be behind the topbar, But the lines at the beginning won't be visible if it's maximized, Is that okay?

**Comment by ibrkhalil** [comment] 2023-11-13 10:04
Should composer's maximum height never reach the topbar?

**Comment by pavloburykh** [comment] 2023-11-13 10:49
> The initial solution will make the composer be behind the topbar, But the lines at the beginning won't be visible if it's maximized, Is that okay?

Hi @ibrkhalil! This solution does not look correct to me. This is how maximised composer should look like after adding images into it. 

![photo_2023-11-13 12 37 52](https://github.com/status-im/status-mobile/assets/97245802/2c4a9f00-dea7-44e1-8479-3f7b0fd0d303)

@ibrkhalil I have updated the description with video, because it has not been uploaded for some reason when I logged this issue. 

Also I have just tried to reproduce the issue in latest nightly but I failed. So please, hold on with this issue for now until we verify if it still exists.

**Comment by ibrkhalil** [comment] 2023-11-13 11:21
> > The initial solution will make the composer be behind the topbar, But the lines at the beginning won't be visible if it's maximized, Is that okay?
> 
> Hi @ibrkhalil! This solution does not look correct to me. This is how maximised composer should look like after adding images into it.
> 
> ![photo_2023-11-13 12 37 52](https://user-images.githubusercontent.com/97245802/282436647-2c4a9f00-dea7-44e1-8479-3f7b0fd0d303.jpeg)
> 
> @ibrkhalil I have updated the description with video, because it has not been uploaded for some reason when I logged this issue.
> 
> Also I have just tried to reproduce the issue in latest nightly but I failed. So please, hold on with this issue for now until we verify if it still exists.

Thanks Pavlo!
Please mention/ping me if it still exists
In the meantime I'll unassign myself to focus on other things.

**Comment by ibrkhalil** [comment] 2023-12-17 14:03
@pavloburykh Is this still relevant?

**Comment by ibrkhalil** [comment] 2023-12-23 10:09
Couldn't reproduce it on the Pixel 6 emulator
![Screenshot_20231223_120921](https://github.com/status-im/status-mobile/assets/33176106/088e8b8c-20fb-4d31-8f5a-1a873770878f)

**Comment by Parveshdhull** [comment] 2024-01-19 13:10
Hi, I am unable to reproduce this issue.
I am unassigning myself if anyone else wants to look into this. Otherwise, hopefully, it will be fixed as a side product of refactoring.

**Comment by pavloburykh** [comment] 2024-01-19 13:31
@Parveshdhull hi! Thank you for looking at this issue. 

Could you please try with some new steps:

**Steps:** 

1. Open any chat
2. Paste a long multiline message to fully expand the composer
3. Add an image/images into composer
4. **Fold down the composer**
5. **Close the chat**
6. **Re-open chat**
7. See if opened composer does not overlap status bar

**Actual result:** composer overlaps status top bar. Composer is fixed after user starts text editing. Issue might not be reproducible from the first time, couple of re-openings might be required (check the video below)


https://github.com/status-im/status-mobile/assets/97245802/6522b7ca-c8b8-4909-8dc4-4aaeb1b01176

**Comment by Parveshdhull** [comment] 2024-01-19 13:44
Hi, I tried multiple times. But it always works for me

https://github.com/status-im/status-mobile/assets/17097240/de12816e-c36f-4a10-9b97-0cde72b21783

But from your video, it seems cause of this issue is the space between keyboard and send button(which pushes content over status bar), as in https://github.com/status-im/status-mobile/issues/18234 cc @VolodLytvynenko

Also it looks like, It happens randomly and probably also depends on device we are using for testing.

I am not sure what's the root cause here, if anyone wants to explore.

Otherwise hopefully this issue might get fixed, while [optimizing](https://github.com/status-im/status-mobile/issues/18137) composer.
(Might be related to how keyboard avoiding view, or calculations of position/height of composer works)

**Comment by Parveshdhull** [comment] 2024-01-19 14:04
Hi, apparently multiple issues were caused by same bug (space between keyboard and composer).

I closed others, as this one is oldest and has research history and single issue is easier to track.
Also updated the description of current issue, to make sure we test all scenario in relevant/future PR.

> NOTE (Please also test)
> https://github.com/status-im/status-mobile/issues/18234
> https://github.com/status-im/status-mobile/issues/18236
> https://github.com/status-im/status-mobile/issues/18536

Thank you @pavloburykh, @VolodLytvynenko, @mariia-skrypnyk.

**Comment by pavloburykh** [comment] 2024-01-19 14:07
Thank you @Parveshdhull!

**Comment by pavloburykh** [comment] 2024-03-15 17:09
@Parveshdhull I am still reproducing the issue with this [steps](https://github.com/status-im/status-mobile/issues/17842#issuecomment-1900432055) so I will keep it open in order someone can pick it up. Thank you for your efforts on investigation of this problem @Parveshdhull

**Comment by churik** [comment] 2024-06-21 11:57
Not reproducible anymore on nightly 21/06/24 (Google Pixel7)

Please, reopen if still relevant

**Closed as completed by churik** 2024-06-21 11:57 UTC
Labels: android, messaging, chat-composer, chat
