### ISSUE TITLE
Allow both release and develop version to coexist

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2998] opened 2018-01-11 08:39 UTC
### User Story

As a developer, I want to have both release and developer version running at the same time on android.

### Description

Currently both versions share same identifier preventing to keep the released version installed.

*Type*: Feature

**Comment by status-open-bounty** [comment] 2018-01-11 08:46
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xcdc5efe1eaa92ab61a785dabb4c7f2201841c55d3271f7265effe31371081266](https://etherscan.io/tx/0xcdc5efe1eaa92ab61a785dabb4c7f2201841c55d3271f7265effe31371081266)

**Comment by pacamara** [comment] 2018-01-20 00:25
@jeluard Hi, here's a fix for this issue: https://github.com/status-im/status-react/pull/3098 :beers:

**Comment by oskarth** [comment] 2018-02-12 10:30
@andytudhope Seems like the issue is harder than we initially thought, can we make this a medium bounty?

**Comment by debragail** [comment] 2018-04-26 02:55
https://developer.android.com/training/articles/user-data-ids

<blockquote><img src="https://developer.android.com/_static/b0b5dc6d7e/images/android/favicon.png" width="48" align="right"><div>Android Developers</div><div><strong><a href="https://irina-redesign.android.com/training/articles/user-data-ids">Best practices for unique identifiers  |  Android Developers</a></strong></div></blockquote>

**Closed as completed** 2018-05-08 11:23 UTC
Labels: android
