### ISSUE TITLE
Error Cannot access member 'sliderValue' of null [develop]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2170] opened 2017-10-16 15:04 UTC
### Description

*Type*: Bug

*Summary*: `Error Cannot access member 'sliderValue' of null` shown in 1x1 chat under Rinkeby network

#### Actual behavior
[comment]: # (Describe what actually happened.)
![image](https://user-images.githubusercontent.com/28752642/31619038-474cc1cc-b29c-11e7-8a8a-4cff9bc42fdd.png)

### Reproduction
- Open Status under Rinkeby network
- Send transaction in 1x1 chat and receive error with slider

### Additional Information
* Status version:  0.9.10-238-g82363020+ (1795)
* Operating System: Android

#### Logs
* https://app.testfairy.com/projects/4803622-status/builds/6867790/sessions/10/?accessToken=13EnNt42eonIttOu0y6zTTavdgw

**Comment by rasom** [comment] 2017-10-16 20:35
@asemiankevich do you test this while network is not synced?

**Comment by rasom** [comment] 2017-10-16 20:37
duplicate of #2099 anyway

**Closed as completed** 2017-10-16 20:37 UTC
