### ISSUE TITLE
Start a new chat on search

### ISSUE THREAD

**Issue by decanus** [status-im/status-react#10890] opened 2020-06-29 21:39 UTC
# Feature Issue

An intuitive design for starting a chat with a user is to search for their name. Currently the search bar does not handle this case. When I search for a user who I do not have a chat started with I should be presented with a button that allows me to start a new chat. 

![image](https://user-images.githubusercontent.com/7621705/86058725-a0c3c500-ba61-11ea-9300-5c1abf30b132.png)

### User Story

As a user, I want to be presented with a option to start a new chat if I search for someone I do not have a conversation started with. 

### Notes

For examples, see telegram.

**Comment by hesterbruikman** [comment] 2020-06-30 08:16
@decanus do you mean search the ENS registry? @flexsurfer @andremedeiros can you think of a reason we do not have this yet? We basically use the same functionality when registering a name, correct?

cc @errorists

**Comment by decanus** [comment] 2020-06-30 08:37
It should probably work with public keys too @hesterbruikman my main point was that the UI should be bridged for minimal effort. I should be able to start a chat through search.

**Comment by errorists** [comment] 2020-06-30 08:49
ok I admit i had to read it a couple times to 'get' it's the chat list search bar we're talking about :) thanks, yea I believe adding relevant suggestions to the empty state here could be a worthwhile improvement

<img width="522" alt="Screenshot 2020-06-30 at 10 47 34" src="https://user-images.githubusercontent.com/4932774/86105029-1d38c100-babf-11ea-884c-d549bc51c01c.png">

**Comment by flexsurfer** [comment] 2020-06-30 09:00
yeah i also always trying to create new chat in search :)

**Comment by decanus** [comment] 2020-06-30 10:15
@errorists sorry, my description may have not been the best, it was late in the evening. Glad we are on the same page however.

**Comment by hesterbruikman** [comment] 2020-08-05 10:41
Partial solution implemented: https://github.com/status-im/status-react/commit/8652f899e02f3962dd61ed202a0eeab018b9b90d

~~Doesn't resolve non-stateofus.eth names. Leaving the issue open~~

Not sure how this could be handled for non-stateofus.eth names as I believe we wouldn't know if they have a chat key connected. Issue needs investigation if this is feasible, if not, issue can be closed

**Comment by Ferossgp** [comment] 2020-08-05 14:11
@hesterbruikman the merged solution handles all cases which are handled by the `new chat` screen. I think this issue should be closed as it is a duplicate of https://github.com/status-im/status-react/issues/10988

**Comment by churik** [comment] 2020-08-05 14:14
it is done, agree

**Comment by churik** [comment] 2020-08-05 14:15
Closed and removed from https://docs.google.com/spreadsheets/d/1YPRb-JVSgIOyeEcRKXA5k1N1yaKE1-UdCbXnQcmjSzg/edit#gid=1370845310

**Closed as completed by churik** 2020-08-05 14:15 UTC
