### ISSUE TITLE
Profile QR code encodes universal link to user profile instead of pure public key

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6348] opened 2018-10-16 15:52 UTC
***Type***: Bug

*Summary*: Profile QR code encodes a universal link to user profile instead of the pure public key. Trying to scan QR code from user profile page when adding a new contact - results in 'Incorrect public key' message 

#### Expected behavior
Profile QR code encodes public key

#### Actual behavior
Profile QR code encodes universal link to user profile page
E.g. of the profile QR code that encodes universal link: 
<img width="291" alt="screen shot 2018-10-16 at 18 51 13" src="https://user-images.githubusercontent.com/8749671/47029559-84400600-d174-11e8-82b3-0458a6a690ec.png">

### Reproduction
- Open Status and create new account on Device1 (Contact1)
- Open Status and create new account on Device2
- Try to add Contact1 by account created in Device2 (or scan QR with any other app to get the data profile QR code holds in it)

### Additional Information
* Status version: `Develop 0.9.30 (10659)`
* Operating System: Android and iOS

**Comment by chadyj** [comment] 2018-10-16 18:06
Dupe of https://github.com/status-im/status-react/issues/6347 ?

**Comment by lukaszfryc** [comment] 2018-10-17 07:33
yes it is. Closing this one.

**Closed as completed by lukaszfryc** 2018-10-17 07:33 UTC
