### ISSUE TITLE
Message input: issues, mentions

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14362] opened 2022-11-14 17:09 UTC
This is a list of some input field bugs. 

### ISSUE 1 (Android only) Mention list is not shown after typing @

**Steps:**

1. Type @ symbol in the input field
2. See if mention list is shown

**Actual result:** Mention list is not shown

**Expected result:** Mention list appears after typing @

https://user-images.githubusercontent.com/97245802/201714486-a293ae8b-e706-413a-ac26-34452ca593d3.mp4

### ISSUE 2 (Android only) Input field expands to the full heights of the screen after clearing it

**Steps:** 
1. Type some text in the input field
2. Clear text in the input field
3. Observe the result

**Actual result:** input field expands to the full heights of the screen when the keyboard is active

**Expected result:** input field preserves it's original size

https://user-images.githubusercontent.com/97245802/201713244-48d305ea-cf53-4b58-916c-d477262db0a0.mp4

### ISSUE 3 (Android/IOS) Input field containing multiline message scales down when closing keyboard

**Steps:** 

1. Type some multiline message in the input field
2. Close the keyboard
3. Observe the behaviour of the input field

**Actual result:** Input field scales down, the message becomes invisible (only first 2 lines are partially visible). Overall, manual expanding/collapsing of the input field does not work smoothly which is resulting in poor user experience.  

**IOS**

https://user-images.githubusercontent.com/97245802/201721675-7b3c5a6b-031a-4a13-8771-963407b8b26d.mp4

**Android**

https://user-images.githubusercontent.com/97245802/201721583-28fa4c82-19e3-4248-98d0-a4e420d854dd.mp4

### ISSUE 4 The messages and contact requests are not shown if one of the device change his time within settings

**Steps:** 
1. Send contact request as USER_A to USER_B
2. Accept the request
3. Create any chat (1-1, group, public, community)
4.  Change time to +1 within the settings of your device using USER_A
5. Send a message to USER_B in any created chat
6. Send contact request to USER_C

**Actual result:**
- USER_A and USER_B don't see each other messages after the time is changed within device settings
- USER_C does not see a contact request of USER_A

**Expected result:**
- Users see messages and contact requests of each other even if the time for a particular device is changed

**OS** Both Android and IOS

**Comment by churik** [comment] 2022-11-14 17:48
Mention designs depending on scroll position are here: https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=5286%3A528699&t=m26RYsptjuPkKMN1-4

**Comment by churik** [comment] 2022-11-24 14:41
from #14432 
The chat sheet should expand as the user types new lines. It no longer does that as of today.

https://user-images.githubusercontent.com/65834069/203697970-f3626d7a-8b09-4189-b237-525a81c42c9b.mp4

**Comment by ibrkhalil** [comment] 2022-11-27 07:15
Issue one was resolved by
https://github.com/status-im/status-mobile/pull/14442
UPDATE:
I was able to reproduce again .. Working on it
UPDATE:
Turns out the fix I did only worked for iOS .. I applied it to Android too

**Comment by ibrkhalil** [comment] 2022-11-28 14:25
Can we add this issue too ?
Selection a mention doesn't autocomplete the selected user's name in the chat input
https://user-images.githubusercontent.com/33176106/204301802-e4f81c79-fa0d-4e30-84ea-9f095a228352.mp4

**Comment by ibrkhalil** [comment] 2022-11-29 19:25
> Can we add this issue too ? Selection a mention doesn't autocomplete the selected user's name in the chat input https://user-images.githubusercontent.com/33176106/204301802-e4f81c79-fa0d-4e30-84ea-9f095a228352.mp4

Fixed, Thanks @flexsurfer

**Comment by ibrkhalil** [comment] 2022-11-29 19:30
> from #14432 The chat sheet should expand as the user types new lines. It no longer does that as of today.
> 
>  22-11-23-22-58-10.mp4


https://user-images.githubusercontent.com/33176106/204629767-8f08be3d-31f7-49c9-ba50-efa7e11dc13b.mp4

**Comment by ibrkhalil** [comment] 2022-12-03 10:25
@pavloburykh Can you please test the first three issues, I started working on the fourth today .. I just want to check if I can improve on the older ones ?

**Comment by ibrkhalil** [comment] 2022-12-04 10:21
@pavloburykh I tried to reproduce the timezone issue and I couldn't

**Comment by flexsurfer** [comment] 2022-12-06 12:37
hey @pavloburykh im not sure how ISSUE 4 related to input field ?

**Comment by pavloburykh** [comment] 2022-12-06 12:43
> hey @pavloburykh im not sure how ISSUE 4 related to input field ?

This one has been logged by @VladimrLitvinenko I guess, it should be logged separately if still reproducible in latest nightly. @VladimrLitvinenko

**Closed as completed** 2022-12-15 09:49 UTC
Labels: messaging
