### ISSUE TITLE
Handling cases when wrong card is tapped

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10791] opened 2020-06-09 14:41 UTC
# Feature Issue

Currently, cases when wrong card is tapped at attempt to long, sign transaction, change PIN and other flows are not consistent and can cause bugs.

### User Story

As a user, I want to see nice error if I'm using wrong card and want to be able to continue working with app after tapping valid keycard.

### Case 1: Wrong card on login or on send transaction flow
Endless "Processing", can continue if tap valid  card which corresponds multiaccount

### Case 2: Wrong card during account creation \ pairing
Tried wrong card on stage of back up seed phrase (so last stage) , after tapping invalid card got
endless "Processing", can't proceed with valid card even after restarting application (endless Processing)
Logs: [Status-debug-logs-10.zip](https://github.com/status-im/status-react/files/4753171/Status-debug-logs-10.zip)
**No workaround in this case**

### Case 3: Wrong card on changing PIN or on adding new account in wallet
![ezgif com-video-to-gif (21)](https://user-images.githubusercontent.com/4557972/84161828-fd8a1c00-aa6f-11ea-9a6d-36e54084cff1.gif)
After tapping wrong card
- can't enter right pin
- if close this screen and open "Send transaction" screen - still can't enter PIN code.
**Workaround:** go back to "Change passcode" and finish the process with valid card

#### Acceptance criteria
In all cases can see error, can close it, tap valid card and proceed

**Comment by churik** [comment] 2020-07-03 15:10
cc @guylouis @hesterbruikman

**Comment by guylouis** [comment] 2021-05-27 08:34
@churik  @qoqobolo 
this one would deserve to be tested again, since @bitgamma fixed some of these situations, to know if some cases are still present and need to be fixed

**Comment by qoqobolo** [comment] 2021-05-27 15:10
@guylouis some of these cases are still reproducible, although they look different now. E.g. in most cases, the error text is shown but overlaid by another element.
So this does not need to be urgently fixed. Also, we can consider them as edge cases, so feel free to close the issue. 

https://user-images.githubusercontent.com/67952253/119850579-f886dc80-bf0d-11eb-8791-0fc80d235346.mp4

https://user-images.githubusercontent.com/67952253/119850635-03da0800-bf0e-11eb-950f-dbd85251be59.mp4

**Closed as completed** 2021-07-27 10:29 UTC
