### ISSUE TITLE
Data randomly remains in composer after sending a message

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18172] opened 2023-12-13 16:49 UTC
Unfortunately, there are no precise steps to consistently reproduce this issue. It occurs randomly.

### Steps:
1. Paste text and a link into the composer.
2. Quickly start entering any data
3. Quickly tap "send" button
4. Check the result.

### Actual result:
The link persists and continues to be displayed in the composer area after the message sending

https://github.com/status-im/status-mobile/assets/52490791/44e391c8-b0e8-439d-a0e5-c389cafec97f

### Expected result:
The link is not shown in the composer after the message sending

### Devices:
- iPhone 11 Pro Max, IOS 16
- Pixel 7a, Android 14

### Logs:
[Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13663482/Status-debug-logs.zip)

### ENV:
- Nightly [13 Dec 2023]

**Comment by churik** [comment] 2024-06-21 12:09
still the case unfortunately, sometimes can see it on IOS

**Comment by ilmotta** [comment] 2024-07-05 01:25
Let's wait and see the outcome of designer's review of PR https://github.com/status-im/status-mobile/pull/20125 and then revisit this issue armed with more information. Because we may be able to remove a lot of code complexity from the composer, maybe this issue will be fixed automatically as a bonus.

**Comment by ulisesmac** [comment] 2024-09-11 21:56
@flexsurfer  is this issue still reproducible?

**Comment by flexsurfer** [comment] 2024-09-12 05:18
It is better to ask @VolodLytvynenko

**Comment by VolodLytvynenko** [comment] 2024-09-12 09:31
hi @flexsurfer @ulisesmac  yes. Still reproducible. I can reproduce it on the Pixel 7a, Android 14 using the new simplified composer.
Here is the data [data.txt](https://github.com/user-attachments/files/16976898/data.txt) I use as predefined in the composer. Steps are the same as described here https://github.com/status-im/status-mobile/issues/18172#issue-2040111107

https://github.com/user-attachments/assets/8dd673ce-821d-43f1-96af-e7f489da8670

### logs:
[Status-debug-logs.zip](https://github.com/user-attachments/files/16976876/Status-debug-logs.zip)

**Comment by flexsurfer** [comment] 2024-09-12 09:44
thank you, i'll take a look

**Comment by flexsurfer** [comment] 2024-09-13 09:13
@VolodLytvynenko i couldn't reproduce it, try this one https://github.com/status-im/status-mobile/pull/21262 please, thanks

**Closed as completed** 2024-09-13 12:14 UTC
Labels: messaging, chat-composer, mobile-core
