### ISSUE TITLE
Blank drawer appears after user taps on Trash icon on the Key pair account screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19830] opened 2024-04-29 12:03 UTC
# Bug Report

#### Expected behavior
<img width="338" alt="Screenshot 2024-04-29 at 13 47 29" src="https://github.com/status-im/status-mobile/assets/147824399/566593bc-e5da-41fa-a68e-4a5ef8abcdae">

https://www.figma.com/file/xLs1KYmF4e6WwRTZVJKeUK/Descoped-Wallet?type=design&node-id=900-234771&mode=design&t=UKGKyv3q8EgpsqTY-0

#### Actual behavior

https://github.com/status-im/status-mobile/assets/147824399/f19762be-534f-4e6c-94a7-5c4b9b161606

### Reproduction

1. Login to app
2. Go to `Wallet` -> Create `New Wallet Account`
3. Tap on `Edit` Key pair
4. Tap on `+` to create New Key pair account
5. Open created Key pair account
6. Tap on `Trash Icon`

### Additional Information

- Status version: nightly 28/04
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by VolodLytvynenko** [comment] 2024-04-30 07:00
Duplicate of https://github.com/status-im/status-mobile/issues/19375

**Closed as completed by VolodLytvynenko** 2024-04-30 07:00 UTC
