### ISSUE TITLE
User can't log in with biometrics anymore after logging out

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#18004] opened 2023-11-27 12:22 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)
Currently if the user logs out (through settings) from their account that has biometrics enabled, they can't use biometrics to login again nor can they enable it from the settings. The enabling from the settings would come with Settings V2, but the user should still be able to use biometrics after they log out or switch accounts. ATM all biometry information is erased during logout (auth-method & password) from the keychain.

#### Expected behavior
The user can log-out and log in again using biometrics. I guess the user shouldn't be prompted with the biometrics check right after logging out, but when the app is opened again biometrics should be prompted.

#### Actual behavior
The user can't log in with biometrics ever again after logging out

### Reproduction

1. Create account with biometrics
2. Go to profile -> Log out -> Confirm
3. Can only log in with password, even after closing the app and opening again

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment] 2024-01-09 05:37
hi @clauxx, will https://github.com/status-im/status-mobile/pull/18258 solve this issue? Or these are separate issues?

**Comment by clauxx** [comment] 2024-01-09 07:32
Hi @yqrashawn, it doesn't solve it, but we decided to put a hold on it for now as we don't have a defined flow for handling biometrics during the logout phase. The issue you mentioned allows to re-enable it from the settings, which helps a bit until we have a flow.

**Comment by clauxx** [comment] 2024-04-05 14:52
As discussed during the crew sync _(Usability and readiness for public beta)_, should discuss the flow with the design team and prioritize this task accordingly. If the flow would become overly complex, should be removed from the scope of this release.

During the sync we discussed two potential options: 
1. keeping the biometric data in the keychain when logging out (without triggering the automatic biometric check on the login screen)
2. keeping the biometric data, but disabling biometrics until the user logs in again, after which the biometric check will be available again.

**Comment by clauxx** [comment] 2024-04-18 07:49
After discussing with @John-44, we decided to go with the 1st option to avoid user friction.

**Comment by cammellos** [comment] 2024-04-30 08:36
Removing this from 2.29 as we might not have enough time to implement cc @clauxx

**Comment by clauxx** [comment] 2024-04-30 08:39
@cammellos Yeah makes sense :+1:

**Comment by mariia-skrypnyk** [comment] 2024-09-06 12:05
We received a feedback https://discord.com/channels/1210237582470807632/1260272291888107520/1280732358730977291 from our user regarding switching accounts and that no biometrics is ON after it.

Here is a discussion https://discord.com/channels/1210237582470807632/1217173176086302821/1280855001488560170

So the issue is still relevant.

**Comment by ilmotta** [comment] 2024-10-04 02:31
This is the new UX for improving how users login with biometrics https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=14657-26209&node-type=instance&m=dev.

@xAlisher is the UX & UI approved in that Figma link? For context, with the new keycard flows I was told only the UX was approved, not the UI, so from now on I'll try to ask for both to prevent communication issues 🙂

Once UX/UI are approved I'll create a feature issue, link to this bug issue and once the feature is implemented this bug will be nicely resolved by proxy.

**Comment by xAlisher** [comment] 2024-10-08 09:19
@ilmotta it's approved by @pedro-et

**Comment by ulisesmac** [comment] 2024-10-12 00:45
@xAlisher @ilmotta 

Which one is exactly is the flow approved?

 is it the one with the folllowing header:

![Image](https://github.com/user-attachments/assets/ef95aa8d-0814-47c3-a9f9-5eb73328d03f)
[LINK](https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=14656-26145&m=dev)

or the whole file?

**Comment by ilmotta** [comment] 2024-10-15 05:27
Correct @ulisesmac, only the top flow is approved https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=14656-26145&node-type=shape_with_text&m=dev. It's the simplest one for now. Basically, the idea is to allow the user to switch profiles by logging out, but with difference that the user is redirected to the profile selection screen instead of going to the last profile auth screen.

**Comment by ulisesmac** [comment] 2024-10-16 19:53
@ilmotta I'm taking this issue but I'll start it when we plan it

**Comment by ilmotta** [comment] 2024-10-21 19:45
> [@ilmotta](https://github.com/ilmotta) I'm taking this issue but I'll start it when we plan it

Thank you @ulisesmac 👍🏼 I created a new _feature_ issue which supersedes this one https://github.com/status-im/status-mobile/issues/21476. The issue will be part of an epic to simplify onboarding flows for 2.32. Based on the user feedback we got, we decided to improve the solution instead of just doing a quick bug fix.

**Closed as completed by ilmotta** 2024-10-21 19:45 UTC
Labels: onboarding, mobile-core
