### ISSUE TITLE
Starter pack icons are not shown in 1-1 chat on "Accept" button in dark mode

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11257] opened 2020-10-02 07:35 UTC
# Bug Report

## Problem

In a dark mode after redirecting to 1-1 chat when you proceeding referral link no icons are shown

![photo_2020-09-28_16 10 24](https://user-images.githubusercontent.com/4557972/94898813-78999700-0492-11eb-8711-cd49faf04d7e.jpeg)

**Comment by Ferossgp** [comment] 2020-12-08 07:38
@churik debugging the issue and seems like the problem is that data wasn't loaded from the contract and not related to dark mode.

**Comment by flexsurfer** [comment] 2021-01-12 13:20
@churik is this still relevant?

**Comment by churik** [comment] 2021-01-12 13:43
@Serhy  has more experience in starter pack testing, maybe he is aware

**Comment by flexsurfer** [comment] 2021-01-20 12:30
@Serhy ?

**Comment by Serhy** [comment] 2021-01-20 15:18
> @churik debugging the issue and seems like the problem is that data wasn't loaded from the contract and not related to dark mode.

This is a correct answer. If contract for starter pack distribution which is called was empty then there is no icons (this data pulled from contract).
I've checked in test network and icons are visible:

<img width="252" alt="Screenshot 2021-01-20 at 17 16 29" src="https://user-images.githubusercontent.com/8749671/105195647-80fe0680-5b43-11eb-8350-0572ec96e5f1.png">

Closing this issue

**Closed as completed by Serhy** 2021-01-20 15:18 UTC
