### ISSUE TITLE
Android debug app crashes on hot reloading

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15808] opened 2023-05-04 07:59 UTC
That issue happens even when `FastRefresh` is disabled.

**Comment by OmarBasem** [comment] 2023-05-04 08:33
Also tried building app with hermes disabled, same result

**Comment by Parveshdhull** [comment] 2023-05-05 09:53
Please share more details
1. Is this happens after every code change or after few instances
> `Android Emulator crashes on code changes`
2. Just to be sure, complete emulator crashes not the app?
3. Any useful android or metro logs?
4. Please attach a video if possible

**Comment by OmarBasem** [comment] 2023-05-08 06:02
Hi @Parveshdhull, 
1. Yes this happens on every code change. 
2. The app crashes.
3. It crashes with no errors.

I will try to attach a video.

**Comment by Parveshdhull** [comment] 2023-05-08 07:37
Please also attach adb logs at the time of crash,
`adb logcat --buffer=crash`

**Comment by OmarBasem** [comment] 2023-05-11 11:53
@Parveshdhull nothing seems to print when I use that command

**Comment by Parveshdhull** [comment] 2023-05-11 12:32
Working configuration of emulator
```
Name: Pixel_5_API_30
CPU/ABI: Google APIs Intel Atom (x86)
Path: /home/parvesh_monu/.android/avd/Pixel_5_API_30.avd
Target: google_apis [Google APIs] (API level 30)
Skin: pixel_4
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_5
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 30
tag.id: google_apis
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Pixel 5 API 30
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 2340
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-30/google_apis/x86/
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Pixel_5_API_30
hw.lcd.density: 440
hw.arc: false
hw.device.hash2: MD5:3274126e0242a0d86339850416b0ce34
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
disk.dataPartition.size: 6442450944
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

**Comment by Parveshdhull** [comment] 2023-06-12 15:55
hi @OmarBasem, any update on this? Issue still happening?

**Comment by OmarBasem** [comment] 2023-06-12 18:30
@Parveshdhull never tried using emulator again :)

**Comment by Parveshdhull** [comment] 2023-06-21 21:21
Related discussion: https://discord.com/channels/1103692771585433630/1103692773363810317/1120672571126448198
Related question: https://stackoverflow.com/questions/76509778/how-to-add-delays-between-shadow-cljs-auto-builds

**Comment by Parveshdhull** [comment] 2023-06-21 21:23
> Related discussion: https://discord.com/channels/1103692771585433630/1103692773363810317/1120672571126448198 Related question: https://stackoverflow.com/questions/76509778/how-to-add-delays-between-shadow-cljs-auto-builds

Even if I try to avoid collision between hot reloading and force rendering by increasing gap between refreshes, app crashes after some refreshes with below error. Not sure if error is caused by same problem.

![error](https://github.com/status-im/status-mobile/assets/17097240/044d53aa-1ff1-43fe-949c-fd4bdefad959)

**Comment by cammellos** [comment] 2023-07-14 13:14
closing for now until repro steps added

**Closed as not planned by cammellos** 2023-07-14 13:14 UTC
Labels: android

**Comment by Parveshdhull** [comment] 2023-12-18 07:49
Hi @cammellos, related to our [discussion](https://discord.com/channels/1103692771585433630/1103692773363810317/1183776435563933747) about debug app crash on hot-reload

- It depends on state of app. If app has chat screen open with link-previews and images, its easier to crash it
- Basically UI is too heavy to be reloaded some time
- Also crashes depends on frequency of reloading, which was improved in https://github.com/status-im/status-mobile/pull/16349


As you requested, logs from latest develop (related information is in last 5 mins)
- Crash logs - [logs-crash-new.txt](https://github.com/status-im/status-mobile/files/13700819/logs-crash-new.txt)
- Raw logs - [logs-crash-new-raw.txt](https://github.com/status-im/status-mobile/files/13700826/logs-crash-new-raw.txt)
- Video - https://github.com/status-im/status-mobile/assets/17097240/29b796da-7d9d-461a-a6bb-6b2bd77c0c25

**Comment by Parveshdhull** [comment] 2023-12-18 07:50
btw, I am using `Pixel_5_API_30` and installing app using `make run-android DISABLE_HERMES=true`

**Comment by Parveshdhull** [comment] 2023-12-18 07:53
Sorry for bumping the thread, didn't wanted to open a new issue. (Not sure if we can fix this one, as UI is heavy, and it somewhat looks like hardware limitation)

**Comment by Parveshdhull** [comment] 2023-12-18 18:03
Sometime this error is shown before crash

![shot](https://github.com/status-im/status-mobile/assets/17097240/4251342f-828b-450f-94b9-8196165952a6)
