### ISSUE TITLE
[iOS] Keyboard opens automatically when creating a new wallet account

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18876] opened 2024-02-16 16:40 UTC
# Bug Report

### Reproduction:
1. Open wallet on iOS
2. Add a new account

https://github.com/status-im/status-mobile/assets/67952253/87eaaf39-d942-4abc-ac4b-81dbae9b5e39

### Additional Information

- Status version: nightly 16/02
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by siddarthkay** [comment] 2024-02-17 10:23
I'm not 100% sure if it is the intended behaviour but I got the keyboard to not auto appear when navigating to create wallet account page.
ref : https://github.com/status-im/status-mobile/pull/18881
cc @J-Son89 I leave it to your judgement.

**Comment by qoqobolo** [comment] 2024-02-19 11:27
> I'm not 100% sure if it is the intended behaviour but I got the keyboard to not auto appear when navigating to create wallet account page.

Based on the [designs](https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=1-132380&mode=design&t=fqxvhN4qndUU2GVX-4), we shouldn't open the keyboard right after navigating to that screen.
I also see that the slider should be above the keyboard when it is opened, as it happens on Android, so there is another part of the issue that I did not specify in the description.

<img width="2076" alt="Screenshot 2024-02-19 at 12 24 32" src="https://github.com/status-im/status-mobile/assets/67952253/13538c0d-d7ef-496f-b46a-dccadf2f19c0">

@siddarthkay I checked [this PR](https://github.com/status-im/status-mobile/pull/18881) and it fixes the original keyboard auto opening issue.
But maybe we should also fix the slider position?
@J-Son89 @siddarthkay WDYT?

**Comment by J-Son89** [comment] 2024-02-19 11:37
@qoqobolo - the slider position has a bug for that here https://github.com/status-im/status-mobile/issues/18841 

Happy to put these into one issue if that's easier?

**Comment by qoqobolo** [comment] 2024-02-19 11:41
@J-Son89 okay, I'll move this to https://github.com/status-im/status-mobile/issues/18841
they just didn't seem the same due to keyboard opening, so logged it separately. 

What then should we do with @siddarthkay's PR https://github.com/status-im/status-mobile/pull/18881, should we merge it?

**Comment by siddarthkay** [comment] 2024-02-19 14:29
Since https://github.com/status-im/status-mobile/pull/18881 is ready better to merge it.
I'm okay either way :)

**Comment by qoqobolo** [comment] 2024-02-19 14:51
Updated https://github.com/status-im/status-mobile/issues/18841
> Since https://github.com/status-im/status-mobile/pull/18881 is ready better to merge it.
I'm okay either way :)

Checking it again to make sure there is no regression in other parts of the app.

**Comment by qoqobolo** [comment] 2024-03-01 09:46
Adding the `design` label and a link to the [discussion](https://discord.com/channels/624634427930312714/1197225590315552838/1209095958516727879) to make it clear why testing of the [corresponding PR](https://github.com/status-im/status-mobile/pull/18881) was postponed

**Comment by J-Son89** [comment] 2024-04-08 10:20
@qoqobolo, @siddarthkay - any confirmation on this. Should we close it?

**Comment by siddarthkay** [comment] 2024-05-27 06:14
Hey @J-Son89 : Sorry I missed this comment.
At the moment I am unsure of what was the latest decision.
However It would be best if I un-assign myself so others could take this up.
Thank you

**Comment by OmarBasem** [comment] 2024-06-03 05:58
Seems to me like this issue can be closed. If someone thinks otherwise feel free to reopen.

**Closed as completed by OmarBasem** 2024-06-03 05:58 UTC
Labels: ios, blocked
