### ISSUE TITLE
Image of 'Get started' view changes height/width if navigate back from "Enter seed phrase"

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10634] opened 2020-05-13 11:01 UTC
# Bug Report

## Problem

If to navigate back to main welcome view from "Enter your seed phrase" view then images become really small aligned to the top.
It happens only when navigating back from "Enter you seed phrase" view, but all **fine** when navigating back from `Generate keys`  or `Recover with Keycard` view.

No issues on iOS

#### Expected behavior

Images keep staying on the same place

#### Actual behavior

<img width="346" alt="Screenshot 2020-05-13 at 13 56 33" src="https://user-images.githubusercontent.com/8749671/81804336-9c7b3100-9521-11ea-946f-3edc4dcac3c7.png">

### Reproduction

- Install Status and open the application
- Tap `Access key` -> `Enter seed phrase`
- Tap `<` top-left button OR hardware Back button

### Additional Information
- Status version: develop 0.14.0 (20200513025927)
- Operating System: Android only

**Comment by Serhy** [comment] 2020-05-13 11:02
All good with Release 1.3.1 build.

**Comment by churik** [comment] 2020-05-13 13:09
@hesterbruikman do you think it should be fixed in 1.4.1?
Regression issue, but affects main carousel view.

**Comment by hesterbruikman** [comment] 2020-05-13 16:55
Yes please, I also can't image this being a massive task. Do you think it's a regression of this merge? https://github.com/status-im/status-react/pull/10442

**Comment by Serhy** [comment] 2020-05-15 11:53
@hesterbruikman yes, likely regression from #10442 (likely because it was dealing with images) because all fine in release 1.3 app version.

**Comment by flexsurfer** [comment] 2020-06-15 15:16
@Serhy can't reproduce

**Comment by Serhy** [comment] 2020-06-15 15:48
@flexsurfer I can't reproduce too on Android 9 (Galaxy S8)...
But reproduced on Android 8.1 and Android 6 (latest nightly and release 1.4).
Could you check please Android 6-7-8?

**Closed as completed** 2020-06-16 13:34 UTC
Labels: android
