### ISSUE TITLE
Contact requests are not delivered to receiver [BLOCKER]

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18992] opened 2024-02-26 08:39 UTC
**Steps:**

1. User A sends contact request to User B
2. See if User B has received CR

**Actual result:** CR has not been received. 

[UserA_cont_req_sender.zip](https://github.com/status-im/status-mobile/files/14401823/UserA_cont_req_sender.zip)
[UserB_cont_req_receiver.zip](https://github.com/status-im/status-mobile/files/14401824/UserB_cont_req_receiver.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment] 2024-02-26 09:56
Quick Update: If I select shards.test in both builds, then contact request is working for me

**Comment by Parveshdhull** [comment] 2024-02-26 09:56
maybe we need to update, default fleet? cc @cammellos

**Comment by cammellos** [comment] 2024-02-26 09:57
mmh, it should be already the default one, was it not?

**Comment by Parveshdhull** [comment] 2024-02-26 10:12
yes, it is default for new installations. I had an update on one of device, so needed to change.

For me contact requests are working as expected without any issues, tried different networks. So not sure what's the issue

**Comment by pavloburykh** [comment] 2024-02-26 15:43
**UPDATE:**

It turned out that problem exists until first re-login, i.e. after signup users have 0 peers but after relogin peers are found. Based on that this issue is no so critical as we supposed before but it is still e2e blocker as all tests will keep failing.

**Comment by igor-sirotin** [comment] 2024-02-26 15:56
I'm currently looking into this as it seems to be affected by my PR https://github.com/status-im/status-go/pull/4785/files

**Comment by igor-sirotin** [comment] 2024-02-26 18:37
After a long investigation I found this. It was actually on top and easy to find, but I was looking into wrong direction.

It seems that a hotfix for https://github.com/status-im/status-go/issues/3024, `WakuV2Nameserver: "8.8.8.8"` is missing in call to `CreateAccountAndLogin`.

This explains the `dns discovery error` in logs. 
Also this explains why for some people (me) it was working perfectly. I just don't have issues with default DNS.

Can someone from mobile team pick this up?

cc @cammellos

**Comment by Parveshdhull** [comment] 2024-02-26 19:11
Hi @igor-sirotin, Thank you for finding this and reporting.

Weird, we already passing `WakuV2Nameserver: "8.8.8.8"` while calling `CreateAccountAndLogin`
https://github.com/status-im/status-mobile/blob/42d2690c85c6502aef32327efedeb53abe4c2ac4/src/status_im/contexts/profile/config.cljs#L12

**Comment by igor-sirotin** [comment] 2024-02-26 20:09
> Weird, we already passing `WakuV2Nameserver: "8.8.8.8"` while calling `CreateAccountAndLogin`
> 
> https://github.com/status-im/status-mobile/blob/42d2690c85c6502aef32327efedeb53abe4c2ac4/src/status_im/contexts/profile/config.cljs#L12

Isn't this call of `Login` method?

UPD: oh, I see the `merge` word now. I love clojure 😄 
UPD2: still, is it actually it? this is `Create` method, not `CreateAccountAndLogin`.

**Comment by igor-sirotin** [comment] 2024-02-26 20:12
I was able to see this difference from the logs @pavloburykh gave me.

To the left is node config during the call of `LoginAccount` method. And to the right is `CreateAccountAndLogin`

<img width="858" alt="image" src="https://github.com/status-im/status-mobile/assets/25482501/9acc76da-e168-4fb7-acfb-8efb7a648c18">

**Comment by smohamedjavid** [comment] 2024-02-26 20:25
@igor-sirotin - On a glance, the login (`LoginAccount` method is used by mobile) sets the WakuV2Config - nameserver (the value received in the request)

https://github.com/status-im/status-go/blob/2445cda3e0c680962c285bd6e904ceb67968da3f/api/geth_backend.go#L627-L639

But on the profile creation `CreateAccountAndLogin` method doesn't update the nameserver as login.
(It calls the `startNodeWithAccount` method (almost a duplicate of the `loginAccount` method) at the end which loads the node config similar to login but does not update the nameserver as login.)

https://github.com/status-im/status-go/blob/2445cda3e0c680962c285bd6e904ceb67968da3f/api/geth_backend.go#L731-L740

**Comment by igor-sirotin** [comment] 2024-02-26 20:40
@smohamedjavid the `Nameserver` during `CreateAccountAndLogin` is set here:

https://github.com/status-im/status-go/blob/34c693bdeae4de261e42d8c935c0fb8a4681f4a0/api/defaults.go#L235-L237

as part of call to `defaultNodeConfig` here:

https://github.com/status-im/status-go/blob/34c693bdeae4de261e42d8c935c0fb8a4681f4a0/api/geth_backend.go#L1385

-----

IMO,  it doesn't make much sense to pass anything to `defaultNodeConfig`, but that's what we have.

**Comment by smohamedjavid** [comment] 2024-02-26 20:45
I guess, I found the issue of why the nameserver value is removed.

The `CreateAccountAndLogin` method uses the `defaultNodeConfig` method to build node config and sets the nameserver value as expected
https://github.com/status-im/status-go/blob/2445cda3e0c680962c285bd6e904ceb67968da3f/api/defaults.go#L189

but at the `startNodeWithAccount` method, we call the `updateNodeConfigFleet` method which in turn sets the fleet and sets (reset in our case) `wakuV2Config` 
https://github.com/status-im/status-go/blob/2445cda3e0c680962c285bd6e904ceb67968da3f/api/defaults.go#L105

That's why Login worked as expected as set the nameserver after this method.

**Comment by igor-sirotin** [comment] 2024-02-26 21:03
> but at the `startNodeWithAccount` method, we call the `updateNodeConfigFleet` method which in turn sets the fleet and sets (reset in our case) `wakuV2Config

Indeed, looks like that 😲
Let me take a look at this then. The clojure code made me think that `Nameserver` is not actually set.

**Closed as completed** 2024-02-27 16:15 UTC
Labels: e2e test blocker, blocker
