### ISSUE TITLE
L1 - L2 transaction fails with `L1_ETH_BRG: Value does not match amount` in blockchain

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21180] opened 2024-09-05 08:44 UTC
Looks like this is third party (hopper side) issue. Currently I am unable to perform transaction that includes L1 - L2 bridging neither in develop nor in release builds. 

**Steps:** 

1. Send L1 - L2 transaction. I used eth for testing.
2. Check transaction on blockchain

**Actual result:** Transaction fails with `L1_ETH_BRG: Value does not match amount` 

https://etherscan.io/tx/0x1867537c062312f3e9f19289b6a18c704c76f332a980d6ee2dbc8a74efb28e5b

[Status-debug-logs - 2024-09-04T183851.348.zip](https://github.com/user-attachments/files/16873363/Status-debug-logs.-.2024-09-04T183851.348.zip)

<img width="1291" alt="Ethereum Transaction Hash (Txhash) Details | Etherscan 2024-09-04 18-23-04" src="https://github.com/user-attachments/assets/d033ae51-9d8d-4c43-bebd-631e54f426f5">

https://github.com/user-attachments/assets/22f6e03d-b582-431f-bc92-3ade65da32c3

- Status version: nightly, release 2.30
- Operating System: Android, iOS

**Comment by VolodLytvynenko** [comment] 2024-10-07 15:40
Can't verify this yet due to high fees on L1. Need to wait for the merge of [this PR](https://github.com/status-im/status-mobile/pull/21378).

**Comment by saledjenic** [comment] 2024-10-14 10:41
@pavloburykh yes, I agree, it's hard for all of us to test bridge since it only works on real chains, not on test chains, but wondering if have you faced the same using the desktop app? And if yes, is that easily reproducible in the desktop app?

**Comment by pavloburykh** [comment] 2024-10-14 11:26
> [@pavloburykh](https://github.com/pavloburykh) yes, I agree, it's hard for all of us to test bridge since it only works on real chains, not on test chains, but wondering if have you faced the same using the desktop app? And if yes, is that easily reproducible in the desktop app?

@saledjenic I as far as I remember bridge was failing on Desktop as well, but we need to recheck. Currently I am not able to re-check on Desktop develop as I am getting `abi: cannot use func as type ptr as argument` when building L1-L2 route. We need to get this fix https://github.com/status-im/status-go/pull/5915 into Desktop develop, I suppose it is not there yet. 


![Image](https://github.com/user-attachments/assets/f4e001ff-1c17-47a1-88fe-56af694de173)

**Comment by saledjenic** [comment] 2024-10-14 11:39
@pavloburykh that was fixed here https://github.com/status-im/status-go/pull/5915 and merged last week, could be that you're using an old build? Or the desktop master branch still doesn't include that change?

**Comment by pavloburykh** [comment] 2024-10-14 11:44
> [@pavloburykh](https://github.com/pavloburykh) that was fixed here [status-im/status-go#5915](https://github.com/status-im/status-go/pull/5915) and merged last week, could be that you're using an old build? Or the desktop master branch still doesn't include that change?

@saledjenic yes, I know it was fixed as I have mentioned in my comment [above](https://github.com/status-im/status-mobile/issues/21180#issuecomment-2410926905), I suspect Desktop go version hasn't been updated yet and does not include the fix. As I am using latest Desktop master version and I am getting this error.

**Comment by pavloburykh** [comment] 2024-10-14 11:47
@saledjenic regarding the bug itself: in the title and description I have mentioned that bridge is failing with this error `L1_ETH_BRG: Value does not match amount`. But in fact it fails with other errors too. For example this transaction which I performed on Friday on mobile is just marked as `Fail`, without any specific errors https://etherscan.io/tx/0x2319ea9c04cd9f5586eac2922e484eae4484ff82412eda6c5722b84c4fed98d7 In other words, the main problem is that we are unable to perform L1-L2 bridge, because it is failing and reverted with different errors.

**Comment by saledjenic** [comment] 2024-10-14 12:31
> https://etherscan.io/tx/0x2319ea9c04cd9f5586eac2922e484eae4484ff82412eda6c5722b84c4fed98d7 In other words, the main problem is that we are unable to perform L1-L2 bridge, because it is failing and reverted with different errors.

Looking at the tx on etherscan.io, I cannot say what's wrong, all looks correct, maybe it's up to the network itself, don't know. Is that happening with each bridge tx?

**Comment by pavloburykh** [comment] 2024-10-14 12:49
>  Is that happening with each bridge tx?

For me it happens all the time when tying to bridge L1-L2. L2-L2 works fine.

**Comment by pavloburykh** [comment] 2024-10-15 12:21
**Update:**

Had a conversation today with @saledjenic. I have tried to bridge L1-L2 and for some reason it worked this time. So according to Sale investigation it seems to be a network issue which is the reason why L1-L2 transactions often failing in blockchain. I am going to make some more transactions to make sure it works and then probably descope or close this issue as a third party problem. 

@smohamedjavid I see you have assigned yourself for this PR. In case you have already conducted some investigation and think that problem still might be on our side - please share.

**Comment by shivekkhurana** [comment] 2024-10-16 08:08
Javid was assigned under the presumption that https://github.com/status-im/status-go/pull/5941 will fix this issue. 

If the Go PR doesn't fix this issue, we'll have to move it to the next release ((

**Comment by smohamedjavid** [comment] 2024-10-16 11:29
@pavloburykh I did a couple of L1-L2(opt/arb) and L2(opt/arb)-L2(arb/opt) bridge TX on the mainnet, and they all succeeded. This is WITHOUT the status-go PR (https://github.com/status-im/status-go/pull/5941). Can you check once again with the latest nightly on your side and see if the issue persists? 🙏

**Comment by pavloburykh** [comment] 2024-10-16 11:41
> [@pavloburykh](https://github.com/pavloburykh) I did a couple of L1-L2(opt/arb) and L2(opt/arb)-L2(arb/opt) bridge TX on the mainnet, and they all succeeded. This is WITHOUT the status-go PR ([status-im/status-go#5941](https://github.com/status-im/status-go/pull/5941)). Can you check once again with the latest nightly on your side and see if the issue persists? 🙏

Thanks @smohamedjavid! As I have mentioned above, I also managed to perform successful transaction, so the reason of previous failures must have been third party network issues. It has nothing to do with https://github.com/status-im/status-go/pull/5941. 

I will close this issue later after I perform some more testing on mainnet in scope of https://github.com/status-im/status-mobile/pull/21116

**Comment by smohamedjavid** [comment] 2024-10-25 14:14
**Quick update:** 

The Bridge-only transactions (Bridge Flow) are working well; the issue occurs only on Send flow transactions where Bridge and Send (`sendToL2`) are involved (e.g., `Sending ETH from 0x1 (L1) -> 0x2 (L2)`). 

The error `L1_ETH_BRG: Value does not match amount` ([Tx hash](https://etherscan.io/tx/0x1867537c062312f3e9f19289b6a18c704c76f332a980d6ee2dbc8a74efb28e5b) posted by @pavloburykh in the issue description) comes from the Hop contract where the TX value (`0.005`) and amount (`0.004554216928840596`) passed to the contract call are not equal.

https://etherscan.io/address/0xb8901acb165ed027e32754e0ffe830802919727f#code#F1#L23

We need to check the route calculation code in **_status-go_** as mobile returns the `amount-out` returned by the route, and the client sends it back again while creating the (multi) transaction.

The other failed transaction ([Tx hash](https://etherscan.io/tx/0x2319ea9c04cd9f5586eac2922e484eae4484ff82412eda6c5722b84c4fed98d7) posted by @pavloburykh in https://github.com/status-im/status-mobile/issues/21180#issuecomment-2410980288) where no error is shown was due to **out of gas** but the value and amount are equal and passed the contract validation.

https://eth.blockscout.com/tx/0x2319ea9c04cd9f5586eac2922e484eae4484ff82412eda6c5722b84c4fed98d7?tab=internal

<img width="900" src="https://github.com/user-attachments/assets/e443d614-ea75-4895-9a8e-893b1917004f" />

We need to check the **_status-go_** code to increase the Gas Limit for those transactions.

Special thanks to @briansztamfater 

cc @saledjenic @shivekkhurana 

--- 

On a side note, If we simplify the send flow in upcoming releases, we probably won't have to spend effort on this.

**Comment by pavloburykh** [comment] 2024-10-25 15:00
> Quick update:

Thanks for great research @smohamedjavid

**Comment by saledjenic** [comment] 2024-10-29 13:28
@pavloburykh @smohamedjavid is that error happening if you're doing the same in the desktop app?

If that's the mobile-only issue then it could be up to `wallet_createMultiTransaction` call that is not maintained anymore, the desktop app uses new endpoints for sending tx.

If not, then it would be nice to have the input parameters for calling the `wallet_getSuggestedRoutesAsync` so that I can test the router for that specific case.

>  the issue occurs only on Send flow transactions where Bridge and Send (sendToL2) are involved (e.g., Sending ETH from 0x1 (L1) -> 0x2 (L2)).

If you've set the params properly, there should be no differences between doing a bridge or sending tx.

Here you can see the route when I tried to bridge:

![Image](https://github.com/user-attachments/assets/28f25cb8-221a-45c9-bcce-7fb540c1ff79)

And here when I tried to send, setting params that the bridge is the only option for send (disabling "to" chains):

![Image](https://github.com/user-attachments/assets/04907f0e-eef8-4ebd-a9e6-e367962bb92e)

> On a side note, If we simplify the send flow in upcoming releases, we probably won't have to spend effort on this.

The router is pretty configurable, we can simplify UI, and that's not a problem, but the routing algorithm will be unchanged, cause it's configurable. We need to check how does the mobile app do the send?

**Comment by saledjenic** [comment] 2024-10-29 17:14
I spent some time inspecting the code and analyzing errors that we're getting when bridging, and I think that changes done in this PR https://github.com/status-im/status-go/pull/6012 should fix both issues we have:
- reverted tx due to `out of gas` error
- `Fail with error 'L1_ETH_BRG: Value does not match amount'` error

Here is a desktop PR that includes statusgo fixes from PR#6012.

@smohamedjavid could you please create a corresponding mobile PR that will include the mentioned statusgo changes?

Here is the bridge tx I did running the Send flow in the desktop app:
- https://etherscan.io/tx/0xee2484f85ead30396fdbaeb9bd3c71d45f32f400513eef8ccd0ef409e0601930

@pavloburykh please give it a try and let me know.

**Comment by smohamedjavid** [comment] 2024-10-29 17:21
Corresponding Mobile PR: https://github.com/status-im/status-mobile/pull/21523

**Closed as completed** 2024-11-04 09:00 UTC
Labels: re-check, wallet-core
