### ISSUE TITLE
Keyboard opens when tapping on the composer with audio in preview stage, causing the audio to be removed after typing

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15930] opened 2023-05-17 08:34 UTC
## Problem 
When audio is in the composer in the preview stage, the keyboard can be opened by tapping on the composer. This allows data to be typed, which results in the audio being removed from the composer

### Reproduction
1. Open any chat
2. Start recording the audio
3. Stop recording
4. Tap on the composer

#### Actual behavior
The keyboard opens, even though there is audio in the composer.

https://github.com/status-im/status-mobile/assets/52490791/70a9bc1d-9a0e-4bb3-afe1-7c6e54b5f388

#### Expected behavior
The keyboard should not open when the audio is in the composer

### ENV: 
- nightly [17 May 2023]
- Operating System: Android, iOS

**Comment by VolodLytvynenko** [comment] 2023-05-17 08:35
Approved with the design team
![image](https://github.com/status-im/status-mobile/assets/52490791/6cf680cd-1641-496a-b840-89e15aac4ba7)

**Comment by vkjr** [comment] 2023-05-23 12:33
@VladimrLitvinenko, I can't reproduce this one. Could you please double-check? Maybe already fixed by other composer changes.

**Comment by VolodLytvynenko** [comment] 2023-05-23 15:41
> @VladimrLitvinenko, I can't reproduce this one. Could you please double-check? Maybe already fixed by other composer changes.

hi, @vkjr still reproducible for me. Tried on the latest nightly:

### Steps:
The same as in https://github.com/status-im/status-mobile/issues/15930#issue-1713408765
or
1. Tap on the composer (now the keyboard is opened)
2. Start recording
3. Stop recording

### Actual result:
keyboard is still opened when audio is in the composer

https://github.com/status-im/status-mobile/assets/52490791/5fe556bd-78d5-4f64-9c87-96c7aedee1f5

### Devices: 
- Android studio Pixel 6. Android 12 (sometimes needs to be tapped on the different areas of the composer)
- Real device: Huawei p20 light, Android 9
- Real device: iPhone 11 Pro max, IOS 16

**Closed as completed** 2023-07-14 11:20 UTC

**Comment by vkjr** [comment] 2023-07-14 11:53
@cammellos, was it solved, or are you closing all descoped/stale issues?

upd: I've found the answer in chat)))

**Comment by cammellos** [comment] 2023-07-14 13:22
@vkjr closing descoped issues, in order to get more clarity on the issues section, but feel free to reopen if you'd think is best
