### ISSUE TITLE
Error when applying a markdown above the previous one in the Android app

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#20997] opened 2024-08-09 13:55 UTC
# Bug Report

### Reproduction

1. Send a message with markdown formatting (e.g., Hello **world** !)
2. Edit the sent message.
3. Select the entire text, including markdown symbols (e.g., Hello **world** !).
4. Apply another markdown formatting (e.g., *Hello **world** !*) on top of the existing one .

#### Expected behavior
The new markdown should be applied correctly on top of the existing one, allowing for combined formatting.

#### Actual behavior
The app fails to apply the new markdown correctly, resulting in either no change, the removal of the previous markdown, or incorrect formatting.

https://github.com/user-attachments/assets/3a957ea3-8d42-4e4c-8003-c5b6a154de34

### Additional Information
- Status version: release
- Operating System: Android, iOS

**Comment by ilmotta** [comment] 2024-10-04 01:51
@Horupa-Olena, I'm changing the issue to be a feature, not a bug because what you described is not an error, but a limitation of our markdown processor (in terms of processing nested styles as you demonstrated in the video).

I don't see us working on improving the markdown processor and the display of more complicated markdown any time soon, therefore I'm closing the issue with "Close as not planned".

Thank you for reporting in detail.

**Closed as not planned by ilmotta** 2024-10-04 01:51 UTC
Labels: feature, mobile-core
