### ISSUE TITLE
Scrolling returns to the end of chat instead of scrolling up to the previous messages on Android 9

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#5526] opened 2018-08-16 10:25 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  only on Android 9 (can't repro on 6 and 7):
Scrolling up (touch screen, move finger down, remove finger from the screen) does not go up in the chat (public or 1:1) instead you see end of the chat with most recent messages. It works only if you scroll up with 2 fingers and each moment one of fingers touches the screen, as soon as no fingers are touching the screen you go back to the end of chat or remain in position where you've moved finger away from the screen.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Can scroll messages in the chat up and down
#### Actual behavior
[comment]: # (Describe what actually happened.)
If scroll up and remove finger from the screen - end of chat is shown instead of scrolling up to previous messages 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status public chat or any other 1:1 or public chat with messages 
- Scroll up to see Yesterday's messages

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly from Aug 16 http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-31924f-n-fl.apk and https://i.diawi.com/ynGb9s
version 0.9.26 (6406) node a6d69ed
* Operating System: real Pixel XL (Android 9). 
Can't reproduce on real Galaxy S6 with Android 6.0.1 and on real Xiaomi Redmi 4 wtih Android 7

#### Logs

Tf session: https://app.testfairy.com/projects/4803622-status/builds/8559654/sessions/4398732690/?accessToken=Qv-2PggPzX5DMAz-ZJYwjIx6P-g

<blockquote></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/ynGb9s">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8559654/sessions/4398732690/?accessToken=Qv-2PggPzX5DMAz-ZJYwjIx6P-g">TestFairy: Status 0.9.26 (6406) @2018</a></strong></div></blockquote>

**Comment by lukaszfryc** [comment] 2018-09-06 10:25
@jpbowen has just reproduced this issue on his phone. It totally broke his experience. I think we should fix it asap since more and more people are upgrading to Android 9.

**Comment by mandrigin** [comment] 2018-09-14 09:40
RN issue: https://github.com/facebook/react-native/issues/19434

**Comment by mandrigin** [comment] 2018-09-14 10:12
Android 9 issue: https://issuetracker.google.com/issues/112385925

<blockquote><div><strong><a href="https://issuetracker.google.com/issues/112385925">Sign in - Google Accounts</a></strong></div></blockquote>

**Comment by mandrigin** [comment] 2018-09-14 11:25
Workaround in our fork: 
https://github.com/status-im/react-native/pull/1

**Comment by mandrigin** [comment] 2018-09-14 11:26
Workaround in RN: https://github.com/facebook/react-native/pull/21117

**Comment by mandrigin** [comment] 2018-09-14 14:41
Merged the workaround, it should fix the issue

**Closed as completed by mandrigin** 2018-09-14 14:41 UTC
