### ISSUE TITLE
Update design for a new restore from seed phrase screen

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15476] opened 2023-03-24 14:15 UTC
Followup of https://github.com/status-im/status-mobile/pull/15452 cc @cammellos 

Designs of new restore from seed phrase screen:

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2647-285839&t=uK2HsSO2bYyGLnXP-0

**Comment by qoqobolo** [comment] 2023-05-31 14:48
@ulisesmac this issue is assigned to you, but as I understand correctly, this is a duplicate of https://github.com/status-im/status-mobile/issues/15759 which is fixed in https://github.com/status-im/status-mobile/pull/15946, right?
May this one be closed?

**Comment by ulisesmac** [comment] 2023-05-31 16:11
@qoqobolo Yes, this can be closed.

**Closed as completed by ulisesmac** 2023-05-31 16:11 UTC
Labels: feature, onboarding
