### ISSUE TITLE
LES not syncing for Ropsten (LES) network

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6844] opened 2018-11-22 15:45 UTC
***Type***: Bug

***Summary***: There is no syncing starts for contact loged in under Ropsten (LES) network.
In geth.log it is reflected as `lvl=info msg="LES protocol is disabled" package=status-go/node`

#### Expected behavior
Syncing happens for contact logged in to Ropsten (LES) network
#### Actual behavior
No syncing in Ropsten (LES) network. In geth.log: "LES protocol is disabled" package=status-go/node. 

### Reproduction

- Open Status and create new account
- In Profile settings navigate to Fleet and set les.dev.ropsten
- Login to account again. Navigate to Profile -> Network -> Ropsten (LES) and confirm your choice
- Log in to account again and verify syncing started 

### Additional Information
* Status version: Develop nightly 22nd Nov 2018
* Operating System: Android and iOS

#### Logs

[GethWhenLES.log](https://github.com/status-im/status-react/files/2608649/geth.6.log)

**Comment by mandrigin** [comment] 2018-11-22 15:53
@Serhy thanks! It used to sync, so it looks like a regression...
Can you check either a binary from this PR or a nightly that happened the next day after it was merged?

**Comment by dshulyak** [comment] 2018-11-22 16:15
these lines are simply not accurate, we have some issue in status-go or geth. both ssh and les are definitely enabled. 

```
t=2018-11-22T15:34:07+0000 lvl=info msg="LES protocol is disabled" package=status-go/node
t=2018-11-22T15:34:07+0000 lvl=info msg="SHH protocol is disabled" package=status-go/node
```

for instance, next line won't be in the log if les is disabled

```
t=2018-11-22T15:34:10+0000 lvl=info msg="Added trusted checkpoint"               chain=testnet block=4063231 hash=0xa372a53decb68ce453da12bea1c8ee7b568b276aa2aab94d9060aa7c81fc3dee
```

**Comment by mandrigin** [comment] 2018-11-22 16:17
How come they are there? о__О

**Comment by Serhy** [comment] 2018-11-22 17:21
Ok so it's all fine in Develop nightly 20th of https://ci.status.im/job/status-react/job/nightly/812/ - it is possible to login and sync progress is visible. 

Develop nightly 21th Nov had https://github.com/status-im/status-react/issues/6829 issue so it's not clear whether syncing stopped working next day because of another commit, however, with the builds https://github.com/status-im/status-react/pull/6830#issuecomment-440676860 (in the PR fixing 6829 issue) sync is not happening.

So, possibly, that what brought https://github.com/status-im/status-react/issues/6829 issue could be a reason of current 'Ropsten(LES) not sync'. 
Or it's a regression of https://github.com/status-im/status-react/pull/6830
  

<blockquote><img src="/static/60651f1e/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/nightly/812/">status-react » nightly #812 [Jenkins]</a></strong></div></blockquote>

**Comment by dshulyak** [comment] 2018-11-22 18:50
That's would be really strange. With 6830 exactly the same config file is passed if les.dev.ropsten fleet is selected as before 6829

**Comment by dshulyak** [comment] 2018-11-22 19:03
oh hell, i messed up one line in config during rebase in github

**Comment by dshulyak** [comment] 2018-11-23 07:19
> Login to account again. Navigate to Profile -> Network -> Ropsten (LES) and confirm your choice

i am missing this option. I have only Ropsten/Rinkeby/Mainnet with upstream RPC and POA chains

**Comment by mandrigin** [comment] 2018-11-23 08:13
@dshulyak that is only available with a les-enabled fleet.

**Closed as completed** 2018-11-23 08:12 UTC

**Comment by dshulyak** [comment] 2018-11-23 08:28
@mandrigin but i selected les.dev.ropsten

**Comment by mandrigin** [comment] 2018-11-23 09:44
that is weird. android?

**Comment by dshulyak** [comment] 2018-11-23 10:08
@mandrigin yes. @Serhy suggests that perhaps it is not enabled in .env file for PR builds

**Comment by Serhy** [comment] 2018-11-23 10:10
Correct. It is enabled in nightly builds, however in PR builds it should be available as well (when https://github.com/status-im/status-react/pull/6830 was tested - Ropsten (LES) as network option was there). Both Andriod and iOS.

**Comment by dshulyak** [comment] 2018-11-23 11:07
so this option became available only when i created a new account. this is probably a bug. LES option won't be available to users with already created accounts.

**Comment by Serhy** [comment] 2018-11-23 11:58
@dshulyak @mandrigin, indeed it's an issue for accounts after upgrade. Described behavior in separate GHI :  https://github.com/status-im/status-react/issues/6859
