### ISSUE TITLE
Add a timestamp to an every message

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3295] opened 2018-02-12 16:44 UTC
### User Story

As a user, I want to know at what time my message was sent.

### Description

*Type*: Feature

**Comment by flexsurfer** [comment] 2018-02-12 16:50
and was received

**Comment by annadanchenko** [comment] 2018-02-20 12:11
what about grouping by Today, Yesterday, past date (Feb 20)

**Comment by chadyj** [comment] 2018-02-20 18:28
Adding `design-blocked` until these ^ issues can be resolved.

**Comment by chadyj** [comment] 2018-04-11 18:29
Dupe of https://github.com/status-im/status-react/issues/3793

**Closed as completed by chadyj** 2018-04-11 18:29 UTC
