### ISSUE TITLE
Fix Wallet user avatar styles and implementation

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#17481] opened 2023-10-03 07:52 UTC
# Bug Report

## Problem 
The wallet user avatar has, at least, the following problems:

- Its circle is always in a 50 custom color variant regardless of the theme selected.
- It's not using the `with-theme` fn.
- The sizes received by its API are not following our current standard (a `:size-NN` keyword).

This issue consists of improving the implementation and spot and fix any other possible problem.

#### Expected behavior

We want that the component is looking as designs:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=114-7648&mode=dev
and match our guidelines and standards for components

**Comment by J-Son89** [comment] 2023-10-05 21:09
@ulisesmac this issue is somewhat of a duplicate - @tumanov-alex is already working on an issue related to this component - see: https://github.com/status-im/status-mobile/pull/17328

feel free to reopen later if this is still needed

**Comment by J-Son89** [comment] 2023-10-05 21:13
@ulisesmac this looks like a duplicate of https://github.com/status-im/status-mobile/pull/17328

**Closed as completed** 2023-10-05 21:12 UTC
Labels: design-system
