### ISSUE TITLE
in case of a reply to image with a text message, only <image> will be displayed in quoted message instead of <text + Image> 

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15644] opened 2023-04-13 16:15 UTC
#### Steps to reproduce:
1. Go to any chat
2. Type any text
3. Attach the image
4. Send current message

#### Actual result:
Only 'image' is shown in the quote
![image](https://user-images.githubusercontent.com/52490791/231818781-706e95d2-a5d0-4365-9bb7-2c34a02cb8c5.png)

#### Expected result:
The text should be present in the quoted message text message with images
![image](https://user-images.githubusercontent.com/52490791/231820866-3d67d7c4-f4f2-4278-bf71-d9329471a771.png)
https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?node-id=2839-282773&t=ciO0LuTINcIhxfRu-0
#### ENV:
Nightly [13 Apr 2023]

**Comment by ilmotta** [comment] 2024-10-09 09:45
I'm closing this issue because I couldn't reproduce this bug in the release build 2.30.0.

**Closed as completed by ilmotta** 2024-10-09 09:45 UTC
Labels: chat, mobile-core
