### ISSUE TITLE
Empty space displayed between 'send' button and device's opened keyboard

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18234] opened 2023-12-19 15:16 UTC
follow up for https://github.com/status-im/status-mobile/pull/18055

### Steps:
1. Paste some long text into the composer
2. Close chat
3. Reopen chat
4. Focus composer

### Actual result:
Upon reopening the chat and focusing on the composer area, an empty space is observed between the 'send' button and opened keyboard

https://github.com/status-im/status-mobile/assets/52490791/89e22a42-1399-4b7f-9bb1-5044d5c0be0c

![image](https://github.com/status-im/status-mobile/assets/52490791/cbc31cc1-1d24-4f83-b681-ec2abb83cfc1)

### Expected result:
No empty space is shown
![image](https://github.com/status-im/status-mobile/assets/52490791/518d0bfe-d759-4bf2-9e36-a0a8a068f50c)

### Devices:
- iPhone 11 Pro max, IOS 16
- Pixel 7a. Android 14

**Comment by Parveshdhull** [comment] 2023-12-24 11:58
As this is composer related, I will be fix this along https://github.com/status-im/status-mobile/issues/18137

**Comment by Parveshdhull** [comment] 2024-01-19 13:10
Hi, I am unable to reproduce this issue.
I am unassigning myself if anyone else wants to look into this. Otherwise, hopefully, it will be fixed as a side product of refactoring.

**Comment by VolodLytvynenko** [comment] 2024-01-19 13:18
@Parveshdhull Thank you for the update.

This issue is not reproducing anymore for me as well. It seems we have a mysterious y superhero who fixed it :)

**Comment by Parveshdhull** [comment] 2024-01-19 13:47
Unfortunately, Issue is still happening (randomly). ref - https://github.com/status-im/status-mobile/issues/17842#issuecomment-1900432055

**Comment by Parveshdhull** [comment] 2024-01-19 13:50
Ok, closing back this issue. As both issues are tracking same bug.

**Closed as completed by Parveshdhull** 2024-01-19 13:50 UTC
Labels: chat-composer
