### ISSUE TITLE
👁️ Cannot read property `responseSessionRequest` of null

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#20909] opened 2024-07-29 10:22 UTC
Related comment: https://github.com/status-im/status-mobile/pull/20693#issuecomment-2228288723

Steps (exactly the same as in the comment above):

1. Connect to https://react-app.walletconnect.com/ using testnetwork (Sepolia)
2. Disable testmode and login the app
3. Trigger `personal_sign` event
4. Try to sign the event
5. Observe the result

<img width="314" alt="Screenshot 2024-07-25 at 14 29 21" src="https://github.com/user-attachments/assets/8f90fedf-1920-43a3-8f1a-1b688b5a3773">

_Originally posted by @qoqobolo in https://github.com/status-im/status-mobile/issues/20799#issuecomment-2250208801_

**Comment by mohsen-ghafouri** [comment] 2024-08-23 15:16
@shivekkhurana I cannot reproduce this issue anymore, it looks this changes already handle the network https://github.com/status-im/status-mobile/pull/20906/files#diff-9d6f1ddb525f0c0e381e2f69d5ac04404444d837a32981c690677eb768338c6cR137

current behaviour is like this : in dapp user will see request pending 
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/61861fd6-9fd6-475c-8351-1fc6ab82d8db">
and in app there is no error/notification, but if user switch to the correct network, they will see request modal. 

Please let me know if i should change something here, if all good we can close it.

**Comment by mohsen-ghafouri** [comment] 2024-08-23 15:35
Okay i found an issue that it doesn't send reject request to the dapp, and i'm going to show unsupported network toast in status app.

**Closed as completed** 2024-09-06 12:56 UTC
Labels: dapp-interactions, wallet-connect: Refinement
