### ISSUE TITLE
Integrate native navigation transitions

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#4866] opened 2018-06-20 14:22 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a User, I want to have native transitions while navigating between views so that I have a clear understanding of my location inside the app, how I got here and where I can return to. 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: iOS provides a consistent visual framework of transitions between views. I'd like to suggest we find a way to support those native behaviours, to my basic knowledge integrating **React Navigation** would allow just that. 

#### Expected behavior
Tapping the Back Button in an opened Chat View would smoothly transition the view while placing the previous Home view in its place. The animated segue transition should work both ways: tapping on a chat table cell should smoothly present the detailed chat view above it. 

The same logic should follow other views that are presented onto a navigation stack like choosing a currency from settings, viewing help, tapping cells with disclosure indicators: sending/ receiving transactions, displaying transaction history. 

#### Actual behavior
Views are presented without any transition when navigating between them.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.21 (6078)
* Operating System: iOS

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by denis-sharypin** [comment] 2018-06-20 14:27
Also, related https://github.com/status-im/status-react/issues/3804

**Comment by chadyj** [comment] 2018-06-20 14:30
Nice first issue! This looks like a dupe of #3804?

**Comment by denis-sharypin** [comment] 2018-06-20 14:37
@chadyj #3804 would be implemented when React Navigation will be in place. And this issue is mostly about it

**Closed as completed** 2018-09-18 11:22 UTC
Labels: feature
