### ISSUE TITLE
"No protocol method DateTimeProtocol plus- defined for type null:" error on opening a sent image in chat

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15389] opened 2023-03-16 13:24 UTC
@OmarBasem probably a regression of some of recent PRs related to images

**Steps:**

1. Open any chat
2. Send a message containing image
3. Try to open image after sending

**Expected result:** image opens, no error

**Actual result:** "No protocol method DateTimeProtocol plus- defined for type null:" error appears, image is not opened. In case with messages containing more than 1 image - it is able to open them after re-entering chat, when images start showing as an album. See video below. 

[Status-debug-logs (23).zip](https://github.com/status-im/status-mobile/files/10991266/Status-debug-logs.23.zip)

https://user-images.githubusercontent.com/97245802/225630479-38a6f686-cce4-4059-ab45-344a6709667d.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by OmarBasem** [comment] 2023-03-16 13:34
Thanks @pavloburykh. There was a small typo. Fixed in https://github.com/status-im/status-mobile/pull/15390

**Comment by pavloburykh** [comment] 2023-03-16 13:49
> #15390

Thanx @OmarBasem ! 

I am facing another issue on IOS and I wonder if it could be somehow related to current one or it is a separate issue? Could you please check? 

### "Index argument  nth must be a number" error appears on opening album image on IOS

There are no clear steps. I have managed to reproduce the bug couple of times using these one:

1. Open chat
2. Send message containing 6 images
3. Re open chat
4. Send message containing 1 image
5. Open the the last message to receive "No protocol method DateTimeProtocol plus- defined for type null:" error
6. Try to open different images in the previously sent message containing album

**Actual result:** "Index argument  nth must be a number" error appears

[status_logs (1).zip](https://github.com/status-im/status-mobile/files/10991475/status_logs.1.zip)

https://user-images.githubusercontent.com/97245802/225637451-cd7a4f07-4643-45af-b669-bd9eb2c201da.mp4

**Comment by OmarBasem** [comment] 2023-03-16 13:54
@pavloburykh no it's not related. This happens randomly. And I believe it can happen on Android also.

**Comment by pavloburykh** [comment] 2023-03-16 13:56
@OmarBasem thanx. I will log this issue separately. Will try to figure out more clear steps and try reproduce it on Android. By now I have faced it only on IOS.

**Comment by OmarBasem** [comment] 2023-03-16 13:58
Okay thanks @pavloburykh. Would be good if you can find a clearer way of reproducing it, and whether it is on both platforms.

**Comment by pavloburykh** [comment] 2023-05-02 11:50
@OmarBasem hi! Re-opening the bug as it is easily reproducible on IOS. 

**Steps:** 

1. Open any chat
2. Send 1 image
3. Open and close the image right after it is sent
4. Observe an error

**Actual result:** No protocol method DateTimeProtocol plus- defined for type null:" error on opening a sent image in chat. 

https://user-images.githubusercontent.com/97245802/235658115-4b078115-696c-4e5c-aff4-cdeb69254105.mp4

**Comment by churik** [comment] 2023-06-01 14:47
Can't easy reproduce it anymore

**Comment by pavloburykh** [comment] 2023-06-01 16:57
> Can't easy reproduce it anymore

I am easily reproducing the issue on my iPhone X, IOS 14.1 on latest nightly build. Let's leave this issue opened. 


https://github.com/status-im/status-mobile/assets/97245802/a4129794-fafd-4ddb-b5c0-ca7d70db4b8a

**Comment by flexsurfer** [comment] 2023-06-19 12:47
hey @OmarBasem do you plan to work on it?

**Comment by OmarBasem** [comment] 2023-06-26 09:10
@flexsurfer Yes I will look into it

**Comment by OmarBasem** [comment] 2023-06-27 08:35
@pavloburykh are you still reproducing this issue? I am not able to reproduce it

**Comment by pavloburykh** [comment] 2023-06-27 09:32
> @pavloburykh are you still reproducing this issue? I am not able to reproduce it

@OmarBasem still reproducing (latest nightly, IOS 14.1, iPhone X) but with another error

![photo_2023-06-27 12 31 51](https://github.com/status-im/status-mobile/assets/97245802/0fb48826-69c2-4f1b-b7ca-4ec9228da75a)

https://github.com/status-im/status-mobile/assets/97245802/4d18fc32-0a6b-4c97-a7d2-0f8dbb7fe97b

**Comment by OmarBasem** [comment] 2023-06-27 10:01
@pavloburykh are you getting this error before or after that PR which was merged very recently: https://github.com/status-im/status-mobile/pull/16405.

**Comment by pavloburykh** [comment] 2023-06-27 10:23
> #16405

@OmarBasem I am getting it in today's nightly which does not include this fix https://github.com/status-im/status-mobile/pull/16405

I have just checked build from this PR https://github.com/status-im/status-mobile/pull/16405 and still getting error there.

**Closed as completed** 2023-07-07 13:10 UTC
Labels: images
