### ISSUE TITLE
No drawer top in Photos Drawer

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16877] opened 2023-08-03 16:10 UTC
Part of design feedback in 1.24

Link to the comment: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3709:473614&mode=design#511503901

![image](https://github.com/status-im/status-mobile/assets/4557972/e870a352-d82b-41f2-aa5c-ebaa193cb100)

**Comment by clauxx** [comment] 2023-09-06 12:46
@cammellos closing this since cannot be reproduced. Checked in with @Francesca-G and it looks good on her side as well.

**Closed as completed by clauxx** 2023-09-06 12:46 UTC
Labels: images
