### ISSUE TITLE
Pressing a contact does nothing

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14886] opened 2023-01-25 13:21 UTC
Pressing a contact from the contacts list on messages home does nothing.
Also pressing "Chat" on a user's profile page does nothing.

**Comment by qoqobolo** [comment] 2023-01-25 14:30
Hey @OmarBasem , isn't it a duplicate of https://github.com/status-im/status-mobile/issues/14843 ?
Looks related.

**Comment by OmarBasem** [comment] 2023-01-25 14:42
Could be related, but I think it is different. Pressing a contact or "Chat" button should open the chat. Pressing "view profile" should open the profile.

**Comment by erikseppanen** [comment] 2023-01-25 16:38
They are similar in that they both currently rely on the `:chat.ui/show-profile` event: [source](https://github.com/status-im/status-mobile/blob/develop/src/status_im2/common/contact_list_item/view.cljs#L16)

#14845 will probably fix both.

**Comment by cammellos** [comment] 2023-01-30 21:01
@churik this one should be fixed in develop, could you please confirm?
Thank you

**Comment by churik** [comment] 2023-01-31 09:54
closed in favor of #14939

**Closed as completed** 2023-01-31 12:31 UTC
