### ISSUE TITLE
@everyone mention does not generate PN/AC notification/unread counter if push notifs are enabled (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15795] opened 2023-05-02 15:39 UTC
Should be tested on Android, as PNs are currently not working on IOS

Preconditions: User A (desktop), User B (Android) has PNs enabled. User A and B are members of the same community

**Steps:** 

1. User A send ```@everyone``` mention in community channel
2. See if User B received PN, notification in Activity Center and unread counter appeared in community and channel

**Actual result:** PN/AC notification/unread counter do not appear for User B

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment] 2023-05-02 15:43
closed as duplicate of https://github.com/status-im/status-mobile/issues/15615

**Closed as completed** 2023-05-08 13:22 UTC
