### ISSUE TITLE
Design feedback for chat topbar

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#17509] opened 2023-10-04 11:04 UTC
# Bug Report

Address the design review feedback from design on the comments highlighted in these Figma links.
There's a cutout that happens when scrolling to trigger the minified chat nav.

<img src="https://github.com/status-im/status-mobile/assets/33176106/92973757-a2a8-40e1-a0ee-75767fccc0fd" width="600px"/>

## Resources

Resources
Reported at: https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=5963:43613&mode=design#567134213
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=6142:39869&mode=design#567179730

Figma specs: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8451-541849&mode=design&t=Ox3uxC14FqmagMOp-0

**Comment by ibrkhalil** [comment] 2023-10-06 06:17
Couldn't reproduce the wrong color one as it was merged 3 days ago [here](https://github.com/status-im/status-mobile/commit/26a702799c0ac2ec6cb3b389e76c21d6bd5d27da)

**Comment by ibrkhalil** [comment] 2023-10-07 05:26
https://github.com/status-im/status-mobile/assets/33176106/2ac01226-64c8-42c3-bf48-2843dee1191e

This is the proposed implementation

**Comment by BalogunofAfrica** [comment] 2023-10-07 09:59
Duplicate of https://github.com/status-im/status-mobile/issues/17537

**Comment by ibrkhalil** [comment] 2023-10-07 10:54
The duplication is the button overlaying the back button right?
Not the animaton issues?

**Comment by BalogunofAfrica** [comment] 2023-10-07 11:31
> The duplication is the button overlaying the back button right? Not the animaton issues?

Yes. Not the animation issue.

**Closed as completed** 2023-11-03 12:20 UTC
