### ISSUE TITLE
Messages are stuck in "sending" state while sent from offline (Android) 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#18301] opened 2023-12-26 10:56 UTC
Currently can reproduce consistently with android sending from offline state - messages stuck in "Sending" state forever after getting back online
![IMAGE 2023-12-26 11:48:34](https://github.com/status-im/status-mobile/assets/4557972/68a77b46-b2df-4c8a-9aa1-bd0d97eedca0)

### Reproduction
**Prerequisites:** device A joined to community 

1. Go offline (app should be in the background)
2. Send a couple of messages to community
3. Go online and wait ~5 mins  for messages to be resent

### Logs
Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/13770902/Status-debug-logs.zip)

**Comment by qfrank** [comment] 2024-01-22 09:17
Hi @pavloburykh , this issue seems not reproducable anymore with latest nightly build?

**Comment by pavloburykh** [comment] 2024-01-22 10:42
@qfrank thank you for looking at this issue. So far I am also unable to reproduce it. Maybe something has been fixed on go-waku side recently, not sure. 

Let's keep this issue open for a while. If we face it again we will post an update here.

**Comment by pavloburykh** [comment] 2024-03-11 20:24
Closing the issue as it is not reproducible anymore.

**Closed as completed by pavloburykh** 2024-03-11 20:24 UTC
Labels: waku
