### ISSUE TITLE
All letters are removed when tapping erase button one time in password field after incorrect attempt [iOS only]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1720] opened 2017-08-31 10:22 UTC
### Description

*Type*: Bug

*Summary*: When I am trying to edit the password (like correct 1 last symbol) in the password field after previous password was not accepted I am taping erase on the keyboard and all previously letters are removed

#### Expected behavior
I should be able to remove symbols one by one in password field after previous attempt was not accepted

### Reproduction

- Open Status
- Create an account and remember password
- Click switch accounts
- Tap the account and enter incorrect password
- Tap into the password field
- Tap the erase button on the keyboard

### Additional Information

* Operating System: iOS
* TF https://app.testfairy.com/projects/4803590-status/builds/6979667/sessions/1/?accessToken=xf5vpC2uJrTFmzygeJVY40r0Vfc

**Comment by status-open-bounty** [comment] 2017-11-02 09:09
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x27f372f3c2a2ea95574f4e7af4c98c383677d0caac2e7f8653ce66e422e1ecec](https://etherscan.io/tx/0x27f372f3c2a2ea95574f4e7af4c98c383677d0caac2e7f8653ce66e422e1ecec)

**Comment by dmitryn** [comment] 2017-11-13 13:21
Seems like it's not a bug, but feature of iOS TextField https://stackoverflow.com/questions/7305538/uitextfield-with-secure-entry-always-getting-cleared-before-editing

Also, you get same behaviour on any iOS native app using TextField with secureTextEntry=true.

**Comment by SHA-2048** [comment] 2017-12-25 14:43
@asemiankevich and @annadanchenko maybe this can be closed as per @dmitryn findings

**Comment by raghav-garg** [comment] 2018-01-15 11:18
This can be changed by overriding default behaviour of textField of iPhone, In for it!

**Comment by Newbie1010** [comment] 2018-07-18 13:14
(BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string

Check using:
NSString *resultString = [textField.text stringByReplacingCharactersInRange:range withString:string];
BOOL isPressedBackspaceAfterSingleSpaceSymbol = [string isEqualToString:@""] && [resultString isEqualToString:@""] && range.location == 0 && range.length == 1;
if (isPressedBackspaceAfterSingleSpaceSymbol) { 

//action of backwards delete

**Comment by andytudhope** [comment] 2018-08-24 13:20
@asemiankevich can we close here?

**Closed as completed** 2018-08-24 13:25 UTC
Labels: ios
