### ISSUE TITLE
Profile colour is not applied to UI elements on newly created account until user logs in again

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#16480] opened 2023-07-04 10:52 UTC
## Problem 

The Profile colour selected during onboarding doesn't get applied to UI elements (Buttons, Avatar,...etc) after the user lands in the shell until the user logs out and logs in again.

https://github.com/status-im/status-mobile/assets/19339952/b19b7fd5-f17d-4061-a4c2-6bb50107a978

### Expected behaviour

The selected profile colour should be applied to UI elements in Shell

### Reproduction

1) Open Status
2) Create a new account with a different profile colour (other than blue)
3) Land in the Shell
4) Check the colour of `Jump to` and `Profile Avatar`

### Additional Information

- Status Version: nightly [04/07] 
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment] 2023-07-04 11:08
duplicate of https://github.com/status-im/status-mobile/issues/16444

**Closed as completed** 2023-07-04 11:08 UTC
