### ISSUE TITLE
Implement Shell Scan screen

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#14011] opened 2022-09-15 11:49 UTC
### Instructions

Implement the Shell Scan Screen.

Figma: https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?type=design&node-id=451-18994&t=RlXEGOyFRoEJCjEz-0

You should be re-using existing components where available and create components when not.

These are the following details as specified by the design team.
```
if web or dApp address QR is scanned --> user taken to browser

if a pairing QR is scanned --> user is taken into pairing flow

if a user profile QR is scanned --> user is taken to that user's profile screen

if a community QR is scanned --> user is taken to that community

if a channel in a community QR is scanned --> user is taken to that channel (if they can access it) or to the community home if they can't access that channel

if an ETH address is scanned --> user sees a choice to either send to that address or save that address.  Note if user's client is aware that this address is shared with them via showcase, more metadata can be displayed.

if a WalletConnect QR is scanned --> user enters WalletConnect connect flow

if a user scanner a QR that is non of the above --> an error should be displayed
```

Communities scanning will work like this:
<img width="420" alt="Screenshot_2023-11-29_at_00 49 21" src="https://github.com/status-im/status-mobile/assets/22799766/e0138876-b3b1-4223-9088-3188c5ac48c7">

If this feature grows too large on initial implementation it is fine to notify and only handle 2/3 differrent types of QR codes provided the underlying code easily allows for extending the other features which we can then add in follow up issues.

**Comment by jo-mut** [comment] 2024-01-23 00:12
@J-Son89 looks like this issue is a duplicate of https://github.com/status-im/status-mobile/issues/17574. @alwx has been actively working on it

**Comment by J-Son89** [comment] 2024-01-23 00:14
Let's align with @alwx as good to share what we found so far anyway 👍

**Comment by jo-mut** [comment] 2024-01-23 10:31
@J-Son89 @alwx  I will just create a draft pr on it

**Closed as completed** 2024-02-16 11:06 UTC
Labels: shell, feature
