### ISSUE TITLE
Name still resolving to user `c`

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6738] opened 2018-11-15 10:51 UTC
### User Story

As a desktop user, I want to receive an error for invalid names.

### Description

*Type*: Bug

*Summary*: On desktop, I am still able to resolve certain names to the wrong address. 

#### Expected behavior
ENS names resolve only to the registered Whisper ID. If a name does not have a Whisper ID, there's an error message. 

#### Actual behavior
I just typed in `cologic` and was directed to the user `c` (Creative Wellmade Thrush). 

![image](https://user-images.githubusercontent.com/15470435/48548123-7f35ba00-e8cc-11e8-8078-bd94f35449b3.png)

### Reproduction
Start a new chat with `cologic` on desktop.

**Comment by rachelhamlin** [comment] 2018-11-22 12:12
Another instance of this: Just now I typed in `andrey` but was redirected to `andrei` (Runny Hot Monkey). 

I tried a few more times and was directed to actual Andrey half of the time, and Andrei the other half. Could you take a look @yenda?

**Comment by yenda** [comment] 2018-11-28 14:58
Cannot reproduce which version of desktop are you running? We can't reproduce for now. `c` still resolved because he still owns the name nobody slashed it. But `cologic` isn't registered properly. So in my tests it's just not resolving (red message `enter valid contact name`). @churik

**Comment by rachelhamlin** [comment] 2018-11-29 14:09
Still having weird issues on the latest desktop build. 

First, `nabil` and `naghdy` throw an error (which is correct, since Nabil doesn't have a contact code registered). But with `naghdy` in the input, twice I've clicked on the client/`Start chat`, I get redirected to Andrey. 

Also, `andrei` is not registered at all, but resolves to Runny Hot Monkey. Occasionally, `Andrey` will register to Runny Hot Monkey as well.

So...

`naghdy` - contact code not registered, usually throws error but has also redirected to Andrey
`andrei` - name not registered but resolves to Runny Hot Monkey
`andrey` - registered, usually resolves to Andrey, but occasionally resolves to Runny Hot Monkey. It seems like this happens if I try `Andrei` first.

I believe `naghdy` has resolved to Andrey when I've been chatting with Andrey previously. Maybe that helps!?

**Comment by churik** [comment] 2018-11-30 17:08
Btw, name is not resolved if you paste it (not typed).
If you paste 'andrei' and delete 'i', it resolves to `Runny Hot Monkey` as well.

Video: http://take.ms/qgJNX

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=t7H8Mdjkis4F2maoLqdb6H3f38gtib&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/t7H8Mdjkis4F2maoLqdb6H3f38gtib">File "screencast 2018-11-30 18-06-02.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by churik** [comment] 2018-12-03 14:59
@chadyj - guess it should be `high-prio` for 0.9.0, WDYT?

**Comment by chadyj** [comment] 2018-12-03 15:06
I couldn't reproduce:
- problem pasting in `andrey` (works for me)
- cologic resolving to another user (doesn't resolve at all for me)
- naghdy doesn't resolve
- andrei doesn't resolve

In any case not high priority as most ENS seems to work just fine.

**Comment by Swader** [comment] 2019-03-03 17:38
I get all messages intended for barry it seems. My name is bruno.stateofus.eth

**Comment by rachelhamlin** [comment] 2019-03-03 20:04
Yup, still think this one is a problem. I'll look into it again this week. Thanks @Swader.

**Closed as completed** 2020-02-24 11:41 UTC
