### ISSUE TITLE
Assets (tokens) are not loaded due to infura error

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9280] opened 2019-10-25 08:35 UTC
# Bug Report

## Problem
Sometimes due to "context deadline exceeded" from `infura.io` balance can't be fetched. Can't reproduce, but potentially it can be an issue on mainnet as well.
Caught by e2e. 

#### Expected behavior
Balance assets are loaded

#### Actual behavior
No assets (tokens) are shown.
Full video / log: https://app.saucelabs.com/tests/aaa060e1b584497db876f67e5687a319?auth=f2c8623188b3a2a34e16a0e655e57fcd#54

### Reproduction

- Open Status
- Restore account with funds (ETH + tokens)

### Additional Information

- Status version: nightly 23/10
- Operating System: Android, iOS

#### Logs

```
10-23 04:58:37.739  4296  5214 E GoLog   : ERROR[10-23|11:58:37.739] failed to get transfer in between two bloks from=4200000 to=4300000 error="Post https://ropsten.infura.io/v3/f315575765b14720b32382a61a89341a: context deadline exceeded"
10-23 04:58:37.739  4296  5214 E GoLog   : ERROR[10-23|11:58:37.739] failed to get next batch                 error="Post https://ropsten.infura.io/v3/f315575765b14720b32382a61a89341a: context deadline exceeded"
```

**Comment by churik** [comment] 2019-10-25 08:37
@adambabik @cammellos would be nice if you can comment issue to understand it better.
Thanks a lot!

**Comment by cammellos** [comment] 2019-10-25 09:44
@churik it means it's taking too long the request, and it's timing out, we can probably extend it (at least for tests)

**Comment by ryanschneider** [comment] 2019-10-25 16:49
Can someone familiar with the status code point me to where this is happening?  Based on the logs it sounds like a eth_getLogs query is being slow, but we’ve done a lot of optimizations on our end to make those performant so I’d like to see if I can reproduce a consistently slow query.

**Comment by StatusSceptre** [comment] 2019-11-01 09:42
@yenda @cammellos can one of you point @ryanschneider to the relevant code?

**Comment by yenda** [comment] 2019-11-01 10:40
@ryanschneider I think this is happening here: https://github.com/status-im/status-go/blob/develop/services/wallet/downloader.go#L242

**Comment by churik** [comment] 2019-11-12 13:39
@rachelhamlin it is more visible now, I faced it several times per day.
It is pretty dangerous from user perspective, user may think that he lost assets.
So should be added to v1 from my POV.
Assets don't appear at all in some cases, sometimes they appear after several re-logins

**Comment by ryanschneider** [comment] 2019-11-15 05:44
@yenda based on the error message reported, I think it's actually happening here:

https://github.com/status-im/status-go/blob/89659f85b49b48f4409ed9f522397b99728b214b/services/wallet/iterative.go#L69

Which seems to be called from here:

https://github.com/status-im/status-go/blob/89659f85b49b48f4409ed9f522397b99728b214b/services/wallet/commands.go#L98

But I can't find where that's called to see what sort of deadline the parent context has.  If there iterator is going through a large number of blocks then the queries can add up, especially if a large range is being scanned, as each iteration does 100,000 blocks.

**Comment by corpetty** [comment] 2020-01-08 17:18
Think I got this error today when recovering account on latest nightly

**Comment by rasom** [comment] 2020-01-24 13:16
@churik do we have any signs of this issue in release candidate? This error ` failed to get transfer in between two bloks` was caused mainly by the way how we fetched transfers before, but let me know if you still can reproduce this case.

**Comment by churik** [comment] 2020-01-24 13:17
@flexsurfer says that he got it.
Can confirm @flexsurfer ?

**Comment by flexsurfer** [comment] 2020-01-24 14:10
yes, lots of users report that their SNT balance is 0 all the time, even after a few relogins

**Comment by flexsurfer** [comment] 2020-01-24 14:10
one of them @jakubgs btw

**Comment by rasom** [comment] 2020-01-24 14:46
@flexsurfer I'm asking specifically about `failed to get transfer in between two bloks`

**Comment by flexsurfer** [comment] 2020-01-24 15:02
oh ok , we don't have  any signs  of `failed to get transfer in between two bloks`

**Comment by rasom** [comment] 2020-01-24 15:13
Then probably this issue should be closed and another one with a different description/steps to reproduce be opened. Or this one to be changed, because the problem described here doesn't reproduce currently.

**Comment by flexsurfer** [comment] 2020-01-24 15:43
@churik @Serhy

**Comment by churik** [comment] 2020-01-24 16:07
@jakubgs @flexsurfer do you have logs for issue?

**Comment by flexsurfer** [comment] 2020-01-24 16:08
i can't reproduce this

**Comment by jakubgs** [comment] 2020-01-24 17:22
@churik I just tested this by installing today's nightly over the RC and creating a new account and adding a watch-only address. The tokens loaded just fine an the history did too after a while. So I can't really reproduce it now.

**Comment by rachelhamlin** [comment] 2020-01-27 11:12
I have notorious infura issues and can't repro this either. Let's keep an eye for it, but I don't think it's a v1 blocker.

**Comment by flexsurfer** [comment] 2020-02-03 19:41
fixed by implementing retries on infura error

**Closed as completed by flexsurfer** 2020-02-03 19:41 UTC
Labels: e2e test blocker
