### ISSUE TITLE
Default keyboard setting causes comma to appear in place of fullstop

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#714] opened 2017-01-11 08:18 UTC
European iOS users with default keyboard settings report a comma in place of a full stop when entering an ETH amount. When a user inserts a decimal number using a comma (e.g. 2,13) an invalid number error appears resulting in an inability to process the transaction.

![image](https://cloud.githubusercontent.com/assets/25023739/21840651/7a2675a4-d843-11e6-9e88-42da7a0d1609.png)

https://instabug.com/applications/status/beta/bugs/9
https://instabug.com/applications/status/beta/bugs/8

**Comment by jarradh** [comment] 2017-01-11 08:28
Duplicate of #665

**Closed by jarradh** 2017-01-11 08:28 UTC
Labels: bug, duplicate
