### ISSUE TITLE
Application freezes after recording and attempting to send audio message.

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#11073] opened 2020-08-11 22:40 UTC
# Bug Report

## Problem

After first receiving and opening an audio message. I then record an audio message myself in the same chat, and the audio recording overlay freezes and I cannot send the message. The chat which is currently open I am able to scroll up and down, but that is the only functionality that seems to persist in this state.

Closing the application and reopening causes the app to indefinitely hang on the splash screen.
To restore the app, my device needs to be restarted. 

#### Expected behavior

[comment]: # Audio message should send and use of app able to continue

#### Actual behavior

[comment]: # Audio message doesn't send and application freezes

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Navigate to private chat
- Receive and play an audio message
- Record an audio message in same chat
- Application freezes

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.5.0
[comment]: # (Android or iOS.)
- Operating System: Android / LineageOS
#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)

```
...
```

**Comment by churik** [comment] 2020-08-12 09:58
@Jas0n-F 
thank you for reporting!
Can't reproduce the issue as I understand it from the description on my Android10, so several questions to clarify:
1) did you have history in this chat on previous releases (~amount of messages, and type - i.e. containsa transaction requests / stickers)?
2) Did you record the message for the 1 time (so permission to microphone is requested and you tap "Allow")?
3) what Android version are you using?
4) User is added to contacts (if yes, on what status version)? 
5) Do you have several devices in sync (probably you are using the same account on several devices)?
6) is  the issue still reproducible (if yes, enable please LogLevel = Debug in Profile > Advanced > Log Level and try to reproduce issue and shake the phone to send logs)?

**Comment by Jas0n-F** [comment] 2020-08-12 21:47
@churik 

1) Yes, 200+ messages. A couple of photos. No transactions or stickers. 
2) Yes, first time, allowed access then froze.
3) Android 8.1.0 / Lineage OS 15.1 
4) I don't recall exactly when I added to contacts. Chat logs show first messages in March this year.
5) No, this is my only device using this account
6) Log sent just now

**Comment by flexsurfer** [comment] 2020-08-17 05:25
hey @Jas0n-F at what point did it freeze? right after record button was pressed ? or after some time? thanks

**Comment by flexsurfer** [comment] 2020-08-17 08:44
found this https://github.com/react-native-community/react-native-audio-toolkit/issues/197

**Comment by flexsurfer** [comment] 2020-08-17 08:46
@tbenr sorry for pinging, but you might have ideas, thanks

**Comment by tbenr** [comment] 2020-08-17 09:42
> found this https://github.com/react-native-community/react-native-audio-toolkit/issues/197

@flexsurfer I already fixed this issue in our fork (it has been merged recently) it should be something different

**Comment by tbenr** [comment] 2020-08-17 09:55
> @tbenr sorry for pinging, but you might have ideas, thanks

Could be a compatibility issue with lineageos and audio recorder. Need to take a look to logcat logs to search for meaningful stack traces.

**Comment by tbenr** [comment] 2020-08-19 07:58
@flexsurfer @churik how can I take a look to logs sent by the user?

**Comment by cammellos** [comment] 2020-11-30 16:31
Closing this issue for now as likely stale/we are not able to replicate, feel free to re-open if still an issue, thanks!

**Closed as completed by cammellos** 2020-11-30 16:31 UTC
