### ISSUE TITLE
Share QR Code Gradient

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18168] opened 2023-12-13 12:25 UTC
Share QR code component needs to have a gradient background color.

Designs: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1338-34510&mode=design&t=uZ8OClmzODbilGse-0

**Comment by smohamedjavid** [comment] 2023-12-13 16:06
Duplicate of https://github.com/status-im/status-mobile/issues/17769

**Comment by Pau1fitz** [comment] 2024-01-15 19:28
PR here - https://github.com/status-im/status-mobile/pull/18503

**Comment by J-Son89** [comment] 2024-01-26 14:48
closing as this is a duplicate an already handled now

**Closed as completed by J-Son89** 2024-01-26 14:48 UTC
Labels: feature
