### ISSUE TITLE
Message reply mixes up sender & content

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6583] opened 2018-11-05 08:41 UTC
### User Story
As a user, I want to reply to messages in a chat, so that other participants know specifically what I'm responding to.

### Description

*Type*: Bug

*Summary*: Double tapping on a message created a reply to the message below it. The content was wrong, but the sender was partially correct and had the right display name. 

#### Expected behavior
When I double tap on a message to reply, I'm given the correct content and sender.

#### Actual behavior
I tried to reply to my own message in this chat by double clicking on the body of my message (starting with `Speaking of EIPS`), and this is what happened:

![image](https://user-images.githubusercontent.com/15470435/47986187-34ea5700-e0dc-11e8-8fff-e942d9c07fed.png)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status desktop
- Send two messages back to back
- Try to reply to one
- See if the correct message is chosen

### Additional Information
* Status version: Desktop nightly
* Operating System: MacOS

**Comment by lukaszfryc** [comment] 2018-11-29 12:57
I could not reproduce it on latest nightly. @rachelhamlin could you check it again?

**Comment by rachelhamlin** [comment] 2018-11-29 15:18
@lukaszfryc it seems to be okay for me now but haven't been using replies heavily today.

**Comment by lukaszfryc** [comment] 2018-11-30 09:31
@rachelhamlin ok. So I am closing it for now. Please reopen if it happen again.

**Closed as completed by lukaszfryc** 2018-11-30 09:31 UTC
