### ISSUE TITLE
rename debug into cli 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#2285] opened 2017-10-24 07:28 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer, I want to understand purpose of functionality by ns name

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

status-im.debug should be something like status-im.cli, because it used with https://github.com/status-im/status-dev-cli

**Comment by alwx** [comment] 2017-10-24 19:54
I am not sure about it, actually. And don't also see any problem with the current naming. 
What's placed inside status-im.debug namespace is handlers that will be accessible after you execute **/debug** command and start a **debug** server. So it makes sense to call it this way.

However, status-dev-cli is just one of the examples of tools that can use this server. Nothing prevents developers to write something else instead.

**Comment by jeluard** [comment] 2017-10-25 06:40
How about we move it into `commands.handlers` then?

**Comment by asemiankevich** [comment] 2017-11-24 07:58
I spoke to @flexsurfer about this issue and seems the issue is not fixed yet. I am moving this back to Inbox. @alwx could ypu please take a look into it again or continue coversation so we can come up with a solution?

**Comment by flexsurfer** [comment] 2017-11-24 08:10
we have two debug in code, 1 - means app running in debug mode, 2 - means cli debug, and it's confusing

**Closed as completed** 2018-09-24 19:44 UTC
