### ISSUE TITLE
Fix two subcriptions to extract user theme color

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#16263] opened 2023-06-13 16:56 UTC
# Problem

We are extracting the user profile color from `(rf/sub [:profile/customization-color key-uid])` but it doesn't work for recently created profiles, so we need to extract that value from   `(:color (rf/sub [:onboarding-2/profile])`, leading us to the following piece of code repeated in the code:

```clojure
(or (:color (rf/sub [:onboarding-2/profile]))
    (rf/sub [:profile/customization-color key-uid]))
```

We want to fix it so that we can only use one subscription.

**Comment by Parveshdhull** [comment] 2023-06-13 18:54
duplicate of https://github.com/status-im/status-mobile/issues/16175

**Closed as completed** 2023-06-13 18:54 UTC
