### ISSUE TITLE
Activity Center Screen Closing animation

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14968] opened 2023-02-02 12:22 UTC
The activity center screen seems to be currently using a bottom sheet / popover (or the animations is bottom-sheet-like (?)). Either way the closing animation probably needs to be fixed, or component migrated to a screen if it was using a bottom sheet.

**Comment by OmarBasem** [comment] 2023-02-02 12:33
It seems it is using popover component in `status-im.ui.screens.popover.views`. I think it would be better to keep popover/bottom-sheet for light components. The activity center is probably not a light one, so performance-wise would be better if we migrate it to a screen.

**Comment by ilmotta** [comment] 2023-02-02 12:40
> It seems it is using popover component in `status-im.ui.screens.popover.views`. I think it would be better to keep popover/bottom-sheet for light components. The activity center is probably not a light one, so performance-wise would be better if we migrate it to a screen.

You're right about that. Thanks for bringing this up.

**Comment by ilmotta** [comment] 2023-02-07 12:29
@OmarBasem, there's a design requirement that the Activity Center screen should display a blurred background of the screen behind it. I believe that's the reason it was chosen to use a popover, as you can see here https://github.com/status-im/status-mobile/blob/98b219191fcae33e0e7f0f9f1c4f293c9150166c/src/status_im2/contexts/activity_center/events.cljs#L28

Do you have a specific suggestion considering the screen must show a real time blur of the background screen? Otherwise I'm afraid we should close the issue for the moment.

**Comment by OmarBasem** [comment] 2023-02-07 12:44
@ilmotta I think we shouldn't be compromising on the performance for some design details.

Something that may give a similar effect is the following:
I see the activity center is accessible from a few screens (currently messages home and communities home). Both of these screens look very similar. To simulate the same blurry effect, we can have an Image background of one of the screens and on top of it the blurry view. That should give a very similar look.

**Comment by OmarBasem** [comment] 2023-02-07 12:55
@ilmotta It may be possible to have a transparent screen in react-native-navigation https://github.com/wix/react-native-navigation/issues/5381

If so, you can then easily just have the blurry view as the background of the screen.

**Comment by ilmotta** [comment] 2023-02-07 13:02
> @ilmotta I think we shouldn't be compromising on the performance for some design details.

Fair point @OmarBasem, but I don't have the numbers to back up the claim that the performance is bad in general. I think we can all agree the performance is decent at this point. I can try to render the AC in a simpler screen without any blur effect, release it locally and see if I feel any difference. It'll give us a rough estimate if it's worth pursuing optimizations now, otherwise we might be optimizing just for the sake of optimizing without a noticeable difference.

>To simulate the same blurry effect, we can have an Image background of one of the screens and on top of it the blurry view. That should give a very similar look.

I thought about it before, it might be worth a shot since I'm not the only crazy ;)

>If so, you can then easily just have the blurry view as the background of the screen.

Nice Omar, thanks for taking a look. The one thing to keep in mind is that `react-native-blur` is extremely buggy! It simply doesn't work as intended in many cases (I know that Parvesh and Javid also encountered many bugs). So yes, if we're lucky then it would be easy ;)

---

I'll take a deeper look, thanks for the analysis.

**Comment by OmarBasem** [comment] 2023-02-07 13:15
@ilmotta These popovers/modal in mobile apps are a little different from web (where the concept of screen and navigators is simulated). In mobile development it is generally a bad practice to render heavy component in popovers/modals. This explains a bit why: https://medium.com/@amismail/optimizing-react-native-part-1-modals-vs-navigation-18d074a771ce

**Comment by OmarBasem** [comment] 2023-02-07 13:21
> Nice Omar, thanks for taking a look. The one thing to keep in mind is that `react-native-blur` is extremely buggy! It simply doesn't work as intended in many cases (I know that Parvesh and Javid also encountered many bugs). So yes, if we're lucky then it would be easy ;)

I agree, `react-native-blur` is really buggy

**Comment by ilmotta** [comment] 2023-02-08 18:23
@OmarBasem, I did a full investigation and experimentation around this issue.

So first off, the easiest part and probably the key factor here. Today `2023-02-08` there was a meeting with designers, @cammellos and @smohamedjavid, and @John-44 for a walkthrough on the new application settings, more specifically notification settings. Settings screens all use a true blurred background, just as the Activity Centre. 

There was some discussion around the performance impact for users, but it was aligned that **we should use the solution that matches exactly what's in Figma**. Once we dogfood `status-mobile` and collect feedback around the experience, and if we feel like the performance is affecting the UX, then we can go back to the drawing board and see what we can do. We even have the option of getting help from external contributors specialized in ReactNative in case we need to build from scratch (low-level primitives) support for blurred stacked screens.

----
   
Now for more technical stuff:

I changed the Activity Centre to use a stacked screen, and the performance was **reduced** (from the user's perspective). There was a noticeable impact on the animation behavior because re-frame was rendering the notifications + the AC screen in the same batch. This behavior is largely unpredictable given the myriad of components on screen, but also expected and it's documented by re-frame. It's known that if some expensive components are rendered with lighter ones in the same batch, then the UI can become unresponsive. In practice, the animations to open the AC stopped working well, even after releasing for production (no emulation and compiler optimized). What I'm pointing out here is that replacing a modal screen won't automatically give better performance, as was clearly the case for the AC.

But there's a way to force re-frame to avoid rendering some components on the same batch, and if we do that judiciously, then the UI feels as snappy as it can get. The problem is that doing this is time consuming and requires workarounds. I did just that :nerd_face: to see where I'd get (it's in this [branch](https://github.com/status-im/status-mobile/compare/performance/render-activity-center-screen-without-popover?expand=1)) and I must say I'm very satisfied with the performance. The **caveat is that the screen can't blur the one below it**. The workaround if you want to know is: clean up the AC state (ugly...) when it's closed and fetch notifications only after a delay that allows the opening animation to run for around 150ms.

----

Therefore, after much consideration about possible solutions, including using fake blurred backgrounds (there are many downsides to this approach) and the new business requirements around blurred screens, I think we should consider the case closed until we dogfood more as John explained in the meeting.

I'm closing this issue for now also because the performance is acceptable for our current needs. Thanks for bringing the topic to light. By no means it's the end of story ;)

**Closed as completed** 2023-02-08 18:23 UTC
Labels: feature, activity-center

**Comment by OmarBasem** [comment] 2023-02-09 03:17
Thanks, @ilmotta for the deep investigation. I appreciate you taking the time to dissect the problem. 

As for now, one thing that can be improved is the opening and closing animation of the popover. The opening animation has a weird spring, and there is no closing animation. I can try to look into it myself.

**Comment by ilmotta** [comment] 2023-02-09 11:04
> Thanks, @ilmotta for the deep investigation. I appreciate you taking the time to dissect the problem.
> 
> As for now, one thing that can be improved is the opening and closing animation of the popover. The opening animation has a weird spring, and there is no closing animation. I can try to look into it myself.

That'd be a nice improvement for sure o/
