### ISSUE TITLE
iOS UX Issue - No way to delete accounts

### ISSUE THREAD

**Issue by danieljwonder** [status-im/status-react#8591] opened 2019-07-18 03:45 UTC
**UPDATED VERSION:**

When logged out there is no way to remove an account if you don’t know the password to access it without deleting/reinstalling app. 

**ORIGINAL:**

_When restoring an account in the app there is no double confirmation of your password and no way to verify it is correct. 

This means...

If typed wrong there is no way to know what you typed or reset even whilst logged in. 

And results in...

If you log out there is no way to remove the account even though you don’t know the password to access it and no way to delete the offending account either without deleting/reinstalling app._

**Comment by annadanchenko** [comment] 2019-07-18 10:27
thanks for the report but it looks like duplicate of https://github.com/status-im/status-react/issues/7418 so closing it... please, reopen if don't agree.

request: next time can you put in the issue title something more descriptive than "iOS UX Issue", please? It will be super hard to distinguish between 10 issues with same title that all are ux issues. See https://status.im/docs/report_a_bug.html for recommendations on a good bug report.

**Closed as completed by annadanchenko** 2019-07-18 10:27 UTC

**Comment by danieljwonder** [comment] 2019-07-23 01:35
@annadanchenko not sure how to re-open, but updated title/description to be more specific to issue not covered in the ticket you linked.
