### ISSUE TITLE
Sometimes suggestions for send/request and location are not shown after sending emoji [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1460] opened 2017-07-17 13:00 UTC
### Description

*Type*: Bug

*Summary*: Only on iOS: Suggestions are not fully shown, so no recipient username is visible after send emoji in chat
![img_2132](https://user-images.githubusercontent.com/6584810/28268880-49ffbffc-6b00-11e7-9d85-8e611a563ff9.jpg)
![img_2131](https://user-images.githubusercontent.com/6584810/28268884-4db87daa-6b00-11e7-9fe6-ed4b8e7d7346.jpg)

![img_2135](https://user-images.githubusercontent.com/6584810/28269252-aecb7fb0-6b01-11e7-8856-8e69c0664c37.jpg)

#### Expected behavior
Suggestions with recipient name are shown

![img_2134](https://user-images.githubusercontent.com/6584810/28268965-91a656ae-6b00-11e7-9a3a-2914a6227449.jpg)

#### Actual behavior
Only header with a title is shown, no "content" with recipients list is shown

### Reproduction
TestFairy session for send/receive: https://status-im.testfairy.com/projects/4803590-status/builds/6117316/sessions/7
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7UFhXUWVkQ1dfM1E
- Open Status
- Open 1-1 chat with Jarrad (in Contacts tap on Jarrad)
- send some emoji 
- right after emoji is sent tap on request or send command
- check that suggestions for username is visible

### Additional Information
* Status version: develop 0.9.8-78-g670f873d+ 
* Operating System: 
Real device iPhone 6s, iOS 10.2.1

**Comment by retro** [comment] 2017-08-25 15:14
@annadanchenko Is this behavior present in the simulator too? I've tried to replicate it on the simulator (with the latest develop) and it seemed to be working correctly.

I'm having problems with running the app on the device itself, so I just wanted to check if the simulator is good enough

**Comment by annadanchenko** [comment] 2017-08-31 11:44
@retro sorry for the delayed reply. I can't reproduce it on iOS simulator with latest develop build. I also see that on emulator there is no text keyboard shown when I tap on /send or /location command and this might be the reason it's not reproducible on emulator. Issue still can be reproduced on real device.

**Comment by retro** [comment] 2017-09-01 09:03
I will un - assign myself from this issue since I'm not able to run the (develop version) app on iOS currently. I can retest when #1687 is merged, but fixes from that branch don't help in my case.

**Comment by flexsurfer** [comment] 2017-09-04 10:15
i can reproduce on IOS simulator, you can enable keyboard using `command+K`

**Comment by annadanchenko** [comment] 2017-09-04 14:11
tested on ios and android in 1-1 and group chats

**Closed** 2017-10-19 11:10 UTC
Labels: bug, ios, medium-priority, Tested - OK
