### ISSUE TITLE
[IOS] Unable to scan qr-code because local network access permission

### ISSUE THREAD

**Issue by jo-mut** [status-im/status-react#19952] opened 2024-05-09 12:10 UTC
# Bug Report
Qr-code scanner screen asks for local network access even when it has been granted

## Problem 
The device still asks for `local network access` even though this permission has been granted hence the user is unable to launch the Qr-code scanner

Issue is reproducible all the time on iOS devices

#### Expected behaviour
Qr-code scanner should be already activated since the local network access permission has been granted

#### Actual behaviour
Unable to activate the Qr-code scanner, the app still asks for local network access permission even though its already granted

### Reproduction

1. Open app
2. Sign-in by syncing
3. Accept permission
4. Qr-code scanner not active

- Status version: nightly 
- Operating System: iOS

**Comment by ilmotta** [comment] 2024-07-01 22:32
@churik @jo-mut could you provide a little bit more detail about why this issue is marked as `wont fix`? Is it still relevant? Still reproducible?

I'm concerned about this:

> [...] the user is unable to launch the Qr-code scanner. Issue is reproducible all the time on iOS devices

**Comment by jo-mut** [comment] 2024-07-01 23:21
@ilmotta discussing this issue with @cammellos sometime back I remember this being something that has to do with waku and may not be a easy thing to debug or fix. I did not investigate it further and am not sure why `wont fix`

**Comment by churik** [comment] 2024-07-22 10:34
to be honest, I'm not sure either, must be a mistake. Thank you for noticing!
We'll try to reproduce it

**Comment by ilmotta** [comment] 2024-10-08 08:09
Closing because it appears to be a duplicate of https://github.com/status-im/status-mobile/issues/21257

**Closed as completed by ilmotta** 2024-10-08 08:09 UTC
Labels: ios, syncing, re-check
