### ISSUE TITLE
App crashing on pressing new chat from bottom sheet

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#14723] opened 2023-01-06 10:44 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)

https://user-images.githubusercontent.com/17097240/210995150-d4a865e3-c49e-47b9-9104-e66067f08d6d.mp4

**Comment by Parveshdhull** [comment] 2023-01-06 12:29
probable cause: https://github.com/status-im/status-mobile/pull/14607
cc: @ibrkhalil

**Comment by ibrkhalil** [comment] 2023-01-06 12:31
Yup, That's my mistake
Will merge [this ](https://github.com/status-im/status-mobile/pull/14680)asap

**Comment by churik** [comment] 2023-01-09 11:01
Duplicate of https://github.com/status-im/status-mobile/issues/14671

**Closed as completed** 2023-01-14 13:57 UTC
