### ISSUE TITLE
Broken layout of the /send funds message for small amount

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#3512] opened 2018-03-02 20:43 UTC
### Description

*Type*: Bug

*Summary*: When sending small ETH amount in one-to-one or group chat message layout is broken

Android:
<img width="516" alt="screen shot 2018-03-02 at 10 35 02 pm" src="https://user-images.githubusercontent.com/29711298/36920855-c7c901fa-1e6a-11e8-8bd5-4fa9851b8c66.png">

iOS:
<img width="516" alt="screen shot 2018-03-02 at 10 35 02 pm" src="https://user-images.githubusercontent.com/29711298/36920898-ec81ec78-1e6a-11e8-98cc-36a2e6b322c2.jpeg">

 
#### Expected behavior
Small amount should be rounded in the send funds message

#### Actual behavior
Broken layout of the send funds message for both recipient and sender

### Reproduction
- Open Status
- Create new or sign in to existing account
- Open one-to-one or group chat
- Send 0.0000000001 ETH from a chat

### Additional Information
Status version: 0.9.10-740-gba056bee+, 0.9.11d740 (nightly build from 02.03)
Operating System:
OnePlus 5, Android 8.0.0
iPhone 8+, iOS 11.1.1

**Comment by annadanchenko** [comment] 2018-03-19 15:35
@yevh-berdnyk personally I think that transforming sent amount to other amount (even by rounding) might confuse users who see other numbers than what was sent. Let's consult with design team on the common approach to take. Maybe we can use 2 lines for long amounts...

**Comment by annadanchenko** [comment] 2018-03-19 15:36
btw it's duplicate for #941 but I will close the initial issue, as screenshots are outdated there

**Comment by nikitalukianov** [comment] 2018-03-20 14:30
Guys, I'm working on the new design of chat/ messages/ layout and we'll make all space more optimize. But now this bug will fixed by @denis-sharypin in the current layout

**Comment by yevh-berdnyk** [comment] 2018-03-23 11:46
On iPhone 8+ last characters are hidden:
<img width="416" alt="screen shot 2018-03-02 at 10 35 02 pm" src="https://user-images.githubusercontent.com/29711298/37827514-7968dd78-2ea0-11e8-843e-b9ef537687c8.jpeg">

**Comment by denis-sharypin** [comment] 2018-03-26 05:40
@yevh-berdnyk  Hey, it will be properly fixed in the upcoming redesign of the transaction messages.
For now, as a quick fix, we need to decrease a size of those numbers to 15 px(current font size of the messages in the chat) and make sure that `ETH` is 15 px as well.

**Comment by annadanchenko** [comment] 2018-06-17 11:55
fixed by #4692 can't reproduce in nightly jun 18

**Closed as completed by annadanchenko** 2018-06-17 11:55 UTC
