### ISSUE TITLE
Implement the "Network" variant in the "Preview List" component

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#17026] opened 2023-08-16 14:18 UTC
# Feature

Implement the "Network" variant in the `Preview List` component

<img width="550" src="https://github.com/status-im/status-mobile/assets/19339952/5b5829d5-87ba-4a3c-8eb2-1aaa1cb23aba">

### :warning: NOTES

This issue will cover the implementation of missing sizes (20 and 14) in the component

### Designs

[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2219%3A32014&mode=design&t=Fx9sPvHE1N10Zx4e-1)

### Acceptance Criteria:

- Should follow the [best practices](https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md)
- Should add [component test](https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md)

**Comment by ulisesmac** [comment] 2023-08-23 22:32
@smohamedjavid  Is this a duplicate of
- #17008

?

**Comment by smohamedjavid** [comment] 2023-08-24 08:46
Yes, @ulisesmac. 

Initially, this issue was scoped to implement the `network` type but decided to support other variants needed for wallet development such as `collectibles`, `token`, `dapps`,...etc.

I will tag both issues to the PR 👍

**Closed as completed** 2023-08-25 16:11 UTC
Labels: feature, design-system
