### ISSUE TITLE
No push and notification in activity centre for "everyone" mention on Android

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15615] opened 2023-04-11 08:53 UTC
# Bug Report

## Problem 
On Android there is no notification in the activity center or push notification in case of `@everyone` mention. After a while unread indicator on the community is shown, but that's it

#### Expected behavior
can get AC notification and push

#### Actual behavior
<img width="200" alt="Monosnap 2023-04-11 10-52-12" src="https://user-images.githubusercontent.com/4557972/231108027-d247e728-8f55-4b93-8dbd-24b24900739f.png">

### Reproduction
**Prerequisites:** User A and User B are members of the same community
1) User A (desktop): sends `@everyone ` in community 
2) User B: check activity center / push notification

### Additional Information

- Status version: nightly 11/04/23
- Operating System: Android
- Logs: [Status-debug-logs.zip](https://github.com/status-im/status-mobile/files/11198539/Status-debug-logs.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by churik** [comment] 2023-04-11 10:47
Video to demonstrate difference between mentions/ordinary text/`everyone` mention: https://drive.google.com/file/d/1OhgDP5AiT3wqprx6XyUNZXiocdBRy0cI/view?usp=share_link

**Comment by churik** [comment] 2023-04-17 11:04
@cammellos 
I have the same issue on both devices (Android10/Android12) with an enabled push notification service.

All fine when PN service is turned off.

**Comment by cammellos** [comment] 2023-04-17 11:09
oh interesting, I'll have a closer look

**Comment by pavloburykh** [comment] 2023-07-19 07:43
@cammellos hello! 

Currently @everyone mention still does not generate PNs neither on Android nor on IOS. 

Moreover, on Android @everyone mention does not even generate notifications in AC and unread counters. 

Maybe we should keep this issue opened?

**Comment by clauxx** [comment] 2023-09-21 09:27
@pavloburykh I tried it on the current develop branch with the iOS simulator and worked as expected ([recording](https://drive.google.com/file/d/1bJMadoN2-uiYt-I3ItTkLn8VlUNeK1hz/view?usp=drive_link)). Can you confirm if it's still an issue?

**Comment by pavloburykh** [comment] 2023-09-21 10:41
> @pavloburykh I tried it on the current develop branch with the iOS simulator and worked as expected ([recording](https://drive.google.com/file/d/1bJMadoN2-uiYt-I3ItTkLn8VlUNeK1hz/view?usp=drive_link)). Can you confirm if it's still an issue?

@clauxx bug is reproducible in case if PNs are turned on. See comment [here](https://github.com/status-im/status-mobile/issues/15615#issuecomment-1511136837). 

On IOS push notifications currently not working. So you need to test on Android device. 

**Steps:** 

1. Enable push notifications (go to Profile - Notifications - Switch on notifictions)
2. Generate ```@everyone```notification 
3. See if PN/AC notif appears

 **Actual result**: PNs/AC notifs do not appear.

**Comment by ibrkhalil** [comment] 2023-12-17 10:58
![CleanShot 2023-12-17 at 12 55 00](https://github.com/status-im/status-mobile/assets/33176106/eecf408b-0469-48df-a9d5-ce64d2be5ac5)
![CleanShot 2023-12-17 at 12 56 16](https://github.com/status-im/status-mobile/assets/33176106/cb3ad704-03ee-4dfb-99ef-bcc480868feb)

I tried to reproduce but couldn't, Everyone mention is not implemented on mobile AFAIK (It's desktop only) because it's not handled [here](https://github.com/status-im/status-go/blob/9dea2e8875bba654328aaf0e6a5f37c8a45a5cdd/protocol/messenger_mention.go#L282) That's why it shows as 0x0001.
But the PN worked.

**Comment by pavloburykh** [comment] 2023-12-20 12:23
@ibrkhalil yeah, you are right, initial bug is gone, so I am closing this ticket. Regarding ```0x0001``` in Android PN - we will fix it separately. Thank you.

**Closed as completed by pavloburykh** 2023-12-20 12:23 UTC
Labels: messaging
