### ISSUE TITLE
App crashes if tap several times on photo area when capturing a photo

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1774] opened 2017-09-06 17:23 UTC
### Description

*Type*: Bug

*Summary*: App crashes if on Profile image screen tap several times on area with a photo. Can't reproduce on released 0.9.10 version

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onTouchEvent(RCTCameraViewFinder.java:349)
	at android.view.View.dispatchTouchEvent(View.java:9998)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2816)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
	at com.testfairy.p.q.dispatchTouchEvent(SourceFile:188)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2777)
	at android.view.View.dispatchPointerEvent(View.java:10233)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5397)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4834)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4891)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7359)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7237)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7198)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7469)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:143)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
#### Expected behavior
nothing happens if tap several times on a picture area
#### Actual behavior

app crashes

### Reproduction
from 00:23 https://app.testfairy.com/projects/4803622-status/builds/6504857/sessions/5/?accessToken=LJdwEpiLsjl/mnBJZ5AHu/ThfhE
- Open Status
- Open drawer
- edit profile picture
- select Capture
- on Profile image screen tap several times (3-4) on the area where your future selfie is shown and move a finger after each tap. if it does not crash then return back and select Capture again to open Profile image. Usually, after 1-2 attempts app crashes. Sometimes it's enough to tap twice, sometimes you need 3 taps and then 2 more.

### Additional Information
* Status version: develop build  0.9.10-69-gf88c3fea+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1

**Comment by asemiankevich** [comment] 2017-10-04 13:58
I can reproduce it when tapping twice in the QR code scanner of new wallet
![image](https://user-images.githubusercontent.com/28752642/31179634-22b6018c-a925-11e7-9f7b-78beb73c7c34.png)


```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onTouchEvent(RCTCameraViewFinder.java:349)
	at android.view.View.dispatchTouchEvent(View.java:10013)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
	at com.testfairy.p.q.dispatchTouchEvent(SourceFile:188)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
	at android.view.View.dispatchPointerEvent(View.java:10233)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:356)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:6577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by x-goose-x** [comment] 2017-10-04 20:56
Looks like we've run into this before: https://github.com/status-im/status-react/issues/148

For instances of the camera that don't use any touch, I think this can be fixed by preventing touch events on the camera. This can fix choose recipient but not the profile camera. We might be able to work around it using lifecycle functions but I haven't tried yet.

**Comment by annadanchenko** [comment] 2017-10-19 09:32
Can reproduce on develop build (at least on Android real device Galaxy S6): 

Capture photo - when camera is shown then start tapping with 2 fingers (like a drummer :) )  after several taps (5-10) is shows popup and app crashes
https://app.testfairy.com/projects/4803622-status/builds/6896805/sessions/19/?accessToken=ymAqJAs-JWitdXCeMcnUuLPhVkY



java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.lwansbrough.RCTCamera.RCTCameraViewFinder.onTouchEvent(RCTCameraViewFinder.java:349)
	at android.view.View.dispatchTouchEvent(View.java:9998)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2816)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1848)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
	at com.testfairy.p.q.dispatchTouchEvent(SourceFile:188)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2777)
	at android.view.View.dispatchPointerEvent(View.java:10233)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5397)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4834)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4891)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4726)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4692)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4700)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4673)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7359)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7237)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7198)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7469)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:143)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by annadanchenko** [comment] 2017-11-17 19:37
Can reproduce on real Google Pixel XL, Android 8.0.0, build  0.9.10-372-gc9b785ce
Log and video: https://app.testfairy.com/projects/4803622-status/builds/7105015/sessions/3/?accessToken=k9gHLbbA3Of-13-LtsIeVL5edPE

**Comment by status-open-bounty** [comment] 2017-11-18 20:56
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0x7bea0ce62f0e25609fa84c4ed10f88c812ce1961](https://etherscan.io/address/0x7bea0ce62f0e25609fa84c4ed10f88c812ce1961)
Network: Mainnet
Paid to: nrakochy
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by vizanto** [comment] 2017-11-21 08:03
I'm unable to reproduce in Genymotion simulator, was it crashing there as well?
Unfortunately my phone seems get bricked today...

**Comment by andytudhope** [comment] 2017-12-07 07:33
@nrakochy I see that you've had no response from the Iwansbrough team? Any further progress here/other ideas?

**Comment by nrakochy** [comment] 2017-12-16 21:36
@andytudhope  Sorry for the delay. I am working on a work-around as a substitute for fixing the underlying lib...

**Comment by poiga** [comment] 2018-01-03 16:12
I am working on this!

**Closed as completed** 2018-01-16 14:48 UTC
Labels: bounty
