### ISSUE TITLE
Android build fails on linux

### ISSUE THREAD

**Issue by agazso** [status-im/status-react#18207] opened 2023-12-15 17:59 UTC
# Problem

I was trying to build the app on Linux for Android. I followed the instructions from the [documentation](https://status.im/technical/build_status/). 

The `make run-android` steps fails with this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> Process 'command '/home/attila/.local/bin/cmake'' finished with non-zero exit value 1
```

After asking on discord I was advised to run this command, but it gives the same error: `ANDROID_ABI_INCLUDE=x86_64 make run-android`

## Notes

Commit hash: 9e27a36f5e4dad7b0604d0693b34f72ac9d00ca0
I was on `develop` branch (that seems to be the default after cloning the repo).

![Screenshot from 2023-12-15 17-30-56](https://github.com/status-im/status-mobile/assets/230163/4ec73d36-5deb-4b13-b8d3-81897820d16f)

**Comment by siddarthkay** [comment] 2023-12-15 18:50
According to the screenshot
`Process 'command '/home/attila/.local/bin/cmake'' finished with non-zero exit value 1` 
seems to be the core issue.

for status-mobile we do use `cmake` pinned inside `nix` 
ref : https://github.com/status-im/status-mobile/blob/develop/nix/pkgs/android-sdk/compose.nix#L19
but for some reason in this case your environments `cmake` is being given preference over whats there in `nix`

**Comment by agazso** [comment] 2023-12-15 19:39
Indeed, the my local `cmake` was the problem. If I renamed my local `cmake` to something else and rerun the command it worked after that.

**Comment by siddarthkay** [comment] 2023-12-15 19:54
Thanks for confirming @agazso!

I'll still keep this issue open and try to reproduce this error in my environment and fix it properly.

**Comment by siddarthkay** [comment] 2023-12-16 09:31
Hi @agazso : could you pls let me know the version of `cmake` that you had locally that caused this problem?

`cmake --version` should tell us.

Could you also tell me a bit more about your linux environment? like your linux distro, version etc

**Comment by agazso** [comment] 2023-12-16 11:39
> Hi @agazso : could you pls let me know the version of `cmake` that you had locally that caused this problem?

Sure, here they are.

I had actually two `cmake` versions installed. The one that was the default, but did not work and had to be renamed was this:

```sh
% ~/.local/bin/cmake.renamed -version
cmake version 3.26.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

After I renamed that one this became the default one and with this one it worked:

```sh
% which cmake
/usr/bin/cmake
% cmake -version                     
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Linux is Pop!_OS 22.04 LTS, which is based on Ubuntu 22.04.

Please let me know if you need further information.

**Comment by siddarthkay** [comment] 2023-12-26 08:49
Hi @agazso : I am closing this issue for now, considering having multiple versions of `cmake` installed is a very edge case scenario.

I also tried to reproduce this error on my Linux OS by installing making sure that the `cmake` executable is present at `./local/bin/cmake` but I was able to get `make run-android` to work fine.

<img width="1421" alt="Screenshot 2023-12-26 at 2 17 36 PM" src="https://github.com/status-im/status-mobile/assets/64726664/398385f0-160a-41a9-86b6-837b60e134fe">

Please feel free to re-open this issue should you face it again.

**Closed as completed by siddarthkay** 2023-12-26 08:49 UTC
