### ISSUE TITLE
Remove hot reload while theme changing

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#20563] opened 2024-06-25 12:01 UTC
### Summary

For some reason we added hot-reload for debug builds while changing theme.

https://github.com/status-im/status-mobile/issues/19794#issuecomment-2084615572

Most probably we don't need that because release builds are working fine.

Whoever works on this try changing theme while app is open (better using system theme) to see if debug app works fine. Also test overlay, like bottom sheet while testing.

(Ignore status-bar colors, they maybe be broken)

**Comment by ilmotta** [comment] 2024-06-25 17:43
@Parveshdhull, I'm not working on this issue, but since you asked for people to double-check I'm sharing what I got now: I did a few theme changes from within the app settings with the OS theme in light & dark mode, and all possible combinations, and I didn't see any regressions from removing the hot-reload call. Although I only checked in emulated Android and with API 33, so take it with a grain of salt.

**Closed as completed** 2024-07-08 09:21 UTC
Labels: tech-debt, mobile-core
