### ISSUE TITLE
[iOS] The composer overlapped the status bar

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18536] opened 2024-01-17 11:34 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)
When user types long multiline message and then adds images composer overlapps the status bar

#### Expected behaviour
The composer doesn't overlapping the status bar

#### Actual behaviour
 The composer used a part of the status bar and overlapped it

### Reproduction

1. Open chat
2. Type multiline message
3. Add 7+ images 
![photo_2024-01-17_12-32-25](https://github.com/status-im/status-mobile/assets/147824399/2ca5ac1b-36dd-4264-8e01-00b85edea7e3)

### Additional Information

- Status version: nightly from 17 of January
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment] 2024-01-17 11:48
duplicate of https://github.com/status-im/status-mobile/issues/17842

**Comment by Parveshdhull** [comment] 2024-01-17 11:49
or extension of https://github.com/status-im/status-mobile/issues/17842?

**Closed as completed by Parveshdhull** 2024-01-17 11:48 UTC
Labels: ios
