### ISSUE TITLE
App crashes after opening and then closing an image that has been just sent in chat

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15395] opened 2023-03-16 15:57 UTC
**cc @OmarBasem** 

For now I have been able to reproduce on Android only. 

**Steps:**

1. Open any chat
2. Send message containing image/images
3. Open the image right after sending it
4. Close the image (try closing both by swiping down and tapping close button)
5. Observe error and crash

**NOTE:** you might not reproduce the bug from the first try. Keep sending new images and follow steps 3-4 until you see error and crash. 

**Actual result:** error appears and app crashes (see screenshot and video below)

[Status-debug-logs (24).zip](https://github.com/status-im/status-mobile/files/10992732/Status-debug-logs.24.zip)

![photo_2023-03-16 17 43 03](https://user-images.githubusercontent.com/97245802/225672306-0b074670-2c30-4811-9be5-9c20255809ca.jpeg)

https://user-images.githubusercontent.com/97245802/225672106-10c80f58-4dc5-46dc-b8a6-4a841fe641d6.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android

**Comment by OmarBasem** [comment] 2023-03-17 06:02
~This crash happens also on iOS (when opening a single image) with error: `No protocol method DateTimeProtocol.plus- defined for type null:`~

~So this error happens due to a layout animation that contains a component trying to calculate the date/time. In debug mode it works, but in release mode it causes a crash.~

UPDATE: was fixed in https://github.com/status-im/status-mobile/pull/15422

**Comment by pavloburykh** [comment] 2023-03-17 06:22
> This crash happens also on iOS (when opening a single image) with error: `No protocol method DateTimeProtocol.plus- defined for type null:`

Isn't it a different issue that has already been fixed by you yesterday @OmarBasem ? https://github.com/status-im/status-mobile/issues/11489

**Comment by OmarBasem** [comment] 2023-03-17 06:23
@pavloburykh nope, that was something else

**Comment by pavloburykh** [comment] 2023-03-17 06:25
> @pavloburykh nope, that was something else

okay, got it.

**Comment by OmarBasem** [comment] 2023-03-17 06:26
@pavloburykh oh I see similar titles to the issues, so there was actually 2 different issues causing crash when opening an image. I fixed one yesterday. And there is another one.

**Comment by pavloburykh** [comment] 2023-03-17 06:29
> @pavloburykh oh I see similar titles to the issues, so there was actually 2 different issues causing crash when opening an image. I fixed one yesterday. And there is another one.

Let's see: 

There was an issue https://github.com/status-im/status-mobile/issues/15389 that has been fixed by you yesterday. Current issue https://github.com/status-im/status-mobile/issues/15395 has been discovered as a result of fixing https://github.com/status-im/status-mobile/issues/15389 . Cause before https://github.com/status-im/status-mobile/issues/15389 has been fixed it was impossible to open image right after sending and it is required for reproduction of current bug.

**Comment by pavloburykh** [comment] 2023-03-17 06:31
> This crash happens also on iOS (when opening a single image) with error: `No protocol method DateTimeProtocol.plus- defined for type null:`

So I guess, here you are speaking about the bug https://github.com/status-im/status-mobile/issues/15389 that has been already fixed yesterday. Correct me if I am wrong.

**Comment by OmarBasem** [comment] 2023-03-17 06:31
To avoid confusion, when you were testing my PR yesterday, you did not get that error at all?: `No protocol method DateTimeProtocol.plus- defined for type null:` (on iOS, when opening a single image)

I am able to reproduce it on latest develop.

**Comment by pavloburykh** [comment] 2023-03-17 06:33
> To avoid confusion, when you were testing my PR yesterday, you did not get that error at all?: `No protocol method DateTimeProtocol.plus- defined for type null:` (on iOS, when opening a single image)
> 
> I am able to reproduce it on latest develop.

no, I haven't got this error in your PR. Let me check develop too.

**Comment by OmarBasem** [comment] 2023-03-17 06:43
@pavloburykh if you can't reproduce it on develop, then that means it also happens randomly, cause I was able to repoduce it release mode only. But I already know the reason for the bug, and I will fix it. No worries.

**Comment by pavloburykh** [comment] 2023-03-17 06:43
> To avoid confusion, when you were testing my PR yesterday, you did not get that error at all?: `No protocol method DateTimeProtocol.plus- defined for type null:` (on iOS, when opening a single image)
> 
> I am able to reproduce it on latest develop.

@OmarBasem could you please provide steps/screenshot how you reproduce this error on develop. 

In develop I currently see the following errors:

1. On Android this error, which is actually reported by current ticket https://github.com/status-im/status-mobile/issues/15395
![photo_2023-03-17 08 42 11](https://user-images.githubusercontent.com/97245802/225831675-e05c51c5-65df-4072-a14f-073e44542fdc.jpeg)

2. On IOS I am facing this error https://github.com/status-im/status-mobile/issues/15391
![photo_2023-03-17 08 43 43](https://user-images.githubusercontent.com/97245802/225831938-cf926456-fdd6-408d-b6d3-34da5982cc69.jpeg)

**Comment by pavloburykh** [comment] 2023-03-17 06:45
> @pavloburykh if you can't reproduce it on develop, then that means it also happens randomly, cause I was able to repoduce it release mode only. But I already know the reason for the bug, and I will fix it. No worries.

Great, thank you @OmarBasem !

**Comment by OmarBasem** [comment] 2023-03-29 10:00
UPDATE: ios bug above was fixed in https://github.com/status-im/status-mobile/pull/15422

**Comment by OmarBasem** [comment] 2023-03-29 10:07
After hours of debugging the cause of this crash on Android, it seems to be coming from Reanimated. Particularly from [that file](https://github.com/software-mansion/react-native-reanimated/blob/main/android/src/reactNativeVersionPatch/nativeHierarchyManager/62/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java).

There is an open issue in reanimated for someone facing this same problem and is using very similar RN and reanimated versions to what we are using: https://github.com/software-mansion/react-native-reanimated/issues/3080

The file above has changed considerably between versions 2.3.0 (what we are using) and the latest reanimated version (3.0.2). There is a good chance that this error can be fixed by upgrading RN and Reanimated versions.


@pavloburykh would you mind excluding this issue from RC2, as upgrading the library versions is not feasible right now

**Comment by OmarBasem** [comment] 2023-05-11 14:38
Dependant on Reanimated upgrade, which is dependant on RN upgrade

**Closed as completed** 2023-07-14 11:19 UTC
Labels: android, blocked
