### ISSUE TITLE
"Enable light client" crashes the app on IOS

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20244] opened 2024-05-29 11:20 UTC
# Bug Report

## Problem 
Enabling light client crashes app on login or a bit later after

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/eb8ad975-1ef2-41ce-b03a-103686d6f5ed

### Reproduction

1. Go to Advanced > Enable lightclient
2. Try to login

### Additional Information

- Status version: release 2.29 (tried on nightly 29/05/24)
- Operating System:  iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment] 2024-05-29 11:56
@churik do you have raw geth logs please?

**Comment by cammellos** [comment] 2024-05-29 11:56
sorry @churik adb logs

**Comment by siddarthkay** [comment] 2024-05-30 12:00
One warning that i noticed was this

```
nw_socket_handle_socket_event [C16.1.1.1:3] Socket SO_ERROR [61: Connection refused]
```

But this is harmless and not the root cause.

**Comment by siddarthkay** [comment] 2024-05-30 12:03
Logs are pretty obscure to be honest. This is what it looks like. I'll try to find more meaningful stuff and post here.
 
![Screenshot 2024-05-30 at 5 25 01 PM](https://github.com/status-im/status-mobile/assets/64726664/296cb482-2ad3-49db-8527-719692b24b84)

**Comment by siddarthkay** [comment] 2024-05-30 14:29
@cammellos : I was able to extract this crucial piece of info : 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102426d00]

goroutine 7230 [running]:
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode.(*Node).Seq(0x39b04fad0?)
	/private/tmp/nix-build-status-go-0.179.24-701b276-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/node.go:89
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager.(*PeerManager).AddDiscoveredPeer(0x3a93da370, {0x4, {{0x39b04fad0, 0x27}, {0x130f45cc0, 0x3, 0x4}}, 0x0, {0x39d982370, 0x1, ...}}, ...)
	/private/tmp/nix-build-status-go-0.179.24-701b276-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go:438 +0x1f4
github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node.(*WakuNode).AddDiscoveredPeer(...)
	/private/tmp/nix-build-status-go-0.179.24-701b276-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:710
github.com/status-im/status-go/wakuv2.(*Waku).connect(0x1309cc780, {{0x39b04fad0, 0x27}, {0x130f45cc0, 0x3, 0x4}}, 0x4)
	/private/tmp/nix-build-status-go-0.179.24-701b276-ios.drv-0/go/src/github.com/status-im/status-go/wakuv2/waku.go:452 +0x11c
created by github.com/status-im/status-go/wakuv2.(*Waku).runPeerExchangeLoop in goroutine 6577
	/private/tmp/nix-build-status-go-0.179.24-701b276-ios.drv-0/go/src/github.com/status-im/status-go/wakuv2/waku.go:523 +0x540
```
coincidence?

**Comment by cammellos** [comment] 2024-05-30 14:30
@siddarthkay no, it's fixed in my PR already, good spot! cc @churik

**Comment by siddarthkay** [comment] 2024-05-30 14:32
you're welcome

**Comment by vitvly** [comment] 2024-05-30 15:13
Same for me here

<img width="840" alt="Screenshot 2024-05-30 at 18 13 04" src="https://github.com/status-im/status-mobile/assets/1019573/a5b756f7-1952-4fb4-a252-d8ce9455bce3">

**Comment by cammellos** [comment] 2024-05-30 15:17
awesome, this should be fixed then soon

**Comment by siddarthkay** [comment] 2024-05-31 06:04
> it's fixed in my PR

I assume that when PR is https://github.com/status-im/status-mobile/pull/20255 is merged, the crash would go away but I reproduced a similar crash with same steps and I have attached the log file below.

[crash.log](https://github.com/user-attachments/files/15508987/crash.log)

**Comment by pavloburykh** [comment] 2024-05-31 08:39
Closing the issue again. Sid's crash was most likely related to Xcode cache. Not reproducible after ```make clean``` and cleaning up Xcode cache.

**Closed as completed by pavloburykh** 2024-05-31 08:39 UTC
