### ISSUE TITLE
Can be redirected to login screen with password if multiaccount was created with keycard ("Back" button from login screen)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9728] opened 2019-12-26 14:59 UTC
# Bug Report

## Problem
It shouldn't be possible to navigate to login screen with password input if multiaccount was created with keycard.
Not if you logout and tap back (until first reopen app) - you will see invalid login screen (with password input instead of PIN code input)
![2019-12-26 15 52 03](https://user-images.githubusercontent.com/4557972/71480185-37d06b80-27f8-11ea-996f-4f001e56f47d.gif)
Issue is not reproducible after reopening app.

#### Expected behavior
list of multiaccounts.

#### Actual behavior
login screen with password input.

### Reproduction

- Open Status
- Create account with keycard
- Log out
- Tap back

### Additional Information
- Status version: nightly 26.12.2019
- Operating System: Android

**Comment by guylouis** [comment] 2020-01-06 13:40
Thanks reproduced too on nightly from 06/01/2020

**Comment by guylouis** [comment] 2020-02-10 14:07
Could not reproduce on nightly from 06/02/2020
- created new account  on keycard
- signed out 
- tap back 
-> I see the login screen

**Comment by guylouis** [comment] 2020-11-06 05:52
I am closing this because it's impossible to reproduce anymore 
clean up

**Closed as completed by guylouis** 2020-11-06 05:52 UTC
