### ISSUE TITLE
Same contact/chat is showing different names

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5157] opened 2018-07-12 21:09 UTC
**Type**: Bug
**Summary**: Username on the left panel is different from the name on chat's top header:

<img width="1429" alt="captura de pantalla 2018-07-12 a la s 6 12 48 p m" src="https://user-images.githubusercontent.com/37297779/42659744-8ee8b536-85ff-11e8-8010-38c2223589a2.png">

**Current behavior**
Left panel is showing the contact name, but a random name is shown on the chat's top header. 

**Expected behavior**
Since the person sent me a message first, I should see his "real" -account- name ("Robert" in this example).

**To Reproduce**

1. Open app
2. Ask another contact to send you a message (don't add him/her as a contact)
3. Open that chat
4. Compare name on top header vs left panel

Note: This only happens with the first on the list, it doesn't happen with the rest of the contacts/chats.

**Comment by churik** [comment] 2018-07-13 07:13
It is duplicate of https://github.com/status-im/status-react/issues/5147

**Closed as completed by churik** 2018-07-13 07:13 UTC
