### ISSUE TITLE
Let users type search queries in the address bar of the browser like the Status desktop app

### ISSUE THREAD

**Issue by du82** [status-im/status-react#12434] opened 2021-08-09 02:09 UTC
Let the user choose between browsers to automatically search for queries in the browser, while letting the app automatically handle Ethereum addresses like it does now.

I really suggest DuckDuckGo as a default, and the Brave browser as a secondary alternative.

**Comment by churik** [comment] 2021-09-22 11:26
duplicate of https://github.com/status-im/status-react/issues/10575

**Closed as completed by churik** 2021-09-22 11:26 UTC
Labels: feature
