### ISSUE TITLE
top bar glitches

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#16266] opened 2023-06-14 08:36 UTC
1) when opening chat the top bar behaves wrong

https://github.com/status-im/status-mobile/assets/11790366/d8346666-0bd0-4069-b5b0-d3e8234b24a8

2) if the chat screen opened in some state it might look broken

<img width="330" alt="image" src="https://github.com/status-im/status-mobile/assets/11790366/89d26852-5d6b-4abd-bfaf-2775e364e567">

**Comment by qoqobolo** [comment] 2023-06-14 14:23
On iOS the top bar does not render until you scroll the chat., looks related.
@alwx is it known or smth new?
Or maybe the same as Issue 1 here: https://github.com/status-im/status-mobile/issues/16160

Currently, I can only reproduce this in a community on iOS

https://github.com/status-im/status-mobile/assets/67952253/ff993ff9-bd9b-44d6-9bf5-d48c32950460

**Comment by alwx** [comment] 2023-06-14 14:37
I appreciate the effort but those issues are only distracting because they all are about the same, they are well-known already and, in addition to that, there is one big issue dedicated to the top bar: https://github.com/status-im/status-mobile/issues/16160

I'm moving its content to a comment of the one above just because they all need to be addressed in the same PR.

**Closed as completed by alwx** 2023-06-14 14:37 UTC
