### ISSUE TITLE
Top bar followup issues

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16564] opened 2023-07-11 18:41 UTC
followup of https://github.com/status-im/status-mobile/pull/16506 cc @alwx 

### ISSUE 1 Top bar disappears when user is at the beginning of chat history (IOS)

Reproducible on IOS only

**Steps:** 

1. Start a new chat
2. Send a couple of messages
3. See if top bar is displayed when closing/opening keyboard

**Actual result:** top bar disappears. 

https://github.com/status-im/status-mobile/assets/97245802/7190d2d2-30a7-421e-8b89-49d61823b36b

### Additional Information

- Status version: nightly 
- Operating System: iOS

**Comment by pavloburykh** [comment] 2023-07-11 18:41
### ISSUE 2 See comments from @Francesca-G related to top bar

[Figma frame](https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=3350%3A274771&mode=design&t=HifnL7wq7x6ouCq2-1)

**Comment by churik** [comment] 2023-07-14 14:18
### ISSUE 3

On 1.24:
IPhone 14 Pro:
![IMAGE 2023-07-14 16:17:54](https://github.com/status-im/status-mobile/assets/4557972/d376d026-734a-4c86-8663-82a534c1b7a7)

Google Pixel 7A:

https://github.com/status-im/status-mobile/assets/4557972/e364b809-28d2-4cde-a49e-c2e21ee044e7

**Comment by pavloburykh** [comment] 2023-08-01 15:20
### ISSUE 4 Top bar disappears after removing user from contacts and going back to 1-1 chat (Android)

Reproduced on Android 12, Samsung Galaxy A52

**Preconditions:** User A (Android) and User B (any other platform) are mutual contacts. They have 1-1 chat with some amount of history in it and at least 1 message from User B. 

**Steps:** 

1. User A enters 1-1 chat with User B
2. User A opens User's B profile screen by tapping on his profile icon aside of his message in chat
3. User A removes User B from contacts
4. User A goes back to 1-1 chat
5. Pay attention at top bar

**Actual result:** top bar disappeared. It re-appears after chat re-opening. 


https://github.com/status-im/status-mobile/assets/97245802/9428bc61-ffd5-4f20-912c-e092caa2040b

**Comment by churik** [comment] 2023-08-30 09:33
@pavloburykh is it https://github.com/status-im/status-mobile/issues/16564#issue-1799553356 reproducible for you? 
I can't if i try  on IPhone 14.

**Comment by pavloburykh** [comment] 2023-08-30 09:38
> @pavloburykh is it [#16564 (comment)](https://github.com/status-im/status-mobile/issues/16564#issue-1799553356) reproducible for you? I can't if i try on IPhone 14.

Yes, still reproducing on my iPhone X


https://github.com/status-im/status-mobile/assets/97245802/d76f08f6-ec54-4ae8-9838-dbb318f82ac7

**Comment by alwx** [comment] 2023-09-07 11:14
Top bar stability PR has been merged! 
But I will keep this issue open to submit updates to design as part of it.

**Comment by alwx** [comment] 2023-09-14 14:16
Wrote about it in discord but got no answer so I'm closing this one and keeping the comment from discord pasted here. Please, open separate issues for stuff that requires attention!

---

I'm missing what exactly still needs to be done now — the top bar was adapted to the dark theme in the last PR, and what's remaining are these two issues:

1) Different blurs for the bar itself and the button (so that the bar itself is "less" transparent than the button that's on that bar — see screenshot attached) — I tried multiple ways to achieve that but don't see how it can be done. The comment given by designers is "If you have two layers with transparency on top of each other, the top layer is seen by the sum of the transparencies. Please check layers opacities, order and colours" — sorry, it sounds great in theory but the reality is that we use an extrnal library for blur that doesn't support deeper customization + I don't really see how this comment is helpful in achieving this goal. We can track this issue separately but I doubt it's doable.

<img width="375" alt="Screenshot 2023-09-12 at 16 57 30" src="https://github.com/status-im/status-mobile/assets/911127/5868e6a1-fa3f-4caa-a432-65e7ff88e907">

2) It's impossible to see the title of the bar when the height of the content area is not big enough (which means the animation cannot really work properly for the title to be put into place) — see this comment https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3678:7819&mode=design#510615112. I'm pretty sure something can be done about that but I'm struggling to understand what exactly. It's kinda obvious why this happens, and there is no miscalculation or anything but I don't understand what's the right approach we should use to fix that. Can anybody from the designers help to get to the right solution?


3) Is there something else I'm missing?

**Closed as completed by alwx** 2023-09-14 14:16 UTC

**Comment by churik** [comment] 2023-09-14 14:17
cc @Francesca-G @pedro-et
