### ISSUE TITLE
Can't leave signing screen in case of losing internet connection

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#9977] opened 2020-02-05 10:13 UTC
# Problem

When signing transaction initiated and internet disconnected user can't exit signing screen. `Cancel` button is available but not functioning. After some time we will get timeout error but until this not grayed out `Cancel` is confusing.

![Screenshot 2020-01-31 at 12 24 53](https://user-images.githubusercontent.com/5786310/73831902-c54ba600-480f-11ea-9838-7d7e27eb7ac1.png)

## Steps to reproduce
- initiate stickerpack purchasing
- sign with the password and quickly turn off the internet
You will stay in signing screen with spinner running and non-functional `Cancel` button.

## Implementation

TBD

## Acceptance Criteria

TBD

**Comment by vkjr** [comment] 2020-02-05 10:15
@errorists, looks like UX issue, wdyt?

**Comment by 0x-r4bbit** [comment] 2020-04-20 12:45
Seems like this can't reproduced in a simulator because even if WIFI and mobile data is turned off it'll still sign messages. 

Trying to setup testing with real device now

**Comment by hesterbruikman** [comment] 2020-08-24 10:53
Fixed in https://github.com/status-im/status-react/pull/10388

**Closed as completed by hesterbruikman** 2020-08-24 10:53 UTC
