### ISSUE TITLE
Communities - Authentication drawer issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19193] opened 2024-03-12 10:31 UTC
# Design Feedback 2.27

## [Communities] Authentication drawer when joining a community
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=4%3A111403&mode=design&t=IwKFMlZGTBic5nwK-1) 

- **Drawer title** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35457&mode=design#712613062)] is too big compared to design tracked here https://github.com/status-im/status-mobile/issues/19525
- **Context tag has the wrong size** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35457&mode=design#712612985)] tracked here but not solved status-im/status-mobile/issues/17560
- **Asking password but should be biometrics** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35457&mode=design#711330126)] tracked here [status-im/status-mobile/issues/17630](https://github.com/status-im/status-mobile/issues/19188)
- **Button has wrong state** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35457&mode=design#711339241)] button should be disabled if the password input is empty
- **Keyboard should be opened** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35457&mode=design#711339241)] when opening the authentication drawer
- **Input field should be in active state** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35457&mode=design#711339241)] since the keyboard is open and ready to type

<img width="500" alt="Screenshot 2024-03-12 alle 11 26 50" src="https://github.com/status-im/status-mobile/assets/122543089/7d7e1904-9c76-4df0-b462-900851d46b35">

### Reproduction

1. Open a community
2. Press the Join button

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment] 2024-11-04 21:13
Closing as resolved because the flows to join a community changed from 2.27 and I can't reproduce the problems anymore.

**Closed as completed by ilmotta** 2024-11-04 21:13 UTC
Labels: community, community-permissions, mobile-core, design-feedback
