### ISSUE TITLE
Wrong opacity of the "I understand my password can't be recovered" disclaimer 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15509] opened 2023-03-28 09:23 UTC
# Bug Report

## Problem 

**Design:**

<img width="309" alt="Screenshot 2023-03-28 at 11 16 31" src="https://user-images.githubusercontent.com/67952253/228189623-f363d90a-09fc-492d-adfc-11098737186a.png">

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=2257-254440&t=tlEyMdlHj7rGbznB-4

**Current implementation:**

<img width="649" alt="Screenshot 2023-03-28 at 11 18 37" src="https://user-images.githubusercontent.com/67952253/228190156-c3d633f8-136e-41b4-84bb-5584cada79e7.png">

### Reproduction

1. Start creating a new account
2. On the `Create profile password` screen tap the `Repeat password` field to make the "I understand my password visible

### Additional Information

- Status version: nightly 28/03
- Operating System: Android, iOS

cc @ulisesmac

**Comment by ulisesmac** [comment] 2023-03-28 15:28
Hi @qoqobolo !

The problem is we lack of some disclaimer variants, I opened this issue (solved): https://github.com/status-im/status-mobile/pull/15462
and while solving it, I noticed we also lack of some other variants (the selectors): https://github.com/status-im/status-mobile/issues/15463 and I'm working on it.

I'll solve this one when its dependencies are ready! :+1:

**Comment by qoqobolo** [comment] 2023-03-28 15:33
Thank you @ulisesmac!

**Comment by VolodLytvynenko** [comment] 2023-04-20 14:47
Issue reproducible again.  That's why the issue is reopened

**Comment by ulisesmac** [comment] 2023-04-20 19:27
> Issue reproducible again. That's why the issue is reopened

Hey @VladimrLitvinenko  I noticed it was due to a recent PR, I was going to solve it in this PR: https://github.com/status-im/status-mobile/pull/15692#discussion_r1171991102, but I closed it, I'll submit a fix soon and let you know

**Closed as completed** 2023-04-26 01:13 UTC
Labels: onboarding
