### ISSUE TITLE
User can not add his existing ENS name to v.1 app

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20468] opened 2024-06-14 13:40 UTC
# Bug Report

We found this issue while testing Profile data migration in scope of https://github.com/status-im/status-mobile/pull/20412 testing.
Also there is an email from Theo Loth <[theo@loth.nl](mailto:theo@loth.nl)> where the user reports the same issue. 

### Reproduction

1. Install app with v.1 (you can find it [here](https://github.com/status-im/status-mobile/pull/20123))
2. Recover your account that contain ENS name
3. Go to Profile -> ENS 
4. Enter your ENS name

#### Expected behavior

ENS name exist and available to be added to your Profile

#### Actual behavior

User cannot add his ENS name. 
Error : Username doesn't belong to you :(

<img width="306" alt="Screenshot 2024-06-14 at 15 05 39" src="https://github.com/status-im/status-mobile/assets/147824399/cedcfb7a-4601-4056-b396-f1032ad2185e">

Logcat logs: [ENS.log.zip](https://github.com/user-attachments/files/15838803/ENS.log.zip)
Shake logs:  [Status-debug-logs.zip](https://github.com/user-attachments/files/15838874/Status-debug-logs.zip)

### Additional Information

- Status version: v.1 android build (1.20)
- Operating System: Android (have no ability to check it on iOS yet)

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment] 2024-06-17 12:49
@mariia-skrypnyk, isn't the issue https://github.com/status-im/status-mobile/issues/20474 a duplicate of this one (or vice-versa)? If they are duplicates, we can close one of them.

**Comment by mariia-skrypnyk** [comment] 2024-06-17 14:20
Ops @ilmotta 😵‍💫 , will communicate to @qfrank and close one of this

**Comment by qfrank** [comment] 2024-06-18 10:25
Hi @mariia-skrypnyk , what network were you using when reproducing `Username doesn't belong to you` ?
Did you try Mainnet ?

**Comment by mariia-skrypnyk** [comment] 2024-06-18 10:40
Hey @qfrank !

Thanks for working on this issue.

I've rechecked on iOS v.1 app and it happens on Mainnet.

<img width="328" alt="Screenshot 2024-06-18 at 12 38 44" src="https://github.com/status-im/status-mobile/assets/147824399/08783fca-74fb-4bd9-a5fa-f94b495462a7">

**Comment by qfrank** [comment] 2024-06-19 10:48
> Hey @qfrank !
> 
> Thanks for working on this issue.
> 
> I've rechecked on iOS v.1 app and it happens on Mainnet.
> 
> <img alt="Screenshot 2024-06-18 at 12 38 44" width="328" src="https://private-user-images.githubusercontent.com/147824399/340643980-08783fca-74fb-4bd9-a5fa-f94b495462a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODA3ODMsIm5iZiI6MTcxODc4MDQ4MywicGF0aCI6Ii8xNDc4MjQzOTkvMzQwNjQzOTgwLTA4NzgzZmNhLTc0ZmItNGJkOS1hNWZhLWY5NGI0OTU0NjJhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNzAxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGU4MjcyYzNmNDcwYjE0MzBlMjhmMTA3ZDhmYzMyYzQ4YmI3YWE2OWMzZTQ1ZjNhMjVjZGI5MmI2ZmNhZjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XBGUhf6qfWs-GuJF9-C3aTa3DpmZzTFos8nShcMxSEY">

Hi @mariia-skrypnyk , where you get the v.1 ios version ? I'm unable to switch network 
<img width="409" alt="image" src="https://github.com/status-im/status-mobile/assets/12406719/27160389-c34e-4743-b38e-3952344cf36e">

**Comment by qfrank** [comment] 2024-06-19 10:50
on goerli network, when searching ens name owner, the backend got this error:
```
t=2024-06-18T14:45:01+0000 lvl=eror msg="failed to obtain owner of ENS username" error="{\"request_id\":\"71573f91d2\", \"details\":\"error processing the request: error parsing relay: chain not found by alias goerli-archival or domain goerli-archival.rpc.grove.city\"}"
t=2024-06-18T14:45:01+0000 lvl=warn msg="Served ens_ownerOf" reqid=33 t=212.544692ms err="{\"request_id\":\"71573f91d2\", \"details\":\"error processing the request: error parsing relay: chain not found by alias goerli-archival or domain goerli-archival.rpc.grove.city\"}"
``` 

cc @cammellos

**Comment by qfrank** [comment] 2024-06-19 10:55
on mainnet (I used local debug ios build and default to mainnet), when searching ens name owner, the backend got this error:
```
t=2024-06-19T10:01:44+0000 lvl=eror msg="failed to obtain owner of ENS username" error="Post \"https://eth-archival.gateway.pokt.network/v1/lb/\": EOF"
t=2024-06-19T10:01:44+0000 lvl=warn msg="Served ens_ownerOf" reqid=35 t=9.019137875s err="Post \"https://eth-archival.gateway.pokt.network/v1/lb/\": EOF"
```

cc @cammellos

**Comment by mariia-skrypnyk** [comment] 2024-06-21 08:56
Hi @qfrank !

I have it in my Testflight app.
@siddarthkay created them for testing.

1.20.6 

![photo_2024-06-21_10-55-55](https://github.com/status-im/status-mobile/assets/147824399/68b3ff5c-dc65-4d7c-8e7c-1cf1a9b6dc49)

**Comment by qfrank** [comment] 2024-06-21 09:00
ok, could you try this [PR](https://github.com/status-im/status-mobile/pull/20509)? thank you @mariia-skrypnyk

**Comment by churik** [comment] 2024-06-21 14:26
cross-linking with https://github.com/status-im/status-mobile/issues/18760

**Comment by ilmotta** [comment] 2024-08-20 01:02
I'm closing this issue because we won't solve it for 2.30. For better or worse, v1 is going to the history books.

**Closed as completed by ilmotta** 2024-08-20 01:02 UTC
Labels: android, mobile-core
