### ISSUE TITLE
Implement 'Pending requests' bottom sheet

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15555] opened 2023-03-31 14:56 UTC
# Bug Report

## Problem 

Currently, when you click on a pending request in the `Contacts` tab on the chat screen, it redirects to the activity center.
By design, a specific `Pending Request` bottom sheet with sub-tabs `Received` and `Sent` should open instead.

Briefly discussed [here](https://github.com/status-im/status-mobile/pull/15415#issuecomment-1488816241).

#### Expected behavior

<img width="1401" alt="Screenshot 2023-03-30 at 18 31 59" src="https://user-images.githubusercontent.com/67952253/228903757-d4153783-36f6-4253-bbf0-6be9e29b1c7c.png">

https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=2010-507764&t=J68ff7AFk1Bb3YF3-4

#### Actual behavior

https://user-images.githubusercontent.com/52490791/228580722-cc7bf0ca-ae78-494e-b440-63f67ae2e5eb.mp4

### Reproduction

1. Send CR to any user
2. Open AC
3. Remove the notification for the outgoing CR in the activity center
4. Open messager -> open the 'contacts' tab
5. Check 'Pending request'

### Additional Information

- Status version: nightly 31/03
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment] 2023-04-02 18:25
Duplicate of https://github.com/status-im/status-mobile/issues/14306

**Closed as completed** 2023-04-03 08:28 UTC
Labels: feature
