### ISSUE TITLE
Wallet connect proposal is not rejected on some dApps' side

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20894] opened 2024-07-26 09:52 UTC
# Bug Report
https://github.com/status-im/status-mobile/pull/20836

For now this example https://yearn.fi/ was found

### Reproduction

1. Trigger wallet connect proposal with given dApp
2. Decline proposal on Status app side
3. See if proposal has been declined in https://yearn.fi/ side

#### Actual behavior

nothing happens on sApp side, QR is still open.

https://github.com/user-attachments/assets/e2c902fd-aed7-4653-9b7d-d1fd02138f71

#### Expected behavior

QR should close

### Additional Information

- Status version: found in this PR https://github.com/status-im/status-mobile/pull/20836
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by mohsen-ghafouri** [comment] 2024-09-25 10:40
Hey @mariia-skrypnyk, thanks for reporting this issue, with latest changes i couldn't reproduce the issue anymore, could you please check and see if it still happen? 

tested with 2 different dapps

https://github.com/user-attachments/assets/5c6c585e-afab-433c-9ca5-a8bbc3e86080


https://github.com/user-attachments/assets/e5b1fcd4-fe45-47e9-aada-f88f8dce09a7

**Comment by churik** [comment] 2024-10-09 10:31
I don't think that this is required for 2.31, deferred

**Comment by mohsen-ghafouri** [comment] 2024-10-28 12:46
Hey @status-im/mobile-qa could you please check if still reproducible or not with latest changes? It should be resolved already

**Comment by mariia-skrypnyk** [comment] 2024-11-04 17:01
Hey @mohsen-ghafouri !

Sorry for not mentioning that was testing using https://yearn.fi/ Web version.
I've checked how it works now and nothing changed.
On Yearn side popup with QR code stays open after I declined connection. 
I've re-checked how it works on another Web dApps. 
E.G. Uniswap and Lido close this QR popup after declining.

**Comment by mohsen-ghafouri** [comment] 2024-11-08 11:25
Hello @mariia-skrypnyk, if you mean this modal 
![Image](https://github.com/user-attachments/assets/297c9d83-7b7f-4f34-badb-c2c77cb3574a)
this is how they implement it, i also tested with metamask and it won't close this modal. but if you  click on `Open`, next to `Need the official WalletConnect modal?` and try with that modal, it works fine. so it's not an issue from our side

**Comment by mariia-skrypnyk** [comment] 2024-11-13 16:21
@mohsen-ghafouri will look detailed and close the issue. Thanks!

**Comment by mohsen-ghafouri** [comment] 2024-12-10 12:34
Hey @status-im/mobile-qa anyone can confirm we can close it or not?

**Comment by pavloburykh** [comment] 2024-12-10 12:46
> Hey [@status-im/mobile-qa](https://github.com/orgs/status-im/teams/mobile-qa) anyone can confirm we can close it or not?

Hey @mohsen-ghafouri! Issue is still reproducible for me on https://yearn.fi/apps

**Comment by mohsen-ghafouri** [comment] 2024-12-10 13:14
@pavloburykh could you please read my comment here https://github.com/status-im/status-mobile/issues/20894#issuecomment-2464469883 , IMO it's not a bug as it works fine with official wallet connect modal. but custom modal it depend on how they implement it. so I don't think it's an issue in our side as it work well with wallet connect

**Comment by pavloburykh** [comment] 2024-12-10 13:18
> [@pavloburykh](https://github.com/pavloburykh) could you please read my comment here [#20894 (comment)](https://github.com/status-im/status-mobile/issues/20894#issuecomment-2464469883) , IMO it's not a bug as it works fine with official wallet connect modal. but custom modal it depend on how they implement it. so I don't think it's an issue in our side as it work well with wallet connect

Sorry @mohsen-ghafouri for missing your comment above. The issue can be closed. Thank you!

**Closed as completed by pavloburykh** 2024-12-10 13:18 UTC
Labels: wallet-connect: Refinement, wallet-core
