### ISSUE TITLE
Bottom tabs height is wrong when using swipe navigation instead of buttons

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#15381] opened 2023-03-16 10:09 UTC
# Bug Report

## Problem 
<img src="https://user-images.githubusercontent.com/17097240/225584593-c7cc2a09-4b19-4a1e-9d08-4029b3ed96d4.png" height=400/>

**Comment by Parveshdhull** [comment] 2023-03-16 10:17
This bug might affect other places too, where we have hard coded bottom position differently in ios and android

**Comment by Parveshdhull** [comment] 2023-03-16 10:18
@status-im/mobile-qa Please can you check if only this screen is getting affected or other screens too when using swipe navigation in android

**Comment by Parveshdhull** [comment] 2023-03-16 10:32
> @status-im/mobile-qa Please can you check if only this screen is getting affected or other screens too when using swipe navigation in android

Quick test didn't revealed any problem in other screens, So probably affecting only bottom tabs

**Comment by Parveshdhull** [comment] 2023-03-16 10:41
https://stackoverflow.com/a/56520178

**Comment by qoqobolo** [comment] 2023-03-16 10:42
Hey @Parveshdhull!
Hmm I can't reproduce the issue on my Huawei, tried navigation from different places in the app. 
Do you remember by any chance, from which screen did you go back to reproduce this?

**Comment by Parveshdhull** [comment] 2023-03-16 10:46
Hi @qoqobolo, Thank you for looking into this.
We need to change navigation system from device setting for reproducing this issue.

https://user-images.githubusercontent.com/17097240/225593837-68f1c927-09fe-48a5-aa6b-11bd3fc5de00.mp4

**Comment by qoqobolo** [comment] 2023-03-16 11:12
> We need to change navigation system from device setting for reproducing this issue.

Ahh okay! I was already using the gesture navigation system at the time, so I couldn't reproduce it.

And as I can see, it's not specifically about the **gesture** navigation system. The point is to switch the system while using the app. In the video, you can see how I switch from gestures to Three-key navigation, and this also breaks the display of the tabs.


https://user-images.githubusercontent.com/67952253/225599659-6713846c-7ba9-432f-abe5-2a02b463c088.mp4

Now I'm looking at what else the navigation system change can affect.

**Comment by qoqobolo** [comment] 2023-03-16 11:32
@Parveshdhull I couldn't find any other places that would be affected either

**Comment by Parveshdhull** [comment] 2023-03-16 11:40
> The point is to switch the system while using the app.

Oh, I didn't notice that, thank you for finding it.

>  I couldn't find any other places that would be affected either

That's good news. So it only affects the home stack and only if the system is changed while using the app. So it's low priority I think. Will fix this later then. 

Thank you very much for all your help.

**Comment by qoqobolo** [comment] 2023-03-16 11:41
@Parveshdhull thanks for finding and reporting this!

**Comment by cammellos** [comment] 2023-07-14 13:06
closing as this is probalby a wont-fix, feel free to repon if necessary

**Closed as not planned by cammellos** 2023-07-14 13:06 UTC
