### ISSUE TITLE
Support mentions in group or public chats

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#4609] opened 2018-06-03 19:45 UTC
### User Story

As a user, I want to tag other users in busy group or public chats so that they'll be more likely to see my message.

### Description

*Type*: Feature

*Summary*: Tagging a user will notify them so they can find the mention in a group/public chat.

#### Expected behavior
User A types an "@" sign followed by User B's display name to tag them in a group or public chat.

User B receives a push notification which opens to User A's message within the chat.
<br>
<img src="https://user-images.githubusercontent.com/15470435/40890487-1cc7caba-6777-11e8-825c-61c97075ae9b.png" width = 400/>

#### Actual behavior
Mentions aren't possible and users can easily miss responses from others.

**Comment by lukaszfryc** [comment] 2018-06-04 08:03
@rachelhamlin I'm closing it as duplicate of https://github.com/status-im/status-react/issues/4272

**Closed as completed by lukaszfryc** 2018-06-04 08:03 UTC
Labels: feature
