### ISSUE TITLE
Messages from latest chat are not shown when switching from "Profile" tab to "Home" 

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5457] opened 2018-08-10 18:59 UTC
**Issue**
When the user switches from "Home" tab to "Profile" and then back to "Home", messages from latest chat are not shown on the right panel, even when the chat is highlighted on the left panel. 

It feels like something is forever loading or missing:
![ezgif-1-45c5a03c91](https://user-images.githubusercontent.com/37297779/43976353-a7d47aee-9cb6-11e8-9759-70ea66daad4b.gif)

**Current behavior**
When clicking "Home" tab from "Profile" current chat is highlighted on the left panel, but messages are not shown on the right panel, only a label that says "Status.im". Messages are shown once the user clicks on the left panel again.

**Expected behavior**
When switching from "Profile" tab to "Home", we should show the latest chat that is highlighted and it messages on the right panel.

**Steps to reproduce issue**
1- Open Status Desktop
2- Open a chat with messages from left panel
3- Click on "Profile" tab
4- Click on "Home" tab >> Current chat is highlighted on left panel but messages are not shown on the right panel.

Found on OSX.

**Comment by churik** [comment] 2018-08-13 11:38
closed as duplicate of https://github.com/status-im/status-react/issues/5136

**Closed as completed by churik** 2018-08-13 11:38 UTC

**Comment by EugeOrtiz** [comment] 2018-08-14 22:01
Thanks!!
