### ISSUE TITLE
Wallet: Receive screen

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18152] opened 2023-12-12 04:32 UTC
Implement the receive screen UI inside account screen, and sharing the address.

Designs: https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=850-220368&mode=design&t=LiGka1ERPbcjgCSI-0

**Comment by smohamedjavid** [comment] 2023-12-13 16:08
Duplicate of https://github.com/status-im/status-mobile/issues/17677

**Closed as completed** 2023-12-21 18:07 UTC
Labels: feature
