### ISSUE TITLE
Welcome screen and beta warning overlap each other if put app on background after creating account

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7972] opened 2019-04-12 16:57 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: 
On some Android devices (Galaxy S6, Android 6.0.1) beta warning popup and Welcome screen are overlapping each other if app was moved to background and back after account is created. 

Note: on another real Android device Pixel XL, Android 9 it can't be reproduced
![Screenshot_20190412-183639](https://user-images.githubusercontent.com/6584810/56052685-5e29a600-5d52-11e9-84a1-1d0e263c4805.png)

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)

#### Expected behavior
1. popup is shown on top
2. behind popup Welcome screen is shown

#### Actual behavior
Picture from the Welcome screen is shown above beta warning popup

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=1_ttV2n6PmcfDIERjD0E1zQaufb03V-O9
- Open Status
- Create new account
- when beta warning is shown move app to background
- move app to foreground 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly April 12, 0.12.0
- Operating System: Android 6.0.1, real Galaxy S6

**Comment by Serhy** [comment] 2019-04-12 17:14
Hmm, cannot reproduce with Android 6.0.1 Galaxy Note 4 (nightly April 12). 
However, unlike to Galaxy S6 (on video in description), I don't have so heavy lags with Status "layers redrawing" when it foregrounds (on video it's noticeable when Status just opened that password+popup appears first and then the bottom sheet Get Started)

Android 8.1 looks OK too.

**Comment by churik** [comment] 2020-02-26 14:40
Closing as couldn't reproduce (nightly 26/02/2020)

**Closed as completed by churik** 2020-02-26 14:40 UTC
