### ISSUE TITLE
Error "Invariant Violation: `refreshing` prop must be set as a boolean..." if sign in when device is offline

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3568] opened 2018-03-14 21:01 UTC
### Description

*Type*: Bug

*Summary*: When device is offline and user runs the app and signs in then Error "Invariant Violation: `refreshing` prop must be set as a boolean in order to use `onRefresh`, but got `null`" is shown. If close error popup then white screen is shown and app is unuasable

#### Expected behavior
It's possible to sign in when device has no Internet connection (e.g. in flight mode) and browse tabs and chats

#### Actual behavior

```
03-14 21:52:06.691 15772 15832 E ReactNativeJS: Invariant Violation: `refreshing` prop must be set as a boolean in order to use `onRefresh`, but got `null`
03-14 21:52:06.691 15772 15832 E ReactNativeJS: 
03-14 21:52:06.691 15772 15832 E ReactNativeJS: This error is located at:
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in t
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in t
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in reagent23
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in reagent48
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in wallet
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in reagent44
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in reagent20
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in with-activity-indicator
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in reagent18
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in main-tabs
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in reagent17
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in main
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in root
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in reagent1
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in RCTView
03-14 21:52:06.691 15772 15832 E ReactNativeJS:     in t
```
### Reproduction
- set device in flight mode
- run Status
- sign in. check if any errors are shown

### Additional Information
* Status version: nightly build March 14
* Operating System: Android and iOS

**Comment by oskarth** [comment] 2018-03-27 02:00
@lukaszfryc Can you confirm this is still in 0.9.16 release branch? @jeluard says https://github.com/status-im/status-react/pull/3393 should've fixed it, which was merged before release branch was cut.

**Comment by oskarth** [comment] 2018-03-27 02:12
Unable to reproduce on iOS simulator in develop. Expected behavior works for me with described steps (Airplane mode <=> Network offline).

**Comment by oskarth** [comment] 2018-03-27 02:12
Unable to reproduce on iOS simulator in develop. Expected behavior works for me with described steps (Airplane mode <=> Network offline).

**Comment by lukaszfryc** [comment] 2018-03-27 10:40
Can't reproduce it either (Android, iOS).

**Closed as completed by lukaszfryc** 2018-03-27 10:40 UTC
