### ISSUE TITLE
User is not redirected to community page after finishing onboarding

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15491] opened 2023-03-27 08:31 UTC
followup of https://github.com/status-im/status-mobile/pull/15370 cc @jo-mut

Expected result: according to the feature [description](https://github.com/status-im/status-mobile/issues/15033#issue-1574817901 ) 
"should direct user to communities home page afterwards"

**Actual result:** user is redirected to Jump to screen

https://user-images.githubusercontent.com/97245802/227504770-dfcd2192-0a36-45c6-bbb4-c43048c97f8c.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by jo-mut** [comment] 2023-03-28 21:49
@pavloburykh this issue seems to have been resolved in another pr. I am unable to reproduce it anymore on develop

**Comment by pavloburykh** [comment] 2023-03-29 08:15
Hi @jo-mut ! I have just checked latest nightly (March 23, 2023) and I am still redirected to Shell screen after creating/restoring account. Could you please show how it works for you in develop? 


https://user-images.githubusercontent.com/97245802/228470299-8f723379-dd0f-4b99-ab49-eb5b79fc3a7d.mp4

**Comment by jo-mut** [comment] 2023-03-29 08:43
https://user-images.githubusercontent.com/28704507/228477907-8947b452-9617-4cfd-b7aa-6dab29f3e2b3.mov

**Comment by jo-mut** [comment] 2023-03-29 08:44
@pavloburykh 

https://user-images.githubusercontent.com/28704507/228478349-310f624b-88d3-45cc-974d-cd34df39e0ad.mov

**Comment by jo-mut** [comment] 2023-03-29 08:45
https://user-images.githubusercontent.com/28704507/228478423-6ea189fd-89ec-442b-9c0f-058914dcb7c9.mov

**Comment by jo-mut** [comment] 2023-03-29 08:46
@pavloburykh before i was able to reproduce it but now seems to work. Is there a step i am missing

**Comment by pavloburykh** [comment] 2023-03-29 08:50
@jo-mut As far as I see on video you are using Temporary (old) flow for creating account. It will be soon deprecated. Try creating/restoring account using new flows during onboarding (see screenshot below). I am not redirected to community screen using new onboarding flows. 

![photo_2023-03-29 11 49 59](https://user-images.githubusercontent.com/97245802/228480041-4dbca7da-4117-4e65-97b2-a9f51102379c.jpeg)

**Comment by jo-mut** [comment] 2023-03-29 08:51
thanks i was missing that

**Closed as completed** 2023-04-07 23:45 UTC
Labels: onboarding
