### ISSUE TITLE
Message isn’t sent on enter on iPad with external keyboard 

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12695] opened 2021-10-11 08:56 UTC
Instead new line is added

https://user-images.githubusercontent.com/41779817/136760781-edc36a8c-3056-458b-9e3c-51f2ee97f184.mp4

As a user I want iPad or any Android tablet support

**Comment by rasom** [comment] 2021-10-14 10:16
duplicate of https://github.com/status-im/status-react/issues/12441

**Closed as completed** 2021-10-14 12:11 UTC
Labels: feature
