### ISSUE TITLE
Filling recipient after entering Tx amount clears amount

### ISSUE THREAD

**Issue by StatusSceptre** [status-im/status-react#9671] opened 2019-12-16 21:17 UTC
# Bug Report

## Problem

The amount is the first field in a transaction. When you fill this out, and then add recipient by scanning their QR code, the amount is reset.

#### Expected behavior

Amount is maintained unless user cancels the Tx.

#### Actual behavior

Set Tx amount.
Scan recipient QR code.
Amount is cleared and must be re-entered.

**Comment by ghmulti** [comment] 2019-12-28 10:59
Is there any additional information that might help - on which app version the problem has been observed?

**Comment by churik** [comment] 2020-03-27 16:37
It is a duplicate of #9580

**Closed as completed by churik** 2020-03-27 16:37 UTC
Labels: good-first-issue
