### ISSUE TITLE
Endless fetching messages for fresh account with no chats on Android 9

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7376] opened 2019-01-30 10:53 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: For more than 5 minutes I see moving indicator for fetching messages on fresh account with no chats. Relaunching app for 3-4 times does not help. After one more relaunch everything started to work fine and fetching is no longer shown.
For the new user with 0 chats it looks like too much fetching 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
fetching indicator can be shown but not for so long time
#### Actual behavior
[comment]: # (Describe what actually happened.)
fetching indicator is shown for 5 minutes, and again if relaunch app 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Install Status, create new account, set profile picture
- open home tab and check if fetching indicator is shown and for how long

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: nightly Jan 30 
* Operating System: Android 9 real device

#### Logs

[Status.log](https://github.com/status-im/status-react/files/2812192/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2812193/geth.log)

**Comment by annadanchenko** [comment] 2019-02-04 16:26
@mandrigin tried again on build 11 for release 0.9.33 and can reproduce again: see Fetching indicator and then Connecting... 
[Status.log](https://github.com/status-im/status-react/files/2828876/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2828877/geth.log)
[logcat.log](https://github.com/status-im/status-react/files/2828882/logcat.log)

however if I join at least some public chat then it gets history fine and indicator is not shown.
I don't have such issue on same device with 0.9.32 release (latest status-go hotfix) installed

**Comment by annadanchenko** [comment] 2019-02-04 16:57
TRACE log level geth.log: [geth.log](https://github.com/status-im/status-react/files/2829011/geth.log)

contains many msg="Waiting for a peer to restore communication"

**Comment by annadanchenko** [comment] 2019-02-04 18:00
if try on PR https://github.com/status-im/status-react/pull/7414 (Android build 1) then have similar issue
logs:
[geth.log](https://github.com/status-im/status-react/files/2829227/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2829230/Status.log)

**Comment by mandrigin** [comment] 2019-02-05 09:40
no user feedback and the unusable app is caused by: https://github.com/status-im/status-react/issues/7422

but also, for some reason some mailservers don't work on Android, but seems to work okay on iOS (status-go issue??), I will investigate that in the scope of this task...

**Comment by mandrigin** [comment] 2019-02-05 15:08
it makes no sense, but the error for this mailserver is "already connected", I will investigate further...

**Comment by mandrigin** [comment] 2019-02-05 16:20
okay, it looks like the mailserver is declining *us* there.

**Comment by annadanchenko** [comment] 2019-02-05 17:01
@mandrigin logcat filtered by "mailserver", log level = debug.

note it's collected from app installed from https://github.com/status-im/status-react/pull/7425 (build 2). At some point it managed to connect fine and fetching indicator is gone (as expected)

[mailservergrep.log](https://github.com/status-im/status-react/files/2833034/mailservergrep.log)

**Comment by mandrigin** [comment] 2019-02-05 17:15
okay, so mailservers are declining some android clients due to them being "already connected"... weird

**Comment by mandrigin** [comment] 2019-02-05 17:43
@annadanchenko so that is server-side for sure... I will try to make a test that reproduces that locally with `statusd`, so far we decided to just restart mailservers every few hours to mitigate the issue (we are as stable as ICQ now!). Please, double-check your app now.

**Comment by annadanchenko** [comment] 2019-02-05 18:18
@mandrigin I can confirm that on release 0.9.33 build 11 where issue was present I can't repro it now

**Comment by mandrigin** [comment] 2019-02-05 18:28
So let’s keep this issue open, but it’s mailserver related, so it shouldn’t block the release.

**Comment by mandrigin** [comment] 2019-02-14 08:24
I will close this one and we'll continue investigation in 
https://github.com/status-im/status-react/issues/7488

**Closed as completed by mandrigin** 2019-02-14 08:24 UTC
Labels: android
