### ISSUE TITLE
Empty community screen is opened when following an "old" community link

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18624] opened 2024-01-25 13:01 UTC
# Bug Report

## Problem 

We encountered an issue in e2e tests when clicking on certain links, a blank community screen opens.

<img width="484" alt="Screenshot 2024-01-25 at 13 59 09" src="https://github.com/status-im/status-mobile/assets/67952253/1e4a35fb-c052-4f1f-8350-a70afe0d522d">

**Test example with video:** https://app.eu-central-1.saucelabs.com/tests/bd486b79f980443fbc5c7127d2194dd9?auth=78eb25acecf48b024d251656d3ee2ac7#121

Tried to reproduce this manually and found that it seems that only links to “old” communities work this way, i.e. communities that were created once, but then for some period of time (~30 days?) the admin of these communities did not recover their account on any device. This assumption is based on the fact that in the tests, communities for these links were created once, and then only links were used without recovering the admin-user themself.

**Link examples:**

1. https://status.app/c#zQ3shbmfT3hvh4mKa1v6uAjjyztQEroh8Mfn6Ckegjd7LT3XK

2. https://status.app/c/G8EAAGTiXKuwNbVVAu0GNLD-XzX4oz_E8oC1-7qSLikaTnCuG9Ag13ZgQKrMd8En9Qcpuaj3Qx3mfZ1atZzH8Zw-x_sFJ_MDv0P_7YfqoV-pNr3V4dsza-jVk41GaCGWasJb92Oer8qggaoNWf0tYCgSH19VonXciKPUz3ITdgke#zQ3shbmfT3hvh4mKa1v6uAjjyztQEroh8Mfn6Ckegjd7LT3XK

3. https://status.app/c/ixiACjAKCHRlc3RDb21tEhZkemZ4Z2Nodmpra2xra2xrbCAgbGxsGAYiByM4OEIwRkYqARQD#zQ3shuK3RAMBGtNWJ5QAKtuGeyEhiwko5gXhyGg6T89Q2xrHq 

4. https://status.app/c/CxWACikKElQtZyBjb21tdW5pdHkgbWludBIFZmZmZmYYASIHIzIxNjI2NioBMwM=#zQ3shfxPTZ1dUZTXpjEwYHc2TMSeVjAA6JJ5SD46EVKM2Wtcb

5. https://status.app/c/Ow==#zQ3shbmfT3hvh4mKa1v6uAjjyztQEroh8Mfn6Ckegjd7LT3XK

None of these links open on mobile or desktop (empty screen on mobile and the link is not clickable on desktop).

If you follow link 1 (without encoded data) the website also does not open if you open it in Chrome on your computer.

<img width="366" alt="Screenshot 2024-01-25 at 13 44 50" src="https://github.com/status-im/status-mobile/assets/67952253/bd847655-9c54-4f7b-ba6e-cc5dfa1cffda">

Links in the format like link 5 don't work at all, even for new communities/users, if you follow them from outside the app. 
So maybe this is a separate issue. 

The main guess atm, and the question associated with it: is the data stored on Waku for communities supposed to expire after some time?
If so, is this period equal to the storage period for backed-up data - 30 days?
**And the main question is: is this an issue or expected behavior?**

cc'ing @igor-sirotin and @yqrashawn, maybe you have some info/idea on this matter? 

### Reproduction (hypothetical steps):

1. Create a community, save the community invite link
2. Don't recover the admin user for ~30 days
3. Share the with another user in a Status chat
4. Follow the link

### Additional Information

- Status version: nightly 25/01
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by igor-sirotin** [comment] 2024-01-25 13:26
> is the data stored on Waku for communities supposed to expire after some time?

Yes

> is this period equal to the storage period for backed-up data - 30 days?

Yes, 30 dyys

> And the main question is: is this an issue or expected behaviour?

Yes, it's expected 🙂 

----- 

Waku store nodes keep the data for 30 days. It's the community control node responsibility to stay online, the app will automatically push the community description to the network each 5 minutes (not sure of this period).

Switching to an empty screen doesn't look like a good solution to me. Probably we should come up with some UI design for such case. 

Same thing about profile links btw.

**Comment by igor-sirotin** [comment] 2024-01-25 13:46
> 1. https://status.app/c#zQ3shbmfT3hvh4mKa1v6uAjjyztQEroh8Mfn6Ckegjd7LT3XK

> If you follow link 1 (without encoded data) the website also does not open if you open it in Chrome on your computer.

Not sure what's wrong with this one. Parses fine for me:
```json
{
  "r": {
    "community": {
      "displayName": "",
      "description": "",
      "membersCount": 0,
      "color": "",
      "tagIndices": [],
      "communityId": "0x02d55c8d59f0193c44fb0f7e72dd2efd6f998434e9109017ed4282300c12595a26"
    },
    "channel": null,
    "contact": null
  }
}
```

I think this is just the same thing as other links. For links 2-3-4 this message appears in the bottom-right corner in status-web:
<img width="381" alt="image" src="https://github.com/status-im/status-mobile/assets/25482501/42fd8724-5a7f-4b28-9201-2b39c4aa309a">

Which means no data was found in waku. But I wonder why this request is so fast, usually it takes a few seconds to make the request to the storenodes.

------

> Links in the format like link 5 don't work at all, even for new communities/users, if you follow them from outside the app.
So maybe this is a separate issue.

I can confirm that this link doesn't open in status-web.
https://status.app/c/Ow==#zQ3shbmfT3hvh4mKa1v6uAjjyztQEroh8Mfn6Ckegjd7LT3XK

<img width="922" alt="image" src="https://github.com/status-im/status-mobile/assets/25482501/8a6be6e8-356e-412a-992e-6ba3e5c92e84">

But the link parses just fine in status-go. This is either wrong implementation of url parse in status-go or status-web bug.
Better to ping @MishkaRogachev and @felicio

**Comment by qoqobolo** [comment] 2024-01-25 14:01
@igor-sirotin thanks for the answer and explanation!

> Yes, it's expected 🙂

The puzzle is solved now! 👍

> Switching to an empty screen doesn't look like a good solution to me. Probably we should come up with some UI design for such case.

I'll communicate this to design and John. 

> Not sure what's wrong with this one. Parses fine for me

Yes, it looks like the only difference is the presence of encoded data in the link itself. But the reason is the same.

---

I'll close this issue for now. If necessary, will open a separate one for `https://status.app/c/Ow==` links when get an answer.

**Comment by pavloburykh** [comment] 2024-02-01 10:04
Hi @igor-sirotin! Currently we are facing global issues related to community fetching. Empty screen is loaded when opening any community link. 

Community link example https://status.app/c/G8EAAMTP9i5Kd7W8gMMhkU2WJtTmM_mZZEuFO-FP-nPKgUPePMKWUzvQ9XgPuClC4Bhb_8XW4hVFTAHkMx57ZEappDn-Qomfzl_xbDwpsA1JoRMeEThCKIrIjA6URYrJQ7zZcshY5yDJEXeScjuRwSUC5RQhTHx6ChCSXRIKigQYJbCy5KNDPPSbgTRG5zCgPNvMrUD6PZqs6uvTbrvfHjflSb8N#zQ3shwQnEfMtcXpHXF4qJPyCGgw2F18N3nbGzYbzsVHnMq4yK


[Status-debug-logs (98).zip](https://github.com/status-im/status-mobile/files/14123347/Status-debug-logs.98.zip)

https://github.com/status-im/status-mobile/assets/97245802/c55234cb-b033-493b-ade1-e0a1c9f54881

**Comment by pavloburykh** [comment] 2024-02-01 17:52
> Hi @igor-sirotin! Currently we are facing global issues related to community fetching. Empty screen is loaded when opening any community link.

**UPDATE:** there was an issue related to DB. It is fixed now.

**Comment by pavloburykh** [comment] 2024-02-01 18:08
@igor-sirotin got another issue related to fetching the community.

> Waku store nodes keep the data for 30 days. It's the community control node responsibility to stay online, the app will automatically push the community description to the network each 5 minutes (not sure of this period).

So, here we have a community https://status.app/c/G0UAAMTyNsn2QZDEG0EXftOl8pOEfwEBOOSA_YTfIk85xmADDgINGmxpUHAXzK36bN0fK42Xf4YD2yjPk1z2pbFwFw==#zQ3shgkDFQEnwxji7CvMTokMrShmC2UgxiJ549X5Aw746zQrK which is not fetched (empty screen is opened when following the link on mobile).

The interesting fact is that community's Admin is one of our test accounts (I can provide a seed phrase if needed). This account is being restored from Waku multiple times a day during numerous e2e runs. So based on your quoted comment above, I would assume community's data should be okay and thus be fetched as the control node appears online multiple times a day when account is restored. 

Or maybe restoration of an account itself does not result in restoration of the control node which should always be on the same one device? Would appreciate you clarification on this issue.

**Comment by igor-sirotin** [comment] 2024-02-05 13:33
@pavloburykh I can confirm that this community is not found on `shards.test` fleet:
```go
store-02.do-ams3.shards.test --- envelopes fetched: 0, community - 
store-01.do-ams3.shards.test --- envelopes fetched: 0, community - 
store-01.gc-us-central1-a.shards.test --- envelopes fetched: 0, community - 
store-02.gc-us-central1-a.shards.test --- envelopes fetched: 0, community - 
store-02.ac-cn-hongkong-c.shards.test --- envelopes fetched: 0, community - 
store-01.ac-cn-hongkong-c.shards.test --- envelopes fetched: 0, community - 
```

>  I would assume community's data should be okay and thus be fetched as the control node appears online multiple times a day when account is restored.

I would say so. Though it probably depends on how long it stays online for. 
Because this happens in tests, could be that it just doesn't reach the moment of publishing the community description. Donno.

> Or maybe restoration of an account itself does not result in restoration of the control node which should always be on the same one device?

Not sure of this, but I would say that restoring an account is enough.
Better ping @mprakhov and @osmaczko about this.

**Comment by osmaczko** [comment] 2024-02-05 15:45
> Or maybe restoration of an account itself does not result in restoration of the control node which should always be on the same one device? Would appreciate you clarification on this issue.

You are right. The community's private key is not synced, meaning the control node is not restored with the account. The risk of losing access to the community is high in this case, but since we have tokenized ownership that mitigates it, we decided to keep it like that.

**Comment by pavloburykh** [comment] 2024-02-05 16:50
@igor-sirotin @osmaczko thank you for clarifying on that.

**Closed as completed by pavloburykh** 2024-02-05 16:50 UTC
Labels: deep-link, universal-link

**Comment by felicio** [comment] 2024-03-21 02:55
@qoqobolo 

>  will open a separate one for https://status.app/c/Ow==#zQ3shbmfT3hvh4mKa1v6uAjjyztQEroh8Mfn6Ckegjd7LT3XK

Indeed, that's an invalid link.

More info: https://github.com/status-im/status-mobile/pull/18020#issuecomment-1850102009
