### ISSUE TITLE
When editing my own profile it is not possible to add my phone number

### ISSUE THREAD

**Issue by Kimoa85** [status-im/status-react#2863] opened 2018-01-01 15:44 UTC
Type: Bug

**Summary:**
When entering my profile and trying to add my phone number nothing happenes

**Expected behavior**
when pressing the kebab menu near my phone number field it should be possible to edit it

**Actual behavior**
the menu opens and when selecting Edit nothing happens

**Reproduction**
Enter your own profile's kebab menu,  scroll down to Phone number and select the kebab menu near it, select Edit - nothing happens.

**Additional Information**
Status version: release 0.9.12 
Operating System:
Xiaomi redmi note 4, android 6.0.1

**Comment by annadanchenko** [comment] 2018-01-03 11:31
duplicate of #1677

**Closed as completed by annadanchenko** 2018-01-03 11:31 UTC
