### ISSUE TITLE
Error undefined is not an object (evaluating 'u[n]') 

### ISSUE THREAD

**Issue by ghost** [status-im/status-react#2581] opened 2017-12-02 17:57 UTC
Error undefined is not an object (evaluating 'u[n]') shown while holding a contact icon.

Operating system: Android 4.4.0

**Comment by annadanchenko** [comment] 2017-12-02 21:22
@ardielgonzalez thank you for the bug report! Can you, please, add steps to reproduce and the screenshot of the screen with `contact icon`?

**Comment by ghost** [comment] 2017-12-04 07:50
1.-Go to contacts menu
2.-Hold on any contact's profile icon
3.-Get error
![screenshot_2017-12-02-13-08-16](https://user-images.githubusercontent.com/34160036/33541644-bb165a9a-d8c7-11e7-8a0f-24991fb4572d.png)

**Comment by annadanchenko** [comment] 2017-12-07 16:31
@ardielgonzalez I can't reproduce the issue yet. Would you mind to install the development build where extra logging is enabled, try to reproduce the issue and let me know the outcomes, please? To find the video/log from your device I need to know date-time-minutes when session was started, country and the device type you are using. Development build from Dec 7: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk

**Comment by annadanchenko** [comment] 2018-06-17 11:35
closing as this screen is no longer available in the app

**Closed as completed by annadanchenko** 2018-06-17 11:35 UTC
