### ISSUE TITLE
Make hashtags clickable

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5774] opened 2018-09-06 11:16 UTC
### Description

*Type*: Feature

*Summary*: It is common for hashtags (e.g. #ethereum, #mexico) to be clickable. But, in Status hashtags are treated like a normal text. Maybe they should open a public channels? 

#### Expected behavior
Clicking a hashtag in chat should open public channel.

#### Actual behavior
Clicking a hashtags does nothing.

### Additional Information
* Status version: 0.9.26
* Operating System: Android, iOS

**Comment by chadyj** [comment] 2018-10-05 12:12
Dupe of https://github.com/status-im/status-react/issues/6139

Ahh I searched for this issue but didn't find it

**Closed as completed by chadyj** 2018-10-05 12:12 UTC
Labels: feature
