### ISSUE TITLE
System messages are always on the top on group chats

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9654] opened 2019-12-12 14:48 UTC
# Bug Report

## Problem
Regardless of timestamp system messages are at the top of the chat.

#### Expected behavior
Messages are sorted by timestamp

#### Actual behavior
![photo_2019-12-12 15 47 26](https://user-images.githubusercontent.com/4557972/70721946-ba383600-1cf6-11ea-9b6e-f6dcf776800b.jpeg)

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create group chat with User B
- Send several messages to group chat
- Make other user Admin

### Additional Information

- Status version: nightly 12/12/2019
- Operating System: Android, iOS

**Comment by churik** [comment] 2019-12-12 15:01
cc @rachelhamlin @cammellos

**Comment by cammellos** [comment] 2020-01-15 10:22
This has been fixed now, already in develop, @churik @Serhy would you mind confirming and closing if that's the case? Thanks!

**Comment by Serhy** [comment] 2020-01-15 12:18
Looks good to me now on iOS and Android with latest nightly build, can not reproduce the issue (I could not check 'Added member' system message due to https://github.com/status-im/status-react/issues/9831 but I don't think there should be an issue as well because it's system message like any other. 
Closing the issue.

**Closed as completed by Serhy** 2020-01-15 12:18 UTC
