### ISSUE TITLE
Design review: community channel list

### ISSUE THREAD

**Issue by churik** [status-im/status-react#16860] opened 2023-08-03 09:49 UTC
- [x] #18143
- [x] #18145
- [x] #18146
- [x] #18147

**Comment by cammellos** [comment] 2023-08-04 16:36
2,3 looks like small issues, 1.25
1,4 to be looked at by someone with better understanding than my self

**Comment by ibrkhalil** [comment] 2023-08-17 04:22
Comment on issue 4, CC: @Francesca-G 
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511293331

**Comment by cammellos** [comment] 2023-09-13 12:36
Please create separate issue if you are working on any and reference them

**Comment by jo-mut** [comment] 2023-12-06 23:37
@ibrkhalil are you still working on this. I could take a look at this if you are held with something else

**Comment by ibrkhalil** [comment] 2023-12-07 06:40
> @ibrkhalil are you still working on this. I could take a look at this if you are held with something else

Thank you very much, Sure feel free to pick it up

**Comment by jo-mut** [comment] 2023-12-13 17:44
some comments on the following issues as they seems to have been fixed already perhaps on 1.25 release

Issue 1: https://github.com/status-im/status-mobile/issues/18143#issuecomment-1854432232
Issue 2: https://github.com/status-im/status-mobile/issues/18145#issuecomment-1854417220
Issue 3: https://github.com/status-im/status-mobile/issues/18146#issuecomment-1854329111

Issue 4: is not fixed as the others I have however worked on it and will raise a pr and just add the link to this comment

**Comment by pavloburykh** [comment] 2023-12-14 12:30
> some comments on the following issues as they seems to have been fixed already perhaps on 1.25 release
> 
> Issue 1: [#18143 (comment)](https://github.com/status-im/status-mobile/issues/18143#issuecomment-1854432232) Issue 2: [#18145 (comment)](https://github.com/status-im/status-mobile/issues/18145#issuecomment-1854417220) Issue 3: [#18146 (comment)](https://github.com/status-im/status-mobile/issues/18146#issuecomment-1854329111)

Thank you for review @jo-mut! All of those issues should pass @Francesca-G review using latest nightly builds.

**Comment by jo-mut** [comment] 2023-12-14 15:18
@pavloburykh thank you for your response. @Francesca-G when you find time kindly could confirm my finding so the issues can be closed.

**Comment by jo-mut** [comment] 2023-12-14 22:27
@Francesca-G could you also take another look at the issues reported here on this figma as they all look to me to have been fixed probably in 1.25 release  https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511295255

Also I did notice the following bug which might fall under the scope of this issue but are not well captured in the issue description

When the user scroll community channels very first, the ` x ` and `...` button blur background may or may not be applied so the button but when the user just scrolls relatively slowly the background of these two buttons is well applied. Maybe this is what the **`ISSUE 2`** refers to or the previous fix on 1.25 did not take to account the scroll behaviour as the button background does not seem to be the issue in this case

https://github.com/status-im/status-mobile/assets/28704507/200c5fd5-630b-4201-bf75-fb47221f3e3b

**`ISSUE 4`** Blur and line category looks okay to me as is on the designs unless I am missing something. However I did notice the Blur header seems has a different height on android when compaired to ios and to the designs could be a known case but seems to be an issue that can be fixed separately as its not within the scope of the feedback

**iOS & Figma**

<img width="600" alt="Screenshot 2023-12-11 at 22 32 16" src="https://github.com/status-im/status-mobile/assets/28704507/31b5910d-6055-476a-973f-2335e97804a4">

**Android $ Figma**

<img width="600" alt="Screenshot 2023-12-14 at 23 08 27" src="https://github.com/status-im/status-mobile/assets/28704507/6ad6e635-b05b-4085-9e55-564b5255dd79">

**Comment by Francesca-G** [comment] 2023-12-15 09:59
> @Francesca-G could you also take another look at the issues reported here on this figma as they all look to me to have been fixed probably in 1.25 release https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3674:338290&mode=design#511295255
> 
> Also I did notice the following bug which might fall under the scope of this issue but are not well captured in the issue description
> 
> When the user scroll community channels very first, the `x` and `...` button blur background may or may not be applied so the button but when the user just scrolls relatively slowly the background of these two buttons is well applied. Maybe this is what the **`ISSUE 2`** refers to or the previous fix on 1.25 did not take to account the scroll behaviour as the button background does not seem to be the issue in this case
> 
It looks fixed to me, I didn't encounter the bug you mentioned (tested on iPhone 13, 1.26 build) 

> 
> **`ISSUE 4`** Blur and line category looks okay to me as is on the designs unless I am missing something. However I did notice the Blur header seems has a different height on android when compaired to ios and to the designs could be a known case but seems to be an issue that can be fixed separately as its not within the scope of the feedback
> 
I can confirm that it looks good on iOS but we still have height and blur issues on Android (screenshot below).
I think it's a known issue as you said, feel free to fix it separately if that works best for you :)


<img width="375" alt="IMG_0203 1" src="https://github.com/status-im/status-mobile/assets/122543089/6736e7d1-856b-4018-a13b-cc28f8d777f7">

**Comment by jo-mut** [comment] 2023-12-15 10:20
@Francesca-G thank you

**Comment by jo-mut** [comment] 2024-01-04 12:31
@Francesca-G after looking into **issue 4** i think the current implementation of the design is just okay. This PR https://github.com/status-im/status-mobile/pull/18239 tries resolve the issue and work well on my android device but a different screen size. I just think its a device issue and not a mis-implementation unless you can confirm otherwise the code looks fine. We can close this issue

**Comment by Francesca-G** [comment] 2024-01-05 10:16
> @Francesca-G after looking into **issue 4** i think the current implementation of the design is just okay. This PR #18239 tries resolve the issue and work well on my android device but a different screen size. I just think its a device issue and not a mis-implementation unless you can confirm otherwise the code looks fine. We can close this issue

I'm currently only able to use a Xiaomi Redmi 5 Plus for Android testing (Android 8.1.0), not sure how it looks on other more recent devices so that could be the issue

**Comment by Samyoul** [comment] 2024-01-22 10:13
These issues are basically resolved. Any queries speak with @jo-mut .

@Francesca-G Is this fine to close now?

**Closed as completed** 2024-01-24 14:25 UTC
Labels: community

**Comment by jo-mut** [comment] 2024-02-19 09:53
Closing https://github.com/status-im/status-mobile/issues/18143 https://github.com/status-im/status-mobile/issues/18145  #18146 https://github.com/status-im/status-mobile/issues/18147 as the main issue has been closed #16860
