### ISSUE TITLE
Null is not an object error shown when logging in [0.9.12]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2313] opened 2017-10-27 07:21 UTC
### Description

*Type*: Bug

*Summary*: Error shown `Null is not an object (evaluating `cljs.core.deref(status_i.data_store.realm.core.account_realm)path`) when user try to log in.

![image](https://user-images.githubusercontent.com/28752642/32092341-b639fff2-bb00-11e7-9540-fa435bf99291.png)

### Reproduction
Need to get more details as I can't reproduce it on my devices

1. updating from 0.9.11 On Android 6.1
2. login on my 1st account created and get the error upon password entry iOS 6s 

### Additional Information
* Status version: release build `0.9.12`
* Operating System: Android, iOS

#### Logs
Android (OS Level 24):
[log11.txt](https://github.com/status-im/status-react/files/1424018/log11.txt)

Android (OS Level 23):
[console logs.txt](https://github.com/status-im/status-react/files/1622853/console.logs.txt)

**Comment by mplsvbhvr** [comment] 2017-11-22 17:32
I get this error both on my original account and a new one just created after trying to switch back and forth. 

Status Version 0.9.12+
Android Version 8.0.0
Phone: Pixel XL

**Comment by oskarth** [comment] 2018-01-08 11:01
> We need to reproduce https://github.com/status-im/status-react/issues/2313 as I remember Roman and Eric assumed it’s because of lots of data. Maybe if you or someone else can look again to give more hints on types of data (chats or messages in chats, kind of messages) it would be easier for us to focus on creating that specific dataset

@rasom @yenda What are your thoughts on this one?

**Comment by oskarth** [comment] 2018-01-08 11:01
Tentatively adding to release for bug fix day, but we need to repro it first. Might be cut from scope (no worse than 0.9.12 release).

**Comment by mplsvbhvr** [comment] 2018-01-09 00:11
Thanks for the update oskarth

**Comment by asemiankevich** [comment] 2018-01-11 13:59
@oskarth @yenda some logs attached ^

**Comment by Serhy** [comment] 2018-01-11 14:38
This can be reproduced upgrading from 0.9.12 to 0.9.13 in next way (confirmed on both Android and iOS - so below if to interchange 'Android user' with 'iOS user' you'll get the same error on respective device).

Key items to note here: 
- user should be added from same Status version (it’s not reproducible if 0.9.12 scans QR code and adds user from 0.9.13 version)
- delete chats

Steps:
1) Install 0.9.12+ from Play Store on Android device
2) Install 0.9.12+ from TestFlight on iOS device
3) Open Status on Android, create new user (i've used password 'aaaaaa')
4) Open Status on iOS, create new user (i've used password 'aaaaaa')
5) On iOS navigate to profile and open QR code ('Show QR code')
6) Android user adds iOS user via scanning QR code. (Note: Android user lands on 1-1chat after adding account.)
7) Android user navigates to Chats screen. 
8) Android user -> create "Group chat" (I named group chat 'Grchat'). Add Jarrad and iOS user.
9) Android user -> in Group chat send text message
10) Android user -> in Group chat send emoji
11) Android user -> navigate back to Chats screen. 
12) Android user -> create public chat (use random name here, e.g. "lkjhgfd".)
13) Android user -> in public chat send text message
14) Android user -> in public chat send emoji
15) Android user -> navigate back to Chats screen
16) Android user -> create one more public chat (i've named it 'pch')
17) Android user -> navigate back to Chats screen
18) Android user deletes all chats created above
19) Android user closes the Status app (I don't log out, do stop the app - just close it).
20) Android user upgrades to 0.9.13 version
21) Android user logs in with account created above in 0.9.12 version).

Current result: `Primary key property 'user-status.status-id' has duplicate values after migration` error 
![first](https://user-images.githubusercontent.com/8749671/34830516-caab2e16-f6ec-11e7-81c1-71684fab2b69.png)
22) Android user taps 'OK' on above error message.
23) Android user taps 'Sign In'.
Current result: `Primary key property 'user-status.status-id' has duplicate values after migration` error `null is not an object (evaluating 'cljs.core.deref(status_im.data_store.realm.core.account_realm).path')` error 
![second](https://user-images.githubusercontent.com/8749671/34830623-241a1c64-f6ed-11e7-8ba5-d7a9e4eea42a.png)

**Comment by janherich** [comment] 2018-01-11 18:51
@Serhy I have one question, which would help me tremendously - can you confirm that the above bug **doesn't** happen when the step 18. (deleting all chats) is omitted from the sequence ?

**Comment by Serhy** [comment] 2018-01-12 11:01
@janherich Yes, excluding 18th step from above scenario - does not bring errors after upgrade from 0.9.12 to 0.9.13 version. Deleting the chats - is the root cause.

**Closed as completed** 2018-01-16 13:48 UTC
