### ISSUE TITLE
Backed up data not restored after user restoration

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18637] opened 2024-01-26 11:21 UTC
Unfortunately, this issue is not reproduced frequently. I attempted to restore the current user at least 5 times, and only twice the data was restored. Waiting and relogin do not help.

### Steps:
1. Restore the user with some backed-up data

### Actual result:
No data is restored

### Expected result:
The data is restored

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/14064257/Status-debug-logs.1.zip)

### ENV:
IOS, Android

**Comment by igor-sirotin** [comment] 2024-01-26 15:08
I believe same thing is reproducible in Desktop.

**Comment by richard-ramos** [comment] 2024-01-26 15:22
Is it possible to obtain debug logs for this? I could only see info and error in geth logs

**Comment by VolodLytvynenko** [comment] 2024-01-26 15:52
> Is it possible to obtain debug logs for this? I could only see info and error in geth logs

@richard-ramos sure. Just a moment

**Comment by VolodLytvynenko** [comment] 2024-01-26 16:12
Hey @richard-ramos , I just noticed an important detail related to this issue. I am not able to recover the account only if I use the mobile network. It seems this issue is not reproducible for me on Wi-Fi. Here are the logs when the mobile network is used:
[android_logcat4.txt](https://github.com/status-im/status-mobile/files/14067042/android_logcat4.txt)

**Comment by richard-ramos** [comment] 2024-01-30 21:30
@status-im/mobile-devs, i have a dumb question: is it possible to set the build to use DEBUG level in the node config when restoring the profile? geth logs in info mode don't have enough details for me to discover what's wrong with the store node requests.

**Comment by richard-ramos** [comment] 2024-01-30 21:31
In the meantime, i'll try using a custom status-go version that sets everything to DEBUG by default

**Comment by qfrank** [comment] 2024-01-31 03:18
> @status-im/mobile-devs, i have a dumb question: is it possible to set the build to use DEBUG level in the node config when restoring the profile? geth logs in info mode don't have enough details for me to discover what's wrong with the store node requests.

PR build version default to [`DEBUG` level](https://github.com/status-im/status-react/blob/96d7ed77790e387b7a5d215c9a5e9b2dbece0233/.env.jenkins#L8) , if you want set it for local build, here is the [location](https://github.com/status-im/status-react/blob/96d7ed77790e387b7a5d215c9a5e9b2dbece0233/.env#L9)

relate files: <img width="270" alt="image" src="https://github.com/status-im/status-mobile/assets/12406719/1ed4f16c-ac1d-479c-856d-4171f7af59eb">

**Comment by richard-ramos** [comment] 2024-01-31 20:50
While debugging, this issue, I noticed the following log lines:
```
INFO [01-31|20:15:44.732|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:326]                                          connecting to mailserver                 address=/dns4/store-01.gc-us-central1-a.shards.test.statusim.net/tcp/30303/p2p/16Uiu2HAmMELCo218hncCtTvC2Dwbej3rbyHQcR8erXNnKGei7WPZ
INFO [01-31|20:15:44.732|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:373]                                          connecting to mailserver                 peer=store-01.gc-us-central1-a.shards.test
INFO [01-31|20:15:44.733|github.com/status-im/status-go/protocol/messenger_mailserver_cycle.go:423]                                          mailserver available                     address=16Uiu2HAmMELCo218hncCtTvC2Dwbej3rbyHQcR8erXNnKGei7WPZ
INFO [01-31|20:15:44.733|github.com/status-im/status-go/protocol/messenger_mailserver.go:128]                                                trying performing mailserver requests    try=0
DEBUG[01-31|20:15:44.818|github.com/status-im/status-go/protocol/messenger.go:1459]                                                          connection changed                       online=false
```

Looking at whats the flow to retrieve the backup, I see this function is invoked via `wakuext_requestAllHistoricMessagesWithRetries`:
https://github.com/status-im/status-go/blob/f31808d93891fd8e8d6d55c3a3a15620b54cedad/protocol/messenger_mailserver.go#L319-L322

And then, the function `IsOnline()` is invoked (https://github.com/status-im/status-go/blob/develop/protocol/messenger_mailserver.go#L44 ), which will return `false` as seen in the previous lines, thus, it will return early due to this piece of code.

```go
	if !shouldSync {
		return nil, nil
	}
```

So, it seems to me that it's a problem of trying to fetch the profile before we are even connected to a single peer. Perhaps we need to remove this code: 
```go
func (m *Messenger) shouldSync() (bool, error) {
	if m.mailserverCycle.activeMailserver == nil || !m.Online() {   <------------
		return false, nil                                       <------------
	}                                                               <------------
```
or should mobile wait to be 'online' (having at least one peer) before doing the request to `wakuext_requestAllHistoricMessagesWithRetries`.

thoughts? cc: @qfrank, @cammellos, @igor-sirotin

**Comment by cammellos** [comment] 2024-01-31 20:55
In theory, it should try to fetch backup if hasn't fetched it next time we go online, provided that RequestAllHistoricMessages is called:

```
// RequestAllHistoricMessages requests all the historic messages for any topic
func (m *Messenger) RequestAllHistoricMessages(forceFetchingBackup bool) (*MessengerResponse, error) {
        ...

	backupFetched, err := m.settings.BackupFetched()
	if err != nil {
		return nil, err
	}

	if forceFetchingBackup || !backupFetched {
		m.logger.Info("fetching backup")
		err := m.syncBackup()
		if err != nil {
			return nil, err
		}
		m.logger.Info("backup fetched")
	}

	filters := m.transport.Filters()
	m.updateFiltersPriority(filters)
	defer m.resetFiltersPriority(filters)
	response, err := m.syncFilters(filters)
	if err != nil {
		return nil, err
	}
	return response, nil
}
```

Or I misunderstand?

**Comment by richard-ramos** [comment] 2024-01-31 20:57
Hm. then there's something weird going on. I was logged in for some minutes and did not see that function being executed again. I'll try adding more logs to status-go to confirm.

**Comment by cammellos** [comment] 2024-01-31 21:00
> Hm. then there's something weird going on. I was logged in for some minutes and did not see that function being executed again. I'll try adding more logs to status-go to confirm.

interesting, that might be the issue then

**Comment by igor-sirotin** [comment] 2024-01-31 21:01
> Hm. then there's something weird going on. I was logged in for some minutes and did not see that function being executed again. I'll try adding more logs to status-go to confirm.

But if you already logged in before fetching the backup, wouldn't you push a new backup to the network therefore override the old one?

**Comment by richard-ramos** [comment] 2024-01-31 21:04
Btw, @cammellos another thing that could likely be also the cause of this problem. This code is also part of the `shouldSync` function, and going to the legacy settings, i see that syncing on mobile networks is disabled by default. Perhaps this is what's really messing things up,  because i just noticed that I run out of data plan on my phone hence why it never got online :)  

```go
       if !m.connectionState.IsExpensive() {
		return true, nil
	}

	syncingOnMobileNetwork, err := m.settings.CanSyncOnMobileNetwork()
	if err != nil {
		return false, err
	}
```

@VolodLytvynenko did mention earlier in https://github.com/status-im/status-mobile/issues/18637#issuecomment-1912317303 that he only runs into this problem when using mobile data!

**Comment by cammellos** [comment] 2024-01-31 21:04
> > Hm. then there's something weird going on. I was logged in for some minutes and did not see that function being executed again. I'll try adding more logs to status-go to confirm.
> 
> But if you already logged in before fetching the backup, wouldn't you push a new backup to the network therefore override the old one?

I am not familiar exactly with backup code anymore, but backup don't override each other I believe (ish, for example if you set a new name during onboarding, it would override, but say that you have communities in an old one, and you don't have any in the new account, that would not be overriden)

**Comment by cammellos** [comment] 2024-01-31 21:06
> Btw, @cammellos another thing that could likely be also the cause of this problem. This code is also part of the `shouldSync` function, and going to the legacy settings, i see that syncing on mobile networks is disabled by default. Perhaps this is what's really messing things up, because i just noticed that I run out of data plan on my phone hence why it never got online :)
> 
> ```
>        if !m.connectionState.IsExpensive() {
> 		return true, nil
> 	}
> 
> 	syncingOnMobileNetwork, err := m.settings.CanSyncOnMobileNetwork()
> 	if err != nil {
> 		return false, err
> 	}
> ```
> 
> @VolodLytvynenko did mention earlier in [#18637 (comment)](https://github.com/status-im/status-mobile/issues/18637#issuecomment-1912317303) that he only runs into this problem when using mobile data!

ah nice catch, I don't think we offer that anymore to the users, at least for now, so maybe we should remove that option and syncing anyway

**Comment by igor-sirotin** [comment] 2024-01-31 21:14
@richard-ramos the thing about checking `isOnline` during fetching from store nodes doesn't make any sense anyway, right? It could work earlier, but remember this PR happened recently: https://github.com/status-im/status-go/pull/4380. 
Store nodes were previously used as peers.

**Comment by richard-ramos** [comment] 2024-01-31 21:24
Yeah, i think it makes sense, because theoretically it could happen that you're not really connected to any node but can still connect to a store node!

**Comment by pavloburykh** [comment] 2024-02-01 14:08
> @VolodLytvynenko did mention earlier in [#18637 (comment)](https://github.com/status-im/status-mobile/issues/18637#issuecomment-1912317303) that he only runs into this problem when using mobile data!

Hey @richard-ramos! I think there might be also some different problem not related to mobile network. My assumption is based on our e2e tests. Emulators do not use mobile network but still sometimes data is not restored from Waku in our e2e. Anyway, once this fix https://github.com/status-im/status-mobile/pull/18688 will be tested and merged we will keep an eye on this issue and report if we will be facing it again.

**Closed as completed** 2024-02-02 17:03 UTC
Labels: waku
