### ISSUE TITLE
Deleting user's credentials from the device

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#4186] opened 2018-05-10 09:51 UTC
*Type*: Improvement

There is currently no way a user can remove their private and public key pairs from the device after
creating or recovering their account on the device without uninstalling Status. As it's possible to have multiple accounts, it's recommended to provide an option to delete them together with all data and key pairs.

### Solution
- add option to delete an account and make sure all artifacts fo that account are deleted as well

**Comment by mandrigin** [comment] 2019-02-26 16:44
duplicate of https://github.com/status-im/status-react/issues/1126, closing

**Closed as completed by mandrigin** 2019-02-26 16:44 UTC
