### ISSUE TITLE
Message from A is shown to B in the beginning of 1-1 chat if chat was deleted by A and started again 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1195] opened 2017-05-10 14:56 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: A has 1-1 chat with B. A deletes chat with B. A starts new chat with B by opening B from Contacts and sending new message "New after delete". For B new message is shown in the  beginning of 1-1 chat instead of being shown at the end.
Issue demonstrates itself in the same way as in #1051 and #1015

![chat with misplaced message after chat delete](https://cloud.githubusercontent.com/assets/6584810/25904818/a28547d6-35a0-11e7-9e42-698ddad3f493.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
New message is shown at the end of conversation in 1-1 chat
#### Actual behavior
[comment]: # (Describe what actually happened.)
New message is shown as a second message in the beginning of 1-1 chat
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- As Alice:
    - Open Status and login
    - Add Bob to your contacts by scanning QR code
    - Write to Bob "Hi Bob"
- As Bob:
    - Open Status and login
    - Open Chats
    - Tap on new chat with unknown contact (Alice)
    - Reply to Allice "Hi alice [add time]"
- As Alice
    - Wait for message from Bob
    - Write to Bob "will delete this chat [add time]"
    - Go back to Chats screen (tap on <)
    - In Chats screen tap "..." in top right corner
    - In menu select Edit chats
    - Next to the chat with Bob tap on "..."
    - Tap on Delete chat
    - Open Contacts
    - Tap on Bob
    - In chat write to Bob new message "NEW after delete on [add time]
- As Bob
    - check where is the message from Alice "New after delete" placed

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.6-66
* Operating System: Android  and iOS

**Comment by asemiankevich** [comment] 2017-08-08 09:15
I can reproduce it as described in case we have syncing very slow, so the very first message from A to B is "pending" and appears in the end of the chat later

https://app.testfairy.com/projects/4803622-status/builds/6285165/sessions/8/?accessToken=KCfHyfM5ggARF/JqlxuvPex6H5k

**Comment by oskarth** [comment] 2017-08-08 09:37
@asemiankevich At what time in that video does this happen?

**Comment by asemiankevich** [comment] 2017-08-08 09:40
@oskarth I 've seen it today less then hour ago on 0.9.8-114-g243cb7de+ branch, right after this syncing became slow again.

**Comment by oskarth** [comment] 2017-08-08 09:42
@asemiankevich I mean the linked video is almost 40 minutes long, at what timestamp does the problem occur?

**Comment by asemiankevich** [comment] 2017-08-08 09:43
@oskarth gosh))) sorry for that) it is the first 5 minutes)

**Comment by oskarth** [comment] 2017-08-08 09:44
@asemiankevich thanks, will have a look

**Comment by oskarth** [comment] 2017-08-08 09:53
@asemiankevich The sequence of events in the video in first 3 minutes isn't clear to me, it seems like it is all happening on a different phone not recorded? Could you write down what action what account is taking in what order? Thanks

**Comment by asemiankevich** [comment] 2017-08-08 11:02
@oskarth yeah sure

## Reproduction

### As Alice:

- Open Status and login
- Add Bob to your contacts by scanning QR code
- Write to Bob "First message" (notice the message status is stuck on "sending")

### As Bob:

- Open Status and login
- Open Chats
- Notice that no new chat is created because message is stuck on Sending 

### As Alice:

- Get back to Alice and delete chat with Bob 
- Send new message "Second message" to Bob

### As Bob:

- Tap on new chat with unknown contact (Alice)
- Reply to Allice "Hi alice [add time]"

### As Alice

- Wait for message from Bob
- Write to Bob "will delete this chat [add time]"
- Go back to Chats screen (tap on <)
- In Chats screen tap "..." in top right corner
- In menu select Edit chats
- Next to the chat with Bob tap on "..."
- Tap on Delete chat
- Open Contacts
- Tap on Bob
- In chat write to Bob new message "NEW after delete on [add time]

### As Bob

- check where is the message from Alice "New after delete" placed
- Pay attention that the very first message "First message" is now at the end of the chat

**Comment by oskarth** [comment] 2017-08-09 07:58
@asemiankevich Unable to reproduce the original issue on this branch. I suspect this has something to do with: *(notice the message status is stuck on "sending"* As far as I can tell from the issue description this is a separate issue.

Would you mind trying to reproduce again when there are no weird pending message issues? The related PR should be merged into `develop` soon, which might introduce related fixes that makes the pending message / syncing more stable.

If you are unable to reproduce I think we should open a separate issue, since, if I understand it correctly, the issue might not have anything to do with "deleting" messages but just a pending message being resent after another message? It'd be great to get a minimal case on that one, since I suspect it has something to do with the order we retry sending messages. I don't know how to simulate the bad pending message, though.

If you are able to reproduce the original issue again without the pending message thing, we'll have to debug further to see what is different in our setups.

**Comment by asemiankevich** [comment] 2017-08-09 08:21
@oskarth yeah, I will open separate issue for this Pending messages. Need to test and dig more into it  as I can't reproduce it now. The original PR can be merged as planned

**Closed** 2017-08-15 16:22 UTC
Labels: bug, medium-priority, Tested - OK
