### ISSUE TITLE
Text Jumping Issue in Maximized Composer on iOS 17.x

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17870] opened 2023-11-10 11:13 UTC
Originally reported by @clauxx [here](https://github.com/status-im/status-mobile/pull/17785#issuecomment-1804254216)

Currently the issue has been encountered only on IOS 17.x

**Steps:** 

1. Send a long multiline message (so that composer is maximised) 
2. Open editing of this message 
3. Start entering text into new line
4. Observe the behaviour

**Actual result:** When the composer is maximized and you're entering text into the new line, for the first 2-3 characters, the text jumps up and after ~3rd character the cursor/text comes back. 

https://github.com/status-im/status-mobile/assets/21865759/74dcc752-002c-45b0-ac83-de2dcb99adaa

 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment] 2023-11-21 17:17
Unassigning as I have enough in my queue

**Comment by ibrkhalil** [comment] 2023-12-18 15:53
Was able to reproduce on iOS 16
https://github.com/facebook/react-native/issues/39660
Trying the solution in this issue.

**Comment by ibrkhalil** [comment] 2023-12-19 13:56
Also [this](https://github.com/facebook/react-native/issues/37967) is happening

**Comment by ibrkhalil** [comment] 2023-12-24 11:41
This is an iOS related issue, It was fixed on iOS 17.2

**Comment by churik** [comment] 2024-04-04 14:46
@clauxx would appreciate it if you can confirm that it is not reproducible anymore, thank you!

**Comment by clauxx** [comment] 2024-04-04 14:53
Yep, can't reproduce it anymore so should be fine to close

**Closed as completed** 2024-04-04 15:52 UTC
Labels: ios, chat-composer, re-check
