### ISSUE TITLE
[iOS] Empty Send to screen when ENS address is entered and user gets back from Select assets screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#20983] opened 2024-08-08 09:47 UTC
# Bug Report

### Reproduction

1. Login to app on iOS device
2. Go to Wallet
3. Tap on Send
4. Enter ENS (e.g. elonmusk.eth)
5. Tap Continue
6. Go back

#### Expected behavior
Send to screen contains Address field with entered data

#### Actual behavior

https://github.com/user-attachments/assets/4588d28c-c79d-4934-9472-75d4cf0e139b

### Additional Information

- Device: iOS 17.5.1
- Status version: release buils
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by vkjr** [comment] 2024-08-08 13:25
@mariia-skrypnyk, can't reproduce this on the ios simulator, could you please attach the link to build where it happens?

**Comment by mariia-skrypnyk** [comment] 2024-08-08 14:02
@vkjr thanks for checking it!

It was a release build that you can find here :

https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F2.30.x/
<img width="248" alt="Screenshot 2024-08-08 at 15 57 37" src="https://github.com/user-attachments/assets/14954a62-c133-4a28-ab2c-260a77bdc007">



This bug is not 10/10 to reproduce but we face it in release build and looks very bad.

**Comment by smohamedjavid** [comment] 2024-08-21 13:09
The root cause is fixed here: https://github.com/status-im/status-mobile/pull/21100

**Comment by vkjr** [comment] 2024-08-21 14:15
@smohamedjavid, thanks for the finding! I will reassign this one to you then, so you can close it when PR merged

**Closed as completed** 2024-08-28 11:58 UTC
Labels: ios, wallet-core, potential-blocker
