### ISSUE TITLE
Color picker selected state doesn't match design [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19306] opened 2024-03-18 10:30 UTC
# Design Feedback 2.27

## [Android] Color picker selected state doesn't match design
**Color picker** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=48:39703&mode=design#738517549)] has incorrect style for the selected color: the border around the color is missing. This screen is from the wallet _Edit account_ page

<img width="393" alt="Screenshot 2024-03-18 alle 11 27 36" src="https://github.com/status-im/status-mobile/assets/122543089/7b794007-d743-423c-8775-afb63f6d56dd">

#### Expected behavior

<img width="375" alt="Screenshot 2024-03-18 alle 11 28 21" src="https://github.com/status-im/status-mobile/assets/122543089/03e28035-4d8e-472c-a8c2-5102857886eb">

### Reproduction

1. Open a wallet account
2. Tap on the wallet avatar at the top right corner of the screen
3. Select _Edit account_

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment] 2024-11-04 20:49
Closing because the issue is resolved since 2.30.0.

**Closed as completed by ilmotta** 2024-11-04 20:49 UTC
Labels: android, mobile-core, design-feedback
