### ISSUE TITLE
Community invite is not received if it was shared by non-admin

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17116] opened 2023-08-25 15:46 UTC
# Bug Report

## Problem 
Community invite is not received if the user shares the community of which they are not admin.

#### Expected behavior
Can see the community invite 

#### Actual behavior
The unread badge is shown, but there is no invite to community in 1-1 chat

### Reproduction
**Prerequisites:**
- User1, User2 and User3 are contacts
- User1 creates any community and shares it with User2

**Steps:**
1) User2: community > options > Share community to User3
2) User3: see unread indicator > open chat with User2

### Additional Information

- Status version: nightly 25/08/23
- Operating System: Android, iOS

https://github.com/status-im/status-mobile/assets/4557972/f0eff0de-7ed4-4896-9abe-1589731ee0a1

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment] 2023-08-27 17:32
I reproduced this issue once where all devices/emulators had different versions (Some old and some new), But on latest, I can't produce.
Can you please check on the latest build on all devices/emulators?

**Comment by churik** [comment] 2023-08-28 08:56
It was reproduced for me on nightly 25/08/23.


What version do you mean?

**Comment by churik** [comment] 2023-08-28 09:09
It is reproduced on PR builds https://github.com/status-im/status-mobile/pull/17091, which contain latest version of status-go.

**Comment by ibrkhalil** [comment] 2023-08-28 11:54
if you are sure that User 2 is on the latest version.
Okay, Will investigate more

**Comment by ibrkhalil** [comment] 2023-09-19 06:17
Hey @churik, I couldn't reproduce it on the latest version.

**Comment by pavloburykh** [comment] 2023-09-25 12:48
> Hey @churik, I couldn't reproduce it on the latest version.

Hi @ibrkhalil! The issue is still still reproducible. 

I have updated prerequisites. Non admin User 2 who shares the community should be a community member. Try the following steps. 


#### Expected behavior
Can see the community invite 

#### Actual behavior
The unread badge is shown, but there is no invite to community in 1-1 chat

### Reproduction
**Prerequisites:**
- User1, User2 and User3 are contacts
- User1 creates any community and shares it with User2
- **User 2 joins the community**

**Steps:**
1) User2: community > options > Share community to User3
2) User3: see unread indicator > open chat with User2

**Comment by ibrkhalil** [comment] 2023-09-26 16:10
Unassigning as I couldn't do much with this task.

**Comment by ilmotta** [comment] 2023-11-20 19:37
@pavloburykh, I just followed the exact steps to reproduce this issue, but it all works for me on `status-mobile` develop (commit 86c5505c94f83e15242f07a3ad735ddcb8c6c4a3). Once you find the time, could you try to reproduce the bug again? Just because your last comment is from ~3 months ago, and many changes were merged into status-go, so maybe this issue can be closed already.

@ibrkhalil, were you able to reproduce the bug? If so, have you done anything different from the reproduction steps shared by @pavloburykh here https://github.com/status-im/status-mobile/issues/17116#issuecomment-1733645946?

**Comment by ibrkhalil** [comment] 2023-11-20 19:44
> @pavloburykh, I just followed the exact steps to reproduce this issue, but it all works for me on `status-mobile` develop (commit 86c5505c94f83e15242f07a3ad735ddcb8c6c4a3). Once you find the time, could you try to reproduce the bug again? Just because your last comment is from ~3 months ago, and many changes were merged into status-go, so maybe this issue can be closed already.
> 
> 
> 
> @ibrkhalil, were you able to reproduce the bug? If so, have you done anything different from the reproduction steps shared by @pavloburykh here https://github.com/status-im/status-mobile/issues/17116#issuecomment-1733645946?

Yup, I reproduced it
Reproducing it is flaky

**Comment by pavloburykh** [comment] 2023-11-20 20:34
> Once you find the time, could you try to reproduce the bug again?

Hey @ilmotta! I am still reproducing the issue. I have tried in release and latest nightly builds. Below is the video recorded on release builds. 

In my case reproducing is not falky, easily reproducing the issue on every try using steps from this comment https://github.com/status-im/status-mobile/issues/17116#issuecomment-1733645946 

@ilmotta is community created on Desktop? 

https://github.com/status-im/status-mobile/assets/97245802/cf101278-249f-4724-9d29-d1da9e928a2b

**Comment by ibrkhalil** [comment] 2023-11-20 20:45
> > Once you find the time, could you try to reproduce the bug again?
> 
> 
> 
> Hey @ilmotta! I am still reproducing the issue. I have tried in release and latest nightly builds. Below is the video recorded on release builds. 
> 
> 
> 
> In my case reproducing is not falky, easily reproducing the issue on every try using steps from this comment https://github.com/status-im/status-mobile/issues/17116#issuecomment-1733645946 
> 
> 
> 
> @ilmotta is community created on Desktop? 
> 
> 
> 
> https://github.com/status-im/status-mobile/assets/97245802/cf101278-249f-4724-9d29-d1da9e928a2b
> 
> 
> 
> 

I am sorry, I thought this was the admin offline one 🤦‍♂️
But yeah, I am going to fix this one too

**Comment by ilmotta** [comment] 2023-11-21 11:52
> is community created on Desktop?

Yes @pavloburykh, same steps you outlined. I never create communities on mobile. But since @ibrkhalil mentioned flakiness, I was probably just lucky and thought the issue was already fixed.

Since the last comment you guys shared here were at the end of September and I was lucky to not hit the bug, I thought we could close the issue. Thanks for re-testing @pavloburykh.

> But yeah, I am going to fix this one too

Cool @ibrkhalil, thanks!

**Closed as completed** 2023-12-15 12:29 UTC
Labels: community
