### ISSUE TITLE
[Perf] User story 4: Time lags navigating to chat with 200 unread messages

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3336] opened 2018-02-15 08:20 UTC
***Type***: Bug

***Summary***: When ~200+ unread messages are present in the chat (public/group/1-1) - navigating to this chat has a noticeable app lag between user taps on the chat and chat screen appearance.
It depends from the device: for example on Samsung Galaxy Note 4 (real device) - it takes 10-12 seconds from the time when user taped on chat on Home screen with 200 unread messages till the actual chat screen with the messages appeared

However, navigating to the same chat with all 'read' messages - significantly faster (delay <0.3 seconds)

#### Expected behavior
When contact navigates to chat with 200 unread messages - they appear with the same time value as if contact would navigate to the same chat with all read messages.

#### Actual behavior
When contact navigates to chat with 200 unread messages - it takes 30 times more for messages to appear than navigating to the same chat with all read messages.

Precondition: 200 unread messages sent to the contact
### Reproduction

- Open Status and log in to account
- Wait till all the messages sent to account arrive (the counter of unread messages should stop incrementing)
- Tap on the chat with 200 unread messages
- Check the time when between you tap on chat from Home screen and when chat view with the messages load

### Additional Information
* Status version: 0.9.16-2-g1abd3c1a+
* Operating System: Android, iOS

#### Logs
There are no logs in TF of what happens during the discussed app freeze, but I believe somehow connected to sending the 'Seen' status for list messages.
Video of behavior navigating to chat with 200 unread messages: from 01:34 - is the time when contact taps on a chat with 200 unread messages. 
https://app.testfairy.com/projects/4803622-status/builds/8101280/sessions/27/?accessToken=-6aGtzW8RJTwTXdPHAjnS2aqqmA

**Comment by janherich** [comment] 2018-02-15 10:02
This is super strange because we already had solved this exact issue some time ago - I will check if there was not some performance regression introduced very recently.

**Comment by Serhy** [comment] 2018-04-15 12:24
Since the new protocol introduced the behaviour has changed a little bit. 
Issue still takes place as described, however now instead of 'Unshadowing' of the actual messages in message bubbles we had before - lags are taken place on actual chat screen appearance. I.e. there is a delay when user taps on chat from Home screen with the number of unread messages and chat with the list of messages appear.

I've updated the description with the new notes and with the new TF session.

**Comment by lukaszfryc** [comment] 2018-05-09 14:30
The issue is still there but it's not critical

**Comment by oskarth** [comment] 2018-05-28 04:38
What's the state of this issue? Is it still a beta blocker?

**Comment by Serhy** [comment] 2018-05-28 13:36
It takes 2 seconds now to open chat with 200 new unread messages on the Galaxy Note 4 (and 8-10 seconds chat with 1000 messages)
For me, such numbers are definitely not a Beta blocker.

The goal is not reached though. There is a difference whether contact navigates to chat with the messages that already seen and unread messages.

**Comment by janherich** [comment] 2018-05-28 13:45
@Serhy just for the record, what's the difference between opening chat with 1000 new unread/unseen messages (8-10s as you stated) and chat with 1000 red/seen messages ?

**Comment by Serhy** [comment] 2018-05-28 14:55
@janherich Navigating to public chat with 1000 read messages happens really fast, I would say <0.3 seconds. 8-10 seconds when unread message relates to public chat too (not only 1-1 / group).

**Comment by rasom** [comment] 2018-06-04 17:59
@Serhy i just tested this scenario 
> Open Status and log in to account
Wait till all the messages sent to account arrive (the counter of unread messages should stop incrementing)
Tap on the chat with 200 unread messages
Check the time when between you tap on chat from Home screen and when chat view with the messages load

on my galaxy note 4, using this build
> Release build 
Tests: :+1:)
Android: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-783f26-rel.apk
iOS: https://i.diawi.com/gsHT2m

and it takes approximately 2.5-2.9s 

<blockquote></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/gsHT2m">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by janherich** [comment] 2018-06-04 23:17
I spent some time evaluating the issue and here are my findings:

On moderately fast platform (Galaxy note 5 in Genymotion Emulator), the biggest culprit for bad performance when navigating to chat with unread messages is the function marking the messages as seen - https://github.com/status-im/status-react/blob/develop/src/status_im/chat/events.cljs#L225-L251
The function has to iterate over all loaded messages and to set operations which can be quite expensive on platform with poorer js performance.

One scenario which I tested was joining the #status channel on new account, immediately navigating back, waiting till all messages are received (takes just couple of seconds) and then navigating to chat again, with some 2-3 seconds lag.

When testing in repl, the function `mark-messages-seen` took over 400ms to compute the results with 1.8k new (unseen) messages, which is quite bad, because it means that only this computation causes 25 dropped frames at minimum and it's linearly growing so when somebody joins very busy public chats with 5000 new messages, it's noticeably worse.

The solution seems to be to not iterate over all the (loaded) messages naively each time chat is opened but maintain an 2 layer index `message-state->user->message` which will enable us to select all messages eligible for `seen` marking super fast, with almost no performance hit even with very big number of messages.


<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by rasom** [comment] 2018-06-05 07:09
@janherich is this enough as quick fix for pubchats? https://github.com/status-im/status-react/commit/7d5e6d5f0f5bb6632c40417d0966952298c72d02
it works ~3 times faster with this change, and as, most likely, we more often will have 200+ unseen messages in public chats than in 1-1 it should be enough as a first step

**Comment by oskarth** [comment] 2018-06-11 08:28
In its current state, is this a strict beta blocker? Or is it more something we'd really want to (keep) improving?

If it's the latter, how about we remove it from beta milestone but keep working on it (barring any other beta blockers)?

**Comment by mandrigin** [comment] 2018-06-11 11:05
Let's keep it in the list and re-evaluate when #4660 is merged.

**Comment by Serhy** [comment] 2018-06-13 08:04
#4660 has been closed. 

At this moment on lastest nighlty develop build (449th Jenkins build, 13th of June) on Galaxy Note 4 when a user navigates to public chat with ~500 unread messages the time delay between a tap on chat from Home screen till the messages appear (along with the app responsiveness) -> it takes ~2 seconds. In 1-1 chat with ~200 unread messages, it's 1-2 seconds.

These figures allow us to not only exclude issue from Beta-blockers list but I'm absolutely fine to close it as "Fixed".

**Closed as completed** 2018-06-13 08:43 UTC
Labels: performance
