### ISSUE TITLE
Community messaging issues

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14797] opened 2023-01-16 15:01 UTC
### ISSUE 1 Community channel appears with delay for newly joined member

**Preconditions**: User A and User B are mutual contacts

Bug is not reproducible every time. Sometimes up to 4 tries are needed for reproduction

**Steps:**

1. Create community by User A (I've been testing on open communities)
2. Send invite to User B
3. Create new community channel by User A 
5. Generate some message history in channel
6. By User B open 1-1 chat with User A (link from User A should be displayed but keep in mind about ISSUE ???)
7. Open community link by User B
8. Tap Join community by User B
9. See if community channel is displayed for User B

**Actual result:** channel appears with delay up to 2-5 minutes.

**Expected result:** channel is displayed right after community join.

https://user-images.githubusercontent.com/97245802/212356668-59fcfb20-6b98-416f-832e-f8b75dc2cf18.mp4

[community_owner_logs.zip](https://github.com/status-im/status-mobile/files/10412861/community_owner_logs.zip)

[new_member_logs.zip](https://github.com/status-im/status-mobile/files/10412863/new_member_logs.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by pavloburykh** [comment] 2023-01-16 15:06
### ISSUE 2 Sometimes channel history for newly joined user  is lost and never delivered later.

Below is an example that has been caught by e2e tests. Bug also can be reproduced manually following steps from ISSUE 1

Sender:
https://app.eu-central-1.saucelabs.com/tests/36d61a3f4d43449aa10fecb2035dab74?auth=54daa51c492ae6ee8c38d8d3b615c65f#139
Receiver: https://app.eu-central-1.saucelabs.com/tests/84e9a0e2e8ad4ff7a50b1d3bf372ce5b?auth=cf617cb29e0b5a3a99467c67ca9a9961#88
Log: 
[test_community_message_edit_geth2.log](https://github.com/status-im/status-mobile/files/10414063/test_community_message_edit_geth2.log)

**Comment by pavloburykh** [comment] 2023-01-16 15:07
### ISSUE 3 Messages sent in channel while being offline are not sent after coming back online. They stuck in sending status.

Seems that bug has been introduced by https://github.com/status-im/status-mobile/pull/14779 as I was not able to reproduce in develop. 

**Steps:**

1. Enable flight mode
2. Send some messages in community channel while being offline
3. Disable flight mode
4. See if messages are delivered after returning online

**Actual result:** messages stuck in "sending" status and never sent later. 

**Expected result:** messages should be sent and delivered after returning online

below video and logs are from PR build as it has not been yet merged into develop at the moment of testing. 

https://user-images.githubusercontent.com/97245802/212707655-f0ec0fe3-35ef-4b4c-9ad9-c408d060534c.mp4

[receiver.zip](https://github.com/status-im/status-mobile/files/10426872/receiver.zip)
[sender.zip](https://github.com/status-im/status-mobile/files/10426873/sender.zip)

**Comment by qoqobolo** [comment] 2023-01-18 14:26
ISSUE 3 is also relevant for deleting messages:
If UserA deletes messages while UserB is offline, some messages will remain in the chat for UserB when returning online.

**Comment by rasom** [comment] 2023-02-10 10:21
re: issue 3

One observation: if you turn connection off and send the message right away, wait 3-4 mins, turn it back on - then message will not be re-sent. But If you turn connection off and wait 3-4 mins, then send the message while offline, wait another 3-4 mins and turn connection back on - the message will be eventually re-sent.

Steps to repro:
1. Enable flight mode
2. Send messages A in community channel while being offline right away
3. wait 3-4 mins
4. Send messages B in community channel while being offline
5. wait 3-4 mins
6. Disable flight mode
7. wait 3-4 mins
8. see that message B is delivered, message A is not

So resending is in place, it just doesn't pick messages which are sent right after loosing connection (1-2 mins or so)

**Comment by rasom** [comment] 2023-02-10 13:40
@cammellos @richard-ramos 
It looks like it takes some time on waku side to "realise" that connection is lost, and this causes issue 3 when messages are sent in public chats and unencrypted communities (because waku still dispatches `EventEnvelopeSent` although there is no connection).

**Comment by cammellos** [comment] 2023-02-10 13:47
cc @siphiuel as he was looking into something similar

**Comment by vitvly** [comment] 2023-02-10 13:58
Interesting. Taking a wild guess, could be related to this code https://github.com/waku-org/go-waku/blob/57d707ff506819c0c20623883fcf73e84ef13ccd/waku/v2/node/keepalive.go#L32 ? Keep-alive needing some time to disconnect peers.

**Comment by rasom** [comment] 2023-02-10 14:32
@siphiuel, I commented out `go w.startKeepAlive(ctx, w.opts.keepAliveInterval)` and it still took about 2 mins on waku side to notice that connection is lost. 
If that's a proper way to verify that `startKeepAlive` is unrelated to the issue.

**Comment by vitvly** [comment] 2023-02-10 14:58
I see. Right, that code is there in the first place to prevent inactive peer disconnects.

Could be that keepAlive is a sort of early-warning mechanism that fails because we have a 10 sec default keepAlive interval (if i read that correctly in status-go), plus we multiply by 3 to get `sleepDetectionInterval`.

If you comment it away, then it makes things worse (it'll never be able to close peer itself), and in that case it's something that libp2p does on a lower level (peer disconnects in 2 mins). Maybe decreasing the `keepAliveInterval` can help.

**Comment by cammellos** [comment] 2023-02-10 15:10
@siphiuel I think the issue here is that we don't have acknowledgements from other peers, as we did in waku-1, so messages are marked as sent if the *leave* the node, but it could be that we are writing on a dead connection that we haven't realized is dead (i.e an half open socket).

It would be nice to get acknowledgements from other peers if possible, did we look into it @richard-ramos ?

**Comment by rasom** [comment] 2023-02-10 15:16
@siphiuel,
> If you comment it away, then it makes things worse

I would say it did not make any difference at all, it was around same 2 mins time. As default `keepAliveInterval` is 2 secs (much less than 2 mins already) I doubt that descreasing it would help here.

@cammellos, 
> as we did in waku-1

yep the issue is not reproducible in pub chats on the old release version which uses waku-1 as far as I understand.

**Comment by vitvly** [comment] 2023-02-10 15:28
> @siphiuel I think the issue here is that we don't have acknowledgements from other peers, as we did in waku-1, so messages are marked as sent if the _leave_ the node, but it could be that we are writing on a dead connection that we haven't realized is dead (i.e an half open socket).

Right. That is why in `startKeepAlive` we're doing the pinging via libp2p's Ping protocol, as this seems to be the good way to find out if the peer is responding and the connection is still alive.

@rasom so after going to flight mode there's a ~2min interval when all messages being sent are lost, disregarding whatever keepAliveInterval we have or if we even have it running? And after 2 mins elapse message can be resent once the connection is back?

**Comment by vitvly** [comment] 2023-02-10 15:34
Meaning - strange, then it seems like `Network().ClosePeer()` is not enough.

**Comment by rasom** [comment] 2023-02-10 15:36
@siphiuel 

> so after going to flight mode there's a ~2min interval when all messages being sent are lost, disregarding whatever keepAliveInterval we have or if we even have it running? And after 2 mins elapse message can be resent once the connection is back?

That is correct. It also can be observer on "Peers stats" screen (on mobile) as "Peers count" slowly decreases to zero during those ~2 mins.

**Comment by rasom** [comment] 2023-02-10 15:40
@siphiuel well, regarding 2 mins: it seems that this time is around that time or even longer on iOS simulator when on real iOS device it might be under 1 minute. So it depends

**Comment by rasom** [comment] 2023-02-10 15:49
@siphiuel just double-checked: if there are zero peers after loosing connection then messages is resent later, otherwise it is lost. So this is a bit more precise way to determine what happens than just waiting for 2 mins :)

**Comment by richard-ramos** [comment] 2023-02-10 15:53
> @cammellos It would be nice to get acknowledgements from other peers if possible, did we look into it?

AFAIK with current implementation, this is only possible with lightpush, since you get a response indicating that the node you chose to broadcast a message received your request. I'll take a look at go-libp2p-pubsub to see how the Publish function works in case of disconnection.

**Comment by richard-ramos** [comment] 2023-02-10 16:13
Seems to me like if go-libp2p-pubsub cannot send a message, nothing happens?
https://github.com/libp2p/go-libp2p-pubsub/blob/master/comm.go#L181-L186

EDIT:
So, `stream.Reset()` and `stream.Close()` are executed. I guess this does not remove the peers from the list of connected peers. I'll continue investigating...

**Comment by rasom** [comment] 2023-02-11 08:57
@siphiuel 
1. I was wrong and `keepAliveInterval` was 10s, not 2s. 
2. Decreasing it to 2s shortens the gap when message is sent and lost but doesn't remove the gap completely. Idk if that is actually desirable to make this interval much shorter or even shorter than 10s.

@richard-ramos @cammellos 
What if on reaching zero peers we mark all messages which were sent in last 1-2mins as not sent so that those are resent on reconnection. This sounds dumb and is not 100% reliable but likely will fix some of issues here.

**Comment by richard-ramos** [comment] 2023-02-14 23:54
So i followed the code from https://github.com/status-im/status-go/blob/develop/vendor/github.com/libp2p/go-libp2p-pubsub/comm.go#L170-L175 and saw that if the node has an active tcp connection, and then the machine is disconnected, it will still attempt to send data via the connection and not fail, so it's getting buffered somewhere...(perhaps at OS level).  The peer only gets disconnected when we try to read data from it (which happens with the keep-alive loop).

I see in go-libp2p-pubsub that `s network.Stream` has a [`SetWriteDeadline`](https://pkg.go.dev/net#TCPConn.SetWriteDeadline) function available. Perhaps we can try to force a small timeout there and see how it behaves? 


> @cammellos: I think the issue here is that we don't have acknowledgements from other peers, as we did in waku-1
> It would be nice to get acknowledgements from other peers if possible, did we look into it @richard-ramos ?

I guess that would involve doing a fork of go-libp2p-pubsub and making changes in the protocol? looking at https://github.com/libp2p/specs/blob/master/pubsub/README.md#stream-management I don't see guidance in the pubsub RFC on how replying to RPC messages is handling.

cc: @Tanguy and @jm-clius for ideas!

**Comment by churik** [comment] 2023-03-10 11:13
09/03 and 10/03 I'm facing a delay in delivering community messages.
Sometimes message state is just is not changed to "Sent", sometimes it is changed, but messages actually are not delivered.

**Data for sender**:
Video: https://app.saucelabs.com/tests/ab45c52418bc45cc87d8185ca27f2462#141 (sent at 5:25)
Full logcat for sender: [logcat (6).log](https://github.com/status-im/status-mobile/files/10941356/logcat.6.log)

**Data for receiver**: 
Video: https://app.saucelabs.com/tests/ef295b053b674875b558c5fc128a56f7#92 (came to chat at 5:45 and waited for almost 2 mins - no message arrived)
Full logcat for receiver:  [logcat (7).log](https://github.com/status-im/status-mobile/files/10941386/logcat.7.log)

Not sure they are useful though, if not - tell me what is the acceptable time to wait for a message in e2e (IMO it should be max 60 sec) and we can measure what the percentage of e2e will fail with a timeout.


сс @cammellos

**Comment by churik** [comment] 2023-03-10 14:03
More logs from now: 
https://app.saucelabs.com/tests/5525b07ca63444fe924d0932747fe328#106 - the message hasn't changed a state to "Sent" during 120 sec.
Logcat: [logcat (8).log](https://github.com/status-im/status-mobile/files/10942724/logcat.8.log)

**Comment by cammellos** [comment] 2023-03-13 09:27
@jo-mut reported a similar issue:

some relevant logs
```
t=2023-03-13T08:43:03+0000 lvl=eror msg="failed to resolve local interface addresses" error="route ip+net: netlinkrib: permission denied"
```

https://github.com/golang/go/issues/40569#issuecomment-1050381441

**Comment by jo-mut** [comment] 2023-03-13 09:43
I also noticed after a long while the messages are delivered but its like the delivery process is choosy. Some are never delivered at all.

**Comment by qoqobolo** [comment] 2023-03-15 11:39
Adding logs from the mobile app for two of my cases when I didn't receive messages on 14/03 and 15/03.
In both cases, I received messages on the mobile app but not on the desktop, although that could be a coincidence.
An attempt to reproduce the issue by just returning from offline failed.

14/03 [logs (56).zip](https://github.com/status-im/status-mobile/files/10978828/logs.56.zip) (messages were not received  on desktop in the #mobile channel)

15/03 [logs (57).zip](https://github.com/status-im/status-mobile/files/10978830/logs.57.zip) (messages were not received  on desktop in the #mobile channel and in one 1-1 chat)

**Comment by churik** [comment] 2023-03-17 12:36
More logs when mobile device completely stopped receiving messages, but it can send messages:
[logs (29).zip](https://github.com/status-im/status-mobile/files/11001363/logs.29.zip)

**Comment by cammellos** [comment] 2023-03-23 16:01
> Adding logs from the mobile app for two of my cases when I didn't receive messages on 14/03 and 15/03. In both cases, I received messages on the mobile app but not on the desktop, although that could be a coincidence. An attempt to reproduce the issue by just returning from offline failed.
> 
> 14/03 [logs (56).zip](https://github.com/status-im/status-mobile/files/10978828/logs.56.zip) (messages were not received on desktop in the #mobile channel)
> 
> 15/03 [logs (57).zip](https://github.com/status-im/status-mobile/files/10978830/logs.57.zip) (messages were not received on desktop in the #mobile channel and in one 1-1 chat)

The issue in this logs is due to the nameserver timing out:


```
t=2023-03-15T10:31:09+0000 lvl=warn msg="dns discovery error " error="lookup prod.nodes.status.im on [::1]:53: dial udp 1.1.1.1:53: i/o timeout"
```
@qoqobolo where are you connecting from? mobile data/wifi etc

**Comment by cammellos** [comment] 2023-03-23 16:05
> More logs when mobile device completely stopped receiving messages, but it can send messages: [logs (29).zip](https://github.com/status-im/status-mobile/files/11001363/logs.29.zip)

this is different, 

```
t=2023-03-17T12:24:14+0000 lvl=warn msg="failed to validate message" site=handleChatMessage error="clock value too high"
```

This happens when clock of sender/receiver drifts too much in the future (with waku-1 they would not be propagated, but with waku 2 they are, so maybe that's why we see them), though is a bit odd since both clocks should be ntp synced, but the cases are two:

either the sender has a time in the future
or the received has time in the past (or both ;)) 

investigating, but in case you have the logs of the sender, that would be helpful (geth.log)

**Comment by qoqobolo** [comment] 2023-03-23 16:26
> where are you connecting from? mobile data/wifi etc

From wifi

**Comment by qoqobolo** [comment] 2023-03-24 10:31
@cammellos regarding this issue:

> This happens when clock of sender/receiver drifts too much in the future (with waku-1 they would not be propagated, but with waku 2 they are, so maybe that's why we see them), though is a bit odd since both clocks should be ntp synced, but the cases are two:
either the sender has a time in the future
or the received has time in the past (or both ;))
investigating, but in case you have the logs of the sender, that would be helpful (geth.log)

I ran into a problem with creating group chats.
I tried to create group chats on one of my devices - Huawei, inviting to those groups two other devices - Pixel and iPhone.

Groups were created on the admin side (Huawei), but the invited members never received them.

I checked the Huawei date&time settings and found that the date and time were set **manually** there, and the time was indeed a little behind the other two devices (~30 seconds).

I changed the setting to `set automatically` and that fixed the problem - groups created on Huawei started showing up on other devices.

Logs before changing the settings 
[Group admin (Huawei) geth.log](https://github.com/status-im/status-mobile/files/11061038/geth.log)
[Member (Pixel) geth.log](https://github.com/status-im/status-mobile/files/11061047/geth.log)



Question: should we (and can we) somehow handle this behavior if the time is set manually on a device? Do we need a separate issue for this?

**Comment by cammellos** [comment] 2023-03-24 10:34
@qoqobolo thanks for the info

We have a solution for this, we use our own, independently synchronized time, that was with waku-1, since we had similar issues. We also have that for waku-2, but seems like it's not been used, investigating, but that should be the solution.

**Comment by pavloburykh** [comment] 2023-03-30 16:16
@cammellos here is a recent example from 1-1 chat

User A sends messages to User B

**Actual result:** User B does not receive messages. At the same time User A receives messages from User B

[User_A_sender.zip](https://github.com/status-im/status-mobile/files/11113666/User_A_sender.zip)
[User_B-receiver.zip](https://github.com/status-im/status-mobile/files/11113667/User_B-receiver.zip)

https://user-images.githubusercontent.com/97245802/228899725-0fad0140-9df9-4fa4-83c4-af8f2b7c3395.mp4

**Comment by cammellos** [comment] 2023-03-30 17:51
There's a couple of suspicious logs:

```
t=2023-03-30T16:02:12+0000 lvl=warn msg="error bumping delivery tag: no decaying tag registered for topic /waku/2/default-waku/proto"
```
```
t=2023-03-30T15:57:20+0000 lvl=info msg="retrieving nodes" enr=enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.nodes.status.im
t=2023-03-30T15:57:20+0000 lvl=dbug msg="iterating peer exchange" error="obtaining iterator: no discv5 listener"
```

But otherwise the peers look healthy on both devices (> 5)

still looking into it

**Comment by cammellos** [comment] 2023-03-30 17:52
oh, the messages are marked as delivered, in the video, this is a bit more troubling, it might not be a waku issue

**Comment by pavloburykh** [comment] 2023-04-05 08:10
> ISSUE 3 is also relevant for deleting messages: If UserA deletes messages while UserB is offline, some messages will remain in the chat for UserB when returning online.

Also, if User A deletes a message while he is offline, the message will not be deleted for User B after User A returns online.

**Comment by churik** [comment] 2023-04-25 13:11
for now, got a situation when the device is lost; 
can send messages, but cannot receive them - not in communities, nor in 1-1 chat.
Note: the account was restored and synced with QR syncing flow.
Logs: [adb_log.log](https://github.com/status-im/status-mobile/files/11322805/adb_log.log)

**Comment by cammellos** [comment] 2023-04-25 13:17
> for now, got a situation when the device is lost; can send messages, but cannot receive them - not in communities, nor in 1-1 chat. Note: the account was restored and synced with QR syncing flow. Logs: [adb_log.log](https://github.com/status-im/status-mobile/files/11322805/adb_log.log)

do you have geth.log from this device?
did you recover this device often lately?

**Comment by churik** [comment] 2023-04-25 13:51
no, I don't have as I reproduced it here: https://github.com/status-im/status-mobile/pull/15689#issuecomment-1521807375 
I recover this device from time to time (couple of times per week more or less)

UPD: got logs.
[geth.log](https://github.com/status-im/status-mobile/files/11323670/geth.log)

cc @cammellos

**Comment by churik** [comment] 2023-05-31 15:02
Closing as not sure it is useful

**Closed as completed by churik** 2023-05-31 15:02 UTC
Labels: e2e test blocker
