### ISSUE TITLE
Collectibles not displayed after account recovery and after watch only account is added until relogin

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18613] opened 2024-01-24 16:13 UTC
### Steps:
1. Add watch only account or restore account with collectibles
2. Go to the 'collectibles' tab

### Actual result:
The collectibles are not displayed until the user performs a re-login.

### Expected result:
The collectibles should be immediately visible after resoter or as soon as the watch only account is added 

### Logs:
[Status-debug-logs (1).zip](https://github.com/status-im/status-mobile/files/14040937/Status-debug-logs.1.zip)

### Additional info:
Feel free to reach out to me directly if you need a user with collectibles.  I will provide the seed phrase.

**Comment by J-Son89** [comment] 2024-04-08 10:30
@mmilad75, @VolodLytvynenko what's the status on this issue? Is it still a problem?

cc @smohamedjavid as you looked into account recovery recently, perhaps a part of a larger issue? 🤔

**Comment by VolodLytvynenko** [comment] 2024-04-08 10:59
> @mmilad75, @VolodLytvynenko what's the status on this issue? Is it still a problem?
> 
> cc @smohamedjavid as you looked into account recovery recently, perhaps a part of a larger issue? 🤔

Yes @J-Son89 the problem still exists

**Comment by smohamedjavid** [comment] 2024-04-08 11:46
@VolodLytvynenko - Quick confirmation: The collectibles (which are not fetched) are from the additional accounts which are not recovered, right?

**Comment by VolodLytvynenko** [comment] 2024-04-08 12:01
> @VolodLytvynenko - Quick confirmation: The collectibles (which are not fetched) are from the additional accounts which are not recovered, right?

Hey @smohamedjavid 
Collectibles are not fetched until the account is relogin in such cases:
- When an account  is recovered
- When new account with collectibles is added (example: add this `0x8d2413447ff297d30bdc475f6d5cb00254685aae` account as watch only)

**Comment by mmilad75** [comment] 2024-04-17 13:54
When an account is recovered (i.e. using recovery phrase), this is the list of accounts that are returned from back end which is only one account address:

<img width="834" alt="Screenshot 2024-04-10 at 15 35 12" src="https://github.com/status-im/status-mobile/assets/55688834/200de314-7cd6-409f-9a58-16e1dc9cb595">

But when the same account is logged in, all of the accounts are returned:

<img width="1357" alt="Screenshot 2024-04-10 at 15 32 35" src="https://github.com/status-im/status-mobile/assets/55688834/709de658-729b-4d19-bb04-61e9b7e70f45">

This seems to be a backend issue.

There is also one more issue when adding a new account for the first time as watch-only account:

<img width="511" alt="Screenshot 2024-04-17 at 12 52 36" src="https://github.com/status-im/status-mobile/assets/55688834/a947922d-100a-4ac4-8b0a-8e0ac2da227d">

This is the log of calling backend using `wallet_getOwnedCollectiblesAsync` method. The following image is the response of the call:

<img width="944" alt="Screenshot 2024-04-17 at 12 58 50" src="https://github.com/status-im/status-mobile/assets/55688834/98e47a4d-b2a6-44db-b100-05a261e3f435">

Where the `[]` is the collectibles, `0x8d2413447f297d30bdc475f6d5cb00254685aae` is the address of the account, and `false` is the value of `hasMore` property. As it can be seen, there is no collectible returned from backend.

Now, after removing the account as watch-only, and the re-add it, the following will happen:

<img width="522" alt="Screenshot 2024-04-17 at 12 54 14" src="https://github.com/status-im/status-mobile/assets/55688834/630d836b-c7d0-4f5f-a143-a4e43d81e763">

As it can be seen, the same params are passed to the backend. But we are getting different response:

<img width="929" alt="Screenshot 2024-04-17 at 12 55 30" src="https://github.com/status-im/status-mobile/assets/55688834/10ee30f6-fb29-40ab-a816-f38ef0046022">

As you can see here, the list of collectibles are returned, and the value of `hasMore` is also true here.

**Comment by smohamedjavid** [comment] 2024-05-27 11:05
> Collectibles are not fetched until the account is relogin in such cases:
> 
> * When an account  is recovered
> * When new account with collectibles is added (example: add this `0x8d2413447ff297d30bdc475f6d5cb00254685aae` account as watch only)


@VolodLytvynenko  - Can you check in the Desktop app? Try to recover a profile with multiple accounts (with collectibles in it). I believe this issue exists in Desktop as well. 


> When an account is recovered (i.e. using recovery phrase), this is the list of accounts that are returned from back end which is only one account address: But when the same account is logged in, all of the accounts are returned:

@mmilad75 - I fixed it in my PR: https://github.com/status-im/status-mobile/pull/20160

**Comment by VolodLytvynenko** [comment] 2024-05-27 13:34
> @VolodLytvynenko - Can you check in the Desktop app? Try to recover a profile with multiple accounts (with collectibles in it). I believe this issue exists in Desktop as well.


hi @smohamedjavid On the desktop, the  collectibles are shown after the account is recovered, but they are not shown for watch-only accounts even after relogin

**Comment by mmilad75** [comment] 2024-05-28 11:37
> > @VolodLytvynenko - Can you check in the Desktop app? Try to recover a profile with multiple accounts (with collectibles in it). I believe this issue exists in Desktop as well.
> 
> hi @smohamedjavid On the desktop, the collectibles are shown after the account is recovered, but they are not shown for watch-only accounts even after relogin

I faced the same thing. I tested with build 2.29.0-rc.4

**Comment by smohamedjavid** [comment] 2024-06-03 09:57
@VolodLytvynenko - Can you help us confirm whether the issue is reproducible on your end in Desktop?

**Comment by VolodLytvynenko** [comment] 2024-06-03 13:50
> @VolodLytvynenko - Can you help us confirm whether the issue is reproducible on your end in Desktop?

@smohamedjavid Yes. Will provide feedback soon

**Comment by VolodLytvynenko** [comment] 2024-06-03 14:33
> @VolodLytvynenko - Can you help us confirm whether the issue is reproducible on your end in Desktop?

@smohamedjavid On desktop, collectibles are shown immediately after the account is recovered. (on mobile they shown after relogin only)
However, for watch-only accounts, collectibles are not shown at all, even after re-login. (on mobile they shown after relogin)

[logs.txt](https://github.com/user-attachments/files/15535277/logs.txt)

**Comment by churik** [comment] 2024-06-21 15:28
cross-referencing with https://github.com/status-im/status-mobile/issues/19422

**Comment by ajayesivan** [comment] 2024-07-26 11:31
@mmilad75 What is the status of this issue? are you still working on it?

**Comment by mmilad75** [comment] 2024-07-26 12:06
@smohamedjavid Hi Javid. As we discussed before, you were working on this issue on another ticket, right?

**Comment by smohamedjavid** [comment] 2024-07-26 16:13
Hi @mmilad75 - No, I'm not working on this at the moment.

**Comment by mmilad75** [comment] 2024-07-26 16:37
> Hi @mmilad75 - No, I'm not working on this at the moment.

But here you said that you had fixed it https://github.com/status-im/status-mobile/issues/18613#issuecomment-2133239238

**Comment by smohamedjavid** [comment] 2024-07-26 17:08
https://github.com/status-im/status-mobile/issues/18613#issuecomment-2133239238 - This is about retrieving all addresses when recovering a profile (previously all addresses were shown when the user re-login). We request collectibles for all the addresses as usual. It looks like the status-go issue, I will check this next week. 👍

**Comment by dlipicar** [comment] 2024-07-29 16:54
Checked the logs in the original message. I see a lot of these:
```
ERROR[01-24|15:40:41.234|github.com/status-im/status-go/services/wallet/collectibles/manager.go:301]                                         FetchAllAssetsByOwner failed for         provider=rarible chainID=1 err="unsuccessful request: 400 Bad Request"
ERROR[01-24|15:40:41.236|github.com/status-im/status-go/services/wallet/collectibles/manager.go:301]                                         FetchAllAssetsByOwner failed for         provider=rarible chainID=1 err="unsuccessful request: 400 Bad Request"
ERROR[01-24|15:40:41.239|github.com/status-im/status-go/services/wallet/collectibles/manager.go:301]                                         FetchAllAssetsByOwner failed for         provider=rarible chainID=42161 err="unsuccessful request: 400 Bad Request"
ERROR[01-24|15:40:41.244|github.com/status-im/status-go/services/wallet/collectibles/manager.go:301]                                         FetchAllAssetsByOwner failed for         provider=rarible chainID=42161 err="unsuccessful request: 400 Bad Request"
ERROR[01-24|15:40:41.306|github.com/status-im/status-go/services/wallet/collectibles/manager.go:301]                                         FetchAllAssetsByOwner failed for         provider=rarible chainID=1 err="unsuccessful request: 400 Bad Request"
ERROR[01-24|15:40:41.317|github.com/status-im/status-go/services/wallet/collectibles/manager.go:301]                                         FetchAllAssetsByOwner failed for         provider=rarible chainID=42161 err="unsuccessful request: 400 Bad Request"
ERROR[01-24|15:40:41.332|github.com/status-im/status-go/services/wallet/collectibles/manager.go:301]                                         FetchAllAssetsByOwner failed for         provider=openseaV2 chainID=10 err="unsuccessful request: 403 Forbidden"
```

Which is explained by these:
```
WARN [01-24|16:10:07.548|github.com/status-im/status-go/services/wallet/thirdparty/rarible/client.go:92]                           Rarible API key not available for Mainnet 
WARN [01-24|16:10:07.555|github.com/status-im/status-go/services/wallet/thirdparty/rarible/client.go:96]                           Rarible API key not available for Testnet 
WARN [01-24|16:10:07.555|github.com/status-im/status-go/services/wallet/thirdparty/alchemy/client.go:91]                           Alchemy API key not available for        chainID=1
WARN [01-24|16:10:07.555|github.com/status-im/status-go/services/wallet/thirdparty/alchemy/client.go:91]                           Alchemy API key not available for        chainID=5
WARN [01-24|16:10:07.555|github.com/status-im/status-go/services/wallet/thirdparty/alchemy/client.go:91]                           Alchemy API key not available for        chainID=11155111
WARN [01-24|16:10:07.555|github.com/status-im/status-go/services/wallet/thirdparty/alchemy/client.go:91]                           Alchemy API key not available for        chainID=11155420
WARN [01-24|16:10:07.555|github.com/status-im/status-go/services/wallet/thirdparty/alchemy/client.go:91]                           Alchemy API key not available for        chainID=421614
```

Not sure what kind of build that is, but status-go is not getting Rarible or Alchemy keys.

**Comment by churik** [comment] 2024-08-08 09:43
due to time/resource constraints, I don't think that we can fix it 2.30.

Deferred for now;

**Comment by smohamedjavid** [comment] 2024-08-08 10:22
The collectibles for those addresses are never fetched before and it is being fetched (updating) in status-go and that's why the user sees the empty data.

status-go fetches collectibles for each chain separately and signals the client when the update is finished so that the client can request the data again. Each chain update time differs. Dario mentioned that Desktop usually resets the list when each chain update is completed. 

IMO, It's not good to apply the same to mobile due to list performance, and json->cljs transforms where the fetched data is going to be reset in a few seconds. Ulises and I think it's good to wait for all chains to be updated. The only caveat is the wait time. On average, if we wait for all the chains to be updated, it takes around 6-12 secs. Typically, the updating time depends on the number of collectibles in each chain too. We can show a loader or information box with a message saying collectibles are being updated. 

We have WIP progress PR https://github.com/status-im/status-mobile/pull/20961 to resolve this. Currently, it resets the list upon each chain update is finished. It will be a tolerable performance of the list if anyone wants to check it out. But we are inclined towards waiting for all the chains to be updated. Let me know your thoughts. @VolodLytvynenko @churik

**Comment by churik** [comment] 2024-08-08 12:17
Thank you for such an extensive update @smohamedjavid !

I'd vote for the loader, yes, if it is less than 1 minute (which I suppose is true based on the comment), that sounds like a good enough solution for now.

**Comment by ulisesmac** [comment] 2024-09-19 01:39
Reopening since while solving:
-  https://github.com/status-im/status-mobile/issues/21270https://github.com/status-im/status-mobile/issues/21270

In:
- https://github.com/status-im/status-mobile/pull/21286

I noticed they are still stuck on a loading state, PR's video:

https://github.com/user-attachments/assets/5a4559e7-edd4-4ef4-bfba-e65c67620981


CC: @smohamedjavid

**Comment by churik** [comment] 2024-09-19 08:55
@ulisesmac 
I suppose that it ius different bug, because in initial the collectibles were not shown at all before several re-logins. Currently it seems that the big amount of collectibles can not be shown in acceptable timeframe.


We'll recheck on accounts with less collectibles.

**Comment by pavloburykh** [comment] 2024-09-19 12:40
@ulisesmac I agree with @churik This is a separate issue which is in fact described here https://github.com/status-im/status-mobile/issues/21270 and thus should be fixed separately. 

Current issue is not reproducible for me, so I am closing it. Feel free to comment here in case you disagree. Thank you!

**Closed as completed by pavloburykh** 2024-09-19 12:40 UTC
Labels: wallet: Collectibles, re-check, wallet-core, potential-blocker

**Comment by ulisesmac** [comment] 2024-09-19 16:25
@churik @pavloburykh 

Thanks for re checking this.

In the video I shared we are actually **not showing any collectible so they are not in a loading state**,  it's just a placeholder that looks as 8 collectibles always loading, so these 8 collectibles don't reflect the amount of collectibles owned by the account.

In other words, in the past when we had no collectibles, we put a meme there, now we put 8 fake collectibles loading.

I have tried multiple relogins and most of the time the result is the same for a fresh status install.

CC: @smohamedjavid are you able to reproduce the issue, seems it was solved, maybe some changes in status-go broke this again? 

Also, now I wonder if this 8 collectible loader is misleading for the user 🤔

**Comment by churik** [comment] 2024-09-23 09:30
@ulisesmac 
before we could reproduce it almost every time with our own accounts, that comprise 10-12 collectibles, currently it seems the case only for watch-only, that's why I think it probably makes sense to move it to separate issue.

I'm not sure about the root cause though, it might be the same.
