### ISSUE TITLE
`eth_signTypedData_v4` signature never completes

### ISSUE THREAD

**Issue by alfetopito** [status-im/status-react#12097] opened 2021-05-07 16:46 UTC
# Bug Report

## Problem 

Signing a message with `eth_signTypedData_v4` never completes.
It keeps "processing" indefinitely.
The same is true for `eth_signTypedData_v3`

#### Expected behavior
The message is signed

#### Actual behavior
The app is "processing" after the card is connected and never completes.

### Reproduction

1. Setup this repo in your local network https://github.com/BboyAkers/js-eth-personal-sign-examples
    1. Clone the repo, cd into it, then: `npm i && npm run build && npx serve`
    2. It should serve a page in your local host at `http://<your local ip>:5000`
1. Make sure your mobile device is connected in the same network as the device serving the above page
1. Open Status
1. Open the app browser
2. Open `http://<your local ip>:5000`
3. Click on connect and accept the local connection
4. Click on `eth sign typed data v4` (the behaviour is the same with `v3`)
5. Follow the steps to use your keycard to sign the message

### Additional Information

- Status version: 1.13.0 
- Operating System: Android

**Comment by bitgamma** [comment] 2021-05-07 17:00
could it be a duplicate of #11706? For example if you are connected to mainnet but the dapp specifies test chain or private chain in the data to sign

**Comment by alfetopito** [comment] 2021-05-07 17:23
Well, I'm not sure, since I have no access to an in app debugger.

I first observed the failure while testing our dApp on Mainnet: https://cowswap.exchage

Actually, the dApp takes the network from the injected provider, so it should use whatever the wallet is giving, which I assume is mainnet.

To reproduce that in CowSwap it'll cost you ETH for one approval and ERC20 funds to actually swap, as that is required before doing a swap.
After that you should be prompted for the signature.

For this reason I went with the github repo where the signature is requested straight away.

**Comment by bitgamma** [comment] 2021-05-11 08:46
I managed to reproduce the issue. I had to switch to the ``signature-refactor`` branch to make it work which was not indicated in the reproduction steps so it took a while to get there.

My findings are as follow:

1. This is not related to Keycard, although the issue #11706 makes it harder to debug since you don't get the error message and it just hangs. If you use a regular account you get an error message
2. Status is correct refusing to sign the v3 example. The problem is that the chainId value while specified to be a number in the JSON it is as string. More pratically, instead of ``"chainId": 1`` the dapp sends ``"chainId": "1"`` (note the quotes). This causes the error ``json: cannot unmarshal string into Go value of type int64``. By changing ``netId`` to ``parseInt(netId)`` at line 301 of the dapp, signing works.
3. in the v4 example the chainId is hardcoded to 1 (which is OK if testing on mainnet) and is indeed a number. The error is ``json: cannot unmarshall number into Go struct field TypedDataDomain.domain.chainId of type *math.HexOrDecimal256``. This one needs more investigation

**Closed as completed** 2021-05-12 10:48 UTC

**Comment by bitgamma** [comment] 2021-05-12 10:49
@alfetopito we have changed the implementation to accept either a string or number as chainID. Now a signature is generated both for v3 and v4

**Comment by alfetopito** [comment] 2021-05-12 17:49
Awesome, thanks for that @bitgamma 

Any idea when that change will go live? I assume it requires a new app release on the respective stores (Android/iOS)

**Comment by bitgamma** [comment] 2021-05-13 06:39
It will be in the next release, but I cannot tell for sure when it will be. We release roughly once a month. If you wish to try it out you can download a nightly build (if you are on Android) from https://status.im/nightly/

**Comment by anxolin** [comment] 2021-05-13 08:35
Hi @bitgamma how can I try it for IOS?

![IMG_9424](https://user-images.githubusercontent.com/2352112/118100526-d9009780-b3d6-11eb-8f3d-7c4e7b4674eb.PNG)

![IMG_9425](https://user-images.githubusercontent.com/2352112/118100532-db62f180-b3d6-11eb-8c68-abc418670afb.PNG)

**Comment by bitgamma** [comment] 2021-05-13 10:22
@anxolin because of how software distribution works on iOS, you will need to wait for the official release unfortunately

**Comment by alfetopito** [comment] 2021-05-13 15:12
Tested out the nightly version on Android, worked perfectly!
