### ISSUE TITLE
Password not cleared in syncing

### ISSUE THREAD

**Issue by ulisesmac** [status-im/status-react#18603] opened 2024-01-23 23:43 UTC
# Bug Report

## Problem 
Status is storing the password and autofilling for autentication.

#### Expected behavior

Not automatically filling the password (and probably not storing it)

#### Actual behavior

[Screencast from 2024-01-23 17-40-44.webm](https://github.com/status-im/status-mobile/assets/90291778/5681d26e-7f89-4db1-8c23-0c005b5f3fb0)

### Reproduction

1.  Open Status
2.  Press on the profile image
3. Syncing
4. Press add buton
5. Slide the button to show the QR code
6. Navigate back
7. Repeat 4 and 5.

The input will be prefilled with the password.

**Comment by J-Son89** [comment] 2024-01-26 14:36
This is happening in all standard authentication btw :)

**Comment by J-Son89** [comment] 2024-02-14 11:36
closing as a duplicate of https://github.com/status-im/status-mobile/issues/18447

**Closed as completed by J-Son89** 2024-02-14 11:36 UTC
