### ISSUE TITLE
explorer.livepeer.org doesn't load properly on Android

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#6179] opened 2018-10-08 01:51 UTC
### User Story

As a user, I want to use explorer.livepeer.org with my Status wallet.

### Description

*Type*: Bug

*Summary*: `explorer.livepeer.org` does not recognize the Status browser on Android.

#### Expected behavior
`explorer.livepeer.org` loads my account with ETH address on both operating systems.

#### Actual behavior
![image](https://user-images.githubusercontent.com/15470435/46589713-def1a780-ca7a-11e8-8463-ea5ddf728a31.png)

### Reproduction
Navigate to explorer.livepeer.org using an Android device.

**Comment by jeluard** [comment] 2018-12-19 09:08
I cannot reproduce with latest release. Livepeer might have fixed this on their end?

**Comment by mandrigin** [comment] 2019-02-27 13:18
works for me on 0.9.33, but it doesn't support Privacy Mode. I don't think it is for us to fix, closing this one. feel free to reopen.

**Closed as completed by mandrigin** 2019-02-27 13:18 UTC
