### ISSUE TITLE
The removed account can be added back with derivation m/44/60'/0'/0/0 path

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20633] opened 2024-07-03 06:41 UTC
### Steps:
1. Create an additional account using seed phrase importing or key pair generation.
2. Remove the current account.
3. Create this account again.

### Actual result:
The keypairs generated with m/44/60'/0'/0/0 path again

https://github.com/status-im/status-mobile/assets/52490791/529d3129-500f-4042-992f-19879b916958

### Expected result:
If the account is removed, the removed derivation path account should not be restored.

How it works on Desktop:

https://github.com/status-im/status-mobile/assets/52490791/e680fb1e-e4bd-4c80-bd2b-7d8d6feda198

### ENV:
NIghtly 3 Jul 2024

**Comment by churik** [comment] 2024-09-19 09:13
@saledjenic  @ulisesmac @xAlisher 
do you know what is expected here? as I can't define priority. 

Thanks for help!

**Comment by pavloburykh** [comment] 2024-09-19 13:14
Unlike from Mobile Desktop has a feature of editing derivation path while adding new account. So even if derivation path is m/44/60'/0'/0/1 during re-adding of the key pair, user can edit it to m/44/60'/0'/0/0. 

<img width="476" alt="Status Desktop 2024-09-19 16-03-02" src="https://github.com/user-attachments/assets/cb004751-9997-48d6-b8b9-f6dcd207ce46">


But still, we are not sure which behaviour is expected, so will appreciate input on [this](https://github.com/status-im/status-mobile/issues/20633#issuecomment-2360450764) question. @saledjenic @ulisesmac @xAlisher

**Comment by ulisesmac** [comment] 2024-09-19 21:32
IMO, Mobile has a right behavior.

Once we remove all accounts from a key-pair, the key-pair gets removed (at least on Mobile), so it makes sense that the derivation count is also lost. Also makes sense that once the key-pair is re-added, the derivation count starts again from zero.

If the key-pair were kept once all derived account are removed, it'd make sense to not restart the count.

I'd say this is not an issue on Mobile. If desktop keeps the count besides the key-pair is removed, I'd say it's kind of a bug, but not critical, since desktop has a field to edit the path, on Mobile we also planned the feature to edit derivation paths, it's hidden and AFAIK it's not completed.

@churik @pavloburykh

**Comment by saledjenic** [comment] 2024-09-20 10:02
> But still, we are not sure which behaviour is expected, so will appreciate input on [this](https://github.com/status-im/status-mobile/issues/20633#issuecomment-2360450764) question. @saledjenic @ulisesmac @xAlisher

Looking at the video above, I see the issue is on the desktop app side. And not sure since when it started cause it was not like that for sure.

So as long as the key pair is in the app, live, we should follow the logic for adding accounts that we were discussing in several different PRs, but as soon as that key pair gets removed, either because of deleting the key pair itself (including all accounts) or by deleting the last account of a key pair, everything further should be like the key pair is added for the first time. This means next time I add the same keypair, adding accounts should start from index `0`.

@churik @VolodLytvynenko @ulisesmac

**Comment by pavloburykh** [comment] 2024-09-20 11:07
> > But still, we are not sure which behaviour is expected, so will appreciate input on [this](https://github.com/status-im/status-mobile/issues/20633#issuecomment-2360450764) question. @saledjenic @ulisesmac @xAlisher
> 
> Looking at the video above, I see the issue is on the desktop app side. And not sure since when it started cause it was not like that for sure.
> 
> So as long as the key pair is in the app, live, we should follow the logic for adding accounts that we were discussing in several different PRs, but as soon as that key pair gets removed, either because of deleting the key pair itself (including all accounts) or by deleting the last account of a key pair, everything further should be like the key pair is added for the first time. This means next time I add the same keypair, adding accounts should start from index `0`.
> 
> @churik @VolodLytvynenko @ulisesmac

Thank you @saledjenic 

@anastasiyaig would you mind verifying and logging the issue on Desktop side? Thank you!

Closing this one as based on comment above, the mobile behaviour is correct.

**Closed as completed** 2024-09-20 11:08 UTC
Labels: wallet: Derivation Path, wallet-core

**Comment by anastasiyaig** [comment] 2024-09-20 11:10
@saledjenic @alaibe is it an issue? can you pls confirm?

**Comment by pavloburykh** [comment] 2024-09-20 11:20
> @saledjenic @alaibe is it an issue? can you pls confirm?

@anastasiyaig to my understanding Sale has already confirmed that is an issue in this [comment](https://github.com/status-im/status-mobile/issues/20633#issuecomment-2363346203)

> Looking at the video above, I see the issue is on the desktop app side. And not sure since when it started cause it was not like that for sure.

**Comment by anastasiyaig** [comment] 2024-09-20 11:25
okay

@virginiabalducci @glitchminer pls add a ticket

**Comment by saledjenic** [comment] 2024-09-20 11:38
> @saledjenic @alaibe is it an issue? can you pls confirm?

@anastasiyaig I confirmed this based on the video recorded in the desktop app that is attached to the description of this issue. Feel free to confirm in the latest master and log the issue. Could be that this needs to be fixed on the statusgo side.

**Comment by anastasiyaig** [comment] 2024-09-23 14:55
https://github.com/status-im/status-desktop/issues/16380 @saledjenic @VolodLytvynenko  @pavloburykh
