### ISSUE TITLE
Allow to send/request ERC20 token: command

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2643] opened 2017-12-06 17:02 UTC
### User Story

As a user, I want to send ERC20 tokens from the chat.

### Description

Modify the `send` and `request` commands so that they support ERC20 tokens.

*Type*: Feature

**Comment by jeluard** [comment] 2018-01-05 06:41
Postponed due to MVP changes: `send` and `request` will be simpler and only accept `contact` as an optional argument.
This requires deep linking support and changes to the API.

**Comment by chadyj** [comment] 2018-05-15 08:37
Dupe of https://github.com/status-im/status-react/issues/3233 and https://github.com/status-im/status-react/issues/3234

**Closed as completed by chadyj** 2018-05-15 08:37 UTC
