### ISSUE TITLE
Command and parameter text are overlapping each other [for some users]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1286] opened 2017-06-07 17:24 UTC
### Description

*Type*: Bug

*Summary*: Several Instabug users have reported issue with command and parameter text overlapping:
![send overlap 098](https://user-images.githubusercontent.com/6584810/26891699-a2600334-4bbe-11e7-9130-2abc72b283dc.jpg)
![location 097](https://user-images.githubusercontent.com/6584810/26891906-4c012a4e-4bbf-11e7-9f76-d28190b6942b.jpg)
![faucet 098](https://user-images.githubusercontent.com/6584810/26892017-a3242a10-4bbf-11e7-9c14-bbadd0fd90ff.jpg)
![phone number](https://user-images.githubusercontent.com/6584810/26948221-3ae183dc-4c9e-11e7-907d-f245d35b4398.jpg)

#### Expected behavior
command and its parameter text are not overlapping
#### Actual behavior
command and parameter overlap each other

### Reproduction
Note: I can't reproduce this issue yet
- Open Status
- Open Console
- tap on /location

### Additional Information
* Status version: 0.9.8, 0.9.7
* Operating System: iOS only
Real devices iPhone 6s, iOS 10.2.1; iPhone 7 Plus iOS 10.3.1

### Instabug
* 0.9.8 https://dashboard.instabug.com/applications/status/beta/bugs/328
* 0.9.7 https://dashboard.instabug.com/applications/status/beta/bugs/285
* 0.9.8 https://dashboard.instabug.com/applications/status/beta/bugs/315
* 0.9.6 https://dashboard.instabug.com/applications/status/beta/bugs/187
* 0.9.7 https://dashboard.instabug.com/applications/status/beta/bugs/279
* 0.9.9 https://dashboard.instabug.com/applications/status/beta/bugs/337
* 0.9.9 https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/602
* 0.9.10 https://dashboard.instabug.com/applications/status/beta/bugs/382
* 0.9.10 https://dashboard.instabug.com/applications/status/beta/bugs/454
* 0.9.10 https://dashboard.instabug.com/applications/status/beta/bugs/433
* 0.9.10 https://dashboard.instabug.com/applications/status/beta/bugs/431

**Comment by dzerenyuk** [comment] 2017-06-24 15:35
Meizu M3s/Android 5.1 
Initial flyme version 5.1.5.3 
![screenshot_2](https://user-images.githubusercontent.com/29678075/27509719-b306823a-590b-11e7-8af7-350e844fb6da.png)
after upgrading to 6.7.4.11G beta  bug disappeared

**Comment by sla-shi** [comment] 2017-10-04 20:46
@anna I can't reproduce it in 0.9.11, can we close it?

**Comment by jeluard** [comment] 2017-10-19 14:15
Can't be reproduced on latest develop.

**Closed by jeluard** 2017-10-19 14:15 UTC
Labels: bug, help to reproduce, intermediate, medium-priority
