### ISSUE TITLE
Unable to edit Profile phone number

### ISSUE THREAD

**Issue by gholmes86** [status-im/status-react#2695] opened 2017-12-12 06:05 UTC
### Description
*Type*: Bug
![editphonenumber](https://user-images.githubusercontent.com/9959969/33869734-12a2121e-ded0-11e7-9153-60e5e120103f.PNG)

[comment]: # User is unable to edit profile phone number after clicking Edit within Phone number for a user profile
*Summary*: ...

#### Expected behavior
[comment]: #User should be able to edit phone number

#### Actual behavior
[comment]: # User unable to edit phone number

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Load the app
right swipe
click the upper right menu icon
click the Phone number menu icon
click edit 

Expected: User should be able to edit phone number
Actual: user is unable to edit the phone number

Status version:0.9.12(1557.321)
Device:iPhone7
OS:iOS
Verison:10.3.3

**Comment by annadanchenko** [comment] 2017-12-13 22:20
duplicate of #1677
Please, search for the known issues before reporting them. For example this one can be found be searching for "profile" and "phone" words. We are happy you have time to help and sorry when you need to waste it to report duplicates :(

**Closed as completed by annadanchenko** 2017-12-13 22:20 UTC
