### ISSUE TITLE
Messages are received in different order then sent

### ISSUE THREAD

**Issue by janherich** [status-im/status-react#2699] opened 2017-12-12 12:59 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

When user A sends messages in rapid succession to user B, while user B is offline, once user B starts the app and and the messages are received, they are displayed in a wrong order, see the attached screenshot.

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status on device A
- Open Status on device B
- Exchange contact info so A and B are mutual contacts
- Starts 1-1 chat between A and B (doesn't matter who starts it)
- Close the app on device B
- Send couple of messages in rapid succession from device A to device B
- Open status app on device B, wait till messages from A are received and examine their order
![screen shot 2017-12-12 at 13 53 14](https://user-images.githubusercontent.com/1910609/33885751-86d568ce-df44-11e7-99bb-d5409ee1171f.png)

**Comment by oskarth** [comment] 2017-12-12 19:23
Fairly sure this isn't a bug but is just bad UX due to indeterministic order. All the info is most likely in there but we haven't made (explicit) design choice to re-order received messages. See issue above.

**Comment by annadanchenko** [comment] 2018-01-04 21:42
can reproduce on nightly build  0.9.10-512-gb42df648+ (2069)
TF of receiver: https://app.testfairy.com/projects/4803622-status/builds/7430381/sessions/50/?accessToken=kNYHtw2SXnwmHSIst1GdjXtOGrM
TF of sender: https://app.testfairy.com/projects/4803590-status/builds/7434230/sessions/30/?accessToken=3QipeQu1it8dpNgBuCel5Jc7ry0

Sender sent 5 messages when receiver was offline:
1. "Test it send offline"
2. T1
3. T2
4. T3
5. T4
Sender went offline too, waited ~15 minutes
Receiver comes online and gets messages in a wrong order:
T3
T5
T1
T4
"Test it send offline"
T2

**Comment by oskarth** [comment] 2018-01-05 06:22
Actual PR that activates queue message behavior https://github.com/status-im/status-react/pull/2860

**Comment by annadanchenko** [comment] 2018-01-07 23:09
Need to recheck on release build, as #2860 is merged and seems to fix the issue
tests to do:
1. more then 30 messages sent in 1-1, group and public chats by 1 user. If works then by several users
2. recheck offline inboxing

**Comment by annadanchenko** [comment] 2018-01-16 16:33
in 1-1 chat messages are received in other order than sent. 
receiver: https://app.testfairy.com/projects/4803590-status/builds/7512658/sessions/8/?accessToken=fAkqZkJG-4-AeFIT/xafXrMFMMc

0. receiver is offline
1. sender sends 6 messages (T1, T2... T6) 
2. immediately after this (no waiting for several minutes) receiver signs in to Status app. Later messages arrive in this order: T1 T6 T3 T4 T2 T5

**Comment by oskarth** [comment] 2018-01-16 17:16
> receiver is offline
> sender sends 6 messages (T1, T2... T6)
> immediately after this (no waiting for several minutes) receiver signs in to Status app. Later messages arrive in this order: T1 T6 T3 T4 T2 T5

Only thing I can think of is that there's a lot of Whisper processing going on at startup, so the 500ms delay isn't enough to reorder messages. It'd be useful to see if this can be reproduced when receiver is online at same time.

We can probably figure out a way to adjust the delay-ms, but this is an enhancement, not a critical bug fix, so removing it from release scope in order not to delay it another week or two.

**Comment by oskarth** [comment] 2018-01-22 13:36
Latest develop using iPhone Xs and Android Galaxy S8 (receiver).

Can't reproduce when app is in background.

Can reproduce when app is in background and the foregrounded (sign-in not necessary).

Investigating. Current hypothesis: 500ms not enough when coming from background due to other Whisper events.

**Comment by oskarth** [comment] 2018-01-22 15:44
Annoyingly, I can't reproduce the background bad behavior in Genymotion with dev mode, and having issues getting local build to run on Android.

**Comment by oskarth** [comment] 2018-01-23 06:05
After recent PRs, the main invariant of the pre-receiver has been broken:

```
> adb logcat | grep QQQ
01-22 11:04:46.846  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 1 54
01-22 11:04:46.882  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 2 55
01-22 11:04:46.954  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 6 59
01-22 11:04:46.986  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 7 60
01-22 11:04:47.013  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 9 62
01-22 11:04:47.064  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: — 53
01-22 11:04:47.080  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 3 56
01-22 11:04:47.092  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 4 57
01-22 11:04:47.105  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 5 58
01-22 11:04:47.121  5598  5641 I ReactNativeJS: INFO [status-im.chat.events.queue-message:23] - QQQ ::queue-message: 8 61
01-22 11:04:47.469  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[54 "1516637073923-36d4340c-c6bb-5d15-9f27-f02bfec07bbb"] [55 "1516637075001-dec30918-2e4c-511b-bdc3-ffbb3147a611"]} 1 54
01-22 11:04:47.471  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 1 54
01-22 11:04:48.024  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[55 "1516637075001-dec30918-2e4c-511b-bdc3-ffbb3147a611"] [59 "1516637078771-afc27454-d838-5def-9127-590fd7ea62de"]} 2 55
01-22 11:04:48.026  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 2 55
01-22 11:04:48.542  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[59 "1516637078771-afc27454-d838-5def-9127-590fd7ea62de"] [60 "1516637079661-c8ad4cc0-38cc-571d-88f5-c20f91197d4a"]} 6 59
01-22 11:04:48.544  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 6 59
01-22 11:04:49.057  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[60 "1516637079661-c8ad4cc0-38cc-571d-88f5-c20f91197d4a"] [62 "1516637081371-0dc822d7-424b-5eba-9ccd-0e5d1ef59e84"]} 7 60
01-22 11:04:49.058  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 7 60
01-22 11:04:49.574  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[62 "1516637081371-0dc822d7-424b-5eba-9ccd-0e5d1ef59e84"] [53 "1516637070248-cd00505c-ab4d-52af-b670-7ad1d820dc4d"]} 9 62
01-22 11:04:49.575  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 9 62
01-22 11:04:50.092  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[53 "1516637070248-cd00505c-ab4d-52af-b670-7ad1d820dc4d"] [56 "1516637075990-43fb2a4d-275b-5853-b780-f805c6296c3a"]} — 53
01-22 11:04:50.092  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: — 53
01-22 11:04:50.610  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[56 "1516637075990-43fb2a4d-275b-5853-b780-f805c6296c3a"] [57 "1516637076844-5a162830-32bc-53dd-af79-08aa5f00c34c"]} 3 56
01-22 11:04:50.611  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 3 56
01-22 11:04:51.126  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[57 "1516637076844-5a162830-32bc-53dd-af79-08aa5f00c34c"] [58 "1516637077812-add3a75c-128d-55e8-88d7-c15ffc8aa1c9"]} 4 57
01-22 11:04:51.127  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 4 57
01-22 11:04:51.641  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[58 "1516637077812-add3a75c-128d-55e8-88d7-c15ffc8aa1c9"] [61 "1516637080568-dc3a07b2-8f73-5e90-ba6b-e5fdf54ebbbf"]} 5 58
01-22 11:04:51.643  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 5 58
01-22 11:04:52.159  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:33] - QQQ seen: #{[61 "1516637080568-dc3a07b2-8f73-5e90-ba6b-e5fdf54ebbbf"]} 8 61
01-22 11:04:52.160  5598  5641 I ReactNativeJS: INFO [status-im.utils.pre-receiver:37] - QQQ add-fn: 8 61
```

Notice how it calls add-fn even when there are messages with lower `clock-value` that comes in <<500ms after. This is because it checks on `message-id`, when it should check on chat identifier. However, reverting to previous behavior and/or using `chat-id` still sometimes causes the second `go-loop` in `pre-receiver` to sometimes go into an infinite loop. I think this is because of how messages get append on the channel again, and there might be some timeout logic missing. This is how far I got yesterday.

**Comment by pedropombeiro** [comment] 2018-01-29 09:34
@oskarth does that mean we have no unit tests for this ordering logic?

**Comment by oskarth** [comment] 2018-02-02 07:25
Removing myself as I'm not currently working on this.

@PombeirP We do (test pre_receiver), but it (1) assumes a certain key field is present (2) only partially simulates reality. So things can certainly be improved in this area.

**Comment by oskarth** [comment] 2018-02-23 01:30
TIME LIMITED BOUNTY UNTIL MAR 3 (just before our offsite).

As far as I know this is a bug and/or regression in how the pre_receiver works and the work itself shouldn't be XL, but it reflects the priority of solving it before the offsite.

See https://github.com/status-im/status-react/blob/develop/test/cljs/status_im/test/utils/pre_receiver.cljs#L6-L35 and https://github.com/status-im/status-react/blob/develop/src/status_im/utils/pre_receiver.cljs

Multiple people attacking this is at once is encouraged.

(Since I did a bunch of work on this previously I'm opting out of the bounty reward).

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by pedropombeiro** [comment] 2018-02-23 21:33
@oskarth why is this 500ms window required? I imagine it's some sort of optimization, but is it feasible to allow any message that arrives to be inserted in the view according to the clock value independently of how far in the future it arrives? Is it a question of the UI component not handling it well (in terms of scroll position, for instance)?

**Comment by status-open-bounty** [comment] 2018-02-24 20:22
Balance: 0.000000 ETH
Tokens: SNT: 6000.00
Contract address: [0x86d842e666b769d83d06db5245af1fcea6398a7c](https://etherscan.io/address/0x86d842e666b769d83d06db5245af1fcea6398a7c)
Network: Mainnet
Paid to: janherich
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by oskarth** [comment] 2018-02-26 11:16
@PombeirP 

> @oskarth why is this 500ms window required? I imagine it's some sort of optimization, but is it feasible to allow any message that arrives to be inserted in the view according to the clock value independently of how far in the future it arrives? Is it a question of the UI component not handling it well (in terms of scroll position, for instance)?

500ms is just empirically what I observed to be enough time for messages arriving out of order. And yes, definitely. My thinking was: let's get basic ordering algorithm working first, then work on UI. Since design is quite complex and not clear how to do it non-confusing way (messages moving around).

Happy to chat more about it if you have ideas, and bounty is up for taking too if you fix it!

**Comment by annadanchenko** [comment] 2018-02-27 11:31
Messages are still received in different order if use same steps as in the issue. 
### Steps:
1. device A: Add device B to the contacts
2. device B: in new 1:1 chat with A use Add to contacts link
3. each device send 1 message to see you can see received messages
4. close app on device B
5. device A: send 25 messages in 1:1 chat with device B (1,2,3,4,5... 25)
6. device B: you'll see notifications "You have a new message)
7. After 25 messages are sent from device A: do not close app on device A
8. device B: open app and log in. On Home tab wait till 25 unread counter will be shown next to chat with device A. As soon as it shows "25" open chat and check the message order (should be 1,2,3,4,5...23,24,25)
Currently: 
![screenshot_20180227-122203](https://user-images.githubusercontent.com/6584810/36726409-f4dc3df0-1bb9-11e8-9ddd-d785ee75b96b.png)

Also see video below
Log and video (device B: Android phone, Pixel XL, Android 8.1.0): https://app.testfairy.com/projects/4803622-status/builds/7782166/sessions/6/?accessToken=Z-Zfiugrl6vZnIKlBS/UD63MgkY 
Installed PR build 4 on real iPhone 6s, iOS 10.3.3 (device A) and real Pixel XL, Android 8.1.0 (device B)

**Closed as completed** 2018-03-04 18:32 UTC
Labels: bounty, Tested - Issues
