### ISSUE TITLE
Jump to replied message

### ISSUE THREAD

**Issue by rapidddenis** [status-im/status-react#12764] opened 2021-10-29 08:45 UTC
https://user-images.githubusercontent.com/41779817/139404659-e2484cb2-408a-4fe0-9fa1-d0a06435ff2d.mp4

Expected: UI scrolls/jumps to message

**Comment by churik** [comment] 2021-10-29 08:46
duplicate of https://github.com/status-im/status-react/issues/11482

**Closed as completed by churik** 2021-10-29 08:46 UTC
