### ISSUE TITLE
No commands shown in chat on a second and next app runs

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#2661] opened 2017-12-07 17:21 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Empty line with no commands are shown in 1-1 and group chats. Expected to see browse, send, request and location commands. On 1st app run (when password is created) all is shown ok. If close app and launch it again then empty line with no commands is shown in chats.

Happens on Android only, works ok on iOS
![screenshot_20171207-180914](https://user-images.githubusercontent.com/6584810/33728511-ed908760-db7a-11e7-8204-43e6873f175e.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Expected to see browse, send, request and location commands in the line above input field
#### Actual behavior
[comment]: # (Describe what actually happened.)
Empty line with no commands 
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
- Install app
- Create password. Wait for account to be created.
- Tap on "<" to go to Chats.
- Open Contacts
- Tap on Jarrad to open 1-1 chat with Jarrad
- Check if commands browse, send, request and location are shown and can be used
- Close app
- Launch Status
- Sign in
- Open Contacts
- Tap on Jarrad to open 1-1 chat with Jarrad
- Check if commands browse, send, request and location are shown and can be used
- Create group chat with Jarrad
- Open group chat
- Check if commands browse, send, request and location are shown and can be used

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version:  0.9.10-427-ga68f0652+
* Operating System: Real Samsung Galaxy S6, Android 6.0.1
There is no issue if perform same steps on same build on iOS (real iphone 6s, iOs 10.0.3)

#### Logs
https://app.testfairy.com/projects/4803622-status/builds/7234321/sessions/37/?accessToken=DbIolzWINMPVh8TvEXQd7NtXxzo

**Comment by annadanchenko** [comment] 2017-12-07 17:24
@antdanchenko please, add such check to the autotests

**Comment by Monali109-zz** [comment] 2017-12-07 17:35
@annadanchenko  If _no messages_ are there at all, then _Delete chat_ this option shouldn't be enable. When no messages are there or no chat then Delete chat option should be disable & if any messages are there then only it should get enable.(_feature_).

**Comment by annadanchenko** [comment] 2017-12-07 17:57
@Monali109 I'm not sure how the comment on Delete chat relates to this issue. Please, create a separate issue if you found some problem

**Comment by Monali109-zz** [comment] 2017-12-08 02:36
@annadanchenko  ok, sorry. It was for chat feature so........

**Comment by rasom** [comment] 2017-12-10 11:10
The problem is fixed in `develop` now but still exists when switching to JSC jail, so the issue shouldn't be closed.

**Comment by rasom** [comment] 2017-12-12 10:13
>Branch: bugfix/#2661
Android: https://i.diawi.com/UypGmR
iOS: https://i.diawi.com/2fowUB

**Comment by churik** [comment] 2017-12-13 14:31
Checked with Galaxy S7 - android 7.0 and Galaxy S7 (emulator) 7.1:
- issue is not reproducible
- Regression (fresh install):
console | /password
console | /browse
console | /faucet
profile set status with hashtag |  
contacts | add
1-1 chat | /location
1-1 chat | ordinary message
1-1 chat | emoji
1-1 chat | /request
1-1 chat | /send
create group chat  |
add smbd to group chat |
Group Chat | /location
Group Chat | ordinary message
Group Chat | emoji
Group Chat | /request
Group Chat | /send
create public chat |  
join public chat |  
Public chat | messaging
Public chat | /location
Public chat | emoji
Public chat | /browse
Dapps | /browse


Upgrade: 
- all commands are available after upgrade and reopening app in 1-1 chat, group chat, public channel

**Closed as completed** 2017-12-13 14:38 UTC
Labels: Tested - OK
