### ISSUE TITLE
Empty chat in opened on pressing hashtag in a community channel

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18095] opened 2023-12-06 14:39 UTC
# Bug Report

## Problem 

The corresponding e2е failed for the first time in https://github.com/status-im/status-mobile/pull/18049
@ilmotta could you have a look to check if this is a regression, please?

### Reproduction

1. Create a community with several channels, e.g. `#channel1` and `#channel2`
2. Tag `#channel1` in `#channel2`
3. Press `#channel1`

https://github.com/status-im/status-mobile/assets/67952253/5c7c6e19-d21f-4e1b-9238-d78908ce5fc3

#### Expected behavior
You're redirected to `#channel1`

#### Actual behavior
An empty chat is opened

### Additional Information

- Status version: nightly 6/12
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment] 2023-12-06 20:55
Will check @qoqobolo! Although I can't understand why they would fail. That PR only changed _test.cljs files that never run in production.

**Comment by ilmotta** [comment] 2023-12-06 21:55
@qoqobolo I bisected our commits and eventually arrived at the one that caused the regression 6ef113e82162cbb4c71d9f755d9f6dc27b8a5835

@Parveshdhull, since you have context about the fix, could you take a look? I don't fully grasp the changes introduced by PR https://github.com/status-im/status-mobile/pull/18066.

I could verify that commenting out the dispatch to `:chat/close` fixes the issue, but I don't know if that's a proper solution since the original PR introduced the dispatch as a fix.

```diff
modified   src/status_im2/navigation/events.cljs
@@ -67,8 +67,8 @@
                                    (dissoc :shell/loaded-screens)
                                    (assoc :view-id (or @shell.state/selected-stack-id :shell)))
     :effects.shell/pop-to-root nil}
-   (when (:current-chat-id db)
-     {:dispatch-n [[:chat/close]]})))
+   #_(when (:current-chat-id db)
+       {:dispatch-n [[:chat/close]]})))
 
 (rf/defn init-root
   {:events [:init-root]}
```

**Comment by qoqobolo** [comment] 2023-12-07 09:01
@ilmotta thanks for finding the cause of the issue, @Parveshdhull thanks for taking it!

**Comment by Parveshdhull** [comment] 2023-12-07 10:02
Thank you @qoqobolo  for finding this issue. And @ilmotta for pinging me.
Looks like there are two issues here
1. We are closing all screens(pop-to-root) when navigating to different channels, even the background community screen. I don't think we should do that.
2. We are closing the previous chat while popping root, but it is too late and causes us to close the current chat.

should be fixed in https://github.com/status-im/status-mobile/pull/18111

**Closed as completed** 2023-12-15 12:44 UTC
Labels: community
