### ISSUE TITLE
Desktop messages can't be resent

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#6449] opened 2018-10-22 11:28 UTC
# Problem

As a desktop user I want to be able to resend messages by clicking on them. Right now it is just red text.

# Implementation

Similar to mobile, click and get asked to resend.

# Acceptance Criteria

Can obviously resend messages.

# Notes

N/A

# Future Steps

See if we can share more code with mobile to make the same thing possible on both platforms. When that isn't possible, consider exposing it in Desktop but marking it as a TODO by default, with a link to new issue (build with users).

**Comment by asemiankevich** [comment] 2018-10-22 12:29
@oskarth as far as i know `resend` feature is disabled on mobile . @janherich may clarify something more

**Comment by janherich** [comment] 2018-10-22 12:52
@asemiankevich I just checked, and on mobile, it's not even possible to send messages while user is offline, so hard to tell. I will check in the code, but I'm not aware of and was not really involved in any discussion about disabling message re-sending, better to ask @dmitryn since he originally developed the feature.

**Comment by asemiankevich** [comment] 2018-10-22 12:55
@janherich oh jeez i am sorry i thought you designed everything in Status :D indeed @dmitryn could clarify a bit

**Comment by oskarth** [comment] 2018-10-22 13:23
Huh, why did we disable a useful feature?

**Comment by lukaszfryc** [comment] 2018-10-22 13:41
> it's not even possible to send messages while user is offline, so hard to tell.

Actually, it is possible. The app does not detect you are offline immediately. So, if you sent a message before seeing "Offline" status, that message will be marked as "sent" but lost (https://github.com/status-im/status-react/issues/6415)

**Comment by dmitryn** [comment] 2018-10-22 13:45
> as far as i know resend feature is disabled on mobile

I didn't know it was disabled. @asemiankevich can you point to issue / PR where it has happened? 

As for desktop, resending might be done in similar way using mobile client code. Desktop just needs its own UI part.

**Comment by asemiankevich** [comment] 2018-10-22 13:48
@dmitryn @oskarth seems i am wrong. I thought it was disabled. sorry for confusion

**Comment by churik** [comment] 2018-10-22 14:07
@asemiankevich @oskarth  but there is no more "Not sent" status (AFAIK) and I couldn't see this feature for a while.
That's why https://github.com/status-im/status-react/issues/6415 and https://github.com/status-im/status-react/issues/6080 were reported (that's where resend options should be used IMO).

From offline mode it is not possible to send a message (button is disabled). For desktop - it is possible (send button is enabled).
I'm not sure where and how for now and if it is even possible to trigger message in "Not sent" status for mobile.

So probably we need just make it consistent between mobile and desktop and find out where "Not sent" status should be used for both platforms?

**Comment by lukaszfryc** [comment] 2018-10-22 14:12
Looks like this GHI should be marked as bug. Resending messages should already work for both mobile and desktop. I suggest to add "bug" label to this issue and work on other issues "Not sent" status, etc. in a separate GHI.

**Comment by lukaszfryc** [comment] 2018-10-22 16:22
@dmitryn could you take https://github.com/status-im/status-react/issues/6415 and https://github.com/status-im/status-react/issues/6080 to fix resending messages on mobile?

**Comment by dmitryn** [comment] 2018-10-22 17:47
@lukaszfryc i'll take a look at #6415 - will hide send button while "Connecting to peers" shown (i.e. no mailserver connection)

**Comment by churik** [comment] 2018-10-23 08:17
@oskarth @siphiuel wdyt about hiding "Send" button when app detects offline mode ("Offline", "Connecting to peers")?

**Comment by oskarth** [comment] 2018-10-23 08:23
Hiding or maybe grey disable? Like this is something you can normally do but not right now. I feel like this is a design decision?

@chadyj @denis-sharypin

**Comment by churik** [comment] 2018-10-23 08:40
@EugeOrtiz please, help)

**Comment by churik** [comment] 2018-11-30 15:39
@lukaszfryc can you constantly emulate situation when we can resend message on mobile? I cannot so request your help

**Comment by EugeOrtiz** [comment] 2018-11-30 17:55
[Designs specs for desktop](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=611%3A8) 
<img width="590" alt="captura de pantalla 2018-11-30 a la s 2 46 55 p m" src="https://user-images.githubusercontent.com/37297779/49305756-e6e42b80-f4ae-11e8-80e2-806aaacf53dc.png">

**Please use Figma to see the rest of the design details.**

**Comment by EugeOrtiz** [comment] 2018-11-30 17:59
> @oskarth @siphiuel wdyt about hiding "Send" button when app detects offline mode ("Offline", "Connecting to peers")?

@churik Can the error happen _after_ I hit the send button? If so, disabling it is not a good solution.

**Comment by vitvly** [comment] 2018-11-30 20:23
@EugeOrtiz @churik I think it might happen that there is no connectivity already, but we don't know about it yet (because e.g. we periodically poll servers for accessibility, and connection might get dropped somewhere in between).

**Comment by lukaszfryc** [comment] 2018-12-03 08:02
> @lukaszfryc can you constantly emulate situation when we can resend message on mobile? I cannot so request your help

Yes, I could simulate it pretty consistently on slow network connection.

**Comment by churik** [comment] 2018-12-03 14:23
If @lukaszfryc can reproduce it on mobile, issue is relevant for desktop as well.
 Will ask your help when  it is fixed. Thanks!

**Comment by lukaszfryc** [comment] 2018-12-03 14:25
Sure!

**Closed as completed** 2018-12-14 16:52 UTC
