### ISSUE TITLE
ENS Resolution not working in some clients

### ISSUE THREAD

**Issue by naghdy** [status-im/status-react#7518] opened 2019-02-18 00:46 UTC
# Problem

When trying to add another user using their ENS username, some devices/versions simply don't resolve properly.

I was able to repro this ~4 times on various peoples devices. This particular screenshot was from Michael B's device.

![img_0591](https://user-images.githubusercontent.com/32269875/52922148-ff105d80-32db-11e9-8290-667a89c8d84a.PNG)

**Comment by mandrigin** [comment] 2019-02-18 07:37
@annadanchenko @asemiankevich is it possible to reproduce it locally?

**Comment by annadanchenko** [comment] 2019-02-19 17:16
@mandrigin yes I can repro it specifically for `naghdy` username on my android 9 device, release 0.9.33 build. Note that for `anna`, `nastya` same search works fine. Same can be reproduced on 0.9.32 release on iOS. It looks to me like the issue can be connected with specific username(s) or the time/way when they were registered. I can always reproduce it (tried ~15 times) on 3 devices and on all of them can't find only `naghdy`

**Comment by mandrigin** [comment] 2019-02-20 16:51
@yenda does it sounds like something for the chat team?

**Comment by yenda** [comment] 2019-02-20 18:01
@annadanchenko @naghdy 
`naghdy` is registered without any contact code so it can't be resolved.
If it is not reproducible with a ens name that has a contact code I suggest we close this issue.
If you don't see a `Your contact code` field under `Your wallet address` field in the `names.statusnet.eth` dapp this means the name was not registered with a contact code.

**Comment by mandrigin** [comment] 2019-02-20 18:02
Can we have some error indication or explanation there? Because otherwise it is super confusing for a regular user...

**Comment by yenda** [comment] 2019-02-20 18:20
The copy could be updated to help with that @andmironov @errorists

**Comment by naghdy** [comment] 2019-02-20 19:01
Can I update "naghdy" to be connected to my contact code? This is super confusing for users...

**Comment by yenda** [comment] 2019-02-20 19:19
@naghdy I think the dapp allows you to do that

**Comment by StatusSceptre** [comment] 2019-02-21 21:23
Hey @naghdy you need to go back to the ENS dapp and search your name to add your contact code to the ens name. I’ve seen this happen multiple times, very confusing from a UX perspective.

**Closed as completed** 2020-01-29 10:35 UTC
