### ISSUE TITLE
Background service stops after a few hours

### ISSUE THREAD

**Issue by dankrad** [status-im/status-react#12658] opened 2021-09-27 17:15 UTC
# Bug Report

The background service on Android, which is required to get notifications on new messages, always stops after a few hours.

## Problem 

See above

#### Expected behavior

Background service should keep running until I stop it

#### Actual behavior

Runs for a few hours then just stops.

### Reproduction

1) Open Status
2) Turn on notifications
3) See Background service for notifications appear in Android notification list
4) After a few hours to 1-2 days it just disappears/

### Additional Information

- Status version: 1.16.0 (20210827115911) 
- Operating System: Android (Samsung)

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment] 2021-09-29 13:06
@dankrad thanks for reporting this!
I could not reproduce this issue on Android device. The Status app was in the background for about a day, and all this time the background service has been working.

Could you please provide additional information:
1. What is your phone model
2. Did you open the application during this time? Or should it always be in the background for the background service to be disabled?
3. Have you received any push notifications in Status? If so, in what types of chats?
Thanks

**Comment by dankrad** [comment] 2021-09-29 13:53
1. Galaxy Z Fold 3
2. It is always in background. I have few contacts on status so open at most once per day or so. 
3. Yes I do receive push notifications from personal charts as long as the service is still open. 

It just happened again, so very reproducable here. 
It could potentially have something to do with the Samsung power saving mode? It can terminate apps to save power. I excluded status from it but I can't find the service itself in the list, maybe it's a different process and still gets terminated?

**Comment by qoqobolo** [comment] 2021-09-29 16:00
@dankrad thanks for the information! We will investigate this further and let you know when we have the results.

**Comment by qoqobolo** [comment] 2021-10-13 17:18
Hello @dankrad
Sorry it took so long to give an update on this issue.

I've reproduced it on my Huawei device, and apparently, the reason is indeed in the power-saving mode. 
If enable it on the device, enable the push notification service and send the Status app to the background, it will log out after ~ 30 minutes. The notification service will be displayed as enabled but in fact, it will stop working. 
After reopening the app and logging in, the notification will restart. 

**Steps to reproduce:**
1. Enable the power-saving mode on an Android device
2. Open Status and enable push notifications
3. Send the app to the background
4. Reopen the app in ~ 30 min

[Status.log](https://github.com/status-im/status-react/files/7339510/Status.log)
[geth.log](https://github.com/status-im/status-react/files/7339509/geth.log)

https://user-images.githubusercontent.com/67952253/137172592-3f41bd9b-97b3-4991-be0e-20da8ae05ec9.mp4

Probably, this behavior is expected with the power-saving mode enabled. But better to ask @cammellos  for clarification.
Take a look, please, when you have time. Thank you!

**Comment by dankrad** [comment] 2021-10-13 17:38
It makes sense that the power savings mode would cause this, but there must be a way for the user to disable it for a specific application? I just can't find how to do this, because I have disabled it for "status" but it is still killed. I wonder if the background notification service is a different process?

As additional information, on many Samsung devices, power saving mode is the only way to get an acceptable battery life. Without it enabled I rarely get through a full day. So this will create a terrible user experience for many users if not fixed.

**Comment by cammellos** [comment] 2021-11-30 11:11
@dankrad thanks for the details,
quick question, just to make sure.
you mentioned you whitelisted the app in the power saving settings,
is this (roughly) what you followed? https://developer.android.com/training/monitoring-device-state/doze-standby#support_for_other_use_cases

I have looked at automatically having the app exempted from power saving mode, but I have read quite a few reports of apps being taken off the playstore after they've done so, and looks like the best thing to do is to prompt the user to whitelist it manually, but looks like it might still be an issue in your case.

Thank you

**Comment by cammellos** [comment] 2021-11-30 11:15
Samsungs seems to be particularly aggressive in power saving mode,
does this help by the way?

https://dontkillmyapp.com/samsung

**Comment by dankrad** [comment] 2021-12-02 11:37
I am trying this now.

**Comment by dankrad** [comment] 2021-12-07 22:14
It seems that this allows the background service to survive for several days. So a lot better than before at least.

So it is probably not your problem but Samsungs. They should provide a way to give an app a permission to run in background permanently.

**Comment by cammellos** [comment] 2022-01-04 13:14
Closing this for now, thanks a lot @dankrad !

**Closed as completed by cammellos** 2022-01-04 13:14 UTC
Labels: android, push-notifications

**Comment by nahuhh** [comment] 2022-01-31 13:22
I'm having issus where

- I have all power saving disabled, including battery optimization 
- background notification enabled and active

If I remove statistics from recent apps, messages will stop coming through after few minutes. 

Seems the notification isn't handling the messages and only when the main status app is running in foreground or still in recent apps, does it work. 

On 3 separate devices. 
Anyone else?

**Comment by cammellos** [comment] 2022-01-31 13:25
Hi @nahuhh ,
thanks for the report. 
One question, which devices are you having this issue on? Sometimes these issues are device/maker specific, and it would help us try to replicate on our side.
Thank you!

**Comment by nahuhh** [comment] 2022-01-31 13:31
1. Samsung Tab A 8.4, Android 11
2. Huawei P30 android 10
3. Samsung S10 android 12

I didn't use status for while, waiting for some features. But believe version 1.13, the first f-droid versions, worked np. 

Somewhere between 1.13 and 1.18, things stopped working for me. (The huawei OS hasn't been upgraded)
