### ISSUE TITLE
ISSUE: Composer UI elements are displayed incorrectly 

### ISSUE THREAD

**Issue by KassUA** [status-im/status-react#16036] opened 2023-05-26 13:21 UTC
### Preconditions
- Composer shouldn't be resized manually
- Composer must be empty from text

### Steps to reproduce
1. Paste/type text into composer
2. Pay attention to composer opacity level
3. Pay attention at Send button UI
4. Continue typing/pasting text into composer until it is fully expanded
5. Collapse composer
6. See if Jump to button is located above composer

https://github.com/status-im/status-mobile/assets/97434915/0d8038f1-d70d-4e1f-95de-ffcdd207a2a1

#### Actual results: 
2. Composer is transparent
3. Send button opacity is not 100% and has white square background 
6. Jump Button partly hidden under the composer

![photo_2023-05-26_15-14-41](https://github.com/status-im/status-mobile/assets/97434915/2154e2c8-75cc-4f9a-ac3a-aac297152051)
![photo_2023-05-26_15-18-20](https://github.com/status-im/status-mobile/assets/97434915/5fc1a94c-3deb-4fe0-9636-725ca48d456f)
![photo_2023-05-26_15-18-43](https://github.com/status-im/status-mobile/assets/97434915/c395fe73-9547-4cae-9f21-31483c600c4d)

#### Expected results:
2. Composer is not transparent
3. Send button has 100% opacity with no background
6. Jump Button sticks to the top of the composer

#### Additional Info:
Device: Redmi Note 8 Pro
OS: MIUI Global 12.0.8 Stable

**Comment by Parveshdhull** [comment] 2023-05-26 13:22
cc: @OmarBasem

**Comment by pavloburykh** [comment] 2023-05-26 13:43
Confirming that bug is reproducible on latest nightly for both IOS and Android.

**Comment by pavloburykh** [comment] 2023-05-26 14:31
> cc: @OmarBasem

@OmarBasem could this bug be related to https://github.com/status-im/status-mobile/pull/16010 which has been merged without manual tesing?

**Comment by OmarBasem** [comment] 2023-05-26 16:21
@pavloburykh can you please check this PR and let me know if this issue is there? https://github.com/status-im/status-mobile/pull/16024

**Comment by pavloburykh** [comment] 2023-05-26 17:54
> @pavloburykh can you please check this PR and let me know if this issue is there? #16024

Looks like it is fixed in https://github.com/status-im/status-mobile/pull/16024 according to quick check. We will perform more thorough testing of this PR next week and provide you with an update. Thank you and have a great weekend.

**Closed as completed** 2023-05-30 12:46 UTC
