### ISSUE TITLE
Back button issues

### ISSUE THREAD

**Issue by ghost** [status-im/status-react#2583] opened 2017-12-02 18:07 UTC
When pressing phone's built in back button the app closes.
It does not close options or submenus opened but closes the app.

**Comment by annadanchenko** [comment] 2017-12-02 21:25
@ardielgonzalez thank you for the bug report! Can you, please, add steps to reproduce? For example: 
1. Launch Status
2. Sign in
3. Open Console chat
4. press device back button

**Comment by ghost** [comment] 2017-12-04 07:42
1.- App closed, not running in backgound
2.-Sign in
3.-Open wallet/Chat/Discover/Contacts
4.-Hit back button
5.-App closes

**Comment by annadanchenko** [comment] 2017-12-04 21:43
@ardielgonzalez what is the expected behaviour from your point of view if Chats tab is active and user hits the device back button? 

I've tried on real Samsung Galaxy S6, Android 6.0.1 in other apps to compare the behaviour. At least in 
1. WeChat - if open app and first is WeChat tab - hit back button - app is minimized
2. WhatsApp - open app, Chats is first tab - hit back button - app is minimized
It seems like Status app behaves in the same way as apps above.

**Comment by annadanchenko** [comment] 2017-12-07 16:47
@ardielgonzalez can you, please, double check if the app is closed and not minimised? I can't reproduce the closing, in my case it's minimized. Also would be very helpful if you can share the device model used and OS version.

**Comment by chadyj** [comment] 2018-09-21 19:57
Closing, as we have had a lot of app changes and this shouldn't be an issue. Please re-open if the problem persists.

**Closed as completed by chadyj** 2018-09-21 19:57 UTC
