### ISSUE TITLE
"Not sent. Tap for options" is displayed for a short time after sending /request command

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4664] opened 2018-06-07 08:30 UTC
### Description

*Type*: Bug
*Summary*: if I'm requesting money in 1-1 chat "Not sent. Tap for options" will appear and then disappear just for a moment
<img width="310" alt="tap" src="https://user-images.githubusercontent.com/6584810/41087827-08cd2fb8-6a3e-11e8-8ac5-b6710a9ecb3c.png">

#### Expected behavior
spinner and then "Sent" status

#### Actual behavior
"Not sent. Tap for options" and then "Sent"

### Reproduction

- Open Status
- Start 1-1 chat
- Send /request with valid amount (i.e. /request 5)
- Pay attention to last message

### Additional Information

* Status version: nightly 07/06/18
* Operating System: Android, iOS

#### Logs

* Video: 
![tap](https://user-images.githubusercontent.com/6584810/41087813-00a25994-6a3e-11e8-95c1-82f08ac9b956.gif)

**Comment by lukaszfryc** [comment] 2018-06-07 09:10
@churik isn't it a duplicate of https://github.com/status-im/status-react/issues/4534?

**Comment by churik** [comment] 2018-06-07 09:15
Sorry, my fault. Closed it.

**Closed as completed** 2018-06-07 09:15 UTC
