### ISSUE TITLE
"error No matching clause:offline" and white screen if try to open 1:1 chat [only on iOS]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8830] opened 2019-08-23 15:42 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: only on iOS: user can't open 1:1 chat because of `error No matching clause:offline`, after closing the popup app is not usable as it shows empty white screen, so relaunch is needed. After this 1:1 chat can't be opened again even if app is online. 

Assumption: To get the error user needs to move app on background and back while being offline but it's possible that issue happens in more cases

See exact steps below

#### Expected behavior

can open 1:1 chat and send/get messages

#### Actual behavior

"error No matching clause:offline"
![81985](https://user-images.githubusercontent.com/6584810/63604946-3df5d780-c5cd-11e9-80b9-026d03aa883a.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=1J7SSLQ8b25dFPE1yD6I4T0Vq1Hl9u-aX
- Install Status
- Create new account
- select "maybe later" for both fingerprint and notifications
- add new contact by scanning its qr code (1:1 chat is opened, use Add to contacts link in the chat)
- send 1 text message in 1:1 chat
- close app
- launch app again
- tap "save password" and sign in
- Tap on "Allow" to allow notifications
- open 1:1 chat
- turn on Airplane mode, wait for "Offline" line to be shown in the app
- move app on background and back
- if no error shown then tap on Back to go to Chats and back to 1:1 chat 
- if no error shown try to move app to background couple of move times (also can scan another QR code with contact code to open new 1:1 chat)

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly from Aug 23 https://ci.status.im/job/status-react/job/nightly/1223/
- Operating System:  iOS only: real iphone 6s iOS 12.4 and real iphone 7+ ios 12.3.1

#### Logs

[status_logs (5).zip](https://github.com/status-im/status-react/files/3535216/status_logs.5.zip)

**Comment by yenda** [comment] 2019-08-24 10:20
This should be fixed in #8832 because sync-data is not modified anymore (it isn't even useful when using rpc which is the only thing that is usable right now in the app). I wonder why only iOS has this issue though, but I think the cause was that sync-data was set to :offline and it is not a case supported by the subtitle for one to one chat which used to display the network syncing status.

**Closed as completed** 2019-08-28 14:49 UTC
Labels: ios
