### ISSUE TITLE
Role is not updated correctly if user unselects several accounts with required tokens one by one

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19407] opened 2024-03-26 17:40 UTC
**Preconditions:** 

1. Let's say we have a community with 2 separate membership permissions: 0.01 ETH to become a member and 10 STT to become a member
2. Mobile User has 3 Accounts A, B, C. He holds 0.01 ETH on Account A and 10 STT on Account B, Account C is without tokens.

**Steps:** 

1. Open Addresses for permissions screen by Mobile user 
2. Quickly unselect Account A and Account B holding required tokens for membership permissions
3. See if error will be displayed 'This address does not contain tokens needed to join'

**Expected result:** 'This address does not contain tokens needed to join' should be displayed. 

**Actual result:** Eligible to join as Member is displayed.

[Status-debug-logs - 2024-03-26T194203.246.zip](https://github.com/status-im/status-mobile/files/14762492/Status-debug-logs.-.2024-03-26T194203.246.zip)

https://github.com/status-im/status-mobile/assets/97245802/64bc6d30-0dbf-441e-ae4a-a442399737d3

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by pavloburykh** [comment] 2024-04-15 09:52
**UPDATE:**

Re-opening the issue as it is broken again in develop. Some time ago it has been fixed by https://github.com/status-im/status-mobile/pull/19439


https://github.com/status-im/status-mobile/assets/97245802/7456ec10-aead-4973-ad24-fbac7502d5f5

**Comment by Parveshdhull** [comment] 2024-04-15 11:32
hi @pavloburykh, thank you very much for reporting this issue.
I am not able to reproduce this issue, please can you check if it is fixed in https://github.com/status-im/status-mobile/issues/19407

**Comment by ilmotta** [comment] 2024-04-15 13:14
@Parveshdhull, @pavloburykh: My understanding from @cammellos's PR is that there's a tiny chance that responses may arrive out of order and we're not ignoring previous requests as he correctly stated. So it looks like we might really need to ignore previous requests.

@Parveshdhull, if you're going to work on the fix, it can be as simple as generating a unique request ID on mobile at the time of RPC request, then before processing the RPC response in the event handler you would check if the request ID matches the originating request ID. If they match you know it's the latest event dispatched by the user interaction.

**Comment by cammellos** [comment] 2024-04-15 13:23
@ilmotta thank you,
https://github.com/status-im/status-mobile/pull/19636/files that's what we discussed as well with Parvesh, the only thing I am not sure, is whether we should use (hash addresses) or uuid (i'd be leaning more towards uuid/random number, though i think either is fine)

**Comment by ilmotta** [comment] 2024-04-15 13:24
Not that I have any strong preference @cammellos, but in the composer to unfurl URLs I remember I opted for UUIDs.

**Closed as completed** 2024-04-17 10:51 UTC
Labels: community, community-permissions
