### ISSUE TITLE
WPP-025 - status-proxy-0.error Error displayed frequently after attempting to build routes from L1 network

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21178] opened 2024-09-04 16:16 UTC
### Steps:
1. Recover user with available ETH on L1 network
2. Attempt to build a route from an L1 network.
3. Test both L1 -> L1 and L1 -> L2 routes.
4. Observe the process as the route is being generated.

### Actual Result:
The error message `WPP-025 - status-proxy-0.error` frequently appears, interrupting the route-building process. 
Desktop
![image](https://github.com/user-attachments/assets/0348b3f0-f0f1-4209-967a-044046c34946)

Mobile
![image](https://github.com/user-attachments/assets/5f771961-25cd-46ec-88d1-ab9d0c3515b9)

### Expected Result:
The routes should be built successfully from the L1 network without any errors.

### Additional Context:
My user has at least 0.021 ETH (~$50), which should be enough to cover the fee. I checked in Hopper and MetaMask, and similar transactions typically cost only $0.10 - $2 USD.

### Logs:
[desktop_logs.txt](https://github.com/user-attachments/files/16873784/logsroute.txt)
Moblie logs [logs (2).zip](https://github.com/user-attachments/files/16873800/logs.2.zip)

### ENV:
Nightly 4 sep, 2024

**Comment by vkjr** [comment] 2024-09-23 11:24
@pavloburykh, would it be correct to add `status-go` lable here because as I understand issue exists on all clients?

**Comment by VolodLytvynenko** [comment] 2024-09-23 12:50
> @pavloburykh, would it be correct to add `status-go` lable here because as I understand issue exists on all clients?

@vkjr correct. Just added

**Comment by pavloburykh** [comment] 2024-09-23 18:15
I believe this issue is a duplicate of https://github.com/status-im/status-mobile/issues/20970 I would close this one in favour of 20970 as there is some discussion already in that ticket. Feel free to re-open if you disagree @VolodLytvynenko

**Closed as completed by pavloburykh** 2024-09-23 18:15 UTC
Labels: status-go, wallet: Networks and Routes, wallet-core

**Comment by VolodLytvynenko** [comment] 2024-09-24 06:59
> I believe this issue is a duplicate of #20970 I would close this one in favour of 20970 as there is some discussion already in that ticket. Feel free to re-open if you disagree @VolodLytvynenko

@pavloburykh that's correct. Thank you!
