### ISSUE TITLE
No PN when your contact adds you to group chat on iOS

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#14035] opened 2022-09-19 11:09 UTC
# Bug Report

## Problem 
There is no push notification on iOS when your contact adds you to a new group chat, as it happens on Android. 

#### Expected behavior
<img width="394" alt="Screenshot 2022-09-19 at 13 05 16" src="https://user-images.githubusercontent.com/67952253/191004032-859278b2-fc76-4628-8319-ddc556b7e8f7.png">

#### Actual behavior
No PN

### Reproduction

1. UserA (iOS) enables PNs
2. UserB adds UserB to contacts
3. UserA puts the app in the background
4. UserB creates a group chat with UserA
5. UserA check PNs

### Additional Information

- Status version: nightly 19/09
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment] 2023-07-14 11:11
closing as duplicate of https://github.com/status-im/status-mobile/issues/13480

**Closed as not planned by cammellos** 2023-07-14 11:11 UTC
Labels: ios, push-notifications, notifications
