### ISSUE TITLE
Unable to delete group chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10057] opened 2020-02-19 10:42 UTC
# Bug Report

## Problem
Can't delete group chat (regardless of the way of deleting)

#### Expected behavior
Group chat is deleted

#### Actual behavior
Group chat is preserved 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Device 1: create a new user
- Device 2: create a new user
- Device 1: add Device 2 to Contacts, start a group chat
- Device 1:  try to delete Group chat

### Additional Information

- Status version: nightly 18/2/20
- Operating System: Android, iOS

**Comment by Serhy** [comment] 2020-03-02 15:13
After https://github.com/status-im/status-react/issues/10054 fixed I can't reproduce this issue.
Can delete Group chat from `Chats` main view, from Group Info view and from group chat menu via Delete chat option. In all of three cases after re-login there were no group chat after relogin and nothing received if message received in group chat that has been deleted. 

@churik I think we may close this one if there is no issue for you too

**Closed as completed** 2020-04-08 14:26 UTC
Labels: group-chat
