### ISSUE TITLE
Error when creating an account on e2e build

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#20806] opened 2024-07-18 16:21 UTC
# Bug Report

## Problem 
Sometimes when creating an account we get a popup with error:

<img width="363" alt="Screenshot 2024-07-17 at 19 13 02" src="https://github.com/user-attachments/assets/db4a29a3-e553-4538-9bff-b0e9ff5d211e">

#### Expected behavior
No error

#### Actual behavior
Please shake your phone to report this error... is shown

### Reproduction

1. Create a new account

### Additional Information

- Status version: nightly 
- Operating System: Android

Logs:
[logcat_shake_the_phone_error.log](https://github.com/user-attachments/files/16286210/logcat_shake_the_phone_error.log)

**Comment by qfrank** [comment] 2024-09-20 06:36
the version seems old in the screenshot you provided? @yevh-berdnyk 

I can't find the usage of "start-using-status" in the cljs file on the latest `develop` branch. Am I missing something? @Parveshdhull  
<img width="640" alt="image" src="https://github.com/user-attachments/assets/70af9aef-9376-41d9-8dd1-3eed5b14e13d">

**Comment by Parveshdhull** [comment] 2024-09-20 07:43
Yes, the screenshot is old, but I also encountered this error recently, just two days ago. [Status-debug-logs.zip](https://github.com/user-attachments/files/17071683/Status-debug-logs.zip)

Note: In my case, I might have installed the wrong build while working on the syncing fallback flow, so the logs may not be very helpful and error might have been expected.

**Comment by Parveshdhull** [comment] 2024-09-20 07:52
Ok, as per logs shared by @yevh-berdnyk
```
07-17 19:12:04.124 24559 24667 E ReactNativeJS: 'An error occured while handling the re-frame event:', '[:visibility-status-updates/visibility-status-option-pressed 1]', '\n', 'Within the', ':visibility-status-updates/visibility-status-option-pressed', 'event handler function.'
```

I removed this call in https://github.com/status-im/status-mobile/pull/21068, so this issue should be fixed

**Comment by Parveshdhull** [comment] 2024-09-20 07:53
@yevh-berdnyk @churik are you still facing this issue?

**Comment by Parveshdhull** [comment] 2024-09-20 07:55
> I removed this call in https://github.com/status-im/status-mobile/pull/21068, so this issue should be fixed

But in my case, error is
```
'An error occured while handling the re-frame event:', '[:push-notifications/switch false]', '\n', 'Within the', ':push-notifications/switch', 'event handler function.'
```

**Comment by Parveshdhull** [comment] 2024-09-20 07:56
So most probably, problem is with `multiaccounts.update/multiaccount-update`. As both functions are using this.
So we trying to update an no existing multiaccount, and this is causing the crash.

**Comment by Parveshdhull** [comment] 2024-09-20 07:58
Ok, real error in my case
```
node.login error failed to start node: failed to apply migrations: failed to apply status-go/protocol migrations: failed to migrate: file does not exist
```

**Comment by Parveshdhull** [comment] 2024-09-20 08:01
> ```
> node.login error failed to start node: failed to apply migrations: failed to apply status-go/protocol migrations: failed to migrate: file does not exist
> ```

But as I was working on seed phrase fallback and trying different builds, this probably is expected in my case. So if no one else faces this issue, we can close it?

**Comment by yevh-berdnyk** [comment] 2024-09-20 09:53
> @yevh-berdnyk @churik are you still facing this issue?

Yes, a lot of. For example, here are the logs from Sep 19 nightly build:
[requests.log](https://github.com/user-attachments/files/17073279/test_community_discovery_requests1.log)
[geth.log](https://github.com/user-attachments/files/17073283/test_community_discovery_geth1.log)
The pop-up appeared when creating a user

**Comment by Parveshdhull** [comment] 2024-09-20 10:11
thank you @yevh-berdnyk for confirming. Do you access to Status.log file

![image](https://github.com/user-attachments/assets/f6a8274b-8582-4e35-925b-36d7b47940d5)

**Comment by yevh-berdnyk** [comment] 2024-09-20 10:15
> thank you @yevh-berdnyk for confirming. Do you access to Status.log file
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/f6a8274b-8582-4e35-925b-36d7b47940d5)
> 
> 

Not for now. We gather geth and requests logs by script, if you need it, I can add gathering Status.log as well

**Comment by Parveshdhull** [comment] 2024-09-23 13:59
Related UX Issue: We are letting user navigate even if account creation is failed.

While testing syncing fallback flow, I changed [AllowEmptyDisplayName](https://github.com/status-im/status-go/blob/a84f78f8aa748181f715eba5c4492c700aef30b3/protocol/requests/restore_account.go#L34) to false.

I can see error in geth log, but UI is still keeping on-boarding flow as it is. I am not sure why account creation is failing in above cases, but UI should react with these failures.


https://github.com/user-attachments/assets/6160a74d-fb57-4612-a03e-600c959bc4c0

**Comment by yevh-berdnyk** [comment] 2024-09-30 09:26
Hi @Parveshdhull, I've discovered that e2e builds don't contain Status.log, only geth and requests. And that's why I can't extract them in e2e  tests.  Is it easy/fast to be added?

**Comment by Parveshdhull** [comment] 2024-10-20 09:52
> Hi [@Parveshdhull](https://github.com/Parveshdhull), I've discovered that e2e builds don't contain Status.log, only geth and requests. And that's why I can't extract them in e2e tests. Is it easy/fast to be added?

Hi @yevh-berdnyk, I’m not sure why Status.log is missing from the e2e builds. I didn’t see any related configuration. @siddarthkay, do you have any idea?

Also, could you please share adb logs(if possible) of the device next time this error happens? That would be great!

**Comment by churik** [comment] 2024-10-21 12:06
well, we'll switch off the workaround for bug for now and next time we face it, we'll add full adb, I just didn't think it is helpful

**Comment by Parveshdhull** [comment] 2024-10-21 12:57
> well, we'll switch off the workaround for bug for now and next time we face it, we'll add full adb, I just didn't think it is helpful

Thanks, @churik! That’s will be awesome. For account creation failures, ADB logs are very important. We are logging the failure message directly in Kotlin: [AccountManager.kt](https://github.com/status-im/status-mobile/blob/020d5cc1c124f9bd2e8931d5275102a7b093d573/modules/react-native-status/android/src/main/java/im/status/ethereum/module/AccountManager.kt#L32)

**Comment by Parveshdhull** [comment] 2024-10-21 13:09
Oh, I checked [your PR](https://github.com/status-im/status-mobile/pull/21471), and it seems as the workaround we were continuing the flow after the cancel button. That's interesting.

Does this mean that only an error message is shown, but the account is created and the flow works after cancel button pressed?

If this is the case, then I think the [node signal](https://github.com/status-im/status-mobile/blob/020d5cc1c124f9bd2e8931d5275102a7b093d573/src/status_im/contexts/profile/create/effects.cljs#L8) is just a little late, and our [arbitrary delay](https://github.com/status-im/status-mobile/blob/020d5cc1c124f9bd2e8931d5275102a7b093d573/src/status_im/constants.cljs#L453) is not sufficient.

By the way, as mentioned [above](https://github.com/status-im/status-mobile/issues/20806#issuecomment-2368357275), this workaround of adding an arbitrary delay is quite strange. We should only navigate to the allow notification screen on a success event; that should resolve both this issue and the UX problem.

**Comment by churik** [comment] 2024-10-21 13:22
> but the account is created and the flow works after cancel button pressed?

Seems yes, but not every time; afterwards there can be some consequences, i.e. use can't connect to peers. But mostly it works.. at least in e2e. And we cannot guarantee that these consequences are related to this particular error.

At the same time users continue to report this particular error almost every day.


>  For account creation failures, ADB logs are very important.

We're very lucky to get it from the first run, attaching the [full logcat](https://github.com/user-attachments/files/17461461/logcat.2.log)

**Comment by Parveshdhull** [comment] 2024-10-21 13:36
Thank you very much for sharing the logs.

```
10-21 12:37:20.569  4827  4957 D AccountManager: restoreAccountAndLogin
10-21 12:37:20.579  4827  4957 D AccountManager: restoreAccountAndLogin success: {"error":""}
```

The account restoration succeeded, so I believe the e2e issue is primarily related to our delay logic. I will address this. 👍

> Seems yes, but not every time; afterwards there can be some consequences, i.e. use can't connect to peers. But mostly it works.. at least in e2e. And we cannot guarantee that these consequences are related to this particular error.

Once this issue is fixed, the scenarios involving other issues will be more visible (and easier to differentiate), allowing us to address them effectively.

**Comment by Parveshdhull** [comment] 2024-10-24 10:39
Hi @churik,

Quick question: When a user fresh installs the app from the Play Store and the account creation fails and if user reports error by shaking device, what log-level file will we receive (info, debug, error)? We won't get ADB logs, right?

I’m asking because we don’t log account creation errors in CLJS, only [in Kotlin ](https://github.com/status-im/status-mobile/issues/20806#issuecomment-2426601982)(ADB). I can log them in CLJS using log.Error, but will we have those logs for a fresh install before any settings are updated? (probably not 🤔 ?)

cc @ilmotta

**Comment by Parveshdhull** [comment] 2024-10-24 10:48
https://github.com/status-im/status-mobile/issues/20996#issuecomment-2346722063 Ok, so no error logs by default. Still I think we should atleast log errors in CLJS for users who have logging enabled, they will be useful if an error happens when creating more accounts. It could also help with debugging PR builds. wdyt @ilmotta?

**Comment by ilmotta** [comment] 2024-10-25 01:34
@churik @Parveshdhull @qfrank:

I can reproduce this problem 100% of the time with the steps below:

1. `make release-android BUILD_TYPE=release`.
2. Do a fresh install, run `adb install result/app-arm64-v8a-release-signed.apk`
3. Open app and create a profile. In the `Enable notifications` screen, pressing on the button `Maybe later` triggers the pop-up.
4. If I press `Cancel` in the pop-up and press `Maybe later` again, eventually I can login.
5. After login the problem never occurs again. The wallet account is never empty in my reproduction steps, so I'm not reproducing https://github.com/status-im/status-mobile/issues/21151https://github.com/user-attachments/assets/7beddf57-c3d6-42e4-8b18-90658fd699ca

In this setup, every single profile creation will trigger the pop-up. If I wait ~10s before pressing `Maybe later`, the pop-up does not appear. Therefore @Parveshdhull, as you said here https://github.com/status-im/status-mobile/issues/20806#issuecomment-2426634343, there's a timing/ordering bug. The bug is not random if I follow the steps above, the timing is always the same as well, so it's quite deterministic, which is good news.

----

> https://github.com/status-im/status-mobile/issues/20996#issuecomment-2346722063 Ok, so no error logs by default. Still I think we should atleast log errors in CLJS for users who have logging enabled, they will be useful if an error happens when creating more accounts. It could also help with debugging PR builds. wdyt @ilmotta?

@Parveshdhull, in a release build the LOG_LEVEL is empty, but geth.log will print WARN and ERROR logs. As far as I checked, when the user creates a profile and changes the log level in the settings, that level is only used for that profile and won't survive after logout. After logout or upon reopening the app the log level will be the default set at build time. Sorry if I misunderstood your question.

**Comment by qfrank** [comment] 2024-10-25 09:04
> We should only navigate to the allow notification screen on a success event; that should resolve both this issue and the UX problem.

Perhaps allow the notification screen after `node.login`. This seems reasonable. Replying with a specific delay value (7000) is not ideal. @Parveshdhull

**Closed as completed** 2024-10-28 19:24 UTC
Labels: e2e test blocker, mobile-core
