### ISSUE TITLE
Long sync (90+ sec) when Fetch24History in 1-1 / Group chats

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#8441] opened 2019-06-19 16:58 UTC
***Type***: Bug

***Summary***: When 'Fetch 24 history' action in 1-1, but especially in Group, chat has tapped - app syncing (blue progress bar) takes 90+ seconds almost always (sometimes longer).
In public chat it's less than 2 seconds. It does not depend from devices: there are similar values for Low-Middle (Android 8) and iPhoneX (iOS 12).

It also depends on mailserver user is connected to, so in below scenarios everything reproduced when connected to the same mail-01.ams3 mailserver

#### Expected behavior
App sync takes <2s (same as for public chat) when fetching 24h history in 1-1/Group Chat with `Fetch 24h history` chat option

#### Actual behavior

App sync takes 90+ seconds when fetching 24h history in 1-1/Group Chat with `Fetch 24h history` chat option. Please see video and logs below.

### Reproduction 1 (Group Chat)

- Open Status and create new account (UserA)
- With another device add UserA in contacts
- Create `Group Chat` with UserA. Send a single 1 line text message.
- UserA joins the group chat. Wait until syncing at this stage is completed.
- UserA from the GroupChat -> top-right chat menu button taps `Fetch last 24 hours`

Video for above scenario: https://drive.google.com/file/d/1iArQsh24q-iQf9cs-hsnc7RtJ6CJxF2u/view
Logcat: [1to1Fetch24Logcat.log](https://github.com/status-im/status-react/files/3307151/GroupNightlyFetch24hLogcat.log)
Geth.log (with DEBUG log level):   [GroupNightlyFetch24geth.log](https://github.com/status-im/status-react/files/3307149/GroupNightlyFetch24geth.log)

### Reproduction 2 (1-1 chat)
- Open Status and create new account (UserA)
- With another device add UserA in contacts and send text message
- UserA from the 1-1 chat view -> top-right chat menu button taps `Fetch last 24 hours`

Video for above scenario: https://drive.google.com/file/d/1-3SbQli-gv_z7tlpzcdtPW1nBFDFnvv3/view
Logcat: [1to1Fetch24Logcat.log](https://github.com/status-im/status-react/files/3307144/11ChatNightly2ChatFetch24hSyncing.log)
Geth.log (with DEBUG log level): [1to1Fetch24geth.log](https://github.com/status-im/status-react/files/3307146/11NightlyFetch24hgeth.log)

### Additional Information

- Status version: Develop Nightly build 19th of June (2019061902)
- Operating System: Android and iOS

**Comment by Serhy** [comment] 2019-06-20 10:24
@mandrigin @cammellos I'm wondering if this reproducible issue could be one of the major reasons of when syncing may take 10+ minutes which can happen from time to time (Note: the 10+ minutes sync may also be because of the location of mailserver user is connected to - happens usually when mailserver autoconnection is set - but it's separate from this issue.)

So if the contact has several 1-1, several group chats and logins to account we start sync of the last 24h history in those chats it takes long time to finish due to bug reproduced here.

**Comment by cammellos** [comment] 2019-06-20 10:33
The issue is a known behaviour, not quite a bug.


1 to 1 and group chats receive messages from what we call the discovery
topic.

This topic contains all the data that is exchanged on 1 to 1 and group
chats from anyone who uses status.

so when you fetch the last 24 hours, you will be receiving all the 1 to 1
messages sent on status ( you will only keep the ones that are for you).

when you fetch a public chat, you only receive messages for that chat, so
it s much faster.


we are addressing the issue by moving to a partitioned/negotiated topic
which will alleviate the load, but will only happen when people start using
the new version ( pr is now under testing).


 overall group chats vs one to one should take the same time (it s the same
request), number of chats is also not relevant ( more or less), as we
always fetch the discovery topic, even if you don't have any chats.

but it is definitely the reason for the 10 minutes syncing

**Closed as completed** 2020-09-17 10:49 UTC
Labels: performance
