### ISSUE TITLE
Canceling Biometric popup saves the password without asking for biometrics

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#11291] opened 2020-10-13 07:59 UTC
# Bug Report

## Problem

If I mark to save the password, it prompts me for biometric saying that is necessary to enable it, but this is not true. Canceling it does not uncheck the save password, and password is not requested in the next login.

#### Expected behavior

Save password is only enabled with biometric is enabled.

**Comment by flexsurfer** [comment] 2020-10-13 08:25
it's confusing for sure, but it works as designed

**Comment by cammellos** [comment] 2020-10-13 08:38
If it's by design I'll close this one, we can probably have a chat with UX if you feel that the UX should be changed

**Closed as completed by cammellos** 2020-10-13 08:38 UTC
