### ISSUE TITLE
Incorrect default name for watch-only addresses

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18664] opened 2024-01-29 16:52 UTC
### Preconditions:
User already has at least one watch only address

### Steps:
1. In the wallet, tap [+] to add an address to watch.
2. Paste a valid address and tap [continue].
3. Check the name of the added watch-only address.

### Actual result:
"Account 1" is always shown by default
![image](https://github.com/status-im/status-mobile/assets/52490791/7c2734e0-251a-41d8-a87d-6fd1fd14cbed)

### Expected  result:
The default name should be "Watched address 1" for the first watch-only address, and subsequent addresses should be named incrementally, such as "Watched address 2," "Watched address 3," and so on.
![image](https://github.com/status-im/status-mobile/assets/52490791/907abca6-e8d0-4a6f-b4d8-c97528ec5a4a)

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=2052-522184&mode=design&t=0DZZUHEcUNcjITk3-0

**Comment by smohamedjavid** [comment] 2024-01-30 06:48
Duplicate of #18416

**Closed as completed** 2024-01-30 08:06 UTC
