### ISSUE TITLE
Android (Gooogle Pixel7): opening "Jump To" leads to a white google pixel panel on Activity centre (should be black)

### ISSUE THREAD

**Issue by codemaster115** [status-im/status-react#18450] opened 2024-01-10 16:06 UTC
On Android (Gooogle Pixel7): opening "Jump To" leads to a white google pixel panel on Activity centre (should be black)

**Comment by Parveshdhull** [comment] 2024-01-10 16:43
Hi @codemaster115, Thank you very much for breaking it and fixing the navigation bar issue. But I think in https://github.com/status-im/status-mobile/issues/17636, 2nd issue was related to status-bar when navigating back to jump-to from activity center.
(`Status system top bar wrong colour issues`)

Please can we undo changes in the https://github.com/status-im/status-mobile/issues/17636, so that it doesn't reflect the original issue is fixed, and we treat this one as new issue.

**Comment by Parveshdhull** [comment] 2024-01-10 17:03
> Hi @codemaster115, Thank you very much for breaking it and fixing the navigation bar issue. But I think in #17636, 2nd issue was related to status-bar when navigating back to jump-to from activity center. (`Status system top bar wrong colour issues`)
> 
> Please can we undo changes in the #17636, so that it doesn't reflect the original issue is fixed, and we treat this one as new issue.

cc: @status-im/mobile-qa (maybe I am wrong here, please can you confirm if original (2nd) issue was related to status-bar or navigation-bar, as it don't have any title) thank you

**Comment by VolodLytvynenko** [comment] 2024-01-11 09:50
> cc: @status-im/mobile-qa (maybe I am wrong here, please can you confirm if original (2nd) issue was related to status-bar or navigation-bar, as it don't have any title) thank you

@Parveshdhull Did I understand you correctly? Are you asking if the [current issue](https://github.com/status-im/status-mobile/issues/18450) is a duplicate of the one created by Tetiana at https://github.com/status-im/status-mobile/issues/17636? If so, yes, it seems like this is a duplicate, and it also relates to the same status bar issue.

**Comment by Parveshdhull** [comment] 2024-01-12 07:47
Oh sorry, I was confused here. Video had two issues, (one with navigation panel, and one with status bar color), and we logged navigation issue in same issue "Status system top bar wrong colour issues" and that created confusion.

<div align="center">
<img src="https://github.com/status-im/status-mobile/assets/17097240/df2a70c6-c2cc-41fc-9d72-7d4273bdc655" alt="Screenshot" height="50"/>
</div>

<div align="center">
<img src="https://github.com/status-im/status-mobile/assets/17097240/c681e415-d2b9-4cc9-a0fe-cc19e18e7d75" alt="Screenshot" height="100"/>
</div>

I modifed #17636, to make sure that issue only logs issue related to status-bar (as that's what title says), and we can treat this one as separate issue.

<div align="center">
<img src="https://github.com/status-im/status-mobile/assets/17097240/b20f7faf-7f30-46d1-bb0c-dbbc949fde03" alt="Screenshot" height="70"/>
</div>


PS: please feel free to revert back, if other way made more sense

**Closed as completed** 2024-01-19 15:20 UTC
