### ISSUE TITLE
The ens stop resolving for user requester after user with ens accepts current request

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14602] opened 2022-12-21 14:57 UTC
**Steps to reproduce:**
1. Go to the contacts as USER_A 
2. Add new contacts -> Paste ENS of USER_B into ENS textbox
3. Login as USER_B
4. Accept the request of USER_A
5. Check the contacts page as USER_A

**Actual result:**
The '3 random name' is shown in contacts list

https://user-images.githubusercontent.com/52490791/208934115-f7002bc3-d89e-4581-a193-ca65f62ce93a.mp4

**Expected result:**
The ENS is shown into contacts list

**ADDITIONAL INFO:**
As USER_B you can use the following data:
Seed phrase: spike spoil hidden sad juice force trap bind situate consider suit demand
ENS: volodymyr.eth
Be advised, the current ENS works only on the Goerli network

**Comment by churik** [comment] 2023-01-24 15:00
Checked nightly on mainnet where the ENS is set in profile for USER_B. The issue is not reproducible, closing

**Closed as completed by churik** 2023-01-24 15:00 UTC
