### ISSUE TITLE
Ens name missing from share key pop over

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#10218] opened 2020-03-25 23:28 UTC
# Bug Report

## Problem

When encountering a user for the first time in a public chat, even after the ens name appears to be verified in the public chat, it is missing from the share key popover. It is there after restarting the app so it seems like it is not properly added to the app state but is properly loaded from status-go.

**Comment by 0x-r4bbit** [comment] 2020-04-14 10:32
It seems this issue has been fixed in the meantime as I'm not able to reproduce this. Here's what I did:

- Joined a public chat (`#test`)
- Asked a core contributor to send a message in the channel
- Received message and waited for his ENS name to be resolved by Status (this  happens apparently every 30sec)
- ENS name resolves
- Went to profile -> profile details -> popover -> ENS name shows

Let me know if there's anything else that needs to be done to reproduce this issue. Otherwise I believe this can be closed.

Assigning back to @yenda as discussed in chat.

**Comment by churik** [comment] 2020-06-10 12:52
It is not reproducible on v.1.4

**Closed as completed by churik** 2020-06-10 12:52 UTC
