### ISSUE TITLE
Previously typed message stays in the input field if continue typing right after hitting send button

### ISSUE THREAD

**Issue by ahmetmertugrul** [status-im/status-react#2603] opened 2017-12-05 10:46 UTC
### Description

*Type*: Bug

I wrote a lot of characters in Message Box and send message. But, old characters were not erased when I wrote again.

Video: [https://drive.google.com/file/d/1GMceq-2Iuin9VwxldaATMNGDLY19EoST/view](https://drive.google.com/file/d/1GMceq-2Iuin9VwxldaATMNGDLY19EoST/view)

### Reproduction

- Open Status
- Sign in
- Chat with console
- Click Message Box
- Write characters
- Send message
- Click Message Box
- Write characters
- Send message

### Solution

- Older characters should be deleted after sending a message.

### Additional Information

* Status version: 0.9.12+

* Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by annadanchenko** [comment] 2017-12-07 21:17
@ahmetertugrul thanks again for the bug reports! Please, update the video so it's shared on youtube on in the google drive

**Comment by annadanchenko** [comment] 2017-12-07 21:33
Can reproduce on real Google Pixel XL (no Samsung keyboard here), Android 8.0 with nightly develop build from Dec 7: http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-a68f06.apk
Status version  0.9.10-427-ga68f0652+ (1984)
Log and video from TestFairy: https://app.testfairy.com/projects/4803622-status/builds/7234321/sessions/54/?accessToken=/dmNhQW8wMia-SVoGtl1spv/vMk
Screen video of the same session (to see all taps and keyboard):  https://drive.google.com/open?id=1RtXvlh4n2kbIAdBSvUAtmXtbhs85J2tn

**Comment by ahmetmertugrul** [comment] 2017-12-08 20:36
Video: [https://drive.google.com/file/d/1FrlfLlpJlkPSYgBtr1Kfbb2B7BpMMGXR/view](https://drive.google.com/file/d/1FrlfLlpJlkPSYgBtr1Kfbb2B7BpMMGXR/view)

- Status version: 0.9.10-427-ga68f0652+ (1984)

- Operating System: Android 6.0 - LG G4 (Real Device)

**Comment by lukaszfryc** [comment] 2018-05-10 14:27
Duplicate of https://github.com/status-im/status-react/issues/3420

**Closed as completed by lukaszfryc** 2018-05-10 14:27 UTC
