### ISSUE TITLE
The chat list for users who upgraded from v1 to v2 takes a long time to fetch

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#20816] opened 2024-07-19 09:11 UTC
## Problem 

The chat list for users who upgraded from v1 to v2 takes a long time to fetch

https://github.com/user-attachments/assets/3ba3a848-4370-41c8-a97c-a1f8a8edb016

#### Expected behaviour

The chat list loading should be quick. 

One suggestion here is to show some loader when fetching as it creates a perception to the user that there are no chats (with the empty state) and suddenly UI updates.

#### Actual behaviour

The chat list loading takes at least 10 seconds for 3 chats.

### Reproduction

1. Create a profile in v1.20.6 (existing App Store version) and a few chats & contacts
3. Upgrade the app to v2.30.0 (from TestFlight)
4. Login to the app
5. After the upgrade, the chat list loading takes a minimum of 10 seconds

### Additional Information

- Status Version: v2.30.0 (from TestFlight) 
- Operating System: iOS

### Logs

[logs.zip](https://github.com/user-attachments/files/16309623/logs.zip)

**Comment by Parveshdhull** [comment] 2024-07-22 10:01
Hi @smohamedjavid, Is this issue only specific for the users who upgraded from v1 to v2 or issue is just with v2 itself?

@ilmotta is this issue related to https://github.com/status-im/status-mobile/issues/20283 (as you are working on it)

**Comment by smohamedjavid** [comment] 2024-07-22 10:29
This is happening for a user who upgraded from v1 to v2. 

I guess #20283 is handling the community area.

**Comment by ilmotta** [comment] 2024-07-24 02:42
Thanks for copying me @Parveshdhull. @smohamedjavid, I wonder if this delay to load chats is related to the merged PR https://github.com/status-im/status-mobile/pull/20173. Before that PR we would block the user from logging in while setting up filters in status-go, which was a major disruption because it blocked users from doing anything on the app, but we don't want to disrupt the fragile funnel to login.

But if what you reported in this issue is related to the time it takes in status-go to set up the filters (ref: https://github.com/status-im/status-go/blob/102b57098eda59fa36cad82e201c9179a95081a7/protocol/messenger.go#L1750), then the problem is surely in status-go and there's nothing we can do on the client side.

Deserves investigation for sure 👍🏼 

> I guess https://github.com/status-im/status-mobile/issues/20283 is handling the community area.

Correct, basically optimizing how community members are consumed and stored in the app-db.

**Comment by monicazng** [comment] 2024-10-15 09:47
A suggestion if the loading is slow is to show a cached chat history

**Comment by churik** [comment] 2024-10-17 12:19
Might be better after https://github.com/status-im/status-mobile/issues/21358, should be re-checked after merge

**Comment by churik** [comment] 2024-11-21 11:48
I believe it got a way better after https://github.com/status-im/status-mobile/issues/21358 , please reopne if it is the same for you @smohamedjavid 

Thank you!

**Closed as completed by churik** 2024-11-21 11:48 UTC
Labels: performance, mobile-core
