### ISSUE TITLE
The app does not show multi-route advanced view and that created confusion

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21788] opened 2024-12-10 15:06 UTC
# Bug Report

## Problem 
If user has assets spread over different networks (i.e. 1 Mainnet / 1 Optimizm / 1 Arb), the attempt to send more than user has on one network leads to enormous fee and in fact building multiroute (see desktop attached screen), but there is no explanation on mobile and no advanced flow presented. 

#### Expected behavior
cannot send more than on 1 network, appropriate error is displayed

#### Actual behavior
On mobile: 
![Image](https://github.com/user-attachments/assets/8945e318-e1b7-4bff-82cc-2e2383799329)

On desktop:
![Image](https://github.com/user-attachments/assets/e4ce44d9-39db-49a0-9621-aac4aa6abfea)

### Reproduction
**Prerequisites:** user has some assets on 2 networks

1. Open send flow
2. Enter the amount bigger than available on 1 network
3. Wait for routes

### Additional Information

- Status version: 2.32
- Operating System: Android, iOS

**Comment by alwx** [comment] 2024-12-19 10:15
Currently investigating how it's done on desktop to make our logic match it.

**Comment by churik** [comment] 2024-12-19 10:23
After https://github.com/status-im/status-mobile/pull/21595 it should not be reproducible (I HOPE SO), so I'll have it opened for a while until we release the flow in case users bump onto it

**Comment by VolodLytvynenko** [comment] 2024-12-23 11:25
The issue is resolved in simplified send flow https://github.com/status-im/status-mobile/pull/21595

**Closed as completed by VolodLytvynenko** 2024-12-23 11:25 UTC
Labels: wallet: Networks and Routes, wallet-core
