### ISSUE TITLE
Wallet - loading on collectibles page for images not fetched

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#20103] opened 2024-05-20 09:08 UTC
If a collectible is unfetchable it will not load correctly. i.e "Can't fetch" state.

In this video the user selects a "can't fetch" collectible it should then show the same on the overview page.
https://github.com/status-im/status-mobile/assets/22799766/b6b26988-fe41-4ea4-90f9-bcdca3cd1bc2
Currently this type is not displaying consistently in the overview page as it is  with the one on the list view

Further, the loading of collectibles on the overview page should have a loading state similar to the collectible list component.

Update the styling to handle this. See: https://github.com/status-im/status-mobile/pull/19945

Acceptance Criteria:
- Collectible should display correctly for "Can't fetch type on overview page" (Duplicate of https://github.com/status-im/status-mobile/issues/20179)
- there should be some loading/ transition on collectible overview page

**Comment by BalogunofAfrica** [comment] 2024-06-04 22:07
can I get the account used in the video? 

For my account and the watched accounts I have, it shows the same info "Unsupported file" in both the list and the details screen

**Comment by BalogunofAfrica** [comment] 2024-06-05 14:46
Duplicate of https://github.com/status-im/status-mobile/issues/20179

PR here: https://github.com/status-im/status-mobile/pull/20281

**Comment by BalogunofAfrica** [comment] 2024-06-06 00:25
Reopening issue as the duplicate issue https://github.com/status-im/status-mobile/issues/20179#issuecomment-2150628312 does not address the loading/transition

**Closed as completed** 2024-07-03 14:49 UTC
Labels: wallet-core
