### ISSUE TITLE
Onboarding - Sign In - Design review 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16063] opened 2023-05-30 20:39 UTC
Currently the issues on Android with blur are causing issues with this page when the camera is enabled.

To address this temporarily the suggested approach is to remove blur for this page on Android, it can be added in later once the blur is working correctly on Android.

Screenshot from Pixel 7a
![photo_2023-05-30_10-44-34](https://github.com/status-im/status-mobile/assets/22799766/0289dbe1-bfbd-4192-8020-78ac1d416413)

**Comment by ilmotta** [comment] 2023-06-05 09:48
This issue is blocked until the new blur approach @briansztamfater is working on is accepted and merged.

**Comment by smohamedjavid** [comment] 2023-06-12 18:51
Guys, This issue may be caused to the Camera not filling the whole screen (due to the camera-kit library issue), and letting the image behind it pass through. I have this WIP PR (https://github.com/status-im/status-mobile/pull/16248) which upgrades the `react-native-camera-kit` library to `v12.0.0` to fix the camera issue. 

As far as I checked, this issue is not reproducible in the PR build as the camera takes the whole screen.

Kindly download the PR build and check.

**Comment by smohamedjavid** [comment] 2023-06-20 13:21
Fixed on https://github.com/status-im/status-mobile/pull/16248

**Closed as completed by smohamedjavid** 2023-06-20 13:21 UTC
Labels: blocked
