### ISSUE TITLE
2 send commands are shown if chat contains 1 or more request messages [3259]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#3350] opened 2018-02-16 17:40 UTC
### Description

*Type*: Bug

*Summary*: 
Second "/send" command is shown in commands list if chat contains 1 or more Request messages sent to this contact. 

![36313191-e249b814-1341-11e8-9416-248c025ac9ce](https://user-images.githubusercontent.com/6584810/36321000-544b2d1e-1359-11e8-862d-4b0421219f81.png)

#### Expected behavior
Only one /send command is shown

#### Actual behavior
``` 
/send
/request
/send 
```
are shown in the list

### Reproduction

- Open Status
- in group or in 1:1 chat send 2 requests to contact B
- as contact B: open the chat with 2 request messages and tap on "command" icon to open commands suggestions list. Check how many times "/send" command is shown.

### Additional Information
* Status version: PR 3259 build
* Operating System: Android and iOS

**Comment by asemiankevich** [comment] 2018-02-19 10:43
reproduced in last nightly from 2/19/18
![image](https://user-images.githubusercontent.com/28752642/36373988-e63b5c9e-157a-11e8-98af-4bff2b475675.png)

**Comment by janherich** [comment] 2018-02-19 11:21
@annadanchenko This is actually not a bug, only bad UI - whenever command request is received, it's added to the "open requests" for you, and those are merged with standalone "commands" in the suggestion list.
So when somebody requests from you twice, let's say `/request 2` and `/request 1`, those are two different command request, with different parameters (2 ETH in first case, 1 ETH in second case), and when you click on any of the request pulsing bubbles, `/send` command is loaded with correct arguments.
Now we also display command requests in the suggestions list, where we merge them with normal commands, we could de-duplicate them, but in that case, which parameters should be pre-filled for `/send` command if you have multiple `/requests` outstanding, parameters of the last request, or first request ?
I see two ways how to solve it:
1. Either only display commands and not command requests in the suggestions list, this is not optimal, because for command requests, you have to scroll in the chat to find the request message (but maybe that's the intention)
2. Display both in suggestions list, but clearly differentiate between commands and command requests + display the latter with params as well

**Comment by annadanchenko** [comment] 2018-02-19 15:02
@janherich I would stick to option 1 (do not show command requests in the suggestions list) because current way is already broken, so users can't get any useful effects from using the second /send

For the future - we might need to implement option 2 based on UX/UI feedback and new designs.

**Comment by denis-sharypin** [comment] 2018-02-19 16:15
I vote for option 1 as well

**Closed as completed** 2018-02-26 19:36 UTC
