### ISSUE TITLE
Status freezes on splash screen (iOS)

### ISSUE THREAD

**Issue by pabloruiz55** [status-im/status-react#2679] opened 2017-12-10 13:26 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to launch the application on an iOS device.

### Description

Type: bug
I downloaded, built and launched everything as instructed in the wiki. When building the app on Xcode (be it simulator or actual device) the app hangs on the splash screen and doesn't do anything. In the Xcode console I can see the following log (see logs at the bottom)

#### Expected behavior
The app should launch

#### Actual behavior
The app just hangs on the splash screen with the Status logo

### Reproduction
1. Install the app as per the wiki instructions
2. Build and run on Xcode
3. The app shows the splash but doesn't go past there, check the console log.

### Additional Information
iOS 11.2
Xcode Version 9.1

#### Logs

```
2017-12-10 10:07:10.361 [info][tid:main][RCTBatchedBridge.m:75] Initializing <RCTBatchedBridge: 0x6000001b8800> (parent: <RCTBridge: 0x6040002c0620>, executor: RCTJSCExecutor)
2017-12-10 10:07:10.413493-0300 StatusIm[70557:1269208] Initializing <RCTBatchedBridge: 0x6000001b8800> (parent: <RCTBridge: 0x6040002c0620>, executor: RCTJSCExecutor)
2017-12-10 10:07:12.575 [info][tid:com.facebook.react.JavaScript] There was an error collecting entropy from the browser:
2017-12-10 10:07:12.576226-0300 StatusIm[70557:1269710] There was an error collecting entropy from the browser:
2017-12-10 10:07:12.579 [info][tid:com.facebook.react.JavaScript] { [TypeError: undefined is not an object (evaluating 'sjcl.random')]
  line: 61724,
  column: 28,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
2017-12-10 10:07:12.578853-0300 StatusIm[70557:1269710] { [TypeError: undefined is not an object (evaluating 'sjcl.random')]
  line: 61724,
  column: 28,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
2017-12-10 10:07:12.686235-0300 StatusIm[70557:1269630] [] nw_connection_get_connected_socket 4 Connection has no connected handler
2017-12-10 10:07:12.687157-0300 StatusIm[70557:1269630] TCP Conn 0x604000176140 Failed : error 0:61 [61]
2017-12-10 10:07:12.848 [info][tid:com.facebook.react.JavaScript] There was an error collecting entropy from the browser:
2017-12-10 10:07:12.849587-0300 StatusIm[70557:1269710] There was an error collecting entropy from the browser:
2017-12-10 10:07:12.851 [info][tid:com.facebook.react.JavaScript] { [Error: Requiring module "629", which threw an exception.]
  line: 136,
  column: 15,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
2017-12-10 10:07:12.851023-0300 StatusIm[70557:1269710] { [Error: Requiring module "629", which threw an exception.]
  line: 136,
  column: 15,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
2017-12-10 10:07:13.297 [info][tid:main][RCTRootView.m:284] Running application StatusIm ({
    initialProps =     {
    };
    rootTag = 1;
})
2017-12-10 10:07:13.298739-0300 StatusIm[70557:1269208] Running application StatusIm ({
    initialProps =     {
    };
    rootTag = 1;
})
2017-12-10 10:07:13.912 [info][tid:com.facebook.react.JavaScript] Running application "StatusIm" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2017-12-10 10:07:13.913527-0300 StatusIm[70557:1269710] Running application "StatusIm" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2017-12-10 10:07:13.971 [info][tid:com.facebook.react.JavaScript] Loading Closure base.
2017-12-10 10:07:13.971015-0300 StatusIm[70557:1269710] Loading Closure base.
2017-12-10 10:07:13.971 [info][tid:com.facebook.react.JavaScript] Shimming require
2017-12-10 10:07:13.971348-0300 StatusIm[70557:1269710] Shimming require
2017-12-10 10:07:14.198 [error][tid:com.facebook.react.JavaScript] { [SyntaxError: Unexpected identifier 'GET']
  line: 129423,
  column: 25,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
2017-12-10 10:07:14.198115-0300 StatusIm[70557:1269710] { [SyntaxError: Unexpected identifier 'GET']
  line: 129423,
  column: 25,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
2017-12-10 10:07:15.506959-0300 StatusIm[70557:1269630] [] nw_connection_get_connected_socket 6 Connection has no connected handler
2017-12-10 10:07:15.507373-0300 StatusIm[70557:1269630] TCP Conn 0x604000175900 Failed : error 0:61 [61]
2017-12-10 10:07:17.601078-0300 StatusIm[70557:1269639] [] nw_connection_get_connected_socket 7 Connection has no connected handler
2017-12-10 10:07:17.601440-0300 StatusIm[70557:1269639] TCP Conn 0x604000172e40 Failed : error 0:61 [61]
2017-12-10 10:07:19.616442-0300 StatusIm[70557:1269638] [] nw_connection_get_connected_socket 8 Connection has no connected handler
2017-12-10 10:07:19.616875-0300 StatusIm[70557:1269638] TCP Conn 0x6000001765c0 Failed : error 0:61 [61]
```

The last 2 lines get repeated ad infinitum until I quit the app.

**Comment by jameszaghini** [comment] 2017-12-10 16:36
@pabloruiz55 I had the same problem. See #2678 for a workaround

**Comment by andytudhope** [comment] 2017-12-11 08:39
Duplicate of #2678 - please try removing the directory, cloning again and running `./scripts/setup-osx` instead and let me know how it goes.

**Closed as completed by andytudhope** 2017-12-11 08:39 UTC
