### ISSUE TITLE
Link is opened in system browser instead of a webview 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1200] opened 2017-05-12 10:38 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Page is opened in system browser browse google.ru, search for "testing" and tap on any link  in found results. Note: this does not happen if search view google.com

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If tap on link then page is loaded inside the webview (in the app not in Safari browser)
#### Actual behavior
[comment]: # (Describe what actually happened.)
If tap on link then page is opened in Safari
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7NE5LVU9iNGtsR1U
- Open Status
- Open Dapp
- google.ru
- search for "testing"
- In found results tap on any link, e.g on wikipedia link

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.7 
* Operating System: iOS

#### Logs
[20171205121940-consolelog.txt](https://github.com/status-im/status-react/files/995813/20171205121940-consolelog.txt)

**Comment by annadanchenko** [comment] 2017-05-30 18:22
set to in progress on request from @occamin

**Comment by flexsurfer** [comment] 2018-05-09 14:41
there is `shouldOverrideUrlLoading` for Android

**Comment by status-open-bounty** [comment] 2018-05-09 16:37
Balance: 0.000000 ETH
Tokens: SNT: 1350.00
Contract address: [0x7d09e91b2dde3397731350fd39f5f95d16dbf81f](https://etherscan.io/address/0x7d09e91b2dde3397731350fd39f5f95d16dbf81f)
Network: Mainnet
Paid to: georgiemathews
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by georgiemathews** [comment] 2018-05-09 19:46
I'll start working on this

**Comment by georgiemathews** [comment] 2018-05-10 20:24
@flexsurfer Looks like the issue is in your fork of react-native-webview-bridge. Is it necessary to still be using this fork since the webview is now integrated into react-native core? If so, could you shed some light on the purpose of maintaining this fork.

**Comment by rasom** [comment] 2018-05-11 06:37
> could you shed some light on the purpose of maintaining this fork

the reason why we need to have our own fork is that we have to ensure that `web3` object is injected into webview **before** any page is loaded, which is impossible with API provided by `react-native`'s implementation. 

For instance, [`react-native`'s webview (iOS version) ](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/React/Views/RCTWebView.m#L36) is based on [UIWebView](https://developer.apple.com/documentation/uikit/uiwebview) which is kind of deprecated. When using `UIWebView` it's just impossible to guaranty that any custom js code will be injected into webview before loading of the web page, when `WKWebView` provides [API for this purpose](https://developer.apple.com/documentation/webkit/wkuserscriptinjectiontime/wkuserscriptinjectiontimeatdocumentstart).
Also `UIWebView` is much slower than [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview)

We have similar situation on Android, but there is no API for such injection at all, so we need to implement our own hack for injection.

**Comment by annadanchenko** [comment] 2018-05-11 07:10
rechecked on Android 8.1.0  (real Pixel XL) - can't reproduce
on iOS 11.0.13 (real iphone 7 plus) - CAN reprodcue

**Comment by flexsurfer** [comment] 2018-05-11 07:13
@annadanchenko retested without this fix, just to make sure it's repro only on ios

**Comment by flexsurfer** [comment] 2018-05-11 08:02
@georgiemathews your changes merged in master, could you please create PR in this repo and change here https://github.com/status-im/status-react/blob/develop/package.json#L61 branch to master

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Closed** 2018-05-14 12:48 UTC
Labels: bounty, bounty-m, bug, high-priority, ios, webview
