### ISSUE TITLE
Text breaks when manually resizing the window

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5416] opened 2018-08-07 16:35 UTC
**Issue**
When resizing the window manually, messages and titles do not adapt to the current window size. E.g. when I make the window smaller and then make it bigger again (manually).

<img width="1099" alt="captura de pantalla 2018-08-07 a la s 1 33 53 p m" src="https://user-images.githubusercontent.com/37297779/43789751-280f4ca6-9a47-11e8-9053-edeaf86275d5.png">

<img width="1097" alt="captura de pantalla 2018-08-07 a la s 1 33 43 p m" src="https://user-images.githubusercontent.com/37297779/43789776-3d8c699c-9a47-11e8-8700-be5e14ef5571.png">

<img width="1091" alt="captura de pantalla 2018-08-07 a la s 12 43 34 p m" src="https://user-images.githubusercontent.com/37297779/43789834-53ecef2c-9a47-11e8-9261-a66773b39f50.png">

**Type:** Bug.

**Solution**: Elements in the UI should adapt to current window size.

**Steps to reproduce**
1- Open Status desktop
2- Sign in
3- Open chat with messages
4- Make window smaller by dragging the corners
5- Make window bigger again by dragging the corners

**Comment by churik** [comment] 2018-08-08 13:27
duplicate of https://github.com/status-im/status-react/issues/5151

**Closed as completed by churik** 2018-08-08 13:27 UTC
