### ISSUE TITLE
Photo view and gallery issues 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15573] opened 2023-04-04 13:14 UTC
# Bug Report

### ISSUE 1: Can't close photo gallery

You can only close the gallery by selecting a photo and confirming selection.

**Steps:**
1. Open chat
2. Open the gallery
3. Try to close it

**OS:** Android, iOS

https://user-images.githubusercontent.com/67952253/229799117-59dd41a5-3201-472f-83fe-1058f4f2a52d.mp4

### ISSUE 2: Images sent from desktop are cropped on mobile in view mode

**Steps:**
1. Send images from desktop
2. Open it on mobile

**OS:** iOS, Android

https://user-images.githubusercontent.com/67952253/229800880-4d2de838-894b-4fc1-bd93-f85904d59783.mp4

### ISSUE 3: Incorrect display of a single image in view mode received from desktop (Android)

In this case, the top buttons and the sender's name are overlapped with the status bar, and the image thumbnail is at the top (should be at the bottom).

**Steps:**
1. Send one image from desktop
2. Open it on mobile

**OS:** Android

<img width="326" alt="Screenshot 2023-04-04 at 15 07 44" src="https://user-images.githubusercontent.com/67952253/229801332-e1ce6dd8-7ce1-4a0c-a3d4-df50d17c7a35.png">

- Status version: RC 1.22 https://ci.infra.status.im/job/status-mobile/job/release/job/release%252F1.22.x/ 
- Operating System: Android, iOS

**Comment by cammellos** [comment] 2023-04-04 13:39
@OmarBasem would you mind looking into this please? 
Thank you

**Comment by OmarBasem** [comment] 2023-04-04 13:49
@flexsurfer I see you in your PR https://github.com/status-im/status-mobile/pull/15467 you disabled gestures on the whole screen by wrapping the gesture detector around the top handle only

**Comment by OmarBasem** [comment] 2023-04-04 13:52
Hi @qoqobolo, is issue 1 on develop or release branch 1.22?

**Comment by pavloburykh** [comment] 2023-04-04 14:31
> Hi @qoqobolo, is issue 1 on develop or release branch 1.22?

hi @OmarBasem issue 1 is reproducible only on release branch not in develop. It might be a result of some problems during last cherrypick to release branch. 

>@flexsurfer I see you in your PR https://github.com/status-im/status-mobile/pull/15467 you disabled gestures on the whole screen by wrapping the gesture detector around the top handle only

These changes should not be cherrypicked into release. Maybe part of them were cherrypicked which caused the above issue 1? 

cc @cammellos

**Comment by OmarBasem** [comment] 2023-04-04 14:33
Thanks @pavloburykh, I will look into it!

**Comment by qoqobolo** [comment] 2023-04-04 14:55
@OmarBasem btw forgot to specify a desktop version: images were sent from master 31/03

**Comment by qoqobolo** [comment] 2023-04-04 15:54
@OmarBasem one more update:
The incorrect placement of the image thumbnail at the top in issue 3 is also reproducible for iOS and albums. Not every time though, you need to re-open the album several times to replicate it 

<img width="392" alt="Screenshot 2023-04-04 at 17 50 03" src="https://user-images.githubusercontent.com/67952253/229847575-87e686a6-5ce2-4456-a776-8a6ec1190792.png">

**Comment by Parveshdhull** [comment] 2023-04-04 16:24
> hi @OmarBasem issue 1 is reproducible only on release branch not in develop. It might be a result of some problems during last cherrypick to release branch.

Yes, there were several merge conflicts while cherry-picking https://github.com/status-im/status-mobile/pull/15562. (also notified that to @churik)
Because https://github.com/status-im/status-mobile/pull/15467 also changes same files as #15562.

@cammellos how should we handle this. Should we delete cherry-picked commit and then cherry-pick both of them, or fix issue again with using release as base.

**Comment by Parveshdhull** [comment] 2023-04-04 16:31
@status-im/mobile-qa, wdyt about including https://github.com/status-im/status-mobile/pull/15467 in release?

**Comment by cammellos** [comment] 2023-04-04 16:36
> @cammellos how should we handle this. Should we delete cherry-picked commit and then cherry-pick both of them, or fix issue again with using release as base.

@Parveshdhull up to us, it does not matter so much, it's a bit easier if we don't have to force push, but it's roughly the same, we are not so concerned over the history of release branch

**Comment by churik** [comment] 2023-04-04 16:48
> @status-im/mobile-qa, wdyt about including https://github.com/status-im/status-mobile/pull/15467 in release?

Then we need to fix these issues that are noticeable in new onboarding

**ISSUE 2** Onboarding screen header elements are located within status bar (Android)
https://github.com/status-im/status-mobile/pull/15467#issuecomment-1488854991

**ISSUE 3** Navigation bar changes mode from dark to light after opening bottom sheet
https://github.com/status-im/status-mobile/pull/15467#issuecomment-1488855314

**ISSUE 6** Status bar elements' color is merged with the background throughout the bottom tabs (IOS)
https://github.com/status-im/status-mobile/pull/15467#issuecomment-1488855926 

And also I guess re-test release from scratch (+2 days)
I don't think it is a good idea for now

**Comment by Parveshdhull** [comment] 2023-04-04 16:50
> And also I guess re-test release from scratch (+2 days)
> Not sure it's worth it.

Yes, doesn't look good.

**Comment by Parveshdhull** [comment] 2023-04-04 16:51
So, I guess we can fix https://github.com/status-im/status-mobile/issues/15560 using release as base and use that directly in release branch.
@OmarBasem Please can you look into this

**Comment by OmarBasem** [comment] 2023-04-04 16:58
@Parveshdhull I am looking into it right now 👍

**Comment by OmarBasem** [comment] 2023-04-04 17:28
Thanks for your input everyone. Pushed a PR: https://github.com/status-im/status-mobile/pull/15576

**Closed as completed** 2023-04-06 09:16 UTC
