### ISSUE TITLE
Blur appearance changes underneath the overlay [Android]

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19283] opened 2024-03-15 13:32 UTC
# Design Feedback 2.27

## [Android] Blur appearance changes underneath the overlay
Blur appearance of buttons and top nav changes when dark overlay is present.
[tracked here: status-im/status-mobile/issues/19228]

Instances where the issue was encountered:

- **1:1 chat** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#729037380)] top nav blur changes when the pinned message drawer is opened

<img width="393" alt="Screenshot 2024-03-15 alle 14 27 25" src="https://github.com/status-im/status-mobile/assets/122543089/bfca58b1-f87d-40c1-be5f-b698bbe9c6aa">

- **Community** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=4:111403&mode=design#737013399)] top nav button blur changes when the authentication drawer is opened

<img width="393" alt="Screenshot 2024-03-15 alle 14 29 16" src="https://github.com/status-im/status-mobile/assets/122543089/c0626846-72ce-4c2f-8ac7-d38bc16b435f">

>
#### Expected behavior
<img width="375" alt="Screenshot 2024-03-15 alle 14 30 25" src="https://github.com/status-im/status-mobile/assets/122543089/e2e83c46-37e8-4a35-8077-80fb92380984">

<img width="375" alt="Screenshot 2024-03-15 alle 14 31 07" src="https://github.com/status-im/status-mobile/assets/122543089/58416d2c-fdbc-4408-a640-67709041ee2c">

### Reproduction

1. Open a chat or a community
2. Open a drawer that will apply the dark overlay on the screen

### Additional Information

- Status version: nightly 
- Operating System: Android 8.1

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment] 2024-06-12 13:57
@flexsurfer we can close this issue now? 🤔

**Comment by ilmotta** [comment] 2024-11-04 22:12
I'm closing the issue because I can't reproduce the problem anymore. Feel free to reopen if it's still relevant.

**Closed as completed by ilmotta** 2024-11-04 22:12 UTC
Labels: android, mobile-core, design-feedback
