### ISSUE TITLE
 [Android] The QR code is shown as enabled after the device comes back from the background mode (reproduced in 50% of cases)

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15672] opened 2023-04-17 18:48 UTC
Follow up for https://github.com/status-im/status-mobile/pull/15584#issuecomment-1511508474

#### Steps to reproduce:
1. Generate a QR code
2. Send device into the sleeping mode or background
3. Come back from the sleeping mode/background

#### Actual result:
 The QR code is still shown as enabled after the device comes back from the background

https://user-images.githubusercontent.com/52490791/232582286-85221bec-fef7-4eae-9dfc-b88826349a9e.mp4

#### Expected result:
The QR code is disabled after the device comes back from the background or sleep mode
![image](https://user-images.githubusercontent.com/52490791/232582354-234373fe-7260-48c6-bd09-2542ac4301c8.png)

#### Device:
- Any android

**Comment by cammellos** [comment] 2023-07-14 13:08
is this still an issue @siddarthkay ? closing for now, feel free to reopen if necessary

**Closed as not planned by cammellos** 2023-07-14 13:08 UTC

**Comment by siddarthkay** [comment] 2023-07-14 13:39
@smohamedjavid can confirm

**Comment by smohamedjavid** [comment] 2023-07-24 17:08
@siddarthkay - From design expectation, We should reset the page when the app goes into the background or sleep mode.

Since this issue is reproduced only in 50% of cases and is a low priority, feel free to make a decision.

CC: @J-Son89
