### ISSUE TITLE
eq() not a number: null error when the app is running in emulator on background 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#20625] opened 2024-07-02 13:02 UTC
# Bug Report

## Problem 
I left my Android 14 emulator running on the background for the night, the app was open on the emulator for the whole time. When I click the emulator next time (after 15 hours approximately) I got this error 

#### Expected behavior
No error

#### Actual behavior
<img width="350" alt="Screenshot 2024-07-02 at 15 05 27" src="https://github.com/status-im/status-mobile/assets/29711298/8bf974ab-530d-47ef-b460-d14f9452c66d">

### Reproduction

1. Create an account or login
2. Leave the app running

### Additional Information

- Status version: nightly e2e
- Operating System: Android

Logs: 

[logcat_error.log](https://github.com/user-attachments/files/16068629/logcat_error.log)

**Comment by Parveshdhull** [comment] 2024-07-02 14:50
I think issue already fixed in https://github.com/status-im/status-mobile/pull/20614
cc @ilmotta

**Comment by ilmotta** [comment] 2024-07-02 15:46
@Parveshdhull is right, this is likely fixed since yesterday (end of the day at the positive GMT side of the world).

**Comment by Parveshdhull** [comment] 2024-07-03 07:33
Closing the issue, please feel free to reopen if still reproducible.

**Closed as completed by Parveshdhull** 2024-07-03 07:33 UTC
Labels: android, no-steps
