### ISSUE TITLE
 Emoji icon is shown instead of cross (x) at the end of the input field for commands (Android only)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1941] opened 2017-09-27 09:00 UTC
### Description

*Type*: Bug

*Summary*:  "emoji" icon is shown instead of cross icon (x) at the end of the input field, so user can't delete the selected command. It was possible in 0.9.10 on Android and it's possible now on the same version on iOS.

#### Expected behavior
cross icon is shown so it's possible to delete a command in the input field
![30444170-adecd5d2-998a-11e7-9f55-114ef92dc5e3](https://user-images.githubusercontent.com/6584810/30904683-5615c134-a37b-11e7-9b22-cd83d049fde2.jpg)

#### Actual behavior
1. emoji icon is shown
2. if tap on emoji icon then command is deleted 
![30444123-85cd1b34-998a-11e7-9cdc-b2e67dc64d62](https://user-images.githubusercontent.com/6584810/30904655-44825d9c-a37b-11e7-8335-3db72591e627.png)
### Reproduction

- open console
- tap on any command (browse, /phone, /location, /debug...)
- check that input field shows "x" at the end and if tap on "x" then command and all typed text is deleted (currently, there is no "x" but emoji is shown instead)

### Additional Information
* Status version: release candidate 0.9.11  and develop builds
* Operating System: 
Can reproduce on real device Samsung Galaxy S6, Android 6.0.1 and on avd emulator Nexus 5, API 23.

**Comment by annadanchenko** [comment] 2017-09-30 10:32
verified ok on release 0.9.11 build 0.9.10-120-g971d1104

**Comment by asemiankevich** [comment] 2017-10-03 14:47
I can't reproduce it in ` 0.9.10-159-g4b6f920e+ (1716)`, closing

**Closed as completed by asemiankevich** 2017-10-03 14:47 UTC
Labels: Tested - OK
