### ISSUE TITLE
Frequently see 'Error connecting to mail server'

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#7488] opened 2019-02-13 08:06 UTC
# Problem

I often see 'Error connecting to mail server' when opening the app.

# Implementation

Not sure, but:

1) Fix underlying problem
2) Automatically pick new mailserver for me

# Acceptance Criteria

Less manual action when opening app.

# Notes

I searched for 'error connecting to mailserver' in issues and couldn't find any duplicate issues.

Using Status nightly, mail-0{1,3}.do-ams3.eth.beta, recent nightly. 4G, good connection.

# Future Steps

Data sync layer and incentivization work work should make this problem go away, as one connection dying shouldn't been disruptive.

**Comment by mandrigin** [comment] 2019-02-14 08:21
the initial issue and investigation: https://github.com/status-im/status-react/issues/7376

long story short: peers (public keys) get stuck on our mailserver side. if that happens, this peer can never connect to the same mailserver again.

(1) we added a dialog on status-react side to try to choose another mailserver
(2) we added monitoring of stale peers on the server side
(3) [wip] adding more logs to mailserver figure out where exactly it fails, current devp2p logs are less than useful there
(4) [plan] find a workaround (idk, force-remove this peer, or something)
(5) [plan] figure out the real issue

**Comment by oskarth** [comment] 2019-02-19 04:25
Any update on this? Considering how disruptive this it seems like fairly high priority.

It also seems likely connected to number of connections, considering how it behaved around Ethdenver. Has this hypothesis been tested? Do we have graphs for how many peers are dropped etc? Would be great to see them pasted in this issue if so, or a link to other relevant issues. cc @adambabik @jakubgs

**Comment by StatusSceptre** [comment] 2019-02-19 04:37
This issue persisted all weekend at ETHDenver with no real relief. This was between multiple WiFi connections, and seemed only a little better on cellular but not enough to have an meaningful conversations.

I got pinged by our own team on telegram Saturday because they didn’t get my status messages, wasn’t cool.

**Comment by mandrigin** [comment] 2019-02-19 09:17
update on this issue

(1) we added a dialog on status-react side to try to choose another mailserver
(2) we added monitoring of stale peers on the server side
(3) adding more logs to mailserver figure out where exactly it fails, current devp2p logs are less than useful there
(4) find a workaround (idk, force-remove this peer, or something)
**---> WE ARE HERE <----**
(4.5) make sure that the workaround is working
(5) [wip] figure out the real issue

**Comment by mandrigin** [comment] 2019-02-19 09:21
Some of my thoughts:
- it might be related to the load of the wifi on EthDenver, this "stale peers" issue seems to reproduce much more frequently when a connection is either slow or a bit flaky (also explains why 3G might made it better).
- the clean-up script runs 1 time per 1 minute (which looks like not enough), so if your peer got stuck on the mailserver it is around 1 min until you can reconnect again.

**Comment by mandrigin** [comment] 2019-02-19 09:25
@adambabik had some ideas about the root cause too, he was investigating that.

**Comment by mandrigin** [comment] 2019-02-19 09:26
also, pivotal story: https://www.pivotaltracker.com/story/show/163752166

<blockquote><div><strong><a href="https://www.pivotaltracker.com/story/show/163752166">Mailservers don't remove disconnected peers sometimes making it impossible to connect again - Pivotal Tracker</a></strong></div></blockquote>

**Comment by adambabik** [comment] 2019-02-19 12:21
I was chasing a case where the TCP conn is half-open and the mail server never tries to send anything through the wire which I guess would keep the conn help-open for unbounded periods of time. This is not a case because there is [this `pingLoop()`](https://github.com/status-im/go-ethereum/blob/master/p2p/peer.go#L206) which does send messages every few seconds.

I was also checking `MsgPipeRW` but it also looks fine.

So back to square one... We are trying to analyze logs one more time in order to confirm for 100% that the problem is in `p2p.Server.runPeer()` and `p2p.Peer.run()` methods.

**Comment by mandrigin** [comment] 2019-02-19 15:15
A bit of history of this issue (if it helps someone)

so basicall, the story
(1) Anna had an Android device that wasn't able to connect to some mailservers (like never able to), Sergey had the same issue as well (with diferent mailserver)
(2) We thought that it is an issue on a mobile-app side, so I started debugging (turned out that one of the test accounts on my test Pixel also can't connect to one of the mailservers.
(3) I found that there is a log entry "error: already connected" in logcat, so I tried to take a look at that, grep-ed the code, found this string and changed it to already connected from local to make sure that that is the right place
(4) I updated status-go with the new string, but still got "error: already connected"(the old string) in the log
(5) So, I found the code that reads the error from the other peer and deserializes it. When it is converted to a string (reason) I added arbitrary suffix ++ there, to check if that is where this error comes from.
(6) yes, I got "error: already connected++"(the patched string) in the log, so the error came from the mailserver
(7) the only place where this error comes from is when you do a handshake with a peer that is already in server.peers in p2p module.
(8) I suggested to restart the mailserver that I couldn't connect to to validate. After restart it connected just fine.
(9) we restarted all the mailservers and Anna's and Sergey's issues were gone.

*I was a bit busy, so between (2) and (7) around 2 days passed

**Comment by mandrigin** [comment] 2019-02-19 16:06
I just did a live debugging session with @pablanopete.

It looks like we show this "error/retry" dialog erroneously if a server takes too long to connect or something.

So, in his case.
He starts the app, it connects to a mailserver (shows the gray "Connecting..." label). Then he gets "Error when connecting to the mailserver" dialog, but **behind** this dialog everything connects just fine.

Logs in Kibana support that too:
<img width="927" alt="discover - kibana 2019-02-19 17-02-18" src="https://user-images.githubusercontent.com/466427/53029087-7a067f00-3468-11e9-9165-ffbb887b1ca5.png">


So maybe quite a bit of complains on ETHDenver (and @oskarth's subpar experience) were because of that.

@annadanchenko can you make an issue for that, **showing this dialog in most case is a UI bug**.


Here we can continue tracking stale peers down.

**Comment by mandrigin** [comment] 2019-02-19 16:07
cc @jarradh @naghdy (see my comment before this one) because it looks like you are affected as well.

**Comment by annadanchenko** [comment] 2019-02-19 17:04
> @annadanchenko can you make an issue for that, **showing this dialog in most case is a UI bug**.

added https://github.com/status-im/status-react/issues/7531 but will need some time to find the way to reproduce

**Comment by mandrigin** [comment] 2019-02-19 18:40
server-side progress.

there is an actual deadlock, it is confirmed, but we aren't 100% sure where

a watchdog was added there, it will set a timeout for the deadlock, but will will still leak some RAM (but we won't leak peers): https://github.com/status-im/status-go/commit/e5abd9eff88890352629bf3c9d45b0e3f4feba1b

also, additional logs to figure out what exactly deadlocks

**Comment by mandrigin** [comment] 2019-02-19 19:09
so, Whisper deadlocks causing devp2p to deadlock. solid.

**Comment by mandrigin** [comment] 2019-02-19 19:36
leak prevention watchdog logs: https://kibana.status.im/goto/0da41dda8fdecf9470b02351bfc7f7e6

<blockquote><div><strong><a href="https://kibana.status.im/goto/0da41dda8fdecf9470b02351bfc7f7e6">Sign In</a></strong></div></blockquote>

**Comment by mandrigin** [comment] 2019-02-19 19:38
okay, issue number 3 there is that sometimes I actually can't connect to a mailserver unless I tap "Retry" a few times... I can't see my pubkey in the mailserver logs as well.

**Comment by mandrigin** [comment] 2019-02-19 19:38
(cc @annadanchenko)

**Comment by mandrigin** [comment] 2019-02-20 16:27
okay, status for tonight:

(1) Whisper deadlock is mitigated and deployed to mailservers (https://github.com/status-im/status-go/commit/e5abd9eff88890352629bf3c9d45b0e3f4feba1b), but we still will need to fix it properly (Adam is working on it, here: https://github.com/status-im/status-go/commit/339a68b52b03aa6481f6ec3d3ad84b1234734f6b)

(2) The UI issue looks like a status-go + status-react issue, one will be fixed when we update status-go (it is already merged: https://github.com/status-im/status-go/pull/1383). @cammellos so 3 retries before showing a dialog, is that something that you will work on?

(3) Not even attempting to connect is still TBD, but let's see how other fixes will affect it.

**Comment by cammellos** [comment] 2019-02-20 16:52
@mandrigin yes, I will be working on it

**Comment by mandrigin** [comment] 2019-02-20 16:53
Thanks!

**Comment by adambabik** [comment] 2019-02-20 22:34
My fix is ready: https://github.com/status-im/status-go/tree/experiment/magic-peers (https://github.com/status-im/status-go/commit/339a68b52b03aa6481f6ec3d3ad84b1234734f6b, https://github.com/status-im/status-go/commit/617672a03ced672e7dd205a6df9be527e4f26bdc). 

I would like to sync with you @mandrigin and @jakubgs tomorrow in the morning to deploy it and confirm that it fixes the issue. After that, I guess we will cherry pick these commits to a fresh branch from develop and merge it.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by mandrigin** [comment] 2019-02-21 16:06
(1) so the fix is deployed and get got one hour with no stale peers at least

**Comment by mandrigin** [comment] 2019-02-21 16:10
(2) is https://github.com/status-im/status-react/pull/7543

**Comment by cammellos** [comment] 2019-02-21 16:11
there's also https://github.com/status-im/status-react/pull/7543 , another issue that I discovered today is that as soon as we go offline (disconnect from wifi) the pop up will be displayed, not sure whether that should be the case, maybe if we know we are offline, we should not show the pop up, and just try to reconnect automatically ? ( if we are online and it fails, then it's ok to show the pop up)

**Comment by mandrigin** [comment] 2019-02-21 16:12
yeah, offline should probably be treated separately

**Comment by cammellos** [comment] 2019-02-21 16:12
also that only happens for people that have actually selected a mailserver, new accounts should not see the pop up as the mailserver is changed automatically

**Comment by mandrigin** [comment] 2019-02-21 17:03
<img width="708" alt="discover - kibana 2019-02-21 18-02-03" src="https://user-images.githubusercontent.com/466427/53187209-f3d27000-3602-11e9-806b-ce0790af7b69.png">
looks like the fix works

**Comment by mandrigin** [comment] 2019-02-22 14:16
So we are going to release a new version soon to address the UI bugs. If everything goes as planned — next week.

**Comment by mandrigin** [comment] 2019-02-26 14:54
I guess everything that was there is fixed on `develop` branch and we are release testing new version here: https://github.com/status-im/status-react/issues/7566

closing this issue

**Closed as completed by mandrigin** 2019-02-26 14:54 UTC
