### ISSUE TITLE
Red line above profile picture and below Testnet mode banner appears when user reopens app from the background 

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19490] opened 2024-04-03 09:43 UTC
# Bug Report
followup https://github.com/status-im/status-mobile/pull/19348

## Problem 
[comment]: # (A problem description)

#### Expected behavior
No red line

#### Actual behavior
Red line above profile picture and below Testnet mode banner appears when user reopens app from the background 

https://github.com/status-im/status-mobile/assets/147824399/bf77d81c-4339-4d56-94ad-b46780c742d4

### Reproduction

1. Install app
2. Turn on Testnet mode and make sure banner appeared 
3. Minimize the app
4. Return app from the background

### Additional Information

- Status version: PR https://github.com/status-im/status-mobile/pull/19348
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment] 2024-04-03 10:20
Hi @mariia-skrypnyk, Thank you for reporting this issue. Please can you confirm if issue also exists in Android and if possible please attach an video. (I am currently not able to reproduce this issue in android)

**Comment by Parveshdhull** [comment] 2024-04-03 11:08
Tried reproducing in ios simulator, and red line flicker visible. So it seems it is os specific and might be library issue.

**Comment by Parveshdhull** [comment] 2024-04-03 11:30
fixed in https://github.com/status-im/status-mobile/pull/19495

**Comment by mariia-skrypnyk** [comment] 2024-04-04 15:13
Hi @Parveshdhull !

Thanks for your investigation!
Yes, it was iOS specific.
Will check fix when it will be ready.

**Comment by Parveshdhull** [comment] 2024-04-04 15:57
> Will check fix when it will be ready.

Thank you, fix is ready

**Closed as completed** 2024-04-10 15:46 UTC
