### ISSUE TITLE
Add form validation 

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#5570] opened 2018-08-20 23:52 UTC
### User Story

As a user, I want to be properly notified about possible errors while filling in forms, so I can properly use Status desktop.

### Description
*Type*: Feature

*Summary*: 
There are different instances where the user needs to fill in information that we need to validate.
Instances:
- Onboarding (sign in/sign up/recover account)
- New 1:1 chat > contact code
- New public chat > topic name

*Pre-conditions*:
In order to validate forms for onboarding, #4418 needs to be implemented first.

#### Expected behavior
When the user fills in a form with information, we need to validate it -when possible- inline.

#### Actual behavior
Validation is not consistent yet. Examples:
<img width="656" alt="captura de pantalla 2018-08-20 a la s 8 47 21 p m" src="https://user-images.githubusercontent.com/37297779/44372466-629b0900-a4ba-11e8-939e-747e96c6bf97.png">
Contact code format is not validated.

<img width="663" alt="captura de pantalla 2018-08-20 a la s 8 47 53 p m" src="https://user-images.githubusercontent.com/37297779/44372479-72b2e880-a4ba-11e8-9fb3-e1c574294a8a.png">
Wrong topic name format doesn't explain why the button is disabled.

### Reproduction
- Open Status
- Click on "+" button to start a new chat
- Write a contact code with an invalid format (anything that doesn't start with 0x...) or write a topic name with special characters.

### Solution
Design and cases here >> zpl.io/bAEEv3B (Zeplin, needs permissions)
Example:
<img width="822" alt="captura de pantalla 2018-08-20 a la s 8 52 44 p m" src="https://user-images.githubusercontent.com/37297779/44372593-0be1ff00-a4bb-11e8-88a4-c3b5ff3acc18.png">

**Comment by churik** [comment] 2018-08-21 07:54
closed as duplicate of https://github.com/status-im/status-react/issues/5117. Solution was added to 
https://github.com/status-im/status-react/issues/5117.

**Closed as completed by churik** 2018-08-21 07:54 UTC

**Comment by EugeOrtiz** [comment] 2018-08-21 13:20
@churik Ok, we need to make sure to replicate the same issue when sign in/up flows get implemented.
