### ISSUE TITLE
Unable to swipe between tabs in the Activity Center; Tabs disappear after notifications are read/unread.

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19000] opened 2024-02-26 14:50 UTC
### Steps:
1. Open Activity Center (AC)
2. Select the last tab
3. Reopen AC
4. Attempt to swipe previous tabs 
5. Mark as read the notifications

### Actual result:
- In step 4: Only the last tab is shown in the AC, and the user is unable to select other previous tabs from the AC.

https://github.com/status-im/status-mobile/assets/52490791/917722a2-9e04-415c-9566-cf1177fc96ce

- In step 5: The tabs disappear in the AC after some messages are marked as read/unread.

https://github.com/status-im/status-mobile/assets/52490791/026ab2b2-daa2-483f-b0ee-1094a6fba321

### Expected result:
- The user should be able to swipe between tabs and select other tabs in the AC.
- The tabs within AC are not disappear after the messages are marked as read/unread

### Additional info:
The same issue occurs when other tabs are selected and the app is reopened. However, after swiping right and left, the previous tabs can be selected

### ENV:
Nightly [26 Feb 2024]

**Comment by ajayesivan** [comment] 2024-02-28 09:13
The tab scroll issue is caused by using [`initial-scroll-index` ](https://reactnative.dev/docs/0.72/virtualizedlist#initialscrollindex)without implementing the `get-item-layout` function. This could have been easily fixed by implementing the get-item-layout function, but in this case, the width(horizontal list) of each item cannot be calculated beforehand because it depends on the tab title and can only be calculated on render using `on-layout`.


https://github.com/status-im/status-mobile/blob/7171c7085dc04315c315652af27fe5053c56bbfe/src/quo/components/tabs/tabs/view.cljs#L161-L162

**Comment by ajayesivan** [comment] 2024-02-28 09:18
Instead of setting `initial-scroll-index`, I tried using the `scrollToIndex` function, which solves the original bug but only works 80% of the time and fails randomly. Sometimes, the scroll position is slightly off.

**Comment by ajayesivan** [comment] 2024-02-28 09:21
I was able to fix the bug by using `ScrollView` instead of `FlatList`. However, the correct solution should involve using `FlatList` and `initial-scroll-index`. Yet, I'm not sure how we can implement it with a list of items of random sizes. I'll check with the team before moving forward.

**Comment by ajayesivan** [comment] 2024-02-28 09:35
> Instead of setting `initial-scroll-index`, I tried using the `scrollToIndex` function, which solves the original bug but only works 80% of the time and fails randomly. Sometimes, the scroll position is slightly off.

With a `50ms` timeout, this solution seems to be working perfectly. I will test it on Android as well, and if it works there too, I will raise a PR and gather feedback.

**Closed as completed** 2024-03-20 15:37 UTC
Labels: chat
