### ISSUE TITLE
"Error when connecting to the mailserver" is shown when connection is successful 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7531] opened 2019-02-19 17:03 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: while investigating #7488 it was found that in some cases "Error when connecting to the mailserver" is shown when connection is successful: https://github.com/status-im/status-react/issues/7488#issuecomment-465194775

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
If app is connected to mailserver then no error should be shown
#### Actual behavior
[comment]: # (Describe what actually happened.)
"Error when connecting to the mailserver"  is shown even after connection was successful
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.33

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by cammellos** [comment] 2019-02-19 17:53
I think I know what's going on, @annadanchenko if you have logs it would be helpful, can't replicate but by looking at the code there's something a bit odd.

**Comment by annadanchenko** [comment] 2019-02-19 18:11
@cammellos I have no logs yet, maybe @mandrigin has some extra info as this issue was created as a result of his investigation with @pablanopete

**Comment by mandrigin** [comment] 2019-02-20 16:21
so here we will update status-go, it looks like the issue was on it's side

**Comment by mandrigin** [comment] 2019-02-20 16:21
see this PR: https://github.com/status-im/status-go/pull/1383

**Comment by mandrigin** [comment] 2019-02-26 17:42
@annadanchenko I think it is fixed in 0.10.0 release branch, right?

**Comment by mandrigin** [comment] 2019-02-27 14:36
cannot reproduce it on iPhone XS (iOS 12), 0.10.0 RC, closing.
feel free to reopen if you will be able to reproduce it.

**Closed as completed by mandrigin** 2019-02-27 14:36 UTC
