### ISSUE TITLE
After upgrade from 1.4.1 to Nightly 31/07/20 all chat history is empty

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11023] opened 2020-07-31 10:25 UTC
# Bug Report

## Problem

If upgrade the app from 1.4.1 to nightly 31/07/20, chat list will be saved, message previews in chat list will be shown, but after opening any chat history will be empty.

#### Expected behavior

chat history is preserved

#### Actual behavior

![ezgif com-resize (10)](https://user-images.githubusercontent.com/67952253/89025548-56b35500-d327-11ea-8692-66feeb13092f.gif)

### Reproduction

- Install Release build
- Log in
- Home -> + -> Join all types of chats 
- Send several messages of different types to every chat

- Install Nightly 31/07/20
- Log in
- Open chats to check message history 

### Additional Information

- Status version: Release 1.4.1; Nightly 31/07
- Operating System: Android 10

### Logs

[Status.log](https://github.com/status-im/status-react/files/5006594/Status.log)

сс @hesterbruikman

**Comment by hesterbruikman** [comment] 2020-07-31 11:10
Can't reproduce on Fairphone 2, Android 7. @cammellos any luck?

**Comment by cammellos** [comment] 2020-07-31 11:10
haven't started :)

**Comment by hesterbruikman** [comment] 2020-07-31 11:18
Sorry, it's clear on the issue, messages are visible in chat list, not in chat view. Can reproduce on Android 7 and 9

**Comment by churik** [comment] 2020-07-31 11:54
Fixed in https://github.com/status-im/status-react/pull/10912

**Closed as completed by churik** 2020-07-31 11:54 UTC

**Comment by hesterbruikman** [comment] 2020-08-03 10:06
Believe this was fixed in Emoji PR https://discordapp.com/channels/624205794384281629/626738033701683200/738718878791761951

@qoqobolo can we close the issue or do you want to confirm on release?
