### ISSUE TITLE
Empty 'Seed phrase' on screen when generate new account from keycard starting from 'Recover from keycard'

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9676] opened 2019-12-17 14:56 UTC
# Bug Report

## Problem

There are two paths to generate new account from keycard now: starting from `Get started` -> `Generate new key` OR `Access key` -> `Recover with keycard`

If to follow `Access key` -> `Recover with keycard` way at the point of when we display `Seed phrase` to remember - there are no words for seed phrase.

#### Expected behavior

Seed phrase displayed when generating new account with keycard via `Access key` -> `Recover with keycard` flow
#### Actual behavior
No seed phrase displayed when generating new account with keycard via `Access key` -> `Recover with keycard` flow

### Reproduction

- Open Status
- Tap `Access key` -> `Recover with keycard` -> `Begin recovery`
- Hold keycard to the back of you device
Result: `There is nothing to recover here`  view with `Generate an new key` button
- Tap `Generate an new key` -> `Begin setup` and hold card to the back of phone
- Enter 6-digit PIN
- Confirm 6-digit PIN
- Tap Next on PUK/Pair codes screen
**Actual result:** 
<img width="291" alt="Screenshot 2019-12-17 at 16 52 33" src="https://user-images.githubusercontent.com/8749671/71006222-aa04ca00-20ed-11ea-902c-1d7aee2d3657.png">

### Additional Information

- Status version: develop 2019121702
- Operating System: Android

**Comment by Serhy** [comment] 2019-12-17 15:04
cc @rachelhamlin @guylouis 
Including in V1 scope because it's high probability to start keycard pairing from `Access key `-> `Recover with keycard` (maybe even it's higher chance to start with keycard from this flow versus Generate new key where keycard option is somewhere in the middle of flow)

**Comment by guylouis** [comment] 2019-12-17 18:57
Thanks for raising this point, and congrats for spotting this! 
 You're right that this in the design it's a corner case, but user might actually often go through it since the difference in menaing between "generate a key" and "access key" is not 100% obvious for new users

**Comment by guylouis** [comment] 2020-02-10 12:44
reproduced on nightly from 06/02/2020
interestingly also, when going through this flow the user is not prompted to chose his 3 names
is there any issue with how the different part of the code is branched in this particular flow ? 

This issue only happens when a user generates  a new account starting from the 'recover from keycard' option and taps an empty keycard.
There is no issue when a user generates a new account starting from the loginscreen/.../generate a new key or startup onboarding screen/get started/generate keys

**Comment by rachelhamlin** [comment] 2020-02-11 09:11
I'm going to add the blocker label to anything that should be fixed before keycard is released - feel free to disable @guylouis.

**Comment by Ferossgp** [comment] 2020-02-18 14:36
The problem is that the step of generating the key is skipped and the phrase does not exist. This happens because the flow now goes like that:
![before 001](https://user-images.githubusercontent.com/5794620/74745280-b4218100-5274-11ea-989c-1a8e1e68ba51.jpeg)

Updating it to that will solve the problem cause it allows user to generate keys (Reuses the onboarding flow):
![after 001](https://user-images.githubusercontent.com/5794620/74745392-e337f280-5274-11ea-85bb-a3650c7ca89c.jpeg)
 
What do you think @guylouis ?

**Comment by guylouis** [comment] 2020-02-18 15:04
@Ferossgp I agree it's the most natural and best way to go !

**Closed as completed** 2020-03-11 14:21 UTC
