### ISSUE TITLE
Sometimes sender's contact request remains in pending state despite receiver has accepted it

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21371] opened 2024-10-03 08:10 UTC
Bug is not reproducible every time. Might be Waku issue. 

**Steps:** 

1. User A sends contact request to User B
2. User B receives and accepts contact request
3. See if request status is changed from Pending to Accepted for User A and User B appears as his contact

**Actual result:** Request remains in Pending state. User B does not appear as contact for User A despite request has been accepted. 

[User_A_request_sender.zip](https://github.com/user-attachments/files/17241224/User_A_request_sender.zip)
[User_B_request_receiver.zip](https://github.com/user-attachments/files/17241225/User_B_request_receiver.zip)

![photo_2024-10-03 11 09 22](https://github.com/user-attachments/assets/9ca8f4db-8911-4861-bbcb-664b5c3c2201)

- Status version: nightly 
- Operating System: Android, iOS

**Comment by chaitanyaprem** [comment] 2024-10-07 06:30
this has been noticed multiple times recently in various tests. i think the source of the issue is something else because for some reason only the mobile instance is only connected to store nodes and not any bootstrap nodes (which then causes further issues because since there are peers available the node thinks it is online but peerexchange, lightpush and filter protocols won't work since there are no peers supporting those protocols) 
similar issue noticed here https://github.com/status-im/status-go/issues/5679 where there is DNS failure. this leads to only store nodes being connected which doesn't have peer-exchange enabled hence leading to failure of filter,lightpush and peerexchange client side protocols leading to reliability issues. 

the logs that we are observing are side-effect of the issue which is somewhere i am suspecting is somewhere else in status-go code. Probable suspect is how the bootstrap nodes are set or something in the waku initialization sequence of status-go  is failing and causing no other peers to be connected.



https://github.com/status-im/status-mobile/pull/21386 is the mobile PR that reduces log flooding and might provide some useful logs to help root-cause the issue i.e why node is able to connect to store nodes but no other bootstrap nodes.

**Comment by pavloburykh** [comment] 2024-10-07 08:11
> [#21386](https://github.com/status-im/status-mobile/pull/21386) is the mobile PR that reduces log flooding and might provide some useful logs to help root-cause the issue i.e why node is able to connect to store nodes but no other bootstrap nodes.

Thank you @chaitanyaprem! I have triggered e2e in this PR and faced the issue. I have attached logs in this comment, please take a look https://github.com/status-im/status-mobile/pull/21386#issuecomment-2396211602

**Comment by churik** [comment] 2024-10-17 15:21
allegedly fixed in https://github.com/status-im/status-go/pull/5785

**Closed as completed by churik** 2024-10-17 15:21 UTC
Labels: waku, re-check, mobile-core
