### ISSUE TITLE
Android build crashes after launch with Java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#10433] opened 2020-04-24 15:24 UTC
# Bug Report

## Problem

Right after start Android builds crashes with 
<img width="338" alt="Screenshot 2020-04-24 at 18 01 41" src="https://user-images.githubusercontent.com/8749671/80229116-a1527080-8658-11ea-8ed3-442ae496a91c.png">

Apparently after changes https://github.com/status-im/status-react/pull/10420

**Comment by jakubgs** [comment] 2020-04-24 17:28
Testing a revert here: c305b24c99f09929fc64582cf90976c8942097e9
https://ci.status.im/job/status-react/job/manual/667/

**Comment by jakubgs** [comment] 2020-04-24 17:42
Nope, looks like issue was caused by: 548fe04f54fe6d6b572dd8ecbbf6de88227f68d1
Testing revert: 5c43eddc3b347b0fb7ac02f4f6c913a731fb6a7c
https://ci.status.im/job/status-react/job/combined/job/mobile-android/12588/

**Comment by jakubgs** [comment] 2020-04-24 18:32
Fixed with https://github.com/status-im/status-react/commit/439643daa4ed9f1d8ee0662141d73818ea474a55.
Build: https://ci.status.im/job/status-react/job/manual/669/

**Closed as completed by jakubgs** 2020-04-24 18:33 UTC
