### ISSUE TITLE
Error null is not an object (evaluating 'a.cljs$core$IFn$_invoke$arity$1') when multitapping Sign In

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4105] opened 2018-05-04 11:01 UTC
### Description

*Type*: Bug

*Summary*: `null is not an object (evaluating 'a.cljs$core$IFn$_invoke$arity$1')` when i tap `Sign in` several times (6 in my case) while recovering account

#### Expected behavior
no errors 

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/39624883-a3929fe8-4fa3-11e8-820b-eeb25c06d0da.png)

### Reproduction

- Open Status
- Enter passphrase and password
- Tap `Sign in` 6 times while app is signing you in

### Additional Information
* Status version: nightly
* Operating System: Android

#### Logs
`01:01 I/ReactNativeJS: NAME: "TypeError"
01:01 I/ReactNativeJS: MESSAGE: null is not an object (evaluating 'a.cljs$core$IFn$_invoke$arity$1')
01:01 I/ReactNativeJS: 
01:01 I/ReactNativeJS: index.android.bundle:12:6925045
01:01 I/ReactNativeJS: index.android.bundle:12:3977649
01:01 I/ReactNativeJS: index.android.bundle:12:3977662
01:01 I/ReactNativeJS: invoke_interceptor_fn@index.android.bundle:12:3903000
01:01 I/ReactNativeJS: invoke_interceptors@index.android.bundle:12:3903301
01:01 I/ReactNativeJS: execute@index.android.bundle:12:3905750
01:01 I/ReactNativeJS: handle@index.android.bundle:12:3914163
01:01 I/ReactNativeJS: re_frame$router$IEventQueue$_process_1st_event_in_queue$arity$1@index.android.bundle:12:3948712
01:01 I/ReactNativeJS: re_frame$router$IEventQueue$_run_queue$arity$1@index.android.bundle:12:3931051
01:01 I/ReactNativeJS: index.android.bundle:12:3936803
01:01 I/ReactNativeJS: re_frame$router$IEventQueue$_fsm_trigger$arity$3@index.android.bundle:12:3941014
01:01 I/ReactNativeJS: index.android.bundle:12:3933569
01:01 I/ReactNativeJS: index.android.bundle:32:1369
01:01 I/ReactNativeJS: x@index.android.bundle:32:643
01:01 I/ReactNativeJS: callTimers@index.android.bundle:32:2788
01:01 I/ReactNativeJS: value@index.android.bundle:27:3582
01:01 I/ReactNativeJS: index.android.bundle:27:1067
01:01 I/ReactNativeJS: value@index.android.bundle:27:3009
01:01 I/ReactNativeJS: value@index.android.bundle:27:1039
01:01 I/ReactNativeJS: [native code]
01:01 I/ReactNativeJS: `

**Comment by annadanchenko** [comment] 2018-05-06 16:21
can't reproduce on nightly from May 6, build 366. Tried 2 ways:
1. install app, recover account when no other accounts are available yet
2. recover account when 1 account is already present and was used.

**Comment by asemiankevich** [comment] 2018-05-07 09:24
I can repro it in nightly 367 : this bug is reproducible when i multitap `sign in` while i am actually being signed in after i entered passphrase and password. however error is different

![image](https://user-images.githubusercontent.com/28752642/39695010-d47e4bac-51f1-11e8-88d5-28befad34aa9.png)

![image](https://user-images.githubusercontent.com/28752642/39695072-0447acd4-51f2-11e8-8041-b65387e293de.png)


https://app.testfairy.com/projects/4803622-status/builds/8233339/sessions/42/?accessToken=YKF9tviFJhydE1/wuGk0QAJuaDM

**Comment by lukaszfryc** [comment] 2018-05-10 16:12
I've just had it on nightly (May 10) on Android when I had one account and tried to recover another one. After tapping sign in (I tapped once) the error appeared. When I pressed OK the dialog was closed and account was recovered.

**Comment by churik** [comment] 2018-05-18 09:14
Reproducible on nightly (May 18) - Android when I  recovered account. After tapping sign in (I tapped two times) the error appeared. When I pressed OK the dialog was closed and account was recovered.

**Comment by lukaszfryc** [comment] 2018-05-31 07:16
Fixed by https://github.com/status-im/status-react/issues/4127

**Closed as completed by lukaszfryc** 2018-05-31 07:16 UTC
