### ISSUE TITLE
[IOS] App crashes during onboarding

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19787] opened 2024-04-24 14:56 UTC
### Steps:
1. Onboard after app installing

### Actual result:
App is crashed

https://github.com/status-im/status-mobile/assets/52490791/8a9ed4fb-1e9c-44f6-8fe7-07191049e165

### Additional info:
No matter if some permissions, such as notifications and local network access, are allowed or not allowed during onboarding, the app crashes in all cases.

### ENV: 
- IOS
- Nightly [24 Apr 2024]

### Devices:
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (9).zip](https://github.com/status-im/status-mobile/files/15096250/logs.9.zip)

**Comment by pavloburykh** [comment] 2024-04-24 15:36
**UPDATE:** 

This issue is most likely OS specific (or device). I am not reproducing on my iPhoneX, IOS 16.7.7

**Comment by mariia-skrypnyk** [comment] 2024-05-08 18:27
Have this issue on nightly 07/05 on my iPhone 13 (17.3.1)

**Comment by jo-mut** [comment] 2024-05-08 23:12
I have not been able to reproduce it on iPhone 12 Pro(17.4.1) , iPhone 11 Pro(17.2) and iPhone 13 (17.2)

but something that maybe unrelated but referenced in the issue description, I noticed that sometimes the app still asks for `local network access` permission even when permission has been granted, its possible that the crash maybe related. I will log the issue separately if it is indeed something needing some fixing

**Comment by yqrashawn** [comment] 2024-05-10 05:43
can't reproduce on iphone 11 pro, 17.4.1

**Comment by yevh-berdnyk** [comment] 2024-05-10 12:09
Can't reproduce on iPhone SE 2020 and 2022, versions 13.7, 15.7, 16.7. Neither on iPhone 14 pro with iOS 17.2.1

**Comment by yqrashawn** [comment] 2024-05-10 13:34
Just reproduced on my device

according to https://suelan.github.io/2021/03/05/20210305-crash-ate-bad-food/ https://developer.apple.com/documentation/xcode/sigkill and crash report on my device
the app is killed by watch dog because the main thread got blocked for too long.
Need more time to look into the stack trace.

```json
{
  "exception": {
    "codes": "0x0000000000000000, 0x0000000000000000",
    "rawCodes": [
      0,
      0
    ],
    "type": "EXC_CRASH",
    "signal": "SIGKILL"
  },
  "termination": {
    "code": 2343432205,
    "flags": 6,
    "namespace": "FRONTBOARD",
    "reasons": [
      "<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-create watchdog transgression: app<im.status.ethereum.debug(C4641303-92AF-4C80-9AE4-E1C3F7E097C0)>:10192 exhausted real (wall clock) time allowance of 19.45 seconds",
      "ProcessVisibility: Foreground",
      "ProcessState: Running",
      "WatchdogEvent: scene-create",
      "WatchdogVisibility: Foreground",
      "WatchdogCPUStatistics: (",
      "\"Elapsed total CPU time (seconds): 24.970 (user 24.970, system 0.000), 24% CPU\",",
      "\"Elapsed application CPU time (seconds): 0.973, 1% CPU\"",
      ") reportType:CrashLog maxTerminationResistance:Interactive>"
    ]
  }
}
```

From https://developer.apple.com/documentation/xcode/addressing-watchdog-terminations

> When scene-create appears in the Termination Description, the app didn’t render the first frame of its UI to the screen within the allowed wall clock time. If scene-update appears in the Termination Description instead of scene-create, the app didn’t update its UI quick enough because the main thread is too busy.

**Comment by yqrashawn** [comment] 2024-05-14 06:13
Unfortunately, the crash report above is not the right one, it's the crash caused by splash screen (only happens on first launch after installation in debug build)
And the report for the one I reproduced last Friday is gone.

Try to reproduce this again

**Comment by yqrashawn** [comment] 2024-05-14 06:20
Hi @status-im/mobile-qa, can you help me get the crash report.

After app crash, you can find the crash log based on app name and crash date time
After app crash, go to Settings -> Privacy & Security -> Analytics & Improvements -> Analytics Data, in the list, there should be a crash report named "StatusIm(or StatusPR)-datetime", you can download the report by airdrop

https://github.com/status-im/status-mobile/assets/15090582/e236d8a7-d167-42fd-bf49-62cb7d1bca6e

**Comment by qoqobolo** [comment] 2024-05-14 08:15
Hi @yqrashawn , I just reproduced the crash, but there is no report you're describing on my device for some reason.
I'm trying a nightly build, however, the only Status file I see in reports is `Status PR` dated May 9th.

Do you know how do I get a fresh nightly report? 

<img width="394" alt="Screenshot 2024-05-14 at 10 11 23" src="https://github.com/status-im/status-mobile/assets/67952253/301ed4db-909c-43b0-90bb-3d652635b592">
<img width="399" alt="Screenshot 2024-05-14 at 10 11 59" src="https://github.com/status-im/status-mobile/assets/67952253/d6aaa3bb-7869-4886-a52d-23b8c1f8c6d5">

**Comment by mariia-skrypnyk** [comment] 2024-05-14 09:02
Hey @yqrashawn !

I had this issue 5/5 times but now I do not see it on nightly and on PR's.

If somehow I'll catch it today I'll let you know! 
Or I can try some old PR builds if it works for you.

**Comment by yqrashawn** [comment] 2024-05-14 12:26
Thanks @qoqobolo @mariia-skrypnyk

> but there is no report you're describing on my device for some reason

this might explain why I used the wrong crash report. The crash might not generate a report at all.
Maybe iOS doesn't think it's a crash? I'll explore further on this point.

**Comment by siddarthkay** [comment] 2024-05-15 04:16
@qoqobolo and @mariia-skrypnyk : can you pls check if builds from this PR fix the crash -> https://github.com/status-im/status-mobile/pull/20026 
Thank you

**Comment by qoqobolo** [comment] 2024-05-15 12:57
@yqrashawn @siddarthkay as I mentioned on Discord, my iPhone SE does not crash in https://github.com/status-im/status-mobile/pull/20026
We'll close the issue once we're 100% sure it's not reproducible anymore 
@yqrashawn thanks for trying to figure it out!

**Comment by churik** [comment] 2024-05-21 08:20
closing for now, as seems not reproducible after removing Parallax.
Reopen if still exists

**Closed as completed by churik** 2024-05-21 08:20 UTC
Labels: ios, mobile-core
