### ISSUE TITLE
Input selection formatting not working

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14976] opened 2023-02-03 08:12 UTC
That PR https://github.com/status-im/status-mobile/pull/14249 implemented formatting selection natively for the text input on Android. However, it seems to be not stable. On my device (Samsung galaxy note 10 lite - Android 11), after pressing "BIU" nothing happens (most of the time).

Steps to reproduce:
1. Open a chat.
2. Type some text and select it.
3. Select "BIU"

Expected behaviour: Bold, Italic, Strikethrough should appear like in the designs https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?node-id=2630%3A212161&t=amRskTi8EB8gB4wY-0

Current behaviour: nothing happens (I was able to see the menu appearing one time only)

On iOS, it is not yet implemented.

**Comment by qfrank** [comment] 2023-03-07 07:48
my guess, maybe the cause is relate to the comments within [`select-mention`](https://github.com/status-im/status-react/blob/7d9709ee678de416151286be93a88f3afb1f4ed0/src/status_im/chat/models/input.cljs#L42)

**Comment by ibrkhalil** [comment] 2023-04-08 20:07
Unfortuantely, Couldn't reproduce.

**Comment by cammellos** [comment] 2023-07-14 12:07
closing for now until better repro steps are identified

**Closed as not planned by cammellos** 2023-07-14 12:07 UTC
