### ISSUE TITLE
Discover feature appears non-functional [iOS]

### ISSUE THREAD

**Issue by rabbit** [status-im/status-react#696] opened 2017-01-08 21:45 UTC
## Description

Others seem to be using the Discover feature without issue so this is maybe just an iOS issue. I don't know what the expected behavior is so this is difficult to detail. As it is, the Discover view simply shows tags and clicking on those tags shows a view with items that appear clickable but are non-functional.

### Scenario One

[iOS]

1. Go to Discover view with both Popular Tags and Recent items content shown.
2. Tap `#tagname` to reveal a new view showing `#tagname` in header and back arrow.
3. Several items from users are shown using this tag.

### Scenario Two

[iOS]

1. Go to Discover view with both Popular Tags and Recent items content shown.
2. Tapping on Recent items has no effect.
3. Tapping on blue link tag names on Recent items has no effect.
4. Tapping on user icon for a Recent item takes you to a chat for that user [expected behavior?]

## Observation

Although there are items displayed, seeming to entice me to interact with them, when I tap nothing happens. I'm assuming this should take me to a channel for that tag? Appears non-functional.

## Expectation

Unclear.

**Comment by Jas0n-F** [comment] 2017-01-15 03:41
Android user reporting issues with Discover feature appearing to be non-functional

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/129?status=New

**Comment by alwx** [comment] 2017-01-17 13:35
I don't certainly know what to do with this task :)

The problem is there is only one way of interacting with Discover items — you can start a chat with an author. But there was no plan to add any other way of interacting (maybe we can make tags clickable, but not sure about anything else).

@jarradh what do you think about it?

**Comment by jarradh** [comment] 2017-02-04 04:42
This can be part of the Discover screen re-design @andmironov

**Comment by asemiankevich** [comment] 2017-11-13 13:50
I am closing this one as it is not accurate for now having Discover already re-designed cc @goranjovic @sla-shi @jarradh @andmironov

**Closed by asemiankevich** 2017-11-13 13:50 UTC
Labels: bug, discover, intermediate, medium-priority
