### ISSUE TITLE
Only 1 of 3 Discover communities are fetched

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17175] opened 2023-09-04 11:41 UTC
Related bug has been recently fixed by https://github.com/status-im/status-mobile/pull/17091 But now it is partially reproducable again 

**Steps:** 

1. Login multiaccount
2. Open Discover communities screen
3. See if all communities are fetched

**Actual result:** only 1 of 3 communities are fetched. Community cards are stucked with loading skeleton.

[Status-debug-logs (54).zip](https://github.com/status-im/status-mobile/files/12513348/Status-debug-logs.54.zip)

https://github.com/status-im/status-mobile/assets/97245802/cc5cb7e9-13db-4ed9-b45f-04f6d5ecb65c

**Expected result:** all 3 communities are fetched

### Additional Information

- Status version: nightly 05/09/23
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment] 2023-09-05 13:40
As far as I can see, the issue is that we can't retrieve community info from mailservers, that's likely due to the owner not being online, but I will double check that to make sure, in any case, we should not show skeletons if not available.

**Comment by cammellos** [comment] 2023-09-13 12:39
I will close this one as it's due to the admin not being online

**Closed as completed by cammellos** 2023-09-13 12:39 UTC
Labels: community
