### ISSUE TITLE
Crypto Onramp using "Transak" doesn't let us to change the default purchase value on Android

### ISSUE THREAD

**Issue by eerlo** [status-im/status-react#11922] opened 2021-03-24 14:54 UTC
# Bug Report

## Problem

Crypto Onramp using "Transak" doesn't let us change the default purchase value on Android.
Every time we try to change the purchase value, it recalculates and focuses out of the input

#### Expected behavior

It should let us change the purchase value we want to buy.

#### Actual behavior

Every time we try to change the purchase value, it recalculates and focuses out of the input

#### Notes

This might be a problem on their side.

### Reproduction

- Open Status
- Go to Crypto Onramps option in the wallet
- Select "Transak"
- Inside Transak, try to change the default amount you want to buy.

### Additional Information

[comment]: # Transak looks the best option as their UI is pretty cool and it shows all related taxes, it should work well for Android users.
- Status version: ...
Android V1.12
- Operating System: Android

```
...
```

**Comment by guylouis** [comment] 2021-03-25 10:10
I can't reproduce the problem with status v1.12 and a one plus 6 (android)
iOS v1.12 on iphone 12 working fine too on my side

**Comment by eerlo** [comment] 2021-04-01 13:41
Adding a screen recording of the problem. On Samsung Galaxy A51.

https://user-images.githubusercontent.com/1106118/113302789-c9ba0480-92d6-11eb-960d-99287c37bcd2.mp4

**Comment by guylouis** [comment] 2021-04-07 12:49
can't reproduce with one plus 6, I definitely can edit the amount :) 
 I'll ask to some other CCs if they can test.

**Comment by hesterbruikman** [comment] 2021-04-07 13:22
Tried with VPN, but I can't replicate the issue. @eerlo on What Android OS version was this?

@cammellos Do you think WebView version is relevant?

**Comment by guylouis** [comment] 2021-04-09 08:12
With my Oneplus using android 10 and webview version 89.0.4389.105 I don't have the issue

@eerlo could you precise what is your android version, and the webview version ? 

To find out the webview version you need to go to Settings < Apps < Android System WebView 

Thanks !

**Comment by eerlo** [comment] 2021-04-09 14:24
Samsung Galaxy A51.
Android Version 10.
Android Webview version 89.0.4389.105.

**Comment by guylouis** [comment] 2021-06-10 08:04
closing this, since we can't reproduce it and Transak has been removed from the list 1.14

**Closed as completed by guylouis** 2021-06-10 08:04 UTC
