### ISSUE TITLE
Transaction state is not updated for receiver if it is received to non-default account

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9895] opened 2020-01-23 15:35 UTC
# Bug Report

## Problem
When sending transaction, receiver may share for transaction `Status account` or another account.
In case of another - message state will remain `shared account` forever. 

#### Expected behavior
'Confirmed'

#### Actual behavior
![Monosnap 2020-01-23 16-30-40](https://user-images.githubusercontent.com/4557972/72998201-c20eee00-3dfd-11ea-8509-0e664069deb9.png)

### Reproduction

- User A: send transaction to User B (User B shouldn't have ENS name set)
- User B: create new account in wallet
- User B: share new account
- User A: sign and send transaction
- User B: wait until transaction gets enough confirmations, try to relogin to get updated

### Additional Information

- Status version: RC 2020012313
- Operating System: Android, iOS

**Comment by churik** [comment] 2020-03-03 10:32
More visible in PR https://github.com/status-im/status-react/pull/10100 
cc @flexsurfer

**Comment by churik** [comment] 2020-04-01 16:17
Currently, the transaction state message is not updated to "Confirmed" at all if the transaction was sent between e2e builds.

It is a blocker for `test_network_mismatch_for_send_request_commands` - it will always pass until issue will be fixed

**Comment by cammellos** [comment] 2020-09-17 12:41
I believe this is just a matter of configuring the URL for verifying transactions, @churik  do you still want to enable those e2e tests? ( if so we can get this done, otherwise we can close)

**Comment by churik** [comment] 2020-09-17 13:28
Yes, I would rather enable this case.
IMO that message in "Shared account" state forever is not user-friendly (so you can't tap on it and see transaction state).
I understand it is not high-prio because not a lot of users using non-default account in 1-1 chat, but in case of usage user will be confused for sure.

**Comment by cammellos** [comment] 2020-12-07 11:57
Looking at this.

It looks like we are not checking all wallet accounts.
The assumption is that https://github.com/status-im/status-go/blob/1237cc9ac63f3b94e367a702e06acdc72ce79fb5/services/ext/service.go#L310 should return all wallet accounts, but I see that only the default account is returned.

**Comment by cammellos** [comment] 2020-12-07 12:26
checked and confirmed that the addresses are in the database and we should be querying them correctly, so it must be that at some point we are not correctly building up the map of addresses. investigating.

**Comment by cammellos** [comment] 2020-12-07 13:22
Ok, found the issue, when generating a new account is not marked as a wallet, so it's not picked up by the validator, will fix.

**Closed as completed** 2020-12-16 07:42 UTC
Labels: e2e test blocker
