### ISSUE TITLE
Users still see CR and outgoing CR in AC after both users send CR to each other

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16578] opened 2023-07-13 08:49 UTC
### Steps to reproduce:
1. `User A`  sends contact requests to `User B`
2. `User B`sends contact requests to `User A`  (don't accept the CR of `User A`)
3. Both users check the Activity Centre and 1-1 chat

### Actual result:
- `User A`  still sees the outgoing contact request in the AC.
![image](https://github.com/status-im/status-mobile/assets/52490791/18137c78-4df4-4c77-8b63-2d51e908c538)

- `User B` still sees the CR from `User A` 
![image](https://github.com/status-im/status-mobile/assets/52490791/46f192a0-df32-4a24-8591-8ffb0728f2f1)

### Expected result:
When both users send contact requests to each other, the outgoing contact request should not be shown in the Activity Centre for User A, and the contact request should not be shown in the Activity Centre for User B.

### ENV:
Nightly [13 Jul 2023]

**Comment by ibrkhalil** [comment] 2023-08-12 11:58
Hey @VolodLytvynenko
Do you mean that when users send contact requests to each other we should approve automatically?

**Comment by VolodLytvynenko** [comment] 2023-08-14 08:58
> Hey @VolodLytvynenko Do you mean that when users send contact requests to each other we should approve automatically?

Hi, @ibrkhalil correct. They should

**Comment by cammellos** [comment] 2023-08-16 11:24
@MishkaRogachev any insight on this one?

**Comment by MishkaRogachev** [comment] 2023-08-16 12:27
> @MishkaRogachev any insight on this one?

<img width="561" alt="Screenshot 2023-08-16 at 16 27 03" src="https://github.com/status-im/status-mobile/assets/2522130/d73c79f3-1bbe-434c-94f1-adbacba35b86">

I reproduced this problem on the desktop (with some workaround, since we can't send a CR if we already have a pending CR). What is the requirements here: should we delete initial notification or just accept it?

**Comment by cammellos** [comment] 2023-08-16 12:38
@MishkaRogachev I think accepting it is fine to start with, what do you think?

**Comment by MishkaRogachev** [comment] 2023-08-16 12:53
> @MishkaRogachev I think accepting it is fine to start with, what do you think?

Yes, what should work. If we have more than one pending contact request, should we accept all of them?

**Comment by cammellos** [comment] 2023-08-16 12:54
@MishkaRogachev I think so, all of them should be accepted

**Comment by VolodLytvynenko** [comment] 2024-02-23 12:23
**NOTE for QA:** recheck this TC https://ethstatus.testrail.net/index.php?/tests/view/3466413 after fixing this issue

**Comment by churik** [comment] 2024-06-21 09:22
not the case anymore, state is changed to review CR, closing the issue

**Closed as completed by churik** 2024-06-21 09:22 UTC
Labels: activity-center
