### ISSUE TITLE
IOS push notifications are not working

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14704] opened 2023-01-04 10:29 UTC
# Bug Report

## Problem 
currently on IOS notifications are not working - tried in 1-1, community, group chats

#### Expected behavior
can see PN

#### Actual behavior
no PN

### Reproduction

1) Open Status
2) Android: Add contact, start 1-1 chat
3) IOS: turn on PNs in Advanced > Notifications
4) IOS: put app in the background
5) Android: send message to IOS device

### Additional Information

- Status version: nightly 04/01/23
- Operating System: iOS 16.1.1

[comment]: # (Please, add logs/notes if necessary)

[logs (23).zip](https://github.com/status-im/status-mobile/files/10343234/logs.23.zip)

**Comment by cammellos** [comment] 2023-01-05 11:23
This is due to push notification servers running only on waku-1.

We should run them as well on waku-2, @jakubgs should be able to help you set that up.
Just make sure you are not running them as a mailserver/waku-1  service, since that's no needed.
This would be a good task for someone who wants to have an insight on how the infrastructure works.

It should be mostly a change of config + deployment, if everything goes smoothly.

**Comment by jakubgs** [comment] 2023-01-05 13:22
Oh, I think i know what this is caused by:
```yaml
# iOS API access key in one of 3 formats: pem, p12 or p8
gorush_ios_key_contents: '<contents of the p8 key file>'
# KeyID from developer account (Certificates, Identifiers & Profiles -> Keys)
gorush_ios_key_id: '<ios_key_id>'
# TeamID from developer account (View Account -> Membership)
gorush_ios_team_id: '<ios_team_id>'
```
https://github.com/status-im/infra-misc/blob/master/ansible/roles/gorush/README.md

I think the change in the Apple Org ownership of the app has caused this.

**Comment by cammellos** [comment] 2023-01-05 13:29
Oh that too, but also we should use probably deploy a different fleet, or enable it on some existing waku-2 fleet, if they are not already enabled

**Comment by jakubgs** [comment] 2023-01-05 13:30
Does `nim-waku` support Gorush tho?

**Comment by cammellos** [comment] 2023-01-05 13:31
@jakubgs no, we need to use the go-waku nodes

**Comment by jakubgs** [comment] 2023-01-05 13:31
Fair enough.

**Comment by jakubgs** [comment] 2023-01-05 13:36
I had to create a new key under `Certificates, Identifiers & Profiles` in `Keys`:

![image](https://user-images.githubusercontent.com/2212681/210791884-4bbbcdfb-87cc-4be8-9201-1c7505d60356.png)

I'm assuming we only need the `Apple Push Notifications service (APNs)` option.

**Comment by jakubgs** [comment] 2023-01-05 13:58
I've upgraded Gorush and fixed the Apple credentials:

- https://github.com/status-im/infra-misc/commit/5f519112 - gorush: upgrade from 1.13.0 to 1.16.0
- https://github.com/status-im/infra-misc/commit/53c74844 - gorush: move Docker compose to template file
- https://github.com/status-im/infra-misc/commit/812970a5 - gorush: update Apple credentials, use BitWarden

It's back up and running:
```json
{"level":"info","msg":"Init App Status Engine as leveldb","time":"2023-01-05T13:54:52Z"}
{"level":"info","msg":"gRPC server is disabled.","time":"2023-01-05T13:54:52Z"}
{"level":"info","msg":"HTTPD server is running on 8080 port.","time":"2023-01-05T13:54:52Z"}
```

**Comment by jakubgs** [comment] 2023-01-05 13:58
Need to still add config to `go-waku.*` fleets.

**Comment by cammellos** [comment] 2023-01-05 13:59
Yes, also we need to change the config of the fleet to run on waku v2, unless you added it to some nodes already running on waku v2.

**Comment by jakubgs** [comment] 2023-01-05 14:26
Are we sure `go-waku` supports Gorush?
https://github.com/waku-org/go-waku/search?q=gorush

I see no reference, while `status-go` clearly does support it via `` config:
```go
type Config struct {
	Enabled bool
	// Identity is our identity key
	Identity *ecdsa.PrivateKey
	// GorushUrl is the url for the gorush service
	GorushURL string

	Logger *zap.Logger
}
```
https://github.com/status-im/status-go/blob/d70d3cdf8c92a786a9fbfab7d2295547546f2aed/protocol/pushnotificationserver/server.go#L26-L34

**Comment by cammellos** [comment] 2023-01-05 14:31
@jakubgs status-go does, through go-waku, basically we just need to start a messenger with Waku v2 config & push notifications enabled, I believe.

**Comment by jakubgs** [comment] 2023-01-05 14:43
What do you mean by "messenger"? Some kind of new bridge-type node that will talk to other fleets and gorush?

**Comment by jakubgs** [comment] 2023-01-05 14:48
I see there's a `WakuV2Config` section in `status-go` config I didn't see before:
https://github.com/status-im/status-go/blob/7d04be3613585a5ea0d6232e76353f67a7c7adfa/params/config.go#L155-L212

Is that what you mean?

**Comment by jakubgs** [comment] 2023-01-05 15:20
According to @richard-ramos you cannot use both `WakuConfig` and `WakuV2Config` at the same time.

This means we'd need a separate set of `status-go` nodes with `WakuV2Config` and `PushNotificationServerConfig` enabled.

I guess this ties into this issue I've opened a while ago:

* https://github.com/status-im/infra-push-notify/issues/1

**Comment by jakubgs** [comment] 2023-01-13 17:49
I've deployed a fleet in 3 data centers running Gorush and Status-go speaking Waku v2: https://github.com/status-im/infra-push-notify/issues/1#issuecomment-1382188712

@cammellos how can we verify that his works properly? Any ideas?

**Comment by jakubgs** [comment] 2023-01-18 12:06
@pavloburykh has reported that notification issues still persist, but the endpoint is functioning:
```
 > c https://gorush.status.im/health     
OK

 > c -XPOST https://gorush.status.im/api/push
curl: (22) The requested URL returned error: 400
{"code":400,"message":"Missing notifications field."}
```
Could you elaborate on the symptoms?

**Comment by jakubgs** [comment] 2023-01-18 12:16
I think I see what's happening. There's two Apple accounts:

* Old one, under which the `1.20.2` release was published
* New one, under which the current nightly and PR builds are being published

Considering that it might be necessary to run two Gorush services. One configured for the old account and one for the new.
Leaving `eth.prod` fleet to use the old https://gorush.status.im/ endpoint using old Apple account, and create a separate endpoint for use with Waku v2 fleets like `status.prod`.

**Comment by pavloburykh** [comment] 2023-01-18 12:24
> @pavloburykh has reported that notification issues still persist, but the endpoint is functioning:
> 
> ```
>  > c https://gorush.status.im/health     
> OK
> 
>  > c -XPOST https://gorush.status.im/api/push
> curl: (22) The requested URL returned error: 400
> {"code":400,"message":"Missing notifications field."}
> ```
> 
> Could you elaborate on the symptoms?

Here is a video of current behaviour in latest nightly build. 

[IOS_logs_no_push.zip](https://github.com/status-im/status-mobile/files/10446138/IOS_logs_no_push.zip)

https://user-images.githubusercontent.com/97245802/213170586-b5cd853c-2b0f-4441-8d3a-2420447cf399.mp4

**Comment by jakubgs** [comment] 2023-01-18 12:28
But in the chat you mentioned release `1.20`. Which one is it? The `1.20` release or the nightly that has the issue? Or both?

**Comment by pavloburykh** [comment] 2023-01-18 12:50
> > Here is a video of current behaviour in latest nightly build.
> 
> But in the chat you mentioned release `1.20`. Which one is it? The `1.20` release or the nightly that has the issue? Or both?

the above video is from nightly. But on 1.20 behaviour is the same.

**Comment by jakubgs** [comment] 2023-01-18 13:02
I've re-deployed the old service and changed the domain for the new one: https://github.com/status-im/infra-push-notify/issues/1#issuecomment-1387037668

**Comment by pavloburykh** [comment] 2023-01-18 13:18
> I've re-deployed the old service and changed the domain for the new one: [status-im/infra-push-notify#1 (comment)](https://github.com/status-im/infra-push-notify/issues/1#issuecomment-1387037668)

any additional changes should be done in status-mobile or push notifs (both for nightly and 1.20) should already be fixed on IOS and can be tested?

**Comment by jakubgs** [comment] 2023-01-18 15:15
The nodes on `eth.*` fleets just use the usual https://gorush.status.im/ endpoint:
https://github.com/status-im/infra-role-status-go/blob/238594b97bdb5e11d3add039adefb56748a583e9/defaults/main.yml#L69-L70

So in theory it should Just Work™, unless there's some weird persistent TCP connection that's broken or something.

**Comment by pavloburykh** [comment] 2023-01-18 15:24
> The nodes on `eth.*` fleets just use the usual https://gorush.status.im/ endpoint: https://github.com/status-im/infra-role-status-go/blob/238594b97bdb5e11d3add039adefb56748a583e9/defaults/main.yml#L69-L70
> 
> So in theory it should Just Work™, unless there's some weird persistent TCP connection that's broken or something.

I have just checked on 1.20 which has eth.prod by default. Unfortunately push notifs still don't work on IOS.

**Comment by jakubgs** [comment] 2023-01-18 17:42
Why do you quote everything?

@cammellos any idea how to debug this? I believe you wrote most of the PN code in `status-go`.

**Comment by cammellos** [comment] 2023-01-19 09:24
@jakubgs it should show an error in the logs, otherwise we can set `sync` to true to return errors in the api, can you see anything in the logs?

**Comment by jakubgs** [comment] 2023-01-19 09:45
Hm, indeed there is some now:
```
2023-01-19T09:03:46.549871+00:00 docker/gorush[883]: 9:03AM INF Request ip=2a01:4f9:4b:51df::2 latency=0.745285 method=POST path=/api/push status=200 user_agent=Go-http-client/2.0
2023-01-19T09:03:51.336071+00:00 docker/gorush[883]: {"level":"error","msg":"{\"type\":\"failed-push\",\"platform\":\"ios\",\"token\":\"*******\",\"message\":\"You have a new message\",\"error\":\"Post \\\"https://api.push.apple.com/3/device/token-2\\\": dial tcp 17.188.178.165:443: i/o timeout\"}","time":"2023-01-19T09:03:51Z"}
2023-01-19T09:03:51.336142+00:00 docker/gorush[883]: {"level":"debug","msg":"Start push notification for iOS","time":"2023-01-19T09:03:51Z"}
2023-01-19T09:03:54.101627+00:00 docker/gorush[883]: 9:03AM INF Request ip=2a01:4f9:4b:51df::2 latency=0.399344 method=POST path=/api/push status=200 user_agent=Go-http-client/2.0
2023-01-19T09:04:11.338775+00:00 docker/gorush[883]: {"level":"error","msg":"{\"type\":\"failed-push\",\"platform\":\"ios\",\"token\":\"*******\",\"message\":\"You have a new message\",\"error\":\"Post \\\"https://api.push.apple.com/3/device/token-1\\\": dial tcp 17.188.178.198:443: i/o timeout\"}","time":"2023-01-19T09:04:11Z"}
2023-01-19T09:04:11.338887+00:00 docker/gorush[883]: {"level":"debug","msg":"Start push notification for iOS","time":"2023-01-19T09:04:11Z"}
2023-01-19T09:04:31.338082+00:00 docker/gorush[883]: {"level":"error","msg":"{\"type\":\"failed-push\",\"platform\":\"ios\",\"token\":\"*******\",\"message\":\"You have a new message\",\"error\":\"Post \\\"https://api.push.apple.com/3/device/token-2\\\": dial tcp 17.188.180.15:443: i/o timeout\"}","time":"2023-01-19T09:04:31Z"}
```
No idea what `17.188.180.15` is though. Definitely not one of our hosts.

**Comment by cammellos** [comment] 2023-01-19 09:49
@jakubgs apple servers, can the host connect to it?

**Comment by jakubgs** [comment] 2023-01-19 10:11
Fuck, it's the firewall rules order again:
```
admin@node-01.do-ams3.gorush.misc:~ % sudo nmap -Pn -p443 17.188.180.15
Nmap scan report for 17.188.180.15
Host is up (0.14s latency).

PORT    STATE SERVICE
443/tcp open  https
```
```
admin@node-01.do-ams3.gorush.misc:~ % d exec -it gorush sh  
/ # wget -T5 -So- https://17.188.180.15:443
Connecting to 17.188.180.15:443 (17.188.180.15:443)
wget: download timed out
```

**Comment by jakubgs** [comment] 2023-01-19 11:24
Yup:
```
admin@node-01.do-ams3.gorush.misc:~ % t DOCKER-USER
Chain DOCKER-USER (1 references)
num  target     prot opt source               destination         
1    VPN        all  --  0.0.0.0/0            0.0.0.0/0            /* VPN */
2    SERVICES   all  --  0.0.0.0/0            0.0.0.0/0            /* SERVICES */
3    DROP       all  --  0.0.0.0/0            0.0.0.0/0            /* non-Docker interface */
4    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* Docker interfaces */
5    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
6    ACCEPT     all  --  127.0.0.1            0.0.0.0/0            /* localhost */
7    ACCEPT     all  --  127.0.0.1            0.0.0.0/0            /* localhost */
8    RETURN     all  --  0.0.0.0/0            0.0.0.0/0   
```
Fixed:
```
admin@node-01.do-ams3.gorush.misc:~ % t DOCKER-USER
Chain DOCKER-USER (1 references)
num  target     prot opt source               destination         
1    VPN        all  --  0.0.0.0/0            0.0.0.0/0            /* VPN */
2    SERVICES   all  --  0.0.0.0/0            0.0.0.0/0            /* SERVICES */
3    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* Docker interfaces */
4    ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
5    ACCEPT     all  --  127.0.0.1            0.0.0.0/0            /* localhost */
6    ACCEPT     all  --  127.0.0.1            0.0.0.0/0            /* localhost */
7    DROP       all  --  0.0.0.0/0            0.0.0.0/0            /* non-Docker interface */
8    RETURN     all  --  0.0.0.0/0            0.0.0.0/0   
```
Now it works:
```
admin@node-01.do-ams3.gorush.misc:/docker/gorush % d exec -it gorush sh
/ # wget -T5 -So- https://17.188.180.15:443
Connecting to 17.188.180.15:443 (17.188.180.15:443)
ssl_client: 17.188.180.15: name `17.188.180.15' not present in server certificate
wget: error getting response: Connection reset by peer
```
I REALLY need to find the time to switch to something like [Firewalld](https://firewalld.org/) away from raw IPtables rules.

**Comment by jakubgs** [comment] 2023-01-19 12:11
Now they errors are different: `TopicDisallowed`
```json
{
  "level": "error",
  "msg": "{\"type\":\"failed-push\",\"platform\":\"ios\",\"token\":\"***\",\"message\":\"You have a new message\",\"error\":\"TopicDisallowed\"}",
  "time": "2023-01-19T12:09:00Z"
}
```
According to this comment: https://github.com/appleboy/gorush/issues/164#issuecomment-269188203

>topic means app bundle identifier. "com.example.app", please change ios example.

Hmmmm.

**Comment by jakubgs** [comment] 2023-01-19 12:20
I think this is because the notification credentials have been moved or removed during migration:

![image](https://user-images.githubusercontent.com/2212681/213441414-0100b177-d2e8-403d-98d2-a615e68d2001.png)

And I'm not sure if creating a new one on the old Apple org will work, but lets try.

**Comment by jakubgs** [comment] 2023-01-19 12:29
I have updated the old service config to use the new key on old Apple org and it's throwing the same errors:
```
12:28PM INF Request ip=104.197.238.144 latency=2.463681 method=POST path=/api/push status=200 user_agent=Go-http-client/2.0
{"level":"debug","msg":"Start push notification for iOS","time":"2023-01-19T12:28:19Z"}
{"level":"error","msg":"{\"type\":\"failed-push\",\"platform\":\"ios\",\"token\":\"********\",\"message\":\"You have a new message\",\"error\":\"TopicDisallowed\"}","time":"2023-01-19T12:28:19Z"}
```
I'm not sure using the old org can work at all.

**Comment by jakubgs** [comment] 2023-01-19 12:41
According to @cammellos the `TopicDisallowed` might be caused not by wrong org or incorrect key configuration, but because the `status-go` part of the equation might be still using cache but already invalid tokens for devices sending push notifications.

For that reason it's best to test the PN functionality using a fresh installation.
@status-im/mobile-qa I'd appreciate if I could get some manual testing of PN functionality.
Would be good to check both the `1.20` release and a nightly build, to see which has issues with current setup, which is:

* https://gorush.status.im/ - Gorush service using credentials from __old__ Apple org, connected with `eth.*` Waku v1 fleets.
* https://gorush.infra.status.im/ - Gorush using credentials from __new__ Apple org, connected with `status.prod` Waku v2 fleet.

**Comment by pavloburykh** [comment] 2023-01-19 13:15
@jakubgs @cammellos I have re-checked push notifs on IOS, both on 1.20 and nightly (fresh installed builds, new accounts).
Still doesn't work both on 1.20 and nightly. 

I am attaching logs, though I am not sure if they will be helpful. 

[1.20_IOS.zip](https://github.com/status-im/status-mobile/files/10456995/1.20_IOS.zip)
[nightly_IOS.zip](https://github.com/status-im/status-mobile/files/10456996/nightly_IOS.zip)

**Comment by cammellos** [comment] 2023-01-19 16:29
mmh, there must be something we are missing, or the app requires a redeploy on the store, but I am not sure, the thing to do would be to at least get a token from a device, so we can play with and we don't have to test through it anymore and we can hit directly gorush, I can try to set up something like that tomorrow, though not sure, maybe @siddarthkay can help with this one?

**Comment by siddarthkay** [comment] 2023-01-19 18:43
@cammellos : yeah I'll be able to look at this first thing tomorrow.

**Comment by siddarthkay** [comment] 2023-01-21 06:00
> the thing to do would be to at least get a token from a device, so we can play with and we don't have to test through it anymore and we can hit directly gorush


I have an iOS simulator running and I got my device token and certificate and I am trying out the following via CLI : 

```
gorush -ios -m "test Push Notification" -i /Users/siddarthkumar/code/status-im/status-mobile/certifcate.pem -t "my-device-token" -production
```

I get a very weird error when I try via CLI : 

```
failed-push | ios [**********222e71b922af45bb046dc820f9d653269dc58210d3a15d72163b78f80dc02dee4b3c154ac86ff884a029f002d40ab1120c1730ef38ff7a7ca9905b1fd367dd4909226afb0588**********] | test PN | Error Message: MissingProviderToken 
```

its probably configuration related because I clearly passed the token via the -t flag.

anyways, I will try to hit their REST API instead and see what happens, 
referring this endpoint : https://gorush.infra.status.im/

**Comment by jakubgs** [comment] 2023-01-23 16:14
Here you can see logs for the `gorush` services:

* https://gorush.status.im/ - `gorush.misc` - https://kibana.infra.status.im/goto/12b5f830-9b39-11ed-aaa4-85391103106b
* https://gorush.infra.status.im/ - `notify.prod` - https://kibana.infra.status.im/goto/eb355c10-9b38-11ed-aaa4-85391103106b

**Comment by siddarthkay** [comment] 2023-02-21 13:33
![IMG_3099](https://user-images.githubusercontent.com/64726664/220358708-c4e27478-84ee-4310-94c1-1a12f059438d.PNG)

Thanks @jakubgs

**Comment by jakubgs** [comment] 2023-02-21 13:39
I made the old endpoint use the new iOS credentials since the old ones would just cause `TopicDisallowed` errors for Gorush:
```json
{
  "level": "error",
  "msg": "{\"type\":\"failed-push\",\"platform\":\"ios\",\"token\":\"xxx\",\"message\":\"You have a new message\",\"error\":\"TopicDisallowed\"}",
  "time": "2023-02-21T13:07:02Z"
}
```
So the new credentials were necessary:

- https://github.com/status-im/infra-misc/commit/8076080d - gorush: use new iOS Apple team, id, and key

And now we are seeing succcessful pushes for iOS:
```json
{
  "level": "info",
  "msg": "{\"type\":\"succeeded-push\",\"platform\":\"ios\",\"token\":\"xxx\",\"message\":\"You have a new message\",\"error\":\"\"}",
  "time": "2023-02-21T13:37:33Z"
}
```
There's still some android push failures, but that's not that bad is it can be caused by old app installations:
```json
{                                                                                                                
  "level": "error",
  "msg": "{\"type\":\"failed-push\",\"platform\":\"android\",\"token\":\"xxx\",\"message\":\"You have a new message\",\"error\":\"unregistered device\"}",
  "time": "2023-02-21T13:28:16Z"
}
```

**Comment by siddarthkay** [comment] 2023-02-21 13:48
@churik : we did a quick test on call today, but upto you to test / close this issue. Thank you 👍🏻

**Comment by qoqobolo** [comment] 2023-03-01 11:28
Hey @siddarthkay, sorry for the late response.
Just tried the latest nightly: notifications still don't work on ios. Can you check on your side, please?

**Comment by siddarthkay** [comment] 2023-03-01 11:50
Hi @qoqobolo : not sure about the nightlies but notifications work on 1.20 release that is out on the Apple app store.
I got one push notification last night from one of the group chats.

**Comment by siddarthkay** [comment] 2023-03-01 11:51
The scope of this issue was to fix Push notifications on IOS for the old app, I believe for the new one that we are currently building we have not looked at push notifications yet and it maybe broken.

**Comment by churik** [comment] 2023-03-01 12:13
The description is about working on develop, so I see no reason to close this issue and create duplicate - imo should be opened until fix on current develop.

**Comment by qoqobolo** [comment] 2023-05-31 14:59
Fixed in https://github.com/status-im/status-mobile/pull/15897

**Closed as completed by qoqobolo** 2023-05-31 14:59 UTC
Labels: ios
