### ISSUE TITLE
Tap on quoted message

### ISSUE THREAD

**Issue by hardBSDk** [status-im/status-react#12388] opened 2021-07-27 22:01 UTC
Tap on quoted message to climb the chat to the message.

![nexus2cee_whatsapp-quote-reply](https://user-images.githubusercontent.com/55782009/127233293-992fdaa9-73de-473b-ad0a-1c71ed145c09.png)

**Comment by churik** [comment] 2021-07-28 08:24
duplicate of https://github.com/status-im/status-react/issues/11482

**Closed as completed by churik** 2021-07-28 08:24 UTC
Labels: feature
