### ISSUE TITLE
Can't receive messages after returning online until relogin

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#13067] opened 2022-01-31 17:00 UTC
# Bug Report

## Problem 

If the user enables airplane mode, closes the app, receives messages while offline from another user (that goes offline/closes the app after sending messages), re-opens the app, and disables airplane mode, they won't receive the messages until reopening Status.
The issue is reproducible with these steps in ~70% of cases. 

#### Expected behavior
Can receive messages right after returning online

#### Actual behavior
Messages are only received after reopening

https://user-images.githubusercontent.com/67952253/151838253-58c33c07-cf48-4029-a90a-8d0c2be7b14b.mp4

### Reproduction

1. Start a 1-1 chat between UserA and UserB
2. UserA: close the app
3. UserB: turn on airplane mode and close the app
4. UserA: open the app > send several messages to UserB > close the app
5. UserB: open the app > turn off airplane mode (no messages) > reopen the app

### Additional Information

- Status version: nightly 31/01
- Operating System: Android, iOS

### Logs
UserA: [geth.log](https://github.com/status-im/status-react/files/7972517/geth.log)

**Comment by rasom** [comment] 2022-02-02 12:53
@qoqobolo 
I can't reproduce it using iOS simulator as A and iOS real device as B. Is it reproducible only on Android devices?

Also regarding steps 3 and 5: what if you don't close the app but just toggle airplane mode, do you have the same result?

**Comment by qoqobolo** [comment] 2022-02-02 13:43
@rasom it's reproducible for me both on iOS and Android real devices (just double-checked with UserA - Android and UserB - iOS).
Logs for iOS [geth.log](https://github.com/status-im/status-react/files/7986850/geth.log)

Regarding steps 3 and 5: hm yeah, I tried to reproduce without them but it was not successful last time.
Now I tried about 5 times on Android and iOS, and the result is:
- can't reproduce it on Android without steps 3 and 5 at all
- can reproduce it on iOS without steps 3 and 5 in 80% of cases

**Comment by rasom** [comment] 2022-02-03 08:58
> Start a 1-1 chat between UserA and UserB

@qoqobolo do I have to create a new 1-1 pair for each test or I can skip the first step on the next iteration?

**Comment by pavloburykh** [comment] 2022-02-03 10:19
Hey @qoqobolo @rasom I'm reproducing the bug following given steps when using Android as device A (receiver) and IOS as device B (sender). Attaching video and logs. 

https://user-images.githubusercontent.com/97245802/152323466-1c66f959-ce37-4cae-8d17-b91670bd0d50.mp4

[geth.log](https://github.com/status-im/status-react/files/7993608/geth.log)

**Comment by cammellos** [comment] 2022-03-11 07:26
This is due to the slots in the p2p server being full and therefore not re-dialling the server.
Looking into a fix

**Comment by cammellos** [comment] 2022-03-19 09:05
Should be fixed  in #13065 feel free to reopen if necessary

**Closed as completed by cammellos** 2022-03-19 09:05 UTC
