### ISSUE TITLE
Error Cannot access member 'from' of undefinied [0.9.11]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1887] opened 2017-09-19 09:03 UTC
### Description

*Type*: Bug

*Summary*: Sporadic issue , when i double tap on `send` transaction error `Cannot access member 'from' of undefinied` is shown

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/30584299-fe453c18-9d31-11e7-8251-bf94cc4541fa.png)

### Reproduction

- Open Status
- Add somebody to contacts
- call `/send` screen and double tap on `send`

### Additional Information

* Status version: release `0.9.11`  0.9.10-103-g4672df2b+ (1660)
* Operating System: Android, iOS
* TF: from 0:32 https://app.testfairy.com/projects/4803622-status/builds/6583606/sessions/11/?accessToken=3zuhuKI2ABGFcvXMxEDN8jwtlsc

**Comment by oskarth** [comment] 2017-09-19 11:35
According to @asemiankevich this is fixed in https://github.com/status-im/status-react/pull/1710 by @janherich 

Two options:
1) Merge huge PR 1710, or
2) Let this issue still be an issue in 0.9.11

Since this isn't a high priority, it seems like the more prudent choice is to let this regression slide for now and then fix it for the next release.

**Comment by asemiankevich** [comment] 2017-09-19 11:40
This is correct assumption taking into account the fact that issue is sporadic so I can 100% confirm its not reproducible in https://github.com/status-im/status-react/pull/1710 however I havent seen it when testing. 

The agreement is to leave this issue in 0.9.11 and fix in next release.

**Comment by sla-shi** [comment] 2017-10-04 21:21
@asemiankevich can we close it now?

**Closed as completed** 2017-11-07 08:29 UTC
