### ISSUE TITLE
Can't swap some tokens on Uniswap due to `json: cannot unmarshal number into Go struct field ...`  when confirming amount of tokens on your account

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12413] opened 2021-08-03 13:53 UTC
# Bug Report

## Problem 
To swap tokens on Uniswap you need to confirm amount by signing a message.
When signing got an error
`json: cannot unmarshal number into Go struct field TypedDataDomain.domain.chainId of type *math.HexOrDecimal256`
It happens only to tokens, which require signing of json (i.e. UNI, DAI)

Maybe related to https://github.com/status-im/status-react/issues/11742 (not sure)

#### Expected behavior
can swap tokens

#### Actual behavior
![IMAGE 2021-08-03 15:44:59](https://user-images.githubusercontent.com/4557972/128026145-9eadf435-4ef3-42dc-adfe-9f991de83424.jpg)

### Reproduction

1) Open Status (restore multiaccounts with some assets, in my case it was UNI)
2) Connect wallet
3) Try to swap UNI to ETH

### Additional Information

- Status version: nightly 03/08/2020
- Operating System: Android, iOS
- Logs: [status_logs.zip](https://github.com/status-im/status-react/files/6924551/status_logs.zip)

**Comment by bitgamma** [comment] 2021-08-03 14:14
seems to be a regression in our fork of go-ethereum, probably because when upgrading our fork of go-ethereum this commit https://github.com/status-im/go-ethereum/commit/1d0a73437993e000e9f0308e64f154edb1fd6125 hasn't been applied

@cammellos is it OK to re-apply it by branching off v1.10.4-status.1 or was there a specific reason why this wasn't merged?

**Comment by cammellos** [comment] 2021-08-03 16:02
sorry, my bad, I must have missed it, please re apply it (or I can do that
tomorrow).

Thank you

**Comment by bitgamma** [comment] 2021-08-03 16:16
Ok will do

**Closed as completed** 2021-08-04 11:43 UTC
