### ISSUE TITLE
History tab is empty when resuming app from the background [1524]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1814] opened 2017-09-11 12:40 UTC
### Description

*Type*: Bug

*Summary*: on Android if send app to background and back while Unsigned or History tab is active then second tab is reusing the same content - so, History shows empty list if open Unsigned tab, put app on background and back, tap on History

#### Expected behavior

History tab remains the same with all data presented when  I resume the app from background

#### Actual behavior

History tab is empty when resuming app from the background

### Reproduction

You need to have some history for txns on your recovered account

- Open Status
- Recover account
- Go to history tab
- Move the app to background
- Resume to the app and pay attention to the history tab

### Additional Information

* Status version: 0.9.10-87-gf21f9ddf+
* Operating System: Android

**Comment by yenda** [comment] 2017-10-19 13:04
Can't reproduce on Android device One Plus 3. Maybe fixed in develop ?

**Closed as completed** 2017-10-19 13:09 UTC
