### ISSUE TITLE
null is not an object (evaluating 'n.name') when syncing desktop app with mobile on initial sync

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14891] opened 2023-01-25 16:06 UTC
# Bug Report

## Problem 
After initial syncing (using flow Sync setting > devices > Sync all) certain data causes the error `null is not an object (evaluating 'n.name') `
Couldn't reproduce with a fresh multi-account with a couple of contacts, so not sure what exact data may be the reason for the failure

#### Expected behavior
no error

#### Actual behavior
![IMAGE 2023-01-25 16:43:20](https://user-images.githubusercontent.com/4557972/214608053-07f52699-2dbc-4482-970a-68290c99fb8d.jpg)
Issue re-appears from time to time on mobile device

### Reproduction

1) Mobile: restore multi account that you're using on status desktop, go to sync settings > devices > advertise device
2) Desktop: go to settings > devices, enable sync with mobile
3) Desktop: tap on Sync all

### Additional Information

- Status version: nightly 25/01/23
- Operating System: Android, iOS
- Desktop version: 0.9.0 rc7
- Logs: 
[status_logs.zip](https://github.com/status-im/status-mobile/files/10500912/status_logs.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment] 2023-01-27 09:42
@alwx I think I know what the issue is, not 100% sure, but I briefly looked into it.

We receive a signal for `settings` in messenger response, and it's an array, and some values are `null` (`[blah, null,null, null]`, which they should not I suppose), and status-mobile does not like that.

I have just made a quick fix in my branch just to avoid crashing https://github.com/status-im/status-mobile/pull/14878/files#diff-8bbef8beeb04d992a2df973ab0721c9cc88e069a23f790cb20a7206e3994984eR52 , but the fix should really be in status-go, since it should not be passing null values, most likely this is coming from backup handling, since it changed recently. 

Hope it helps, again, not 100% sure that's the issue, but that'd be my guess.

**Comment by alwx** [comment] 2023-01-30 20:49
Still checking it, it's a lot of sync-related code, and it's not easy to tell what exactly and how needs to be fixed. But hopefully will finish with this tomorrow 💪

**Comment by alwx** [comment] 2023-01-30 21:24
Fixed in https://github.com/status-im/status-go/pull/3147

**Closed as completed** 2023-01-31 13:37 UTC
Labels: syncing
