### ISSUE TITLE
Emoticons only show partially.

### ISSUE THREAD

**Issue by Smokyish** [status-im/status-react#742] opened 2017-01-19 09:18 UTC
In the chat view, the emoticons only show partially, they're all clipped from the bottom-right corner.
![status_emoticons_clipping](https://cloud.githubusercontent.com/assets/21331903/22100613/f39434bc-de38-11e6-9773-3bff93ca642c.jpg)

**Comment by alwx** [comment] 2017-01-19 09:30
There is a problem with the component we use for emojis.
There are two possible ways to solve it:
1. Try another component (for example https://github.com/goshakkk/react-native-simple-emoji-picker)
2. Fix this problem in `react-native-emoji-picker`

I will dive deeper and try to understand which scenario suits best.

**Comment by jarradh** [comment] 2017-01-19 11:21
Duplicate of #673 ?

**Comment by alwx** [comment] 2017-01-19 11:22
Yes, let's close it then

**Closed by alwx** 2017-01-19 11:22 UTC
Labels: in progress
