### ISSUE TITLE
Jump to overlaps Logout button

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18999] opened 2024-02-26 14:40 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)

#### Expected behavior
Buttons looks as [designed.](https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?type=design&node-id=3773-221806&mode=design&t=HD9r2m8peryWIH7l-0)
<img width="210" alt="Screenshot 2024-02-26 at 15 38 29" src="https://github.com/status-im/status-mobile/assets/147824399/cb580ca3-4424-4e3c-b815-fd9ddcc122fc">

#### Actual behavior
<img width="258" alt="Screenshot 2024-02-26 at 15 30 39" src="https://github.com/status-im/status-mobile/assets/147824399/d33002d4-6839-4335-b760-e8a4d464399a">

### Reproduction

1. Login to app
2. Go to Profile and scroll to the bottom

### Additional Information

- Status version: nightly 
- Operating System: Android 
- Device: Samsung A34

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment] 2024-02-26 15:46
duplicate of https://github.com/status-im/status-mobile/issues/18893

**Closed as completed by Parveshdhull** 2024-02-26 15:46 UTC
Labels: android
