### ISSUE TITLE
 "eq() not a number: <0.01" Error shown after transaction confirmation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21251] opened 2024-09-11 13:26 UTC
Follow up for https://github.com/status-im/status-mobile/pull/21235

### Steps:
1. Open account
2. Go to the routes generation page -> confirm a transaction

### Actual result:
The user is redirected to the activity page, where the error message "eq() not a number: <0.01" is displayed.

![image](https://github.com/user-attachments/assets/e58423c2-46b4-4af8-81a4-03fda3149469)

### Expected result:
The transaction should be confirmed without showing any error messages
### OS: 
IOS, Android

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (7).zip](https://github.com/user-attachments/files/16947924/logs.7.zip)

**Comment by shivekkhurana** [comment] 2024-09-18 12:14
@vkjr It is possible that this issue gets by itself after #21281 is merged. (Status Desktop pr 5807 might fix it). 

Please confirm that before working on a fix.

**Comment by vkjr** [comment] 2024-09-19 10:01
@shivekkhurana, the exception will disappear but I'd like to investigate how the string that causes exception makes it way to `.eq` function because it shouldn't

**Comment by smohamedjavid** [comment] 2024-09-23 16:02
The routes generation needs to stop after the transaction is successfully made. The existing RPC `createMultiTransaction` doesn't stop the routes generation after the transaction is created. That's why these errors are thrown, because it was processing the route signals after the transaction is confirmed/created.

I see @seanstrom has created a PR to handle the BigNumber crash and added RPC to stop route calculation on the routes generation page. That will stop route calculation after a token transaction is made. But, collectible transactions will still have this issue. I have fixed it in the PR: #21306

**Comment by seanstrom** [comment] 2024-09-24 08:53
@smohamedjavid Nice catch! 🙌 
Thanks for fixing this 🙏

**Closed as completed** 2024-09-25 13:50 UTC
Labels: wallet-core
