### ISSUE TITLE
Sending a transaction from 1-1 chat with wallet set up ends up on Wallet 'Set up your screen' 

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#5975] opened 2018-09-24 17:30 UTC
[comment]: # (Please replace ... with your information. Remove < and >)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
***Type***: Bug

***Summary***: User is navigated to Wallet view instead of 1-1 chat if sending funds from 1-1 chat and performing wallet set up after clicking Send message button

#### Expected behavior
User is returned back to the 1-1 chat

#### Actual behavior
User is landed on the Wallet view with 'Set up your Wallet' screen (while Wallet set up already while sending TX in 1-1 chat!)

### Reproduction

- Open Status
- Recover existing account with funds
- Start new 1-1 chat
- Click Send command, select an asset, input valid amount and click Send message button
- Set up your wallet
- Sign transaction and click Got it! button

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.29 (8943); node 0.15.0
* Operating System: OnePlus 5, Android 8.1

### Additional Information **(Updated)**
* Status version: 0.11.0 Develop
* Operating System: Android and iOS

**Comment by goranjovic** [comment] 2018-10-18 08:30
The previous fix for this caused another bug - #6283 reopened this one

**Comment by antdanchenko** [comment] 2018-11-23 14:05
@goranjovic please take a look at this issue, this one is the last issue in develop branch which should be fixed in order to get 100% passed tests for any PR

**Comment by goranjovic** [comment] 2018-11-23 14:09
@antdanchenko on it :+1:

**Comment by oskarth** [comment] 2018-12-18 12:07
@goranjovic What's the latest state of this?

I saw:
> https://github.com/status-im/status-react/pull/6878#issuecomment-445156497

but not quite clear what this means or implies.

We want automated tests to block as soon as possible. IMO we have two options to get there:
1) Fix this now before end of year (issue high prio)
2) Remove this test from automated test for now (issue not high prio due to redesign, automated tests cutting scope)

@antdanchenko

**Comment by antdanchenko** [comment] 2018-12-18 14:09
@oskarth, @goranjovic 
I am not a big fan of adding workarounds to an automated tests, or disabling tests which fail due to product issues.
Using the approach might lead to the situation when half of the tests are disabled, we always get `100% passed`, but half of the functionality is not tested.

However for this specific case I will add workaround, to make wallet setup before sending a transaction.
Also new test will be added for this specific behavior but will get lower priority which means that the test will run only against nightly builds

**Comment by oskarth** [comment] 2018-12-19 03:33
Thanks @antdanchenko. I generally agree with you. Going forward, if there's a product issue that breaks tests it isn't going to get merged right?

Regarding the redesign and how that impacts fixing stuff perhaps @goranjovic has more details.

Also cc @mandrigin fyi

**Comment by goranjovic** [comment] 2018-12-19 08:53
redesign will definitely impact the tests in the sense that all tests covering "Send transaction" will need to be updated to account for new/changed screens.

**Comment by Serhy** [comment] 2019-03-21 09:22
Still reproduced with 0.11.0 Develop build. 
Same issue but now user landed not on Home view but Wallet view + on that Wallet view the 'Set up your Wallet' screen is shown to user again.

**Comment by Serhy** [comment] 2019-04-24 11:08
Can not reproduce with 0.11.0 Release (and 0.12.0 Develop). Happy to close this one!

**Closed as completed by Serhy** 2019-04-24 11:08 UTC
Labels: e2e test blocker
