### ISSUE TITLE
Messages are not received after going online again

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4318] opened 2018-05-17 13:30 UTC
### Description

*Type*: Bug

*Summary*: When device goes online, messages that were sent while it was offline should be received. It didn't work this way when I tested latest nightly and 0.9.18 release. I was on stable LTE, and after coming back online I didn't receive the messages. When I sent new message it was delivered but still, I didn't get the messages that were sent while I was offline. 

Btw, ideally, there should be a visual indicator that the app is connecting to mailservers and user may expect messages.  

#### Expected behavior
When app goes online, the messages that were sent in the meantime are received.

#### Actual behavior
When app goes online, the messages that were sent in the meantime are not received.

### Reproduction

- Open Status on devices A and B
- Create 1-1 chat between A and B
- Device A: go offline
- Device B: sent a message
- Device A: go online
-> Device A: should receive the message after couple of minutes max

### Additional Information
* Status version: nightly, May 17 and 0.9.18
* Operating System: Android, iOS
* Tested on stable LTE. I didn't try Wifi

**Comment by pedropombeiro** [comment] 2018-05-17 14:16
This seems to share the same root cause as https://github.com/status-im/status-react/issues/4212

**Comment by lukaszfryc** [comment] 2018-05-18 08:52
Slack conversation about possible causes: https://status-im.slack.com/archives/C9B1T4B9B/p1526564024000384

<blockquote><img src="https://a.slack-edge.com/436da/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://status-im.slack.com/archives/C9B1T4B9B/p1526564024000384">Slack</a></strong></div></blockquote>

**Comment by oskarth** [comment] 2018-05-21 10:18
Logs would be useful to debug this

**Comment by lukaszfryc** [comment] 2018-05-21 10:40
I can't replicate it now

**Comment by pedropombeiro** [comment] 2018-05-22 07:43
@yenda are you aware of any recent change which might have fixed this?

**Comment by yenda** [comment] 2018-05-22 07:59
@PombeirP https://github.com/status-im/status-react/pull/4342

**Comment by pedropombeiro** [comment] 2018-05-22 08:11
Fixed by #4342

**Closed as completed by pedropombeiro** 2018-05-22 08:12 UTC
