### ISSUE TITLE
The text is shown in several rows within preview for 1-1 chat, group chat, community after user is re-logged in

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#14543] opened 2022-12-14 16:53 UTC
**Steps to reproduce:**
1. Create any chat
2. Send a message that contains several rows
3. Relogin
4. Open a list of chats

**Actual result:**

https://user-images.githubusercontent.com/52490791/207657835-da23a0f4-1059-48e2-8cc9-94961e5821b6.mp4

**Expected result:**
The text is in one row
![image](https://user-images.githubusercontent.com/52490791/207658079-8c4c4213-0ef2-4215-a195-6ae29e20f7db.png)

**Comment by ajayesivan** [comment] 2022-12-15 11:40
@cammellos Could you please assign this issue to me.

**Comment by ajayesivan** [comment] 2022-12-16 11:57
@VladimrLitvinenko / @flexsurfer I found the root cause, but need help to properly style text, mention, status tag & link in the subheader(last message in the chat list item). Could you please share the Figma design for the subheader component?

**Comment by flexsurfer** [comment] 2022-12-16 12:51
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=10732%3A130432&t=NE5gFB7YhuHqB29B-3

**Comment by ajayesivan** [comment] 2022-12-16 13:15
@flexsurfer I checked the design but couldn't find how to style mentions, status-tags & links when we show them in the last message. Could you please tag someone from the design team to clarify? or let me know how to proceed.

**Comment by flexsurfer** [comment] 2022-12-16 14:16
cc @pedro-et @xAlisher

**Comment by VolodLytvynenko** [comment] 2022-12-16 15:07
Hi @pedro-et @xAlisher 
Except the 1. formatted text 2. mentions 3. status-tags  4. links
add also please: 
5. Image
6. Audio
7. Emoji
8. Sticker
9. Audio

**Comment by pedro-et** [comment] 2022-12-16 17:34
@VladimrLitvinenko here you go: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=0%3A1&t=3SoyiHUtZrJaJZIr-1
Thanks for spotting this!
cc @cammellos

**Comment by ajayesivan** [comment] 2022-12-16 17:37
@pedro-et I'm not able to access the above Figma link,

<img width="463" alt="Screenshot 2022-12-16 at 23 06 18" src="https://user-images.githubusercontent.com/19279756/208156380-3c1e494e-bc27-4bd7-9cd6-46f7752f04b6.png">

**Comment by pedro-et** [comment] 2022-12-16 17:38
@ajayesivan everyone with a status email should be able to :)

**Comment by ajayesivan** [comment] 2022-12-16 17:46
@pedro-et I don't have a status email. I'm not a status team member, just an open-source contributor.

**Comment by flexsurfer** [comment] 2022-12-16 17:52
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/11790366/208158821-1ff8f04f-16c1-4b26-ba61-70700929a055.png">
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/11790366/208158890-24c6981a-32ae-4b17-82c1-8af6e4cf7415.png">

**Comment by cammellos** [comment] 2023-02-07 18:12
@pedro-et @VladimrLitvinenko is this still relevant? Could we give @ajayesivan access to the figma with an updated link please?

**Comment by VolodLytvynenko** [comment] 2023-02-07 18:39
> @pedro-et @VladimrLitvinenko is this still relevant? Could we give @ajayesivan access to the figma with an updated link please?

The issue is relevant.
@pedro-e Could you provide access, please?

**Comment by ajayesivan** [comment] 2023-02-09 11:07
@pedro-et Could you please give me access to the design file

**Comment by VolodLytvynenko** [comment] 2023-03-07 18:01
hi @cammellos @ajayesivan. For this issue, I suggest fixing only that on the preview the text message should be shown in one row after relogin (as described https://github.com/status-im/status-mobile/issues/14543#issue-1497033605)

For other issues related to the correct display of content on the chat preview page, I created a separate ticket https://github.com/status-im/status-mobile/issues/15281

**Comment by ajayesivan** [comment] 2023-04-18 13:31
This issue is due to the way we store & process last message and will be resolved in #15613.

cc: @vkjr

**Comment by vkjr** [comment] 2023-05-15 15:52
Fixed by #15613

**Closed as completed by vkjr** 2023-05-15 15:52 UTC
Labels: messaging
