### ISSUE TITLE
Hiding bottom sheet (component) does not animate

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15458] opened 2023-03-23 07:02 UTC
Calling `:bottom-sheet/hide` does not animate hiding the bottom sheet

Also, when calling `bottom-sheet/hide` to navigate to another screen, the bottom-sheet probably should animate a little faster (compared to the opening animation).

**Comment by Parveshdhull** [comment] 2023-03-23 07:38
possible duplicate of https://github.com/status-im/status-mobile/issues/15134
cc: @flexsurfer

**Comment by flexsurfer** [comment] 2023-03-23 07:40
yes im on it, thanks

**Comment by OmarBasem** [comment] 2023-03-23 07:44
> possible duplicate of #15134 cc: @flexsurfer

I think it is not just new-chat bottom sheet. It is a global issue.

Anyways feel free to close either of them (if duplicated).

**Closed as completed** 2023-03-31 14:13 UTC
