### ISSUE TITLE
[IOS] Composer data becomes invisible on iOS until composer is focused again

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18236] opened 2023-12-19 15:29 UTC
follow up for https://github.com/status-im/status-mobile/pull/18055

### Steps:
1. Paste data containing various content types (links, long text, added images) into the composer.
2. Close the chat.
3. Reopen the chat.
4. Tap the composer to focus.

### Actual result:
Upon reopening the chat and tapping the composer to focus, the data pasted into the composer remains invisible until the composer is tapped once more

https://github.com/status-im/status-mobile/assets/52490791/543e9481-a2b0-445a-9f18-9434f5bd19e1

### Expected result:
The expected behavior involves the immediate visibility of the composer data upon reopening the chat and tapping the composer to focus

### Devices:
- iPhone 11 Pro max, IOS 16

**Comment by Parveshdhull** [comment] 2023-12-24 11:58
As this is composer related, I will be fix this along https://github.com/status-im/status-mobile/issues/18137

**Comment by Parveshdhull** [comment] 2024-01-19 13:11
Hi, I am unable to reproduce this issue.
I am unassigning myself if anyone else wants to look into this. Otherwise, hopefully, it will be fixed as a side product of refactoring.

**Comment by Parveshdhull** [comment] 2024-01-19 13:57
This bug also looks like causes by https://github.com/status-im/status-mobile/issues/18234

So all three issues, https://github.com/status-im/status-mobile/issues/17842, https://github.com/status-im/status-mobile/issues/18234, https://github.com/status-im/status-mobile/issues/18236 are caused by same bug (space between keyboard and composer)

> follow up for https://github.com/status-im/status-mobile/pull/18055

Probably not a follow up, as `17842` was discovered even before `18055` was merged.

**Closed as completed** 2024-01-19 14:01 UTC
Labels: chat-composer
