### ISSUE TITLE
Chat history is not shown after fetching ("Fetch more") until reopening chat

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10133] opened 2020-03-05 11:32 UTC
# Bug Report

## Problem

Chat view is not updated when using "Fetch more" in chat until reopening a chat.
Issue introduced in #9995

#### Expected behavior
Messages are fetched, history is updated

#### Actual behavior
To see history you need to reopen chat

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create new multiaccount
- Join #status 
- Scroll to the beginning of the history 

### Additional Information

- Status version: #1 (release v.1.1.0)
- Operating System: Android, iOS

**Comment by churik** [comment] 2020-03-05 12:34
cc @andremedeiros

**Comment by andremedeiros** [comment] 2020-03-05 19:21
I remember seeing a PR fly past me this morning by @flexsurfer. Was it the fix for this issue?

**Comment by flexsurfer** [comment] 2020-03-05 19:32
no

**Comment by rasom** [comment] 2020-03-06 18:42
almost likely this commit introduced the issue https://github.com/status-im/status-react/commit/4734a4ee0476dcb53ad42d1127ce096de1ebad78

**Comment by flexsurfer** [comment] 2020-03-06 19:15
@rasom yes #9995 in the description

**Comment by flexsurfer** [comment] 2020-03-06 19:17
so in this change we don't add old new messages, only when we scroll we add old messages to the list, but when we fetch we don't scroll and we don't add old messages, tbh i didn't find a good solution for that so far

**Comment by flexsurfer** [comment] 2020-03-06 19:19
i can see two solutions, after press fetch we add 20 new old messages when they come, or if we fetch we add all messages

**Comment by rasom** [comment] 2020-03-08 14:10
> if we fetch we add all messages

that might be a quick fix before we solve it properly 

>  after press fetch we add 20 new old messages when they come

it can't be that simple:
- there might be less than 20 messages
- messages arrive without order

The algorithm could be:
1. after receiving the first message from a requested range we schedule "scroll" event, so that even if we receive less than 20 we show these messages
2. after receiving 20th (the exact number might be different) message we show 20 messages
3. if we receive more messages after that we also add those which are newer than the last shown
4. also in case if scheduled event was dispatched earlier than we received 20th message (that might happen) we at first add every new incoming message till we show 20 messages and then go with 3.

**Comment by cammellos** [comment] 2020-03-09 08:18
It should be simply a matter of picking the first not visible message, instead of picking the last visible message as the code does.
Currently the issue is that when you reach the top of the scrolling, messages should be added regardless, instead we check that the message is less than: `(:clock-value last-visible-message)`, otherwise we don't load.
This is not correct, as if you are on top of the list, they should be added as they will be visible.

Instead we should check that message is less than: `(:clock-value first-not-visible-message)`. If there are not "invisible" messages at the top, it should be added.

It's a bit tricky as we don't get a list of not-visible messages, but I will push out a code doing that in a few mins, and you can take it from there.

**Comment by rasom** [comment] 2020-03-09 08:27
@cammellos ok, thanks

**Closed as completed** 2020-03-09 11:21 UTC
