### ISSUE TITLE
Settings don't work correctly on Pixel 6

### ISSUE THREAD

**Issue by Menduist** [status-im/status-react#13258] opened 2022-04-08 13:02 UTC
# Bug Report

## Problem 
On my pixel 6, the settings menu is a bit broken:
- The top is cropped by the android top bar
- The "go back" swipe motion doesn't do anything

### Additional Information

- Status version: 1.19.0
- Operating System: Android 12

**Comment by churik** [comment] 2022-04-08 14:26
@Menduist thank you for reporting!
Can you please attach a screenshot or video (even better)? 
To make it on Android you need to switch off Privacy and Security > "Block screenshots" first

**Comment by churik** [comment] 2022-04-08 14:26
@Menduist thank you for reporting!
Can you please attach a screenshot or video (even better)? 
To make it on Android you need to switch off Privacy and Security > "Block screenshots" first

**Comment by Menduist** [comment] 2022-04-08 15:27
![Screenshot_20220408-172419](https://user-images.githubusercontent.com/13471753/162473372-8d0e2e34-2c2c-432d-86d8-2032f0e06686.png)

I can't reproduce the swipe not working, interestingly. Must have gotten myself in a weird state earlier
(needless to say that I'm scrolled to the top in this screenshot :) )

**Comment by siddarthkay** [comment] 2022-04-20 07:02
@Menduist : I tried to recreate this issue on an android emulator with device resolution as the pixel 6 and with the Android API 32.

However the top menu does not appear to be cut in my screenshot.
![Screenshot 2022-04-20 at 12 28 27 PM](https://user-images.githubusercontent.com/64726664/164169154-ab1d7d6b-695e-4707-8723-ddd1c900c399.png)

Could you confirm if this behaviour is seen only in the "Need Help?" menu? or elsewhere in the app? 

I'll also try to get my hands on a pixel 6 to test this behaviour.

**Comment by nahuhh** [comment] 2022-04-21 10:44
@siddarthkay 
It appears the user may have a custom text or display size set device wide. (Smaller)

**Comment by Menduist** [comment] 2022-04-21 10:50
Oh right, I have display size & font size set to small

**Comment by Menduist** [comment] 2022-04-21 10:53
With the default sizes, it's not cropped

**Comment by nahuhh** [comment] 2022-04-21 10:53
Does it appear correctly if set to default?

**Comment by siddarthkay** [comment] 2022-04-27 12:42
This does not seem to require a fix. closing this issue for now.

**Comment by Menduist** [comment] 2022-04-27 12:57
It's a stock android option, and status is the only app (that I use) that gets cropped by it
While it's not the biggest issue in the world, I'm probably not the only one with a small font

**Comment by nahuhh** [comment] 2022-04-28 04:35
> This does not seem to require a fix. closing this issue for now.

It should IMHO.

A lot of people use non standard display sizes due to vision impairment.

Im not sure if @Menduist has similar issues when increasing size, but in feel ensuring the app scales properly is important in the long run.

_I do not have this issue._

It appears the problem is status not "beginning" where the system top panel "ends". From @Menduist screenshot, the panel looks large

**Comment by siddarthkay** [comment] 2022-04-28 07:46
@nahuhh : Trying to re-create this on emulator with the lowest font size and was not able to see the top bar break,
<img width="382" alt="Screenshot 2022-04-28 at 11 43 29 AM" src="https://user-images.githubusercontent.com/64726664/165702763-99b261c2-40fd-4265-a68f-143d60c3949b.png">
<img width="382" alt="Screenshot 2022-04-28 at 11 35 45 AM" src="https://user-images.githubusercontent.com/64726664/165703095-d88df5a8-3427-4f47-8389-7e94875df73d.png">

Fortunately @Menduist  is here with me for the Dubai offsite and I will build the latest on his phone and see why it breaks over there, maybe I don't have all of the settings right, I'll keep this issue posted.

**Comment by siddarthkay** [comment] 2022-09-30 10:18
Got a pixel 6 recently.
not able to re-produce anymore on pixel 6.
Closing this for now.

**Closed as completed by siddarthkay** 2022-09-30 10:18 UTC
