### ISSUE TITLE
Scrolling up and exiting a chat, Makes the scroll down indicator show on reopen chat

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#14577] opened 2022-12-19 18:04 UTC
# Bug Report

https://user-images.githubusercontent.com/33176106/208490740-5ea97ca9-6baa-4d21-8dad-7458225257a5.mp4

## Problem 
Scrolling up on a chat and exiting/dismissing the chat makes the scroll to bottom indicator show, Even though the chat screen is at the latest message
The video attach is on latest develop

#### Expected behavior
Scroll to bottom icon shouldn't show

#### Actual behavior
Scroll to bottom icon shows

**Comment by churik** [comment] 2023-06-01 11:43
couldn't reproduce it on nightly 01/06/23, so closing

**Closed as completed by churik** 2023-06-01 11:43 UTC
