### ISSUE TITLE
Commands are not calling anything in Console when launched after install [1710]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#1768] opened 2017-09-06 11:57 UTC
### Description

*Type*: Bug

*Summary*: `/faucet`,  `/phone` , `/debug` , `@browse` commands look like they are not calling any command directly and appear as text. Also I can't remove `/phone` command from chat as no `x` button displayed. Can't send `/faucet` as no send button displayed

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/30110551-1f856d86-9313-11e7-9a92-436ccb80c318.png)

![image](https://user-images.githubusercontent.com/28752642/30110891-6d1e6862-9314-11e7-8216-fc62869672ed.png)

### Reproduction

- Open Status
- Create password
- Type `/faucet` command in Console chat and observe
- Type `/phone` command in Console chat and observe

### Additional Information

* Status version: 0.9.10-73-g3095b32f+
* Operating System: Android

**Comment by annadanchenko** [comment] 2017-09-14 17:24
Issue is partially fixed:
1. OK - Commands /faucet, /phone , /debug , @browse can be sent now (there is send button)
2. Found also #1941 but it can be reproduced also in develop build, so not related to this PR

**Comment by janherich** [comment] 2017-09-19 00:36
As this is also happening in dev, I'm suspecting it has to do with new vector icons.
It's very strange, as the emoji shown instead of the close icon is indeed behaving exactly like close, so it's really just that visual is wrong.  
@flexsurfer do you have some idea what could go wrong with move to vector icons ?

**Comment by flexsurfer** [comment] 2017-09-19 06:38
@janherich I believe it shouldn't be related to vector icons itself, it works fine in other cases

**Comment by annadanchenko** [comment] 2017-09-27 09:03
Moving this issue to Tested as initial bug is fixed and another one #1941 is not caused by this PR (exists in develop also)

**Closed as completed** 2017-10-12 16:35 UTC
Labels: Tested - OK
