### ISSUE TITLE
Sometimes no history is retrieved if join public chat

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#7282] opened 2019-01-15 16:19 UTC
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Sometimes if join public chat there is no history retrieved (stable wifi connection, even if there is history, even if use "Fetch last 24 hours", on mailserver that works fine)

Found on today's 0.9.33 nightly + staging fleet or on default beta fleet and same nightly

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
last 24 h messages are shown in public chat

#### Actual behavior
[comment]: # (Describe what actually happened.)
No messages is shown for the chat (even if it has some)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

I can't reproduce it constantly but if try these steps 3-4 times you might be lucky:

1. create new account
2. add picture to profile (to allow access to Storage)
3. change fleet to staging
4. log in
5. join "status" or "status-core" chat and check if history is retrieved
If relaunch app and log in then history is retrieved fine

I don't think it's because of mailserver. When no messages were retrieved there was "mail-01.do-ams3.eth.staging" mailserver. I've killed and started the app again, other mailserver was selected and history was retrieved. Then I've manually selected "mail-01.do-ams3.eth.staging" and joined another public chat - history is retrieved fine.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.33 (2019011503) status-go v0.17.11-beta.e081f3ec
* Operating System: Android 6.0.1 real Galaxy S6 device

#### Logs
For staging fleet:
[Status.log](https://github.com/status-im/status-react/files/2760435/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2760437/geth.log)

For beta fleet:
[geth.log](https://github.com/status-im/status-react/files/2760484/geth.log)
[Status.log](https://github.com/status-im/status-react/files/2760485/Status.log)

**Comment by cammellos** [comment] 2019-01-16 07:31
Looking into this, checking the logs one thing that can be noticed is that the public-chat was joined before the mailserver was ready (that would explain why it only happens sometimes), but will check to validate that.

**Comment by annadanchenko** [comment] 2019-01-16 09:14
using debug PR https://github.com/status-im/status-react/pull/7285 can reproduce on Android build (real Galaxy S6, Android 6.0.1)

modified steps:
1. create new account
2. add picture to profile (to allow access to Storage)
3. Log out
4. log in
5. join "status" or "status-core" chat and check if history is retrieved

[Status.log](https://github.com/status-im/status-react/files/2763385/Status.log)
[geth.log](https://github.com/status-im/status-react/files/2763388/geth.log)

**Comment by churik** [comment] 2019-01-16 09:25
@cammellos tested 0.9.32 release build on `eth.staging` fleet and some messages are not fetched when you go back from offline.
**Steps to reproduce:**
- close app
- send ~10 messages in different chats from another device
- open app and log in
- wait 2+ mins for messages to fetch

**Expected result:** all messages are fetched
**Actual result:** none of the messages are fetched
Reproducible almost every time.
Sometimes messages are fetched after switching to `eth.beta`, but not every time.
**Logcat:** [logcat-andr.txt](https://github.com/status-im/status-react/files/2763372/logcat-andr.txt)

I believe, the reason can be similar, so I've put it as comment. If it is completely different, let me know and I'll create separate issue.

**NOTE:** it is not reproducible if you have selected `eth.beta` before closing app (5\5 times)

**Comment by cammellos** [comment] 2019-01-16 09:31
@churik would you mind using the test build from https://github.com/status-im/status-react/pull/7285 and replicate? thanks!

**Comment by churik** [comment] 2019-01-16 10:43
@cammellos can't reproduce https://github.com/status-im/status-react/issues/7282#issuecomment-454709787 on https://github.com/status-im/status-react/pull/7285 on eth.staging. Tried around 10 times with different chats number, mailservers and network -  no success

UPD: can't reproduce https://github.com/status-im/status-react/issues/7282#issuecomment-454709787 as well on `eth.staging` + 0.9.32, tried around 10 times.

**Comment by asemiankevich** [comment] 2019-01-16 11:00
i dont see messages in the following case:
- 2 devices in contacts, iOS and android
- ios goes offline
- android sends some messages to ios
- ios gets back online

As a result i see PN coming to iOS but no messages that were sent while iOS was offline. In order to receive them i have to restart the app.

**Closed as completed** 2019-01-29 18:48 UTC
