### ISSUE TITLE
Fix biometric auth after navigation refactor

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#19243] opened 2024-03-14 08:30 UTC
# Bug Report

## Problem 
[comment]: # (A problem description)
After https://github.com/status-im/status-mobile/pull/19068, biometric auth is broken

Error:
```sh

***
NAME: "TypeError"
MESSAGE: null is not an object (evaluating 'input.root')

setRoot@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:203908:40
react_native$navigation$set_root

re_frame$fx$do_fx_after
re_frame$interceptor$invoke_interceptor_fn
re_frame$interceptor$invoke_interceptors
re_frame$interceptor$execute
re_frame$events$handle

re_frame$router$_process_1st_event_in_queue

re_frame$router$_run_queue


re_frame$router$_fsm_trigger

http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:44877:26
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:44788:17
callTimers@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:44996:19
__callFunction@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:16074:36
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:15794:31
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:16011:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=im.status.ethereum.debug&modulesOnly=false&runModule=true:15793:21
callFunctionReturnFlushedQueue@[native code]

***
 ERROR  TypeError: null is not an object (evaluating 'input.root')

```

#### Expected behavior
Can log in with biometrics

#### Actual behavior
Error thrown when logging in with biometrics

### Reproduction

1. Try to log in with biometrics

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment] 2024-03-14 08:42
duplicate of https://github.com/status-im/status-mobile/issues/19236

**Closed as completed** 2024-03-14 08:55 UTC
