### ISSUE TITLE
"database is locked" error, cannot join communities by specific user

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19412] opened 2024-03-27 10:14 UTC
At some point one of my test users has become unable to join communities. Requests stuck in Pending state, control node does not receive community requests.   

Ping me up in DM and I will share seed phrase of the user so you can reproduce. 

**Steps:** 

1. Restore given user
2. Try to join any community by this user
3. Observe the result

**Actual result:** community request stucks in Pending. 

There are lot of "database is locked" errors in geth.log 

[logs (27).zip](https://github.com/status-im/status-mobile/files/14771481/logs.27.zip)

```
ERROR[03-27|09:53:56.805|github.com/status-im/status-go/services/wallet/collectibles/manager.go:769]                                  collectionsDataDB SetData failed         communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.805|github.com/status-im/status-go/services/wallet/collectibles/manager.go:794]                                  fetchCommunityAssets failed              communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.806|github.com/status-im/status-go/services/wallet/collectibles/manager.go:769]                                  collectionsDataDB SetData failed         communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.806|github.com/status-im/status-go/services/wallet/collectibles/manager.go:794]                                  fetchCommunityAssets failed              communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.815|github.com/status-im/status-go/services/wallet/collectibles/manager.go:769]                                  collectionsDataDB SetData failed         communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.815|github.com/status-im/status-go/services/wallet/collectibles/manager.go:794]                                  fetchCommunityAssets failed              communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.819|github.com/status-im/status-go/services/wallet/collectibles/manager.go:777]                                  collectiblesDataDB SetCommunityInfo failed communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.819|github.com/status-im/status-go/services/wallet/collectibles/manager.go:794]                                  fetchCommunityAssets failed              communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.822|github.com/status-im/status-go/services/wallet/collectibles/manager.go:769]                                  collectionsDataDB SetData failed         communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"
ERROR[03-27|09:53:56.822|github.com/status-im/status-go/services/wallet/collectibles/manager.go:794]                                  fetchCommunityAssets failed              communityID=0x039bdd758f1122e17e086d3dd068391688e8b2655d6c86619e1ef5080f42c6cce3 err="database is locked"

```

https://github.com/status-im/status-mobile/assets/97245802/8454cccb-53ba-4484-8b72-96e0a45ead27

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by qfrank** [comment] 2024-05-15 03:22
Hi @pavloburykh , i'm unable to reproduce error("database is locked") with your provided seedphrase. 
<img width="409" alt="image" src="https://github.com/status-im/status-mobile/assets/12406719/0ac3457e-f3f7-4f49-9c0d-14d7096ee58a">
Also I can join the 1st and 4th community i created, i'm just wondering if the control node of 2nd and 3rd community are online?

**Comment by pavloburykh** [comment] 2024-05-15 06:10
> if the control node of 2nd and 3rd community are online?

Hi @qfrank! It is not online 24/7, although it was online when we have been testing it together yesterday and you have failed to join despite of that.

**Comment by qfrank** [comment] 2024-05-15 09:45
Upon investigation, we found that the issue is user-specific and not related to the "database is locked" error. The error logs did not provide any useful information on either side. With the specific mobile user and desktop user (who is the control node), the community request stuck at pending can be reproduced in 100%. Given that this is a user-specific issue, we have decided to deprioritize it for now. We might need to write a test to recover the specific user to simulate such issue to debug. We recommend focusing on other higher-priority issues unless further evidence suggests a broader impact. cc @pavloburykh  @cammellos

**Comment by ilmotta** [comment] 2024-06-06 00:15
Just checking @qfrank @flexsurfer, this issue was moved back again to `In Progress`, but the last [comment](https://github.com/status-im/status-mobile/issues/19412#issuecomment-2112055052) says the issue is now deprioritized.

Shouldn't we move it back to `No Status` and close it?

**Comment by qfrank** [comment] 2024-06-06 02:48
What I can tell: I was not working on this after moving to `low-priority` :) @ilmotta

**Comment by churik** [comment] 2024-06-21 15:09
@pavloburykh are you still the owner of the affected user and the issue is still there?

**Comment by pavloburykh** [comment] 2024-06-21 15:12
> @pavloburykh are you still the owner of the affected user and the issue is still there?

I can find that user. But it has been already [debugged](https://github.com/status-im/status-mobile/issues/19412#issuecomment-2112055052) and it is not clear what causes the bug.

**Comment by churik** [comment] 2024-06-25 15:57
Let's close it then for now and re-open if it reproduces again. Thank you @pavloburykh

**Closed as completed by churik** 2024-06-25 15:57 UTC
Labels: mobile-core
