### ISSUE TITLE
Communities - "Admins will review your request" bug

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19207] opened 2024-03-12 14:35 UTC
# Design Feedback 2.27

## [Communities] "Community admins will review your request" on a joined community page
After requesting to join a community the _Community admins will review your request_ text appears below the community tags and stays even after the user has correctly joined [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=94:35450&mode=design#726030313)]

<img width="430" alt="Screenshot 2024-03-12 alle 15 23 50" src="https://github.com/status-im/status-mobile/assets/122543089/62e00feb-8586-46cf-afc1-104686999ad6">

#### Expected behavior

<img width="300" alt="Screenshot 2024-03-12 alle 15 31 18" src="https://github.com/status-im/status-mobile/assets/122543089/1c1136eb-75da-47bf-bb44-365c2782a91a">
<img width="300" alt="Screenshot 2024-03-12 alle 15 31 40" src="https://github.com/status-im/status-mobile/assets/122543089/c7c83bae-0799-4fac-8441-0d0f421e7a13">

### Reproduction

1. Open a community you're not a member of
2. Request to join

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 15 Pro Max

[comment]: # (Please, add logs/notes if necessary)

**Comment by pavloburykh** [comment] 2024-03-12 15:42
closing as duplicate of https://github.com/status-im/status-mobile/issues/18706

**Closed as completed by pavloburykh** 2024-03-12 15:42 UTC
