### ISSUE TITLE
Public keys in image description instead of usernames

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#15902] opened 2023-05-15 15:30 UTC
# Bug Report
![Uploading 238396943...]

## Problem 
Username shows as PK in image preview

![image](https://github.com/status-im/status-mobile/assets/33176106/8f11709b-fcb6-4170-a781-cca1ca49ad4c)

#### Expected behavior
Username should be resolved into his selected name or nickname

#### Actual behavior
Username shows PK instead of user's name

**Comment by churik** [comment] 2023-06-01 13:47
not only; the issue is also shown on toasts for deleted / cleared chats (just as a part of public keys)
![IMAGE 2023-06-01 14:47:19](https://github.com/status-im/status-mobile/assets/4557972/e1be0182-5809-4e07-b3bc-51fa600e95f9)

**Comment by churik** [comment] 2023-06-01 15:43
Hide the text for images will resolve https://github.com/status-im/status-mobile/issues/15902#issue-1710339153 , toasts should be fixed

**Closed as completed** 2023-06-27 07:42 UTC
Labels: images
